### ISSUE TITLE
v2.4.0: ApacheHttpClient.useIdleConnectionReaper(true) throws NPE on initialization

### ISSUE THREAD

**Issue by jhg023** [aws/aws-sdk-java-v2#1059]
When attempting to use an `S3Client` that was initialized with a custom `ApacheHttpClient` with `useIdleConnectionReaper` set to `true`, a `NullPointerException` is thrown. This does not occur in v2.3.9 and below.

## Expected Behavior
No `NullPointerException` should be thrown.

## Current Behavior
A `NullPointerException` is thrown on the line that contains `ApacheHttpClient.Builder#build`.

Stacktrace:

    Caused by: java.lang.NullPointerException
	    at software.amazon.awssdk.http.apache.ApacheHttpClient.createClient(ApacheHttpClient.java:149)
	    at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:117)
	    at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:99)
	    at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.buildWithDefaults(ApacheHttpClient.java:460)
	    at software.amazon.awssdk.http.SdkHttpClient$Builder.build(SdkHttpClient.java:52)
	    at Test.<clinit>(Test.java:21)

## Possible Solution
Do not use `.useIdleConnectionReaper(true)` (isn't it set to `true` by default in v2.4.0 anyway?)

## Steps to Reproduce (for bugs)
    private static final S3Client S3_CLIENT = S3Client.builder()
			.httpClient(ApacheHttpClient.builder().useIdleConnectionReaper(true).build())
			.build();
	
	public static void main(String[] args) throws Exception {
		S3_CLIENT.listBuckets().buckets().forEach(System.out::println);
	}

## Context
We tried to update our production code to v2.4.0 of the SDK, but this bug is preventing us from doing so.

## Your Environment
* AWS Java SDK version used: v2.4.0
* JDK version used: OpenJDK 11.0.1
* Operating System and version: macOS Sierra Version: 10.12.6

**Comment by jhg023** [comment]
Thanks for the quick fix!
