### ISSUE TITLE
Recurrent "Idle connection.." exception in S3Client.putObject

### ISSUE THREAD

**Issue by dbolotin** [aws/aws-sdk-java-v2#1124]
## Expected Behavior
Should retry and throw exception only if it failed in all the attempts

## Current Behavior
Exception:
```
Exception in thread "Thread-114" software.amazon.awssdk.services.s3.model.S3Exception: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: S3, Status Code: 400, Request ID: 6A82427F61854F63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:115)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:113)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:86)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:51)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:33)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:79)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:3051)
	at software.amazon.awssdk.services.s3.S3Client.putObject(S3Client.java:5096)
        ...   my code ...
```

## Possible Solution
After a day of trying to understand what is going on, as a workaround I am thinking about collecting a bunch of files to send and running a separate `aws-cli` process with `aws s3 cp ...` command.

## Steps to Reproduce (for bugs)
My code basically doing some ETL.

Here is how the client is created:
```java
S3Client s3 = S3Client.builder().region(Region.US_EAST_1)
        .httpClientBuilder(ApacheHttpClient.builder()
                .socketTimeout(Duration.ofMinutes(1))
                .connectionTimeout(Duration.ofMinutes(1))
                .maxConnections(100))
        .overrideConfiguration(c -> c
                .retryPolicy(RetryPolicy.defaultRetryPolicy().toBuilder()
                        .numRetries(15).build()))
        .build();
```

There are several threads that writes files onto the instance storage NVMe (ext4), closes the output stream, and send file name into a fixed-size concurrent buffer and several threads that picks up the names and execute approximately the following:

```
s3.putObject(b -> b.bucket(this.bucket).key(key), RequestBody.fromFile(ts3.path));
Files.delete(ts3.path);
```

## Context

Code is executed inside AWS, in the same zone as S3 bucket. On the c5d.18xlarge instance.

## Your Environment
* JDK version used:
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
* Operating System and version: 
```
amzn2-ami-hvm-2.0.20190115-x86_64-gp2
```
* AWS Java SDK version used: `2.5.5`

**Comment by millems** [comment]
Sounds like a bug. `RequestBody.fromFile` shouldn't get this exception, except in extremely overloaded circumstances.

**Comment by dbolotin** [comment]
Actually, I haven't mention that several other (5~10) threads using the same `s3` client to download files, like this:
```
GetObjectResponse resp = s3.getObject(b -> b.bucket(options.inputBucket).key(input), ResponseTransformer.toFile(inputFile));
```
this might have something to do with the exception...

**Comment by zoewangg** [comment]
I don't think this is a Java SDK bug and we have reports against this issue in other SDKs. See https://github.com/aws/aws-sdk-js/issues/281#issuecomment-43798354

We don't retry this exception in the SDK and we could consider making it a retryable exception and I will discuss with the team.

The workaround would be the following:
```
s3AsyncClientBuilder()
            .overrideConfiguration(
                ClientOverrideConfiguration.builder()
                                           .retryPolicy(AwsRetryPolicy.defaultRetryPolicy()
                                                                      .toBuilder()
                                                                      .retryCondition(
                                                                          OrRetryCondition.create(
                                                                              AwsRetryPolicy.defaultRetryCondition(),
                                                                              RetryOnErrorCodeCondition.create(
                                                                                  "RequestTimeout"))
                                                                      ).build()
                                           )
                                           .build())
            .build();
```

**Comment by millems** [comment]
Fixed in V2.
