### ISSUE TITLE
S3AsyncClient.getObject returns NPE if object size is zero

### ISSUE THREAD

**Issue by er1c** [aws/aws-sdk-java-v2#1148]
## Expected Behavior
```s3Client.getObject(getObjectRequest, outPath).asScala.map { res: GetObjectResponse =>```

Should not throw an NPE if the file contents are empty.

## Current Behavior
```
Caused by: java.lang.NullPointerException
	at software.amazon.awssdk.core.internal.async.FileAsyncResponseTransformer.exceptionOccurred(FileAsyncResponseTransformer.java:81)
	at software.amazon.awssdk.core.internal.http.async.AsyncStreamingResponseHandler.onError(AsyncStreamingResponseHandler.java:67)
	at software.amazon.awssdk.core.internal.http.async.AsyncAfterTransmissionInterceptorCallingResponseHandler.onError(AsyncAfterTransmissionInterceptorCallingResponseHandler.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryErrorIfNeeded(AsyncRetryableStage.java:169)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:124)
	... 56 more
```
## Steps to reproduce

Put a file with zero bytes, and then `.getObject` it.

## Your Environment

* AWS Java SDK version used: 2.5.10
* JDK version used: 11
* Operating System and version: OSX

**Comment by er1c** [comment]
I fixed the NPE locally, but still have the issue that the future times out.

I added some debug statements and the `FileAsyncResponseTransformer.prepare() called` is the only method I can see getting invoked.

**Comment by varunnvs92** [comment]
I tried with sample java code and it worked fine for object with 0 size.
```
        S3AsyncClient client = S3AsyncClient.create();
        GetObjectResponse response =
        client.getObject(b -> b.bucket("my-buicket").key("foobar"), Paths.get("mypath"))
              .get();

        System.out.println(response.contentLength());
```
Can you share the code you are using? (Make sure there are no sensitive details)

> I fixed the NPE locally, but still have the issue that the future times out.

Is NPE from your code? If so, please share the logs from the new error

**Comment by er1c** [comment]
I'll create a minimal test example in the next few days.

**Comment by er1c** [comment]
This isn't throwing an NPE right now, but here is an example of the Async Client timing out:

https://gist.github.com/er1c/fdceec432d806e6ea37c6a2e0e40504e

The Future times out/doesn't ever complete - both using s3mock AND the direct s3 service.

I think it's related to `AsyncRequestBody.fromFile(tmpPath)` being a zero byte file?

**Comment by er1c** [comment]
Actually , I will trim the test file down more.

**Comment by er1c** [comment]
I'm going to close this and re-open if needed, I'm conflating too many issues already.
