### ISSUE TITLE
build fails with dependency problem on project aws-ion-protocol

### ISSUE THREAD

**Issue by ronsmith** [aws/aws-sdk-java-v2#1155]
I cloned the master branch and ran mvn clean install and I get the following error. I added -e and -X to get more information but it wasn't useful to me.

I am using openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
Running on Ubuntu 16.04

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (default) on project aws-ion-protocol: Dependency problems found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (default) on project aws-ion-protocol: Dependency problems found
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Dependency problems found
	at org.apache.maven.plugins.dependency.analyze.AbstractAnalyzeMojo.execute(AbstractAnalyzeMojo.java:253)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more

**Comment by ronsmith** [comment]
I commented out the aws-ion-protocol module in core/protocols/pom.xml then I got a similar dependency issue on transcribestreaming service so I removed the transcribestreaming module from services/pom.xml.
Finally got a successful build.

**Comment by varunnvs92** [comment]
Interesting we run `mvn clean install` on every PR and we are not seeing that issue.
Is that the exact command you ran?
Does the logs have any other specific error messages?
Did you try cloning the repo in another directory and running the same command?

**Comment by zoewangg** [comment]
Closing this due to inactivity. Please feel free to reopen if you're still experiencing this issue.

**Comment by laloyd** [comment]
btw I am aslo having the same issue and my error looks like:
[INFO] AWS Java SDK :: Core :: Protocols :: AWS Cbor Protocol 2.5.40-SNAPSHOT SUCCESS [  3.465 s]
[INFO] AWS Java SDK :: Core :: Protocols :: AWS Ion Protocol 2.5.40-SNAPSHOT FAILURE [  5.122 s]

...
..
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (default) on project aws-ion-protocol: Dependency problems found -> [Help 1]

**Comment by laloyd** [comment]
actually when I ran 
mvn clean install -Dmaven.test.skip=true
it fails, but when I run
mvn clean install
it worked fine    /shrug

**Comment by sworisbreathing** [comment]
I get the error as well, using maven 3.6.1 with amazon corretto jdk 1.8u222 on Windows 10, against sdk version 2.9.24-SNAPSHOT (current master branch).

For Ion Protocol it's reporting:
{code}
[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (default) @ aws-ion-protocol ---
[WARNING] Unused declared dependencies found:
[WARNING]    software.amazon.awssdk:aws-core:jar:2.9.24-SNAPSHOT:compile
{code}

For transcribestreaming it's:
{code}
[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (default) @ transcribestreaming ---
[WARNING] Unused declared dependencies found:
[WARNING]    software.amazon.awssdk:regions:jar:2.9.24-SNAPSHOT:compile
{code}

My workaround is to comment out the `analyze-only` goal section in the parent pom. No clue why it works for the project maintainers but not for the rest of us.

**Comment by mirraj2** [comment]
I'm getting this exact problem.  This is the pom.xml:  https://search.maven.org/artifact/software.amazon.awssdk/ec2/2.13.37/jar

And this is the command I'm running:  mvn install dependency:copy-dependencies
