### ISSUE TITLE
Serializing the model objects is painful

### ISSUE THREAD

**Issue by brharrington** [aws/aws-sdk-java-v2#121]
The example in the _Immutable POJOs_ section of the [blog post] recommends serializing the model objects using the builder. However, this doesn't work transitively so if the object contains other immutable POJOs, then it cannot be serialized successfully. Example:

[blog post]: https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/

```scala
    val mapper = new ObjectMapper()
    val instance = Instance.builder()
      .instanceId("i-12345")
      .monitoring(Monitoring.builder().state(MonitoringState.Disabled).build())
      .build()
    println(mapper.writeValueAsString(instance.toBuilder))
```

Gives an error:

```
No serializer found for class software.amazon.awssdk.services.ec2.model.Monitoring and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl["monitoring"])
com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class software.amazon.awssdk.services.ec2.model.Monitoring and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl["monitoring"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:284)
	at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1110)
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1135)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:69)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:32)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:704)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3057)
```

**Comment by kiiadi** [comment]
I've put out a PR that should resolve this issue: #128
