### ISSUE TITLE
Avoid conflicting setters on builders

### ISSUE THREAD

**Issue by brharrington** [aws/aws-sdk-java-v2#122]
The example in the _Immutable POJOs_ section of the [blog post] shows using the `serializableBuilderClass` to deserialize the model POJOs. However, in many cases this doesn't work without additional annotations because there are overloaded setters with different parameter types. Since the builder seems to be mostly intended for use with the fluent methods, I would guess the setXYZ is just there to make it work with tools that support the java bean conventions. Ideally it would only have one setter that matched the return type of the corresponding getter. Example:

[blog post]: https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/

```scala
    val mapper = new ObjectMapper()
    val instance = Instance.builder()
      .instanceId("i-12345")
      .build()
    val json = mapper.writeValueAsString(instance.toBuilder)
    mapper.readValue(json, Instance.serializableBuilderClass())
```

Gives:

```
Conflicting setter definitions for property "productCodes": software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl#setProductCodes(1 params) vs software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl#setProductCodes(1 params)
 at [Source: (String)"{"amiLaunchIndex":null,"imageId":null,"instanceId":"i-12345","instanceType":null,"kernelId":null,"keyName":null,"launchTime":null,"monitoring":null,"placement":null,"platform":null,"privateDnsName":null,"privateIpAddress":null,"productCodes":null,"publicDnsName":null,"publicIpAddress":null,"ramdiskId":null,"state":null,"stateTransitionReason":null,"subnetId":null,"vpcId":null,"architecture":null,"blockDeviceMappings":null,"clientToken":null,"ebsOptimized":null,"enaSupport":null,"hypervisor":null"[truncated 275 chars]; line: 1, column: 1]
com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "productCodes": software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl#setProductCodes(1 params) vs software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl#setProductCodes(1 params)
 at [Source: (String)"{"amiLaunchIndex":null,"imageId":null,"instanceId":"i-12345","instanceType":null,"kernelId":null,"keyName":null,"launchTime":null,"monitoring":null,"placement":null,"platform":null,"privateDnsName":null,"privateIpAddress":null,"productCodes":null,"publicDnsName":null,"publicIpAddress":null,"ramdiskId":null,"state":null,"stateTransitionReason":null,"subnetId":null,"vpcId":null,"architecture":null,"blockDeviceMappings":null,"clientToken":null,"ebsOptimized":null,"enaSupport":null,"hypervisor":null"[truncated 275 chars]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:305)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3899)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3794)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
Caused by: java.lang.IllegalArgumentException: Conflicting setter definitions for property "productCodes": software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl#setProductCodes(1 params) vs software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl#setProductCodes(1 params)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBeanProps(BeanDeserializerFactory.java:609)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:499)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:226)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:141)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	... 52 more
```

**Comment by kiiadi** [comment]
+1 we've talked about doing exactly that, there's no point having the additional setters on the builder class!
