### ISSUE TITLE
ClosedChannelException during AWS Streaming Transcribe

### ISSUE THREAD

**Issue by bkempe** [aws/aws-sdk-java-v2#1260]
## Steps to reproduce
Running code like the AWS Streaming Transcribe example to transcribe PCM, but logging the `onError` case. This case is not getting logged [in the example code](https://github.com/aws-samples/aws-transcribe-streaming-example-java/blob/master/src/main/java/com/amazonaws/transcribestreaming/TranscribeStreamingRetryClient.java#L184). Are these exceptions not relevant?

Note: The exception is not happening consistently but intermittently and is therefore hard to reproduce.

## Expected Behavior
No exception

## Current Behavior
Seeing
```
software.amazon.awssdk.core.exception.SdkClientException: null
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:123)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:105)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.onError(MakeAsyncHttpRequestStage.java:246)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:252)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.makeRequestListener(NettyRequestExecutor.java:138)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.handler.codec.http2.ForkedHttp2StreamChannelBootstrap.open(ForkedHttp2StreamChannelBootstrap.java:113)
	at io.netty.handler.codec.http2.ForkedHttp2StreamChannelBootstrap.open(ForkedHttp2StreamChannelBootstrap.java:103)
	at software.amazon.awssdk.http.nio.netty.internal.http2.MultiplexedChannelRecord.lambda$bootstrapChildChannel$3(MultiplexedChannelRecord.java:137)
	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.lambda$asyncPromiseNotifyingBiConsumer$1(NettyUtils.java:84)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at software.amazon.awssdk.http.nio.netty.internal.http2.MultiplexedChannelRecord.createChildChannel0(MultiplexedChannelRecord.java:126)
	at software.amazon.awssdk.http.nio.netty.internal.http2.MultiplexedChannelRecord.lambda$createChildChannel$1(MultiplexedChannelRecord.java:119)
	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.doInEventLoop(NettyUtils.java:119)
	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.doInEventLoop(NettyUtils.java:135)
	at software.amazon.awssdk.http.nio.netty.internal.http2.MultiplexedChannelRecord.createChildChannel(MultiplexedChannelRecord.java:118)
	at software.amazon.awssdk.http.nio.netty.internal.http2.MultiplexedChannelRecord.acquire(MultiplexedChannelRecord.java:84)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2MultiplexedChannelPool.acquire0(Http2MultiplexedChannelPool.java:101)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2MultiplexedChannelPool.lambda$acquire$0(Http2MultiplexedChannelPool.java:90)
	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.doInEventLoop(NettyUtils.java:119)
	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.doInEventLoop(NettyUtils.java:135)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2MultiplexedChannelPool.acquire(Http2MultiplexedChannelPool.java:90)
	at software.amazon.awssdk.http.nio.netty.internal.utils.BetterFixedChannelPool.acquire0(BetterFixedChannelPool.java:169)
	at software.amazon.awssdk.http.nio.netty.internal.utils.BetterFixedChannelPool.acquire(BetterFixedChannelPool.java:138)
	at software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.acquire0(HttpOrHttp2ChannelPool.java:78)
	at software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.lambda$acquire$0(HttpOrHttp2ChannelPool.java:67)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	... 5 common frames omitted
```

## Your Environment
* AWS Java SDK version used: 2.5.46
* JDK version used: OpenJDK 64-Bit Server VM 11.0.3

**Comment by millems** [comment]
The exception message isn't great, but it's coming from Netty so it's tough to improve. We'll see what we can do.

This exception is raised when the channel was closed, usually by the service or an intermediary party (e.g. a NAT gateway). The code you provided reconnects automatically in these scenarios, so you theoretically shouldn't have any impact. We have [a mini-proposal](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/design/core/event-streaming/reconnect/README.md) to pull this reconnect logic into the SDK, which will allow us to hide the exception entirely.

For now, you can safely ignored these closed-channel exceptions, and we'll try to improve the exception message to not just say "null".
