### ISSUE TITLE
NPE in ByteArrayAsyncResponseTransformer

### ISSUE THREAD

**Issue by jianjin** [aws/aws-sdk-java-v2#1268]
When exception below happened:
`software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials`
It will trigger NPE below:

 ```
java.lang.NullPointerException

        at software.amazon.awssdk.core.internal.async.ByteArrayAsyncResponseTransformer.exceptionOccurred(ByteArrayAsyncResponseTransformer.java:66)

        at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.lambda$getObject$0(DefaultS3AsyncClient.java:1889)

        at software.amazon.awssdk.utils.FunctionalUtils.runAndLogError(FunctionalUtils.java:40)

        at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.getObject(DefaultS3AsyncClient.java:1888)

        at com.amazon.magnolio.s3.MagnolioS3ClientV2.asyncReadRange(MagnolioS3ClientV2.java:216)
```

It seems the private volatile CompletableFuture<byte[]> cf;  is not initialized before the exceptionOccurred is triggered.
 

* AWS Java SDK version used: 
* JDK version used: 1.8
* Operating System and version: Linux

**Comment by varunnvs92** [comment]
Are you using the latest version of the SDK?

**Comment by jianjin** [comment]
We are using amazon internal build of SDK.  Internal version is:  AwsJavaSdk-Core-2.0 : 2.0.760.0, Dunno how to map to external version.

**Comment by varunnvs92** [comment]
I can repo the issue. I will work on a fix this week.

**Comment by varunnvs92** [comment]
Fixed in https://github.com/aws/aws-sdk-java-v2/pull/1288. Will be included in next release.
