### ISSUE TITLE
Attempting to list the consumers of a Kinesis Stream throws a j.l.NoSuchMethodError

### ISSUE THREAD

**Issue by jhg023** [aws/aws-sdk-java-v2#1291]
I'm attempting to list the consumers of a Kinesis Stream, but a `java.lang.NoSuchMethodError` is thrown.

## Expected Behavior
I expect it to not throw an exception and correctly return a `ListStreamConsumersResponse`.

## Current Behavior
The following error is thrown:
    
    java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.cbor.CBORGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;
	    at com.fasterxml.jackson.dataformat.cbor.CBORGenerator.close(CBORGenerator.java:903)
	    at software.amazon.awssdk.protocols.json.SdkJsonGenerator.close(SdkJsonGenerator.java:251)
	    at software.amazon.awssdk.protocols.json.SdkJsonGenerator.getBytes(SdkJsonGenerator.java:266)
	    at software.amazon.awssdk.protocols.json.internal.marshall.JsonProtocolMarshaller.finishMarshalling(JsonProtocolMarshaller.java:198)
	    at software.amazon.awssdk.protocols.json.internal.marshall.JsonProtocolMarshaller.marshall(JsonProtocolMarshaller.java:187)
	    at software.amazon.awssdk.protocols.json.internal.marshall.JsonProtocolMarshaller.marshall(JsonProtocolMarshaller.java:46)
	    at software.amazon.awssdk.protocols.json.internal.marshall.NullAsEmptyBodyProtocolRequestMarshaller.marshall(NullAsEmptyBodyProtocolRequestMarshaller.java:37)
	    at software.amazon.awssdk.protocols.json.internal.marshall.NullAsEmptyBodyProtocolRequestMarshaller.marshall(NullAsEmptyBodyProtocolRequestMarshaller.java:26)
	    at software.amazon.awssdk.services.kinesis.transform.ListStreamConsumersRequestMarshaller.marshall(ListStreamConsumersRequestMarshaller.java:50)
	    at software.amazon.awssdk.services.kinesis.transform.ListStreamConsumersRequestMarshaller.marshall(ListStreamConsumersRequestMarshaller.java:31)
	    at software.amazon.awssdk.core.client.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:63)
	    at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:106)
	    at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73)
	    at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
	    at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	    at software.amazon.awssdk.services.kinesis.DefaultKinesisClient.listStreamConsumers(DefaultKinesisClient.java:1166)
	    at software.amazon.awssdk.services.kinesis.KinesisClient.listStreamConsumers(KinesisClient.java:1861)
	    at com.***.***.integration.kinesis.KinesisUtilityTest.testGetFirehoseNamesV2(KinesisUtilityTest.java:32)

## Possible Solution
A solution is to include the following dependency, which I assume should be included internally to prevent this from occurring:

    <dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-cbor</artifactId>
      <version>2.9.9</version>
    </dependency>

## Steps to Reproduce (for bugs)
    KinesisClient.create().listStreamConsumers(builder -> {
        builder.streamARN(KINESIS_STREAM_ARN).build();
    });

## Your Environment

* AWS Java SDK version used: 
  * 2.5.60
* JDK version used:
  * Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
* Operating System and version:
  * macOS Mojave (10.14.5)

**Comment by zoewangg** [comment]
`jackson-dataformat-cbor` should be included as part of the SDK. The issue might be caused by conflicting versions of jackson dependencies, could you run `mvn dependency:tree` and post the relevant output?

**Comment by jhg023** [comment]
Oddly enough, I can no longer reproduce the issue, so it most-likely *was* the result of a dependency conflict.
