### ISSUE TITLE
S3AsyncClient- SdkClientException: Unable to instantiate executor interceptor for client

### ISSUE THREAD

**Issue by shanegu** [aws/aws-sdk-java-v2#1491]
## Expected Behavior
When running 
S3AsyncClient s3AsyncClient = S3AsyncClient.create();
In AWS lambda function, got following exception:

## Current Behavior
software.amazon.awssdk.core.exception.SdkClientException: Unable to instantiate executor interceptor for client.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptor(ClasspathInterceptorChainFactory.java:140)
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptorFromResource(ClasspathInterceptorChainFactory.java:95)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptorsFromClasspath(ClasspathInterceptorChainFactory.java:64)
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.getInterceptors(ClasspathInterceptorChainFactory.java:51)
	at software.amazon.awssdk.services.s3.DefaultS3BaseClientBuilder.finalizeServiceConfiguration(DefaultS3BaseClientBuilder.java:57)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:133)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:170)
	at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:28)
	at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:119)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.services.s3.internal.handlers.EndpointAddressInterceptor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at software.amazon.awssdk.core.internal.util.ClassLoaderHelper.loadClass(ClassLoaderHelper.java:112)
	at software.amazon.awssdk.core.internal.util.ClassLoaderHelper.loadClass(ClassLoaderHelper.java:71)
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptor(ClasspathInterceptorChainFactory.java:123)

## Steps to Reproduce (for bugs)
Below is my AWS lambda function written in Java:
```
private S3AsyncClient s3AsyncClient;    
public CommandsHandler() {
        s3AsyncClient = S3AsyncClient.create();
}

```
tried latest version of 2.10.3 in my POM file
```
<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>dynamodb</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sns</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
```

## Context
I am able to instantiate SNS client and DynamoDB client without any problem, but S3 Client failed.

## Your Environment

* AWS Java SDK version used: tried 2.10.3, 2.8.7 and 2.5.3
* JDK version used: 1.8
* Operating System and version: Ubuntu 18.04.3 LTS and Amazon Linux workspace

**Comment by shanegu** [comment]
Just tried SDK V1 S3Client and it works fine:
`private final AmazonS3 s3Client;
public CommandsHandler() {
        s3Client = AmazonS3ClientBuilder.defaultClient();
    }
`
`<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>${aws.sdk.v1.version}</version>
        </dependency>`

Really not sure if it's a bug related to AWS Lambda runtime or there is any dependency missing in my Pom file in order to use SDK v2 S3 client?

**Comment by zoewangg** [comment]
Hi @shanegu I tried to create s3 async client in Lambda but was not able to reproduce the issue.

Were you using mixed version of the SDK clients by any chance?

We recommend using BOM to manage the SDK versions if you use multiple sdk clients.  See https://github.com/aws/aws-sdk-java-v2#importing-the-bom

**Comment by shanegu** [comment]
@zoewangg Thanks for looking into this, what do u mean mixed version of SDK client? do u mean V1 and V2? I only used V2 and did use BOM, is your code also simply just: s3AsyncClient = S3AsyncClient.create();?

`<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>${aws.lambda.java.core.version}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>dynamodb</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sns</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>ssm</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>apache-client</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
        
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>netty-nio-client</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${aws.sdk.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>`

**Comment by zoewangg** [comment]
Hi @shanegu apologies for the delayed response. Yes, I tried `s3AsyncClient = S3AsyncClient.create();` 

Could you check if your jar actually contains `EndpointAddressInterceptor` class?

**Comment by shanegu** [comment]
@zoewangg sorry for late response as well, I found the issue:
I ran: 
`find . -name *.jar -print0 |  xargs -0 -I '{}' sh -c 'jar tf {} | grep EndpointAddressInterceptor.class &&  echo {}'
`
Indeed I didn't find the class, I had maven shade plugin to minimize the jar file, so it was excluded, the reason I had to do this is the cold start issue when using java and I tried to minimize jar file and didn't expect some of packages from s3 will be excluded, after I unset minimize the jar file in pom, it worked. I did notice my cold start time increased from 5.5 second to 6.5 second and jar file size increased by 4 MB. Closing this issue

**Comment by zoewangg** [comment]
Which http client are you using?  `URLConnectionHTTPClient` has the quickest startup time among three supported http clients.

Sample code

```
SnsClient.builder()
            .region(xxx)
            .httpClientBuilder(UrlConnectionHttpClient.builder())
            .credentialsProvider(EnvironmentVariableCredentialsProvider.create())
            .build()
```

I should also note that by default the SDK pulls in both apache http client and netty http client dependencies, so you can exclude them in your pom file if you are not using them to reduce the jar size.

```
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <version>${awsjavasdk.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>netty-nio-client</artifactId>
                    <groupId>software.amazon.awssdk</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by MarkusKramer** [comment]
@shanegu you don't have to disable jar minimizing. you can work around it with
```
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <minimizeJar>true</minimizeJar>
                    <filters>
                        <filter>
                            <artifact>software.amazon.awssdk:s3</artifact>
                            <includes>
                                <include>**</include>
                            </includes>
                        </filter>
                    </filters>
                </configuration>
```

or by explicitly including all classes listed in "execution.interceptors" in your code like
`EnableTrailingChecksumInterceptor.class.toString()`

It would be nice if the AWS SDK would not dynamically load these classes. It makes live with tools that need to statically analyze your code (like the shade plugin or graal's native image tool) so much easier.
