### ISSUE TITLE
Not able to make request with SQSAsyncClient - Credentials must not be null.

### ISSUE THREAD

**Issue by posilva** [aws/aws-sdk-java-v2#1587]
## Expected Behavior

When calling the receiveMessageRequest is expected to receive a response 
## Current Behavior

Received an exception:
`java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Credentials must not be null.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.miniclip.egraph.verticles.SQSConsumerVerticle.createClient(SQSConsumerVerticle.java:97)
	at com.miniclip.egraph.verticles.SQSConsumerVerticle.start(SQSConsumerVerticle.java:49)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Credentials must not be null.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
	at software.amazon.awssdk.core.internal.http.AmazonAsyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonAsyncHttpClient.java:195)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.invoke(BaseAsyncClientHandler.java:263)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:205)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:87)
	at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:51)
	at software.amazon.awssdk.services.sqs.DefaultSqsAsyncClient.receiveMessage(DefaultSqsAsyncClient.java:1149)
	at com.miniclip.egraph.verticles.SQSConsumerVerticle.createClient(SQSConsumerVerticle.java:94)
	... 9 more
Caused by: java.lang.NullPointerException: Credentials must not be null.
	at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:117)
	at software.amazon.awssdk.auth.signer.params.Aws4SignerParams.<init>(Aws4SignerParams.java:42)
	at software.amazon.awssdk.auth.signer.params.Aws4SignerParams$BuilderImpl.build(Aws4SignerParams.java:206)
	at software.amazon.awssdk.auth.signer.internal.BaseAws4Signer.sign(BaseAws4Signer.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.signRequest(SigningStage.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.execute(SigningStage.java:49)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.execute(SigningStage.java:35)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.doExecute(AsyncRetryableStage.java:208)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:107)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:102)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:51)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.execute(AsyncExecutionFailureExceptionReportingStage.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.execute(AsyncExecutionFailureExceptionReportingStage.java:29)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.execute(AsyncApiCallTimeoutTrackingStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.execute(AsyncApiCallTimeoutTrackingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.AmazonAsyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonAsyncHttpClient.java:193)
	... 15 more`

## Steps to Reproduce (for bugs)

```
AwsCredentialsProvider creds = StaticCredentialsProvider.create(AwsBasicCredentials.create(c.accessKeyId(),c.secretAccessKey()));

    SqsAsyncClient sqsClient = SqsAsyncClient.builder().credentialsProvider(creds)
            .region(Region.of(this.awsRegion.toString()))
            .build();

    CompletableFuture<ReceiveMessageResponse> futureGet = sqsClient.receiveMessage(
            ReceiveMessageRequest.builder().queueUrl(this.sqsUrl)
                    .build());
    futureGet.get();
```
## Your Environment

* AWS Java SDK version used: 2.10.44

* JDK version used:  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
* Operating System and version: MacOS Mojave

**Comment by posilva** [comment]
This as a conflict between dependencies now everything is working properly

**Comment by debora-ito** [comment]
@posilva Thank you for the follow-up, I was trying to reproduce it with no success.

**Comment by posilva** [comment]
Actually I will try to reproduce the issue in a separated project and share here. I think it might help others.

**Comment by vatevr** [comment]
I have very similar issue with `S3AsyncClient` after 2.10.56 version upgrade.
Turns out for local mocks the Signer needs to be overriden when the mocks run on unsecured server.
This fixed it

```java
Map<SdkAdvancedClientOption<?>, Signer> signerOption = new HashMap<>();
    signerOption.put(SdkAdvancedClientOption.SIGNER, new NoOpSigner());

    return builder()
      .credentialsProvider(creds)
      .overrideConfiguration(ClientOverrideConfiguration.builder()
        .advancedOptions(signerOption)
        .build())
      .endpointOverride(URI.create(s3Endpoint))
      .build();
```
