### ISSUE TITLE
[Feature Request] DescribeImagesPaginator or ListImages of Ec2Client

### ISSUE THREAD

**Issue by cielong** [aws/aws-sdk-java-v2#1592]
The `describeImages()` method of the `Ec2Client` takes too much time and without any filters, it throws read timeout exception. 
In my case, I want to retrieve all the ids of available images given account and region and I don't care about the filters since I don't want to narrow down the range.
Since there's no api to directly retrieve all the ids and thus I have to work around it using the `describeImages()`, as follows,
```Java
        DescribeImagesResponse response = awsClientFactory
                .getEC2Client(accessKey, secretKey, region)
                .describeImages();

        List<String> items = response.images().stream()
                .map(Image::imageId)
                .collect(Collectors.toList());
```
However, using this I received timeout exception after long time waiting, this just makes no sense for me that there's no pagination, no way to specify the limit number and no way to get only some fields of all the images directly through api.
The error are as follows.
> Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Read timed out
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.handleThrownException(RetryableStage.java:136)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:94)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.ec2.DefaultEc2Client.describeImages(DefaultEc2Client.java:9360)
	at software.amazon.awssdk.services.ec2.Ec2Client.describeImages(Ec2Client.java:16715)

**Comment by debora-ito** [comment]
Hi @cielong, I'll pass your feature request over to the service team behind the EC2 API. 

In the meantime you can try to change the value of connection timeout - https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/section-client-configuration.html#http-transport-configuration

Let us know if that helps.

**Comment by debora-ito** [comment]
The EC2 team added the feature request to their backlog, so I'll go ahead and close this. Feel free to reach out if you have any other question.
