### ISSUE TITLE
Kinesis Client - Unable to parse JSON payload: Illegal length for VALUE_STRING

### ISSUE THREAD

**Issue by razem-io** [aws/aws-sdk-java-v2#1595]
## Expected Behavior
Getting a list of kinesis streams.

## Current Behavior
Executing `kinesisClient.listStreams()` (or any other operation) results in the following exception.

```
2020-01-17 16:07:43 [scala-execution-context-global-32] DEBUG software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain:84 - Loading credentials from EnvironmentVariableCredentialsProvider()
2020-01-17 16:07:43 [scala-execution-context-global-32] DEBUG software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain:84 - Creating an interceptor chain that will apply interceptors in the following order: []
2020-01-17 16:07:43 [scala-execution-context-global-32] DEBUG software.amazon.awssdk.request:84 - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=kinesis.eu-central-1.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2020-01-17 16:07:43 [scala-execution-context-global-32] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer:84 - AWS4 String to sign: AWS4-HMAC-SHA256
20200117T150743Z
20200117/eu-central-1/kinesis/aws4_request
9ff7083d2ab23444ed52a5a0d59aed711f8d1e46ea17d1030461364f0c2005e7
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.http.nio.netty.internal.http2.Http2PingHandler:84 - Received PING ACK from channel [id: 0x4f3f4029, L:/10.35.5.44:39294 - R:kinesis.eu-central-1.amazonaws.com/3.123.12.193:443]
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.request:84 - Received successful response: 200
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.requestId:84 - x-amzn-RequestId : ee5d8c6e-e6b5-fea8-b8c6-5c6e157577b9
2020-01-17 16:07:44 [sdk-async-response-0-0] DEBUG software.amazon.awssdk.request:84 - Retryable error detected, will retry in 56ms, attempt number 1
2020-01-17 16:07:44 [sdk-ScheduledExecutor-2-0] DEBUG software.amazon.awssdk.request:84 - Retrying Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=kinesis.eu-central-1.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2020-01-17 16:07:44 [sdk-ScheduledExecutor-2-0] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer:84 - AWS4 String to sign: AWS4-HMAC-SHA256
20200117T150744Z
20200117/eu-central-1/kinesis/aws4_request
232e0c6813863f9edda454d03a62c691f3ac948e1754a8988f3352f45476f7bf
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.request:84 - Received successful response: 200
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.requestId:84 - x-amzn-RequestId : c912f4f8-6fe8-ac9c-9f89-24f89c28258d
2020-01-17 16:07:44 [sdk-async-response-0-1] DEBUG software.amazon.awssdk.request:84 - Retryable error detected, will retry in 132ms, attempt number 2
2020-01-17 16:07:44 [sdk-ScheduledExecutor-2-0] DEBUG software.amazon.awssdk.request:84 - Retrying Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=kinesis.eu-central-1.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2020-01-17 16:07:44 [sdk-ScheduledExecutor-2-0] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer:84 - AWS4 String to sign: AWS4-HMAC-SHA256
20200117T150744Z
20200117/eu-central-1/kinesis/aws4_request
e0f22e93d6463c397849536a1d9d5a101e10b13d27472cd79a482a2624353c85
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.request:84 - Received successful response: 200
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.requestId:84 - x-amzn-RequestId : edecafa3-d234-e119-bb77-7fa321f46808
2020-01-17 16:07:44 [sdk-async-response-0-2] DEBUG software.amazon.awssdk.request:84 - Retryable error detected, will retry in 186ms, attempt number 3
2020-01-17 16:07:44 [sdk-ScheduledExecutor-2-1] DEBUG software.amazon.awssdk.request:84 - Retrying Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=kinesis.eu-central-1.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2020-01-17 16:07:44 [sdk-ScheduledExecutor-2-1] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer:84 - AWS4 String to sign: AWS4-HMAC-SHA256
20200117T150744Z
20200117/eu-central-1/kinesis/aws4_request
eef80514fcda96dc18d21e7ebf8342e182807cabf0fa4309cc05a672374b0dbc
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.request:84 - Received successful response: 200
2020-01-17 16:07:44 [aws-java-sdk-NettyEventLoop-1-2] DEBUG software.amazon.awssdk.requestId:84 - x-amzn-RequestId : c51d8da9-e7aa-918b-9386-5da9146a189a
2020-01-17 16:07:44.846+0100 error [KinesisFetcherService] Error during check execution.
java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Illegal length for VALUE_STRING: 2470331543460999781
 at [Source: (software.amazon.awssdk.core.io.ReleasableInputStream); line: -1, column: 9]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at tqrs.ingestion.td1.KinesisFetcherService.$anonfun$check$1(KinesisFetcherService.scala:55)
	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:185)
	at cats.effect.IO.unsafeRunTimed(IO.scala:320)
	at cats.effect.IO.unsafeRunSync(IO.scala:239)
	at valmob.util.cats.ServiceIO.$anonfun$startScheduler$1(ServiceIO.scala:24)
	at monix.execution.internal.RunnableAction.run(RunnableAction.scala:24)
	at monix.execution.schedulers.ReferenceScheduler$$anon$2.run(ReferenceScheduler.scala:71)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Illegal length for VALUE_STRING: 2470331543460999781
 at [Source: (software.amazon.awssdk.core.io.ReleasableInputStream); line: -1, column: 9]
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:126)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:108)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$1(MakeAsyncHttpRequestStage.java:171)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal length for VALUE_STRING: 2470331543460999781
 at [Source: (software.amazon.awssdk.core.io.ReleasableInputStream); line: -1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.dataformat.cbor.CBORParser._decodeExplicitLength(CBORParser.java:2773)
	at com.fasterxml.jackson.dataformat.cbor.CBORParser._finishTextToken(CBORParser.java:1947)
	at com.fasterxml.jackson.dataformat.cbor.CBORParser.getText(CBORParser.java:1334)
	at software.amazon.awssdk.protocols.json.internal.dom.JsonDomParser.parseToken(JsonDomParser.java:53)
	at software.amazon.awssdk.protocols.json.internal.dom.JsonDomParser.parse(JsonDomParser.java:41)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:167)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:79)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$5(BaseClientHandler.java:232)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:129)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:171)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:68)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:287)
	at com.typesafe.netty.HandlerPublisher.complete(HandlerPublisher.java:408)
	at com.typesafe.netty.HandlerPublisher.handlerRemoved(HandlerPublisher.java:395)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:972)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:641)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:481)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:427)
	at com.typesafe.netty.http.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:328)
	at com.typesafe.netty.http.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:189)
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:165)
	at com.typesafe.netty.http.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at software.amazon.awssdk.http.nio.netty.internal.LastHttpContentHandler.channelRead(LastHttpContentHandler.java:43)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.onDataRead(Http2ToHttpInboundAdapter.java:66)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:44)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:38)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doRead0(AbstractHttp2StreamChannel.java:851)
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doBeginRead(AbstractHttp2StreamChannel.java:793)
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.beginRead(AbstractHttp2StreamChannel.java:765)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:685)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:670)
	at software.amazon.awssdk.http.nio.netty.internal.http2.FlushOnReadHandler.read(FlushOnReadHandler.java:40)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:685)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:670)
	at com.typesafe.netty.HandlerPublisher.requestDemand(HandlerPublisher.java:86)
	at com.typesafe.netty.http.HttpStreamsHandler$1.requestDemand(HttpStreamsHandler.java:157)
	at com.typesafe.netty.HandlerPublisher.flushBuffer(HandlerPublisher.java:311)
	at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:258)
	at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41)
	at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:452)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

```
After a short debug session, I can confirm that we actually get a json response which looks good.

```
{"HasMoreStreams":false,"StreamNames":["Foo","Bar","foo-bar","Foo-Bar-FOO"]}
```

However it can not be parsed.

## Possible Solution
no clue

## Steps to Reproduce (for bugs)
Just trying to get a list of streams.

## Your Environment

* AWS Java SDK version used: 2.10.50
* JDK version used: openjdk version "11.0.5" 2019-10-15
* Operating System and version: ArchLinux 5.3.12-arch1-1

**Comment by jeffalder** [comment]
An eagle-eyed commenter on https://github.com/aws/aws-sdk-java/issues/1106#issuecomment-343526589 deciphered that original number as `"code": ` and this number (247...812) converts to ASCII as `"hasMore`. Clearly something is bad in the json or in Jackson.

**Comment by jeffalder** [comment]
I think the SDK, or Jackson, is thinking it should be parsing CBOR when it's getting ASCII JSON. I see the error traces say `Illegal length for VALUE_STRING`. ASCII `{` is 0x7B, which, as a leading byte in CBOR, breaks into 3-bit and 5-bit values 0b011 and 0b11011. The 3-bit value 0b011 denotes a text string; 0b11011 (27 decimal) indicates "Next 8 bytes is uint64_t for payload length". That would explain why strings like `"hasMore` and `"code": ` are being reported as string lengths: The beginning of the payload is `{"hasMore` or `{"code": `, which is a perfectly legitimate start to ASCII JSON.

It seems like a reasonable workaround for this would be to attempt to parse CBOR if configured to do so; if parsing fails, fall back to attempting to parse ASCII JSON (maybe only if the response starts with `{"` if you want to be super strict). These kinds of parse exceptions should be relatively rare, so I'd be less concerned about performance. I've also only seen these reports for Kinesis. That sounds like a service-level issue, not an SDK bug, and it should certainly be fixed upstream.

ref: https://en.wikipedia.org/wiki/CBOR

**Comment by jeffalder** [comment]
Oh sure; because Kinesis is the only service whose artifact relates to `aws-cbor-protocol`.

**Comment by razem-io** [comment]
Okay, I do not know why I need to set this but if I do

```System.setProperty("aws.cborEnabled", "false")```

everything works as expected. When connection to aws with the official client I would expect this to be the correct default.

**Comment by jeffalder** [comment]
@razem-io It would help the SDK team identify the source of the problem if you're able to capture the full request and response when this error occurs. I'd have questions, like is there a specific API call that is failing? Is there a CBOR content-type on both request and response? Is it failing after a period of time after setting up the client, implying a token-expiration issue?

It may be worth disabling CBOR by default in the SDK until the source of the issue can be identified.

My impression has been that CBOR _generally_ works, there's just an issue in the Kinesis service that doesn't respect CBOR properly at _some_ point. Is that your experience, as well?

**Comment by zoewangg** [comment]
@jeffalder Thank you a lot for helping troubleshooting the issue! 😃 

@razem-io, I'm not able to reproduce the issue. As @jeffalder mentioned, if you could provide the payload of the response(be sure to redact sensitive info), it would help us find out the root cause.

**Comment by razem-io** [comment]
The source that did not work (same git hash) yesterday, now works flawless. I will close this for now, as I can't reproduce it. If I ever encounter the problem again, I will try to provide additional information here.
