### ISSUE TITLE
Unable to load credentials from system settings

### ISSUE THREAD

**Issue by mintu19** [aws/aws-sdk-java-v2#1775]
Unable to load credentials from system settings

## Describe the issue
I am using sdk to update bucket policy of my s3 bucket in ktor (kotlin) application. I have set key and secret in environment variable and verified that those variables are present by `logger.info(System.getenv("AWS_ACCESS_KEY_ID"))`

But i am getting this error
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId).
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.auth.credentials.internal.SystemSettingsCredentialsProvider.resolveCredentials(SystemSettingsCredentialsProvider.java:58)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:91)
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:104)
	at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:72)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:87)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.s3.DefaultS3Client.putBucketPolicy(DefaultS3Client.java:6430)
	at software.amazon.awssdk.services.s3.S3Client.putBucketPolicy(S3Client.java:13512)
```

I am using s3 client this way

```
S3Client.create().use { s3Client ->
                s3Client.putBucketPolicy { b ->
                    b.bucket(AWS_BUCKET_FIRST_CAPTURES).policy(policyFirstCaptures.toJson())
                }
            }

```
## Your Environment
* AWS Java SDK version used: 2.11.11
* JDK version used: 1.8.0_172
* Operating System: Windows 10

**Comment by mintu19** [comment]
verified that credentials are loaded from environment and s3client is working but this error is still printed in console maybe because system credential are checked before environment and they failed.

**Comment by zoewangg** [comment]
Yes, system properties take precedence over environment variables.

https://github.com/aws/aws-sdk-java-v2/blob/b5fb047dc6daf876bb176dd8ef912ec177745288/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java#L25-L33

**Comment by zoewangg** [comment]
Were the logs printed out DEBUG level logs? The log statement is intended for troubleshooting use.

**Comment by mintu19** [comment]
yes i think they were debug level
