### ISSUE TITLE
aws sdk not theadsafe?

### ISSUE THREAD

**Issue by JJonesAtAvaya** [aws/aws-sdk-java-v2#1779]
I would like to use the aws sdk in a multithreaded app, however, I see evidence it is not threadsafe

If I run a simple single-threaded example, it works fine.  But in the context of a multithreaded app, it consistently fails

example code (used in an async thread)
```
public KinesisTask get() {
    final List<String> rows = task.getRows();
    String json = new Gson().toJson(rows);
    PutRecordRequest putRecordRequest = PutRecordRequest.builder()
        .partitionKey(PARTITION_KEY)
        .streamName(streamName)
        .data(SdkBytes.fromByteArray(json.getBytes()))
        .build();

    CompletionStage<PutRecordResponse> kinesisResponse = kinesisAsyncClient.putRecord(putRecordRequest);
    task.setResult(KinesisResult.COMPLETED);
    CompletableFuture<PutRecordResponse> kinesisResponseFuture = kinesisResponse.toCompletableFuture();
    kinesisResponseFuture.whenComplete((resp, err) -> {
      if (err != null) {
          log.error(err.toString());
          task.setResult(KinesisResult.COMPLETED_WITH_ERRORS);
      }
      if (resp != null) {
        log.info(resp.toString());
      }
    });
    return task;

```
## Describe the issue
When waiting for the completable future response of the KinesisAsyncClient, it consistently fails with this stack trace:
```
2020-04-14 18:06:51,198 [pool-2-thread-1  ] DEBUG software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain - Loading credentials from ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profiles=[Profile(name=default, properties=[region, aws_access_key_id, aws_session_token, aws_secret_access_key])]))
2020-04-14 18:06:51,200 [pool-2-thread-1  ] DEBUG software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain - Creating an interceptor chain that will apply interceptors in the following order: []
2020-04-14 18:06:51,242 [pool-2-thread-1  ] DEBUG software.amazon.awssdk.request       - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=kinesis.us-east-1.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2020-04-14 18:06:51,247 [pool-2-thread-1  ] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer - AWS4 String to sign: AWS4-HMAC-SHA256
20200415T010651Z
20200415/us-east-1/kinesis/aws4_request
b70b913d88c80c630ed02448ec339f0a2a9b1905c82d90c22b497b941304ed9b
2020-04-14 18:06:51,358 [pool-2-thread-1  ] DEBUG io.netty.handler.ssl.JdkSslContext   - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1] 
2020-04-14 18:06:51,358 [pool-2-thread-1  ] DEBUG io.netty.handler.ssl.JdkSslContext   - Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA]


2020-04-14 18:10:18,816 [aws-java-sdk-NettyEventLoop-1-8] WARN  io.netty.channel.ChannelInitializer  - Failed to initialize a channel. Closing: [id: 0xd83aff45]
java.lang.NoClassDefFoundError: io/netty/handler/codec/http2/Http2MultiplexHandler
	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.configureHttp2(ChannelPipelineInitializer.java:129)
	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.channelCreated(ChannelPipelineInitializer.java:87)
	at io.netty.channel.pool.SimpleChannelPool$1.initChannel(SimpleChannelPool.java:113)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
2020-04-14 18:10:18,820 [aws-java-sdk-NettyEventLoop-1-11] DEBUG software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor - Failed to create connection to https://kinesis.us-east-1.amazonaws.com/
io.netty.channel.ExtendedClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(...)(Unknown Source)
2020-04-14 18:10:18,821 [aws-java-sdk-NettyEventLoop-1-11] DEBUG software.amazon.awssdk.request       - Retryable error detected, will retry in 5ms, attempt number 1
2020-04-14 18:10:18,827 [sdk-ScheduledExecutor-4-0] DEBUG software.amazon.awssdk.request       - Retrying Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=kinesis.us-east-1.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2020-04-14 18:10:18,828 [sdk-ScheduledExecutor-4-0] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer - AWS4 String to sign: AWS4-HMAC-SHA256
20200415T011018Z
20200415/us-east-1/kinesis/aws4_request
caf61b3d802f3cd4a7857cfd376c5b3ca7c029cfa1fc9abce5ec5906a853c859
2020-04-14 18:10:18,830 [aws-java-sdk-NettyEventLoop-1-13] WARN  io.netty.channel.ChannelInitializer  - Failed to initialize a channel. Closing: [id: 0x9d5ae1cd]
java.lang.NoClassDefFoundError: io/netty/handler/codec/http2/Http2MultiplexHandler
	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.configureHttp2(ChannelPipelineInitializer.java:129)
	at software.amazon.awssdk.http.nio.netty.internal.ChannelPipelineInitializer.channelCreated(ChannelPipelineInitializer.java:87)
	at io.netty.channel.pool.SimpleChannelPool$1.initChannel(SimpleChannelPool.java:113)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

```

## Your Environment

* AWS Java SDK version used: 2.2.6 (also tried 2.2.11)
* JDK version used: 1.8
* Operating System and version: (OSX Catalina 10.15.2)

**Comment by JJonesAtAvaya** [comment]
It suddenly started working without errors...

I had these dependencies in the client lib which was talking to Kinesis, but it seemed to actually resolve it to add the dependency to the product which was linking with the client
```

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.48.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http2</artifactId>
            <version>4.1.48.Final</version>
        </dependency>

```
