### ISSUE TITLE
GetMetricStatisticsRequest Instant parameter must be truncated to seconds

### ISSUE THREAD

**Issue by vkdot** [aws/aws-sdk-java-v2#1820]
## Describe the bug
When using `startTime` or `endTime` of `GetMetricStatisticsRequest.Builder` it requires `Instant` to be truncated to seconds, otherwise and error `CloudWatchException: timestamp must follow ISO8601` is produced.

## Expected Behavior
The following code ends with a successful response at any time:
```java
    Instant end = Instant.now();
    Instant start = end.minus(1, ChronoUnit.DAYS);

    CloudWatchClient client = CloudWatchClient.create();
    GetMetricStatisticsRequest request = GetMetricStatisticsRequest.builder()
        .namespace("AWS/ApiGateway").metricName("Count").statistics(Statistic.SUM).startTime(start)
        .endTime(end).period(SIX_HOURS_IN_SEC).build();
    client.getMetricStatistics(request);
```

## Current Behavior
The code above ends with `CloudWatchException`, message: `timestamp must follow ISO8601`.

Stack trace:
```
software.amazon.awssdk.services.cloudwatch.model.CloudWatchException: timestamp must follow ISO8601 (Service: CloudWatch, Status Code: 400, Request ID: <REDACTED>
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:189)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:121)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:147)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:101)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.cloudwatch.DefaultCloudWatchClient.getMetricStatistics(DefaultCloudWatchClient.java:1388)
```

When examined the HTTP request by debugging it contains ISO8601 timestamp including nanoseconds, e.g. `2020-05-07T11:03:24.098123000Z`.

Mitigation is to run replace the first line of example code with:
```java
    Instant end = Instant.now().truncatedTo(ChronoUnit.SECONDS);
```

## Steps to Reproduce
Run the example code above.

## Possible Solution
I would expect SDK will automatically truncate the instant, or produce a meaningful error as formatting is not part of the input and user cannot change it.

## Context
SDK behavior is unclear and it requires a user to run debugger.

## Your Environment
* AWS Java SDK version used: 2.13.11
* JDK version used: OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
Hi @vkdot thank you for reaching out. The SDK does not make any validation in the values specified in the request, it is not manageable to maintain validations for 100+ AWS services. 
In cases like this we recommend you consult the [API Reference](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html) docs or the [Javadoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/cloudwatch/model/GetMetricStatisticsRequest.html#startTime--) of the operation, they should contain a description for each field.

In addition, I tried to reproduce the error you're seeing but I wasn't able to. Using your sample code I specified start and end times with nanoseconds, and got a successful response.

You can [enable wire logs](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/java-dg-logging.html#sdk-java-logging-verbose) and check the format of the timestamps that are being sent in the request. If you choose to provide us the wire logs, please make sure there's no sensitive information.

**Comment by vkdot** [comment]
Hi @debora-ito thank you for your reply.

Please, find wire logs below. I hope it will be helpful. Sensitive fields were replaced with `__REDACTED__`.
```
2020-05-14 09:03:11 [main] DEBUG software.amazon.awssdk.request:84 - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=monitoring.eu-west-1.amazonaws.com, encodedPath=, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent], queryParameters=[])
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "POST / HTTP/1.1[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Host: monitoring.eu-west-1.amazonaws.com[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-invocation-id: __REDACTED__[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-retry: 0/0/[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=__REDACTED__/eu-west-1/monitoring/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;x-amz-date, Signature=__REDACTED__[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Type: application/x-www-form-urlencoded; charset=utf-8[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "User-Agent: aws-sdk-java/2.13.11 Windows_10/10.0 OpenJDK_64-Bit_Server_VM/11.0.7+10-LTS Java/11.0.7 vendor/Amazon.com_Inc. io/sync http/Apache[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "X-Amz-Date: 20200514T080311Z[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Length: 214[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:87 - http-outgoing-0 >> "Action=GetMetricStatistics&Version=2010-08-01&Namespace=AWS%2FApiGateway&MetricName=Count&StartTime=2020-05-13T08%3A03%3A11.214243300Z&EndTime=2020-05-14T08%3A03%3A11.214243300Z&Period=21600&Statistics.member.1=Sum"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "HTTP/1.1 400 Bad Request[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "x-amzn-RequestId: __REDACTED__[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Content-Type: text/xml[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Content-Length: 281[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Date: Thu, 14 May 2020 08:03:11 GMT[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Connection: close[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<ErrorResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">[\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "  <Error>[\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "    <Type>Sender</Type>[\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "    <Code>MalformedInput</Code>[\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "    <Message>timestamp must follow ISO8601</Message>[\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "  </Error>[\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "  <RequestId>__REDACTED__</RequestId>[\n]"
2020-05-14 09:03:12 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "</ErrorResponse>[\n]"
2020-05-14 09:03:12 [main] DEBUG software.amazon.awssdk.request:84 - Received error response: software.amazon.awssdk.services.cloudwatch.model.CloudWatchException: timestamp must follow ISO8601 (Service: CloudWatch, Status Code: 400, Request ID: __REDACTED__)
```

**Comment by debora-ito** [comment]
@vkdot your Instant is returning a timestamp with 9 decimal places in the seconds portion, and in my tests I see 6 decimal places:
- `2020-05-13T08:03:11.214243300Z`  in your logs and 
- `2020-06-04T17:30:18.470704Z` in my tests

This is likely due to the difference of JDK + OS, I'm running Java 11 in MacOS. Having 9 decimal places is still a valid ISO8601, so the error message `timestamp must follow ISO8601` is not helpful in this case. I will contact the CloudWatch API team and ask them to make the message more clear.

**Comment by cartwrightian** [comment]
Previsouly working code ported from v1 of the AWS Java SDK to v2 of the SDK throws this exception when creating a MetricDatum using the builder(). The constructor version in v1 of the SDK took a date and I assume peformed the necessary truncation itself.

**Comment by yhware** [comment]
@debora-ito  Is there any progress on this issue? I'm getting the same error \

![image](https://user-images.githubusercontent.com/7122981/106892565-93756400-672f-11eb-9977-a4598f048478.png) \
JDK is Amazon Corretto JDK11.0.4._10 and OS is Windows 10 Enterprise 19042.746

**Comment by debora-ito** [comment]
No updates at this time. The workaround is to truncate the value to the second or millisecond:

```java
Instant endTime = Instant.now().truncatedTo(ChronoUnit.MILLIS);
```

**Comment by salokanto** [comment]
Just ran into this error, too. AWS SDK 2.16.13.

When running on AdoptOpenJDK & Linux, it seems that it only happens on JDK 15. 

No errors on `adoptopenjdk/openjdk14:alpine-jre`.
Fails on `adoptopenjdk/openjdk15:alpine-jre`.

**Comment by youngm** [comment]
I ran into this issue also Windows + AdoptOpenJDK 11.0.9.1+1

**Comment by agjones** [comment]
Also had the same issue, only on amazoncorretto:17 using ECS/fargate

**Comment by debora-ito** [comment]
For visibility to other SDKs, I'm moving this to the `aws-sdk` repository.
