### ISSUE TITLE
source_profile behavior differs from CLI

### ISSUE THREAD

**Issue by PhroZenOne** [aws/aws-sdk-java-v2#1842]
I have a working setup with ~/.aws/credentials and ~/.aws/config that the CLI have no problems working with, but when I try to use this SDK it crashes with 

    Invalid profile file: Circular relationship detected with profiles [dev].

In my config I have:

```
[profile dev]
source_profile=dev
adfs_config.role_arn = <some.login.proxy.role>
role_arn = <some.role>
region = eu-north-1
output = json
adfs_config.ssl_verification = True
adfs_config.adfs_host = <some.domain>
adfs_config.session_duration = 3600
adfs_config.provider_id = urn:amazon:webservices
adfs_config.sspi = False
adfs_config.u2f_trigger_default = True
```

And in my credentials I have:

```
[dev]
aws_access_key_id = <access.key>
aws_secret_access_key = <access.secret>
aws_session_token = <session.token>
aws_security_token = <security.token>
```

If I remove the source_profile, the CLI complains that it needs a source_profile when using role_arn but adding it breaks the SDK

I do expect the SDK and the CLI to work with the same config and credentials files. 

The same issue is noted as a sidenote in #1512 so at least I'm not alone in this. :)

Stacktrace from SDK:

```
Invalid profile file: Circular relationship detected with profiles [dev].
	at software.amazon.awssdk.utils.Validate.validState(Validate.java:384)
	at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.roleAndSourceProfileBasedProfileCredentialsProvider(ProfileCredentialsUtils.java:192)
	at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.credentialsProvider(ProfileCredentialsUtils.java:111)
	at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.lambda$roleAndSourceProfileBasedProfileCredentialsProvider$0(ProfileCredentialsUtils.java:201)
	at java.util.Optional.flatMap(Optional.java:241)
	at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.roleAndSourceProfileBasedProfileCredentialsProvider(ProfileCredentialsUtils.java:200)
	at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.credentialsProvider(ProfileCredentialsUtils.java:111)
	at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.credentialsProvider(ProfileCredentialsUtils.java:88)
	at software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider.lambda$new$0(ProfileCredentialsProvider.java:72)
	at java.util.Optional.flatMap(Optional.java:241)
	at software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider.<init>(ProfileCredentialsProvider.java:72)
	at software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider.<init>(ProfileCredentialsProvider.java:43)
	at software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider$BuilderImpl.build(ProfileCredentialsProvider.java:211)
	at software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider.create(ProfileCredentialsProvider.java:113)
	at xxx.client.FileStorageClient.<init>(FileStorageClient.java:41)
	at xxx.main(FileStorageClient.java:75)

Process finished with exit code 1
```

## Environment
* AWS Java SDK: 2.13.7
* AWS CLI version used: aws-cli/1.18.17 Python/3.7.6 Darwin/18.7.0 botocore/1.15.17
* JDK: 1.8.0_201
* Operating System and version: mac mojave 10.14.6

**Comment by millems** [comment]
```
[profile dev]
source_profile = dev
```

Unfortunately this circular relationship isn't supported in the majority of the SDKs. The CLI supporting it is outside of the specification. You'll need to split your profile into a dedicated source profile. Something like...

~/.aws/config
```
[profile dev]
source_profile = source
adfs_config.role_arn = <some.login.proxy.role>
role_arn = <some.role>
region = eu-north-1
output = json
adfs_config.ssl_verification = True
adfs_config.adfs_host = <some.domain>
adfs_config.session_duration = 3600
adfs_config.provider_id = urn:amazon:webservices
adfs_config.sspi = False
adfs_config.u2f_trigger_default = True
```

~/.aws/configuration
```
[source]
aws_access_key_id = <access.key>
aws_secret_access_key = <access.secret>
aws_session_token = <session.token>
aws_security_token = <security.token>
```
