### ISSUE TITLE
Memory leak leading to java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by atilpaiMomentFeed** [aws/aws-sdk-java-v2#1867]
Experiencing a problem with our Kinesis Consumer application

## Describe the issue
We are using a KinesisAsyncClient with Netty and potentially running into memory leak issues. Our producer rate is 15records/ sec. Consumer rate: batch size 100, batch await 30s

## Steps to Reproduce
I believe if you run a consumer app with our config, you will see similar behaviour. We are using Alpakka Kinesis library.

## Current Behavior
**Expected behaviour:** Stable application consuming stream data.
**Actual behaviour**: Everytime we increase heap size, the app roofs max usage, crashes and restarts.

**Warning:**
2020-05-27 21:18:51.196 [aws-java-sdk-NettyEventLoop-0-3] WARN  s.a.k.r.f.FanOutRecordsPublisher(321) - shardId-000000000000: [SubscriptionLifetime] - (FanOutRecordsPublisher#errorOccurred) @ 2020-05-27T21:18:37.316Z id: shardId-000000000000-49 – CompletionException/SdkClientException/java.lang.OutOfMemoryError: Java heap spacejava.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Java heap space at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:60)at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:74)at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:85)at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:144)at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:125)at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$WrappedErrorForwardingResponseHandler.onError(MakeAsyncHttpRequestStage.java:122)at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.lambda$notifyError$5(ResponseHandler.java:306)at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:179)at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:69)at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.notifyError(ResponseHandler.java:304)at software.amazon.awssdk.http.nio.netty.internal.utils.ExceptionHandlingUtils.tryCatch(ExceptionHandlingUtils.java:42)at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:267)at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:219)at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:407)at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:338)at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291)at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61)at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495)at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)at java.lang.Thread.run(Thread.java:748)Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Java heap spaceat software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43)at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:199)at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:143)... 24 common frames omittedCaused by: java.lang.OutOfMemoryError: Java heap space

**Error:**
2020-05-27 21:05:46.251 [aws-java-sdk-NettyEventLoop-0-3] ERROR io.netty.util.ResourceLeakDetector(320) - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.Recent access records: Created at:io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:96)io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:2151)io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1333)io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1233)io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1280)io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)java.lang.Thread.run(Thread.java:748)

**Error:**
2020-05-28 20:52:21.463 [mf-listings-health-service-akka.actor.default-dispatcher-13] ERROR akka.actor.ActorSystemImpl(77) - Uncaught error from thread [mf-listings-health-service-akka.actor.default-dispatcher-10]: Java heap space, shutting down ActorSystem[mf-listings-health-service] java.lang.OutOfMemoryError: Java heap space at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57) at java.nio.ByteBuffer.allocate(ByteBuffer.java:335) at software.amazon.eventstream.MessageDecoder.<init>(MessageDecoder.java:65) at software.amazon.eventstream.MessageDecoder.<init>(MessageDecoder.java:57) at software.amazon.awssdk.awscore.eventstream.EventStreamAsyncResponseTransformer.<init>(EventStreamAsyncResponseTransformer.java:108) at software.amazon.awssdk.awscore.eventstream.EventStreamAsyncResponseTransformer.<init>(EventStreamAsyncResponseTransformer.java:63) at software.amazon.awssdk.awscore.eventstream.EventStreamAsyncResponseTransformer$Builder.build(EventStreamAsyncResponseTransformer.java:623) at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClient.subscribeToShard(DefaultKinesisAsyncClient.java:2278) at software.amazon.kinesis.retrieval.fanout.FanOutRecordsPublisher.subscribeToShard(FanOutRecordsPublisher.java:281) at software.amazon.kinesis.retrieval.fanout.FanOutRecordsPublisher.subscribe(FanOutRecordsPublisher.java:542) at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29) at io.reactivex.Flowable.subscribe(Flowable.java:14349) at io.reactivex.Flowable.subscribe(Flowable.java:14295) at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82) at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:261) at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:226) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

## Your Environment
* AWS Java SDK version used: 2.13.6
* JDK version used: 8
* JAVA_TOOL_OPTIONS=-XX:+UseConcMarkSweepGC -Djdk.nio.maxCachedBufferSize=262144 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0

**Comment by atilpaiMomentFeed** [comment]
Do you think this is something to do with our service implementation or something to do with Netty client itself?

**Comment by zoewangg** [comment]
What KCL version are you using?

Could you share the code snippet of how you create the kinesis client?

**Comment by atilpaiMomentFeed** [comment]
private val awsHttpClient: SdkAsyncHttpClient = NettyNioAsyncHttpClient.builder().maxConcurrency(100).build()

val amazonKinesisAsync: KinesisAsyncClient = KinesisAsyncClient
      .builder
      .credentialsProvider(AWSProvider.withDefaultProviderChain)
      .httpClient(awsHttpClient)
      .build

We are using KCL 2.0. The dynamo db and cloudwatch clients all share same SdkAsyncHttpClient

**Comment by zoewangg** [comment]
Would it be possible for you to take a heap dump to see if there's a memory leak?

Another config you can experimenting it with is the `initialWindowSize`

https://github.com/aws/aws-sdk-java-v2/blob/c8ec05b58a2aa1b60699b1b79e68cf179de93095/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/Http2Configuration.java#L110-L118

The window size is related to the HTTP/2 flow control and it primarily affects the throughput on the HTTP/2 connections and streams. Setting a value that that's too low will negatively impact throughput as the client will need to continuously send WINDOW_UPDATE frames to the remote endpoint to to get more data. A value that's too large can also be bad since the client will just end up buffering the data on the local side until it processes it.

The default initial window size in the SDK is 1MB. 

https://github.com/aws/aws-sdk-java-v2/blob/5333f578eeda44c5bbbcede41ce64527111919db/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java#L72

**Comment by atilpaiMomentFeed** [comment]
We are not using HTTP 2. 
Let me get you that heap dump

**Comment by zoewangg** [comment]
`KinesisAsyncClient` by default uses HTTP2 protocol :) 

```java
    @Override
    protected final AttributeMap serviceHttpConfig() {
        AttributeMap result = KinesisHttpConfigurationOptions.defaultHttpConfig();
        return result.merge(AttributeMap.builder().put(SdkHttpConfigurationOption.PROTOCOL, Protocol.HTTP2).build());
    }
```

**Comment by atilpaiMomentFeed** [comment]
I see. Thats good to know.

**Comment by halangode** [comment]
@atilpaiMomentFeed Can you please be more specific as to what changes you have done to fix this? I am also facing the same issue with KCL.

**Comment by maciejszumielewicz-360codelab** [comment]
@atilpaiMomentFeed can you provide us with solution which fixed this ? our team is facing the same problem ;/
