### ISSUE TITLE
versions 2.10.60 and above of sdk throw InternalServerError exception when using DynamoDB transactions

### ISSUE THREAD

**Issue by sihutch** [aws/aws-sdk-java-v2#1874]
## Describe the bug
We have a very comprehensive set of System Tests that we have been running for the last 18 months. We recently upgraded the aws-sdk from version 2.10.56 to 2.13.25 and our our test suite began to fail with occasional calls to transactWriteItems. Our test suite calls transactWriteItems hundreds of times and only fails maybe once or twice. I reran the test suite numerous times with version bisection from 2.10.56 to 2.13.25 which failed with the same transactWriteItems failure each time untilI reached 2.10.59 which succeeded. 
Our test suite (which has been running for some time) now passes every time with 2.10.59 but fails with a transactWriteItems on every version since then. 

## Expected Behavior
I expect the same test suite to pass (reasonably consistently) with versions of the sdk since 2.10.59

## Current Behavior
The tests fail with a least one InternaServerError from transactWriteItems on every run with any version since 2.10.60 - the same tests pass every time with 2.10.59

Example stack trace
`Internal server error (Service: DynamoDb, Status Code: 500, Request ID: KDGNGE98O67GG0VUO7E0GG88VRVV4KQNSO5AEMVJF66Q9ASUAAJG): software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException
software.amazon.awssdk.services.dynamodb.model.InternalServerErrorException: Internal server error (Service: DynamoDb, Status Code: 500, Request ID: KDGNGE98O67GG0VUO7E0GG88VRVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:81)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:61)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:74)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:114)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:87)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:61)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:198)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:122)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:148)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:102)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.transactWriteItems(DefaultDynamoDbClient.java:4079)`

## Possible Solution
We are using AWS Lambda and the UrlConnectionHttpClient (which was changed in this [commit](https://github.com/aws/aws-sdk-java-v2/commit/e84bdd4cbf2e57d99e4a5d838720010d39b09e17)  between 2.10.59 and 2.10.60 (may be unrelated but though I would let you know)

* AWS Java SDK version used:  fails with 2.10.60 and above
* JDK version used:  Java 8
* Operating System and version: AWS Lambda

**Comment by debora-ito** [comment]
Can you provide a reproducible sample code?

**Comment by sihutch** [comment]
I can try but it is tricky as the failures are a result of a very large suite of tests that I cannot easily reproduce. Is it possible that you can you use use a specific request id (e.g KDGNGE98O67GG0VUO7E0GG88VRVV4KQNSO5AEMVJF66Q9ASUAAJG) to see what is causing DDB to through an InternalServerError

**Comment by sihutch** [comment]
Does the time between the call to transactWriteItems and the failure (~ 3 seconds) suggest the client retying?

2020-06-04T19:40:34.996+01:00 | 2020-06-04 18:40:34.996 41117236-a70e-40a0-836f-4b7cee31f29c DEBUG TenantAwareDynamoDbClient:243 - TransactWriteItem for PutEntityRequest

and


2020-06-04T19:40:37.555+01:00 | Internal server error (Service: DynamoDb, Status Code: 500, Request ID: KDGNGE98O67GG0VUO7E0GG88VRVV4KQNSO5AEMVJF66Q9ASUAAJG)
-- | --

**Comment by debora-ito** [comment]
Before sending the issue to the service team I just want to be sure this is an issue with the service and not with the SDK, for example. If I send the request ID to the service team, the first thing they will ask for is a sample code to show what you are trying to do.

**Comment by sihutch** [comment]
The code sample below is what causes the error. We perform a transactional write to two tables (Item and Acl). 

`dynamoDbClient.transactionalWriteEntities(DynamoDbTransactionalWriteEntitiesRequest.builder()
                    .putEntity(DynamoDbPutEntityRequest.<Item> builder()
                            .entity(item)
                            .type(Item.class)
                            .build())
                    .putEntity(DynamoDbPutEntityRequest.<Acl> builder()
                            .entity(spaceManagerAcl)
                            .type(Acl.class)
                            .build())
                    .build());`

**Comment by debora-ito** [comment]
@sihutch `transactionalWriteEntities` is not a DynamoDB API, I cannot use it to reproduce the issue on my side. 

Can you provide a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example)? Please also include the values of the items and some context on your tables, because if the error you're seeing is an internal server error I imagine the values specified must have some effect.

**Comment by sihutch** [comment]
@debora-ito My apologies. I sent you our wrapping code. Here is the actual code. 

```java

        final ImmutableList<TransactWriteItem> allTransactWriteItems = buildTransactWriteItems(transactionalWriteEntitiesRequest);

        final TransactWriteItemsRequest transactWriteItemsRequest = TransactWriteItemsRequest.builder()
                .transactItems(allTransactWriteItems)
                .build();

        LOGGER.debug("TransactWriteItemsRequest: [{}]", transactWriteItemsRequest);
        final TransactWriteItemsResponse response = dynamoDbClient.transactWriteItems(transactWriteItemsRequest);
        LOGGER.debug("TransactWriteItemsResponse: [{}]", response);
        return response;
```
Below is the log output from `LOGGER.debug("TransactWriteItemsRequest: [{}]", transactWriteItemsRequest);`which shows the request details prior to the failing call to `dynamoDbClient.transactWriteItems(transactWriteItemsRequest);` . Note, I do not expect that you will be able to recreate this error with these values. Many identical requests succeed during our test run but at least one fails on every run with the InternalServer since 2.10.60 (and never on 2.10.59) - this version increase of software.amazon.awssdk is the only change that we have made - everything else is identical.

```
[
  TransactWriteItemsRequest(TransactItems=[
    TransactWriteItem(Put=Put(Item={
      metadata=AttributeValue(S={
        "cakes:name": "BaseST.purgeSpace"
      },
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      modifiedOn=AttributeValue(S=2020-06-06T06: 19: 29.125Z,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      typeVersion=AttributeValue(N=1,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      createdBy=AttributeValue(S=9f293ad9-7fb4-4da7-8656-fc34110cf87d,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      modifiedBy=AttributeValue(S=9f293ad9-7fb4-4da7-8656-fc34110cf87d,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      id=AttributeValue(S=3044f695-1c8d-44da-8f63-955628ffe44f,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      type=AttributeValue(S=sys: Space,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      version=AttributeValue(N=1,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      createdOn=AttributeValue(S=2020-06-06T06: 19: 29.125Z,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      primarySpace=AttributeValue(S=system-spaces,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ])
    },
    TableName=ci--jenkins--item,
    ExpressionAttributeNames={
      
    },
    ExpressionAttributeValues={
      
    })),
    TransactWriteItem(Put=Put(Item={
      authorityId=AttributeValue(S=9f293ad9-7fb4-4da7-8656-fc34110cf87d,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      roleId=AttributeValue(S=sys: Role-ROLE_SPACE_MANAGER,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      entityId=AttributeValue(S=3044f695-1c8d-44da-8f63-955628ffe44f,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ]),
      authorityType=AttributeValue(S=USER,
      SS=[
        
      ],
      NS=[
        
      ],
      BS=[
        
      ],
      M={
        
      },
      L=[
        
      ])
    },
    TableName=ci--jenkins--acl,
    ExpressionAttributeNames={
      
    },
    ExpressionAttributeValues={
      
    }))
  ])
]
```

**Comment by sihutch** [comment]
@debora-ito Do you have any updates to this issue or is there anything I can provide for you?

**Comment by zoewangg** [comment]
Hi @sihutch, apologies for the delayed response. The 500 internal error normally indicates there was an issue on the service side, and we have reached out to the service team to investigate the root cause.

Could you provide the code of how you create the SDK client? What region do you send requests to?

**Comment by sihutch** [comment]
Hi @zoewangg thanks for getting back to me. 

```
DynamoDbClient dynamoDbClient = DynamoDbClient.builder()
            .httpClient(UrlConnectionHttpClient.builder().build())
            .region(Region.EU_WEST_1)
            .credentialsProvider(DefaultCredentialsProvider.create()).build();
```

We send requests to the _eu-west-1_ region.

**Comment by debora-ito** [comment]
@sihutch So according to the DynamoDB service team there's a known issue where if you delete and re-create tables with the same name some of the requests result in InternalServerError. They have a task to fix this in their backlog.

Marking this as closing soon. Let us know if you have any other question or concern.

**Comment by sihutch** [comment]
@debora-ito - I have done some further testing around this in conversation with the DynamoDB service team (via our account manager). The issue is only (and always) re-creatable when using the UrlConnectionHttpClient but never when using the ApacheHttpClient - Does this imply that the known issue with deleting/recreating tables only applied to a specific client?  - We do not want to use ApacheHttpClient as we are running on Lambda and do not want the initial time penalty.
