### ISSUE TITLE
IllegalArgumentException: 'isReleased' is already in use

### ISSUE THREAD

**Issue by lanwen** [aws/aws-sdk-java-v2#1886]
Evaluation of the ReleaseOnceChannelPool in two classloaders with shared netty will lead to the exception 
```java
Caused by: java.lang.IllegalArgumentException: 'isReleased' is already in use
	at io.netty.util.ConstantPool.createOrThrow(ConstantPool.java:113)
	at io.netty.util.ConstantPool.newInstance(ConstantPool.java:95)
	at io.netty.util.AttributeKey.newInstance(AttributeKey.java:55)
	at software.amazon.awssdk.http.nio.netty.internal.ReleaseOnceChannelPool.<clinit>(ReleaseOnceChannelPool.java:38)
```
and 
```java
Caused by: java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.http.nio.netty.internal.ReleaseOnceChannelPool
	at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient$1.newPool(NettyNioAsyncHttpClient.java:158)
	at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient$1.newPool(NettyNioAsyncHttpClient.java:143)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at software.amazon.awssdk.http.nio.netty.internal.SdkChannelPoolMap.get(SdkChannelPoolMap.java:42)
```

## Describe the bug

We use https://github.com/pf4j/pf4j for the system with netty server serving grpc with some pluggable handlers which are sharing netty in a classpath, but have anything else within an isolated classpath. If two plugins trying to work with dynamodb, each with own copy of the sdk, second plugin will get the exception above, trying to init

https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ReleaseOnceChannelPool.java#L38

at the moment its a *2.13.33* version.

## Expected Behavior

Each sdk have isolated init from the shared netty part. Netty is pretty big framework and embedding it into each plugin could be a great waste of memory. So would be nice to have something like classloader id on such an id.

## Steps to Reproduce
Create a global classloader, load netty, create a child classloader (loading first from child, then from parent), load sdk in there, call sdk. Create the second classloader same as first child, repeat the sdk call.

The project we're using is the https://github.com/bsideup/liiklus.

## Possible Solution

Adding classloader id could help, so that attributes wouldn't care about others.

## Context

Almost the same issue was fixed in the grpc https://github.com/grpc/grpc-java/issues/6707

## Your Environment

* AWS Java SDK version used: 2.13.33
* JDK version used: 11
* Operating System and version: nix

**Comment by bsideup** [comment]
@dagnir wow, impressive response timing! Thanks for fixing it so fast (and everywhere) 👍

**Comment by dagnir** [comment]
@bsideup Happy to help!
