### ISSUE TITLE
DynamoDB enhanced - NPE in deleteItem() when condition is missing either expression names or values

### ISSUE THREAD

**Issue by MamishIo** [aws/aws-sdk-java-v2#1913]
## Describe the bug

If DynamoDbTable.deleteItem() is called with a condition that is missing either expression names or values (which is valid in the low-level DynamoDB API; both are optional), a NullPointerException is thrown. `putItem` and `updateItem` work as expected with the same condition expression.

## Expected Behavior
DynamoDbTable.deleteItem() should work with a condition expression that doesn't specify optional elements.

## Current Behavior
DynamoDbTable.deleteItem() only works with a condition expression if both expression names and expression values are specified.

Stack trace:
```
Exception in thread "main" java.lang.NullPointerException
    at software.amazon.awssdk.enhanced.dynamodb.internal.operations.DeleteItemOperation.addExpressionsIfExist(DeleteItemOperation.java:128)
    at software.amazon.awssdk.enhanced.dynamodb.internal.operations.DeleteItemOperation.generateRequest(DeleteItemOperation.java:68)
    at software.amazon.awssdk.enhanced.dynamodb.internal.operations.DeleteItemOperation.generateRequest(DeleteItemOperation.java:37)
    at software.amazon.awssdk.enhanced.dynamodb.internal.operations.CommonOperation.execute(CommonOperation.java:113)
    at software.amazon.awssdk.enhanced.dynamodb.internal.operations.TableOperation.executeOnPrimaryIndex(TableOperation.java:59)
    at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbTable.deleteItem(DefaultDynamoDbTable.java:115)
    at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbTable.deleteItem(DefaultDynamoDbTable.java:122)
    at io.mamish.sandbox.Main.main(Main.java:20)
```

## Steps to Reproduce

All of the following `deleteItem` calls fail:

```java
public static void main(String[] args) {

    DynamoDbEnhancedClient ddbClient = DynamoDbEnhancedClient.create();
    DynamoDbTable<DummyObject> table = ddbClient.table("SomeTable", TableSchema.fromBean(DummyObject.class));

    Key key = Key.builder().partitionValue("SomeKey").build();

    // Fails with NPE: Expression with no names and no values
    Expression plainExpression = Expression.builder()
            .expression("SomeAttribute = SomeValue")
            .build();

    table.deleteItem(r -> r.key(key).conditionExpression(plainExpression));

    // Fails with NPE: Expression with names but no values
    Expression expressionWithNames = Expression.builder()
            .expression("#attr = SomeValue")
            .putExpressionName("#attr", "SomeAttribute")
            .build();

    table.deleteItem(r -> r.key(key).conditionExpression(expressionWithNames));

    // Fails with NPE: Expression with values but no names
    Expression expressionWithValues = Expression.builder()
            .expression("SomeAttribute = :value")
            .putExpressionValue(":value", AttributeValue.builder().s("SomeValue").build())
            .build();

    table.deleteItem(r -> r.key(key).conditionExpression(expressionWithValues));

}
```

## Possible Solution

Stack trace points to DeleteItemOperation:128, which references `expressionNames()` and `expressionValues()` without null-check:

```java
if (!this.request.conditionExpression().expressionNames().isEmpty()) {
    requestBuilder = requestBuilder.expressionAttributeNames(this.request.conditionExpression().expressionNames());
}

if (!this.request.conditionExpression().expressionValues().isEmpty()) {
    requestBuilder = requestBuilder.expressionAttributeValues(this.request.conditionExpression().expressionValues());
}
```

By comparison, UpdateItemOperation does not have this issue in its implementation of `addExpressionsIfExist`, and does use a null-check on those fields.

## Context
This isn't difficult to work around since any basic expression can be changed to use expression names and values, but is highly confusing at first since it doesn't match expectations for optional attributes of the low-level DynamoDB API.

## Your Environment
* AWS Java SDK version used: 2.13.41
* JDK version used: Java 11 Lambda runtime - unsure of exact version
* Operating System and version: Amazon Linux 2 - 4.14.165-102.205.amzn2.x86_64

**Comment by debora-ito** [comment]
@MamishIo thank you for the detailed report, I'm able to reproduce it.
