### ISSUE TITLE
java.lang.NoClassDefFoundError: software/amazon/awssdk/utils/Validate

### ISSUE THREAD

**Issue by CSLLCUser** [aws/aws-sdk-java-v2#1939]
## Describe the bug
Missing dependencies in SDK class

## Expected Behavior
Dependencies should be included

## Current Behavior
When making the call 

`Region region = Region.US_EAST_1;`

The following exception is encountered (Full stack trace):

```
java.lang.NoClassDefFoundError: software/amazon/awssdk/utils/Validate
	at software.amazon.awssdk.regions.Region.of(Region.java:134)
	at software.amazon.awssdk.regions.Region.of(Region.java:130)
	at software.amazon.awssdk.regions.Region.<clinit>(Region.java:52)
	at com.sequon.api.AWSChime.initiateChimeMeeting(AWSChime.java:421)
	at com.sequon.api.AWSChime.postAwsChime(AWSChime.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1483)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1414)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1363)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1353)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.utils.Validate
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1722)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1573)
	... 43 more

```

I have included the following in build path:

```
aws-sdk-java-2.13.49-SNAPSHOT.jar
aws-sdk-java-auth-2.13.49-SNAPSHOT.jar
aws-sdk-java-aws-core-2.13.49-SNAPSHOT.jar
aws-sdk-java-chime-2.13.49-SNAPSHOT.jar
aws-sdk-java-iam-2.13.49-SNAPSHOT.jar
aws-sdk-java-regions-2.13.49-SNAPSHOT.jar
aws-sdk-java-s3-2.13.49-SNAPSHOT.jar
aws-sdk-java-sdk-core-2.13.49-SNAPSHOT.jar
aws-sdk-java-sts-2.13.49-SNAPSHOT.jar
aws-sdk-java-utils-2.13.49-SNAPSHOT.jar
```

## Steps to Reproduce
Download and compile AWS SDK 2.13.49
`mvn clean install`

## Possible Solution
No solution

## Context
Trying to consumer the AWS Chime API but encounter exception on this statement:
`Region region = Region.US_EAST_1;`

## Your Environment
Eclipse IDE for Java Developers 
Version: 2020-03 (4.15.0)
Build id: 20200313-1211

* JDK version used: openjdk version "11.0.2" 2019-01-15
* Operating System and version: Mac Catalina 10.15.5

**Comment by debora-ito** [comment]
@CSLLCUser May I suggest you try the BOM method?  https://github.com/aws/aws-sdk-java-v2#importing-the-bom
It manages dependency versions and transitive dependencies for you, and you don't have to download the jars of each SDK module.

**Comment by CSLLCUser** [comment]
Not a Maven or Gradle project, but thanks for the suggestion.  With a lot of effort, were able to resolve all dependencies.

**Comment by leadiato** [comment]
@csllc-one  Could you share how you solve it? THANKS!
