### ISSUE TITLE
LocalDateAttributeConverter Default Constructor

### ISSUE THREAD

**Issue by dmkoster** [aws/aws-sdk-java-v2#1963]
## Expected Behavior

When utilizing the `@DynamoDbConvertedBy` annotation for a `LocalDate` type, the compiler will fail because there is no default no-args constructor for `LocalDateAttributeConverter`. This should not occur.

## Current Behavior

Switching to `LocalDateTimeAttributeConverter` works.

## Possible Solution

Examining the source, `LocalDateAttributeConverter` has a private no-args constructor, `LocalDateTimeAttributeConverter` does not.

`LocalDateAttributeConverter` should have its private no-args constructor removed.

## Steps to Reproduce (for bugs)

Fails with a compiler error:
```
@DynamoDbConvertedBy(LocalDateAttributeConverter.class)
public LocalDate getObjectDate() { 
    return objectDate; 
}
```

Passes:
```
@DynamoDbConvertedBy(LocalDateTimeAttributeConverter.class)
public LocalDate getObjectDate() { 
    return objectDate; 
}
```

## Your Environment

* AWS Java SDK version used: 2.0
* JDK version used: 8
* Operating System and version: AL2012.03

**Comment by debora-ito** [comment]
@dmkoster can you provide the stacktrace with the error you're seeing?

**Comment by dmkoster** [comment]
```
Caused by: java.lang.IllegalArgumentException: Class 'class software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.LocalDateAttributeConverter' appears to have no default constructor thus cannot be used with the BeanTableSchema
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.newObjectSupplierForClass(BeanTableSchema.java:350)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.lambda$createAttributeConverterFromAnnotation$2(BeanTableSchema.java:294)
	at java.util.Optional.map(Optional.java:215)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.createAttributeConverterFromAnnotation(BeanTableSchema.java:294)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.lambda$createStaticTableSchema$0(BeanTableSchema.java:215)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.createStaticTableSchema(BeanTableSchema.java:203)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.convertTypeToEnhancedType(BeanTableSchema.java:281)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.convertTypeToEnhancedType(BeanTableSchema.java:263)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.staticAttributeBuilder(BeanTableSchema.java:240)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.lambda$createStaticTableSchema$0(BeanTableSchema.java:212)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.createStaticTableSchema(BeanTableSchema.java:203)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:120)
	at software.amazon.awssdk.enhanced.dynamodb.TableSchema.fromBean(TableSchema.java:55)
```

**Comment by hinews** [comment]
the same issue on the latest version

**Comment by debora-ito** [comment]
Oh I understand the problem now. By default, the table schema provides the converters for all primitive and common Java types through a default implementation of the AttributeConverterProvider interface. This means that you don't have to explicitly define the `@DynamoDbConvertedBy` annotation for such types.

Can you try without the `@DynamoDbConvertedBy ` annotation?
```
public LocalDate getObjectDate() { 
    return objectDate; 
}
```
