### ISSUE TITLE
Exception using claudwatch service inside a docker container 

### ISSUE THREAD

**Issue by mistreckless** [aws/aws-sdk-java-v2#2026]
Without docker everything works fine but when I try to run my app inside a docker container I got 
`software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Channel was closed before it could be written to.`

Inside the docker container
- `System.out.println(Arrays.toString(SSLContext.getDefault().getSupportedSSLParameters().getProtocols()));` prints `[TLSv1, TLSv1.1, TLSv1.2]`
- `System.out.println(Arrays.toString(SSLContext.getDefault().getSupportedSSLParameters().getCipherSuites()));` prints `[TLS_EMPTY_RENEGOTIATION_INFO_SCSV, SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA384, SSL_RSA_WITH_AES_256_CBC_SHA256, SSL_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, SSL_ECDH_RSA_WITH_AES_256_CBC_SHA384, SSL_DHE_RSA_WITH_AES_256_CBC_SHA256, SSL_DHE_DSS_WITH_AES_256_CBC_SHA256, SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_AES_256_CBC_SHA, SSL_ECDH_ECDSA_WITH_AES_256_CBC_SHA, SSL_ECDH_RSA_WITH_AES_256_CBC_SHA, SSL_DHE_RSA_WITH_AES_256_CBC_SHA, SSL_DHE_DSS_WITH_AES_256_CBC_SHA, SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,  SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA256, SSL_RSA_WITH_AES_128_CBC_SHA256, SSL_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, SSL_ECDH_RSA_WITH_AES_128_CBC_SHA256, SSL_DHE_RSA_WITH_AES_128_CBC_SHA256, SSL_DHE_DSS_WITH_AES_128_CBC_SHA256, SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_AES_128_CBC_SHA, SSL_ECDH_ECDSA_WITH_AES_128_CBC_SHA, SSL_ECDH_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_DSS_WITH_AES_128_CBC_SHA, SSL_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, SSL_ECDHE_RSA_WITH_AES_256_GCM_SHA384, SSL_RSA_WITH_AES_256_GCM_SHA384, SSL_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, SSL_ECDH_RSA_WITH_AES_256_GCM_SHA384, SSL_DHE_DSS_WITH_AES_256_GCM_SHA384, SSL_DHE_RSA_WITH_AES_256_GCM_SHA384, SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256, SSL_RSA_WITH_AES_128_GCM_SHA256, SSL_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, SSL_ECDH_RSA_WITH_AES_128_GCM_SHA256, SSL_DHE_RSA_WITH_AES_128_GCM_SHA256, SSL_DHE_DSS_WITH_AES_128_GCM_SHA256, SSL_DH_anon_WITH_AES_256_GCM_SHA384, SSL_DH_anon_WITH_AES_128_GCM_SHA256, SSL_DH_anon_WITH_AES_256_CBC_SHA256, SSL_ECDH_anon_WITH_AES_256_CBC_SHA, SSL_DH_anon_WITH_AES_256_CBC_SHA, SSL_DH_anon_WITH_AES_128_CBC_SHA256, SSL_ECDH_anon_WITH_AES_128_CBC_SHA, SSL_DH_anon_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_NULL_SHA256, SSL_ECDHE_ECDSA_WITH_NULL_SHA, SSL_ECDHE_RSA_WITH_NULL_SHA, SSL_RSA_WITH_NULL_SHA, SSL_ECDH_ECDSA_WITH_NULL_SHA, SSL_ECDH_RSA_WITH_NULL_SHA, SSL_ECDH_anon_WITH_NULL_SHA, SSL_RSA_WITH_NULL_MD5]`

## Describe the issue

Here the same issue https://github.com/aws/aws-sdk-java-v2/issues/1766
I have no idea why the exception appear only when the app runs in docker container. I tried to disable TLS but nothing changed.

## Steps to Reproduce

Just run this piece of code in docker
```
    open fun cloudWatchLoggerClient(): CloudWatchLogsAsyncClient {
        println(Arrays.toString(SSLContext.getDefault().supportedSSLParameters.protocols))
        println(Arrays.toString(SSLContext.getDefault().supportedSSLParameters.cipherSuites))
        return CloudWatchLogsAsyncClient.builder()
            .credentialsProvider {
                AwsBasicCredentials.create(awsCredentials.accessKey, awsCredentials.secretKey)
            }
            .httpClient(NettyNioAsyncHttpClient.builder()
                .buildWithDefaults(AttributeMap.builder()
                    .put(SdkHttpConfigurationOption.TLS_KEY_MANAGERS_PROVIDER, TlsKeyManagersProvider.noneProvider())
                    .put(SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES, true)
                    .build()))
            .region(Region.of(loggerProperties.regionId))
            .build()
    }
```

## Current Behavior

It really hard to debug exceptions which happen only in docker container. Here the stack trace of the exception
```
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Channel was closed before it could be written to.
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98) ~[sdk-core-2.14.12.jar!/:na]
        at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43) ~[sdk-core-2.14.12.jar!/:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:205) ~[sdk-core-2.14.12.jar!/:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:201) ~[sdk-core-2.14.12.jar!/:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:143) ~[sdk-core-2.14.12.jar!/:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:125) ~[sdk-core-2.14.12.jar!/:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor$$Lambda$667.00000000BD969390.accept(Unknown Source) ~[na:na]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:771) ~[na:1.8.0]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:747) ~[na:1.8.0]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:485) ~[na:1.8.0]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1988) ~[na:1.8.0]
        at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:74) ~[utils-2.14.12.jar!/:na]
        at software.amazon.awssdk.utils.CompletableFutureUtils$$Lambda$661.00000000BCC58B50.accept(Unknown Source) ~[na:na]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:771) ~[na:1.8.0]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:747) ~[na:1.8.0]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:485) ~[na:1.8.0]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1988) ~[na:1.8.0]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$WrappedErrorForwardingResponseHandler.onError(MakeAsyncHttpRequestStage.java:126) ~[sdk-core-2.14.12.jar!/:na]
        at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:299) ~[netty-nio-client-2.14.12.jar!/:na]
        at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.tryConfigurePipeline(NettyRequestExecutor.java:219) ~[netty-nio-client-2.14.12.jar!/:na]
        at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.makeRequestListener(NettyRequestExecutor.java:167) ~[netty-nio-client-2.14.12.jar!/:na]
        at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor$$Lambda$659.00000000BCC581F0.operationComplete(Unknown Source) ~[na:na]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:501) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at java.lang.Thread.run(Thread.java:812) ~[na:2.9 (11-06-2018)]
```

## Your Environment

Dockerfile

```
FROM ibmjava:8-jre-alpine
RUN mkdir /opt/main
COPY build/libs/venue-1.0.jar /opt/main
CMD ["java", "-jar", "/opt/main/venue-1.0.jar"]

```

* AWS Java SDK version used: 2.14.12
* JDK version used: openjdk 13.0.2 (ibmjava:8-jre-alpine in docker), 
* Operating System and version: mac os catalina 10.15.6 (the same on ubuntu)
* Docker version 18.09.0, build 4d60db4

**Comment by mistreckless** [comment]
Ok, I didn't find the core problem with this issue, but I found the way to resolve this. 
We should use parent docker image from amazoncorreto not from ibm.
