### ISSUE TITLE
Could not initialize class software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory when building S3Client

### ISSUE THREAD

**Issue by anushkadar** [aws/aws-sdk-java-v2#2073]
I am using 2.50 SDK
I am trying to push objects using S3Client.
When the execution reaches the build() it gives me the following error.
s3Client = S3Client.builder().region(getS3Region()).build();

This especially happens when we deploy the image to EC2 otherwise my local it working fine with the same configurations.

As suggested by another thread I tried replacing the apache.commons.logging with JCL-over-slf4j.jar but still, the issue is persisting

Not exactly sure this is a bug in sdk or another configuration level issue

`Could not initialize class software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory: java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory
	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheHttpClient.java:488)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.create(ApacheHttpClient.java:468)
	at software.amazon.awssdk.http.apache.ApacheHttpClient.createClient(ApacheHttpClient.java:135)
	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:118)
	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:100)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.buildWithDefaults(ApacheHttpClient.java:460)
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$0(DefaultSdkHttpClientBuilder.java:42)
	at java.util.Optional.map(Optional.java:215)
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:42)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$4(SdkDefaultClientBuilder.java:245)
	at java.util.Optional.orElseGet(Optional.java:267)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:245)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:210)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:148)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:27)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:119)
	at com.trimble.rail.financial.util.AwsFileService.putObject(AwsFileService.java:68)
	at com.trimble.rail.financial.template.WmtTemplateService.saveTemplate(WmtTemplateService.java:56)
	at com.trimble.rail.financial.service.WmtFilePersistenceService.createPoInterfaceFile(WmtFilePersistenceService.java:66)
	at com.trimble.rail.financial.service.WmtFilePersistenceService.createPoRaiseInterfaceFile(WmtFilePersistenceService.java:40)
	at com.trimble.rail.financial.batch.purchaseorder.PurchaseOrderWriter.createPoInterfaceFile(PurchaseOrderWriter.java:65)
	at com.trimble.rail.financial.batch.purchaseorder.PurchaseOrderWriter.processItem(PurchaseOrderWriter.java:47)
	at com.trimble.rail.financial.batch.FinancialWriter.write(FinancialWriter.java:70)
	at com.trimble.rail.financial.batch.FinancialWriter.writeItems(FinancialWriter.java:51)
	at org.jberet.runtime.runner.ChunkRunner.doCheckpoint(ChunkRunner.java:537)
	at org.jberet.runtime.runner.ChunkRunner.readProcessWriteItems(ChunkRunner.java:339)
	at org.jberet.runtime.runner.ChunkRunner.run(ChunkRunner.java:202)
	at org.jberet.runtime.runner.StepExecutionRunner.runBatchletOrChunk(StepExecutionRunner.java:226)
	at org.jberet.runtime.runner.StepExecutionRunner.run(StepExecutionRunner.java:147)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runStep(CompositeExecutionRunner.java:164)
	at org.jberet.runtime.runner.CompositeExecutionRunner.runFromHeadOrRestartPoint(CompositeExecutionRunner.java:88)
	at org.jberet.runtime.runner.JobExecutionRunner.run(JobExecutionRunner.java:60)
	at org.wildfly.extension.batch.jberet.deployment.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:184)
	at org.wildfly.extension.requestcontroller.RequestController$QueuedTask$1.run(RequestController.java:497)
	at org.jberet.spi.JobExecutor$3.run(JobExecutor.java:161)
	at org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)`

* AWS Java SDK version used: 2.5.0
* JDK version used: 1.8
* Operating System and version: Docker Aws

**Comment by debora-ito** [comment]
@anushkadar `NoClassDefFound` errors usually indicate conflicting versions of the same dependency in your environment. You can check for conflicts by running `mvn dependency:tree -Dverbose -Dincludes=software.amazon.awssdk` if you're using maven.
