### ISSUE TITLE
dynamodb StaticTableSchema for java list not working

### ISSUE THREAD

**Issue by tkindra2** [aws/aws-sdk-java-v2#2101]
## Describe the bug
Unable to create static table schema for type List

## Expected Behavior
Should be able to save POJO with list type

## Current Behavior
When trying to create DynamoDbTable object using enhancedClient i get exception below

java.lang.ExceptionInInitializerError
	at com.childcare.service.ContactServiceIntegrationTest.testFindByEmail(ContactServiceIntegrationTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4553)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.findConverter(DefaultAttributeConverterProvider.java:153)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.converterFor(DefaultAttributeConverterProvider.java:133)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.ImmutableAttribute.converterFrom(ImmutableAttribute.java:167)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.ImmutableAttribute.resolve(ImmutableAttribute.java:163)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.lambda$new$0(StaticImmutableTableSchema.java:153)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.<init>(StaticImmutableTableSchema.java:159)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.<init>(StaticImmutableTableSchema.java:77)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema$Builder.build(StaticImmutableTableSchema.java:425)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema.<init>(StaticTableSchema.java:66)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema.<init>(StaticTableSchema.java:64)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema$Builder.build(StaticTableSchema.java:255)
	at com.childcare.model.dyanmo.Contact.<clinit>(Contact.java:334)
	... 25 more

## Steps to Reproduce
---In POJO
private List<String> pid;

---In StaticTableSchema
.addAttribute(List.class, a -> a.name("pid").getter(Contact::getPid).setter(Contact::setPid))

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:
<dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.15.7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
<dependency>
			<groupId>software.amazon.awssdk</groupId>
            <artifactId>dynamodb</artifactId>
            <exclusions>
				<exclusion> 
					<groupId>software.amazon.awssdk</groupId>
					 <artifactId>apache-client</artifactId>
				 </exclusion>
			    <exclusion>
					<groupId>software.amazon.awssdk</groupId>
					<artifactId>netty-nio-client</artifactId> </exclusion>
				</exclusions>
		</dependency>
		<dependency>
		  <groupId>software.amazon.awssdk</groupId>
		  <artifactId>dynamodb-enhanced</artifactId>
		</dependency>
		
		<dependency> 
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>url-connection-client</artifactId> 
			
		</dependency>

**Comment by debora-ito** [comment]
@tkindra2 you need to provide the type of the elements in the List, like `List<Integer>` or `List<String>`.

**Comment by tkindra2** [comment]
yes it is private List<String> pid;

**Comment by debora-ito** [comment]
Can you share a sample code showing how you're creating the table?

**Comment by tkindra2** [comment]
The Exception is coming when When static definition of table is being built using StaticTableSchema.builder(Contact.class) followed by build method being called (after defining attributes). 

So could you confirm that i could use private` List<String> pid;` in POJO and then simply use

```
.addAttribute(List.class,
					a -> a.name("pid").getter(Contact::getPid).setter(Contact::setPid))
```

I can't find documentation that confirms or denies that **default converters can handle list of strings**. **If default converter can't convert, could you provide me way to specify converter**. Note data in my table was created with version 1 of api. List of string are saved as` [  { "S" : "lrNEYJ9kQ" },  { "S" : "lrNEYJ9kQ" }]`





To answer your question The code to create table was written in version 1 of API i haven't been able to re-write in version2. Nevertheless i can provide you table details from my AWS Console:


Table name | DEV_ContactCatalog
-- | --
Primary partition key | Id (String)
Primary sort key | -
Point-in-time recovery | DISABLEDEnable
Encryption Type | DEFAULTManage Encryption
KMS Master Key ARN | Not Applicable
Encryption Status |  
CloudWatch Contributor Insights | DISABLEDManage Contributor InsightsNEW
Time to live attribute | DISABLEDManage TTL
Table status | Active
Creation date | August 11, 2020 at 3:36:28 PM UTC-4UTC: August 11, 2020 at 7:36:28 PM UTCLocal: August 11, 2020 at 3:36:28 PM UTC-4Region (N. Virginia): August 11, 2020 at 2:36:28 PM UTC-5
Read/write capacity mode | Provisioned
Last change to on-demand mode | -
Provisioned read capacity units | 2 (Auto Scaling Disabled)
Provisioned write capacity units | 2 (Auto Scaling Disabled)
Last decrease time | August 11, 2020 at 3:47:25 PM UTC-4UTC: August 11, 2020 at 7:47:25 PM UTCLocal: August 11, 2020 at 3:47:25 PM UTC-4Region (N. Virginia): August 11, 2020 at 2:47:25 PM UTC-5
Last increase time | -
Storage size (in bytes) | 6.87 KB
Item count | 36Manage live count
Region | US East (N. Virginia)
Amazon Resource Name (ARN) | 

Also have index

email-index | Active | GSI | email (String)
-- | -- | -- | --

**Comment by debora-ito** [comment]
@tkindra2 thank you for the context of your use case. So I should've asked for a sample code showing how you are defining the table schema. Please provide a full sample that I can use to reproduce the issue you are seeing.

**Comment by debora-ito** [comment]
@tkindra2 are you still seeing the issue? Can you share a table schema/bean I can use to reproduce?

**Comment by JaimeS-ZappyRide** [comment]
Hi I am still having the same issue above.

**Comment by debora-ito** [comment]
@JaimeS-ZappyRide hi, please open a new issue with the problems you are seeing.

**Comment by deandelponte** [comment]
I'm also experiencing this issue and would like to know how resolve
