### ISSUE TITLE
s3 bucket condition filtering error

### ISSUE THREAD

**Issue by liwande** [aws/aws-sdk-java-v2#2148]
## Describe the bug
   The listObjects and listObjectsV2 methods of aws-sdk-java-v2 S3 will report an error ，if the built-in attribute prefix or maxKeys attribute is specified (no error will be reported if you do not specify it) 
The error content is as follows: Exception in thread "main" software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 302, Request ID: null)

## Expected Behavior
The s3 bucket condition can specify the prefix or the maximum number of objects returned

## Current Behavior
The specified prefix or the maximum number of objects returned is abnormal

 Exception in thread "main" software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 302, Request ID: null)

## Steps to Reproduce

AwsCredentialsProvider awsCredentialsProvider = () -> AwsBasicCredentials.create(awsConfig.getAccessKeyId(), awsConfig.getSecretAccessKey());

        Region region = Region.of(awsConfig.getRegion());
        s3Client = S3Client.builder()
                .region(region)
                .credentialsProvider(awsCredentialsProvider)
                .build();

        ListObjectsRequest listObjects = ListObjectsRequest
                .builder()
                .bucket(bucketName)
//                .maxKeys(10)
                .build();

        ListObjectsResponse response = s3Client.listObjects(listObjects);
        List<S3Object> contents = response.contents()

comment:The listObjects and listObjectsV2 methods of aws-sdk-java-v2 S3 will report an error 

## Your Environment

* AWS Java SDK version used: aws-sdk-java-v2
* JDK version used: jdk1.8

**Comment by debora-ito** [comment]
@liwande can you provide the full stacktrace?

**Comment by liwande** [comment]
1、code show as below：

AwsCredentialsProvider awsCredentialsProvider = () -> AwsBasicCredentials.create(awsConfig.getAccessKeyId(), awsConfig.getSecretAccessKey());
int maxKeys = 4;
Region region = Region.of(awsConfig.getRegion());
s3Client = S3Client.builder()
        .region(region)
        .credentialsProvider(awsCredentialsProvider)
        .build();

ListObjectsRequest listObjects = ListObjectsRequest
        .builder()
        .bucket("guangfeng-demo")
        .maxKeys(maxKeys)
        .build();


ListObjectsResponse response = s3Client.listObjects(listObjects);
List<S3Object> contents = response.contents();


ListObjectsV2Response result = s3Client.listObjectsV2(ListObjectsV2Request.builder()
        .bucket("guangfeng-demo")
        .maxKeys(maxKeys)
        .build());

List<S3Object> objects1 = result.contents();
List<S3Object> objects2 = result.name();


2、Description：
The listObjects and listObjectsV2 methods of aws-sdk-java-v2 S3 will report an error ，if the built-in attribute prefix or maxKeys attribute is specified (no error will be reported if you do not specify it)
The error content is as follows: Exception in thread "main" software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 302, Request ID: null)

3、Stacktrace：

Exception in thread "main" software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 302, Request ID: null) at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:115) at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:73) at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58) at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41) at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:64) at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36) at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77) at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39) at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:113) at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:86) at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:62) at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:42) at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57) at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37) at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73) at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44) at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55) at software.amazon.awssdk.services.s3.DefaultS3Client.listObjectsV2(DefaultS3Client.java:2313) at org.example.lwd.aaa.testListWithMaxKeys(aaa.java:27)



975806751@qq.com
 
From: Debora N. Ito
Date: 2020-11-18 05:51
To: aws/aws-sdk-java-v2
CC: liwande; Mention
Subject: Re: [aws/aws-sdk-java-v2] s3 bucket condition filtering error (#2148)
@liwande can you provide the full stacktrace?

**Comment by debora-ito** [comment]
Thank you for the stacktrace. Status code 302 is described as `the requested resource resides temporarily under a different URI`, so it's weird that you only get this exception when maxkeys is provided. I'm not able to reproduce the issue locally.

Can you turn the [verbose wire logging](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/java-dg-logging.html#sdk-java-logging-verbose) on and provide us the logs? Please make sure to redact any sensitive data like access keys. I'm hoping to get additional information from the requests and reponses.
