### ISSUE TITLE
NPe during s3 signing

### ISSUE THREAD

**Issue by nikita-clearscale** [aws/aws-sdk-java-v2#217]
Got NPE during AWS signing process, note that when region is not set, e.g. s3 client created with default region it works,
 but when I set a region signing failed with NPE. I got this when executing code in aws lambda environment 

## Expected Behavior
get s3 object

## Current Behavior
got NPE

## Possible Solution
It seems that either s3 client should be created differently or endpoint should be set with region (not sure why about last)

## Steps to Reproduce (for bugs)
Code in kotlin:
      fun clientForBucket(bucket: String): S3Client {
      val globalClient = S3Client.builder().advancedConfiguration(S3AdvancedConfiguration.builder().pathStyleAccessEnabled(true).build()).build()
        val region = Region.of(
          globalClient.getBucketLocation(GetBucketLocationRequest.builder().bucket(bucket).build())
            .locationConstraint())

            return S3Client.builder()
                    .region(region)
                    .httpConfiguration(ClientHttpConfiguration.builder()
                      .httpClientFactory(ApacheSdkHttpClientFactory.builder().build())
                      .build())
                    .build()
        }
      }

      clientForBucket("MyBucket").getObject(GetObjectRequest.builder()
                  .bucket("MyBucket")
                  .key("MyKey").build(), StreamingResponseHandler.toInputStream())

Expected: - get s3 object stream
Actual got NPE:

    java.lang.NullPointerException
        at java.lang.StringBuilder.<init>(StringBuilder.java:112)
        at software.amazon.awssdk.auth.Aws4Signer.addHostHeader(Aws4Signer.java:470)
        at software.amazon.awssdk.auth.Aws4Signer.doSign(Aws4Signer.java:198)
        at software.amazon.awssdk.auth.Aws4Signer.lambda$sign$0(Aws4Signer.java:181)
        at software.amazon.awssdk.utils.builder.ToCopyableBuilder.lambda$copy$0(ToCopyableBuilder.java:44)
        at software.amazon.awssdk.utils.builder.SdkBuilder.apply(SdkBuilder.java:61)
        at software.amazon.awssdk.utils.builder.ToCopyableBuilder.copy(ToCopyableBuilder.java:43)
        at software.amazon.awssdk.auth.Aws4Signer.sign(Aws4Signer.java:181)
        at software.amazon.awssdk.http.pipeline.stages.SigningStage.signRequest(SigningStage.java:60)
        at software.amazon.awssdk.http.pipeline.stages.SigningStage.execute(SigningStage.java:48)
        at software.amazon.awssdk.http.pipeline.stages.SigningStage.execute(SigningStage.java:35)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:40)
        at software.amazon.awssdk.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:30)
        at software.amazon.awssdk.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:183)
        at software.amazon.awssdk.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:136)
        at software.amazon.awssdk.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:72)
        at software.amazon.awssdk.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:51)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.StreamManagingStage.execute(StreamManagingStage.java:61)
        at software.amazon.awssdk.http.StreamManagingStage.execute(StreamManagingStage.java:45)
        at software.amazon.awssdk.http.pipeline.stages.AfterCallbackStage.execute(AfterCallbackStage.java:43)
        at software.amazon.awssdk.http.pipeline.stages.AfterCallbackStage.execute(AfterCallbackStage.java:32)
        at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.executeWithTimer(ClientExecutionTimedStage.java:72)
        at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:56)
        at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:40)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:35)
        at software.amazon.awssdk.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:24)
        at software.amazon.awssdk.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:419)
        at software.amazon.awssdk.client.SyncClientHandlerImpl.doInvoke(SyncClientHandlerImpl.java:144)
        at software.amazon.awssdk.client.SyncClientHandlerImpl.invoke(SyncClientHandlerImpl.java:126)
        at software.amazon.awssdk.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:101)
        at software.amazon.awssdk.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:70)
        at software.amazon.awssdk.client.SdkClientHandler.execute(SdkClientHandler.java:55)
        at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:1462)

## Context
Try to get s3 object

## Your Environment
* AWS Java SDK version used: Java 8
* JDK version used: got bug in aws lambda
* Operating System and version: lambda

**Comment by nikita-clearscale** [comment]
![image](https://user-images.githubusercontent.com/26218826/31722149-974b0fda-b445-11e7-90c2-ae79cd430e8d.png)

**Comment by dagnir** [comment]
Hi, from the classes in the stacktrace it looks like you're using version `2.0.0-preview-4` of the SDK. Can you confirm?

**Comment by nikita-clearscale** [comment]
Yes

**Comment by spfink** [comment]
Problem here is that S3 returns an empty string for buckets in us-east-1 which you are then passing as the region.

I'll discuss with the team as to what option we want to take here. Should at the very least add validation that region isn't an empty string. Might also want to add specific handling here to have us-east-1 returned instead of an empty string.

**Comment by Saheb** [comment]
I'm getting the same exception with putObject in preview-6. Do we have a fix or temporary workaround?

**Comment by zoewangg** [comment]
Please try with the latest version and feel free to reopen if you continue to see the issue.
