### ISSUE TITLE
Unable to load an HTTP implementation from any provider in the chain.

### ISSUE THREAD

**Issue by mohanr** [aws/aws-sdk-java-v2#2172]
Unable to load an HTTP implementation from any provider in the chain.

## Describe the bug
I have subscribed a lambda to a SNS topic. The lambda tried to connect to Kinesis and when it loads the classes it encounters this error.

`Picked up JAVA_TOOL_OPTIONS: "-DSdkSystemSetting.SYNC_HTTP_SERVICE_IMPL.property=software.amazon.awssdk.sdk.apache.ApacheSdkHttpService"
START RequestId: 9a2a8366-03a9-4d9a-b746-1fec9a737450 Version: $LATEST
2020-12-01 11:10:22 9a2a8366-03a9-4d9a-b746-1fec9a737450 INFO  AuditLambda - null
Unable to load an HTTP implementation from any provider in thechain. You must declare a dependency on an appropriate HTTPimplementation or pass in an SdkHttpClient explicitly to theclient builder.: software.amazon.awssdk.core.exception.SdkClientException
software.amazon.awssdk.core.exception.SdkClientException: Unable to load an HTTP implementation from any provider in thechain. You must declare a dependency on an appropriate HTTPimplementation or pass in an SdkHttpClient explicitly to theclient builder.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkAsyncHttpClientBuilder.lambda$buildWithDefaults$1(DefaultSdkAsyncHttpClientBuilder.java:50)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkAsyncHttpClientBuilder.buildWithDefaults(DefaultSdkAsyncHttpClientBuilder.java:44)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveAsyncHttpClient$7(SdkDefaultClientBuilder.java:255)
	at java.util.Optional.orElseGet(Optional.java:267)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveAsyncHttpClient(SdkDefaultClientBuilder.java:255)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeAsyncConfiguration(SdkDefaultClientBuilder.java:220)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:170)
	at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClientBuilder.buildClient(DefaultKinesisAsyncClientBuilder.java:28)
	at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClientBuilder.buildClient(DefaultKinesisAsyncClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:118)
	at audit.AuditLambda.handleAuditEvent(AuditLambda.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
END RequestId: 9a2a8366-03a9-4d9a-b746-1fec9a737450
REPORT RequestId: 9a2a8366-03a9-4d9a-b746-1fec9a737450	Duration: 667.90 ms	Billed Duration: 668 ms	Memory Size: 512 MB	Max Memory Used: 138 MB	Init Duration: 2267.94 ms`

## Steps to Reproduce
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>kinesislambdaaudit</groupId>
    <artifactId>LambdaAudit</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <name>Kinesis Lambda audit.</name>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>lambda</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>apache-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>1.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>3.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events-sdk-transformer</artifactId>
            <version>2.0.6</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-log4j2</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sts</artifactId>
       </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>kinesis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.13.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.13.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.11.2</version>
        </dependency>

        <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
          <version>4.13.1</version>
          <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>3.1.1</version>
          <configuration>
          </configuration>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>shade</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </build>
</project>

```

```
        AssumeRoleRequest assumeRoleRequest = AssumeRoleRequest.builder()
                .roleArn("arn")
                .roleSessionName("kinesistest")
                .build();


        SdkHttpClient httpClient = ApacheHttpClient.
                                    builder().
                                    build();

        StsClient stsClient = StsClient.
                                    builder().
                                    region(Region.EU_WEST_2).
//                                    httpClient(httpClient).
                                    build();


        credentialsProvider = StsAssumeRoleCredentialsProvider
                                    .builder()
                                    .stsClient(stsClient).refreshRequest(assumeRoleRequest)
                                    .asyncCredentialUpdateEnabled(true)
                                    .build();

```

## Your Environment
This happens whether I include a HTTP client in the Java code or not.
* pom.xml is shown above:
* JDK version used: 1.8

**Comment by mohanr** [comment]
`       customClient = NettyNioAsyncHttpClient.builder().maxConcurrency(100).build();
`
I switched to an async. client with a new property.

```
-Dsoftware.amazon.awssdk.http.async.service.impl=\
software.amazon.awssdk.http.nio.netty.NettySdkAsyncHttpService
```
The effect is still an exception of the same kind.

**Comment by debora-ito** [comment]
Can you test it with a newer version of the SDK? I see you're using version `2.1.0` and it had many changes since then. The latest version is `2.15.40`.

**Comment by YingjieQiao** [comment]
the same issue still persists

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" software.amazon.awssdk.core.exception.SdkClientException: Unable to load an HTTP implementation from any provider in the chain. You must declare a dependency on an appropriate HTTP implementation or pass in an SdkHttpClient explicitly to the client builder.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$1(DefaultSdkHttpClientBuilder.java:49)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:43)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$5(SdkDefaultClientBuilder.java:274)
	at java.util.Optional.orElseGet(Optional.java:267)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:274)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:225)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:158)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:27)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:129)
	at com.example.escapp.test_script.createBucket(test_script.java:14)
	at com.example.escapp.test_script.main(test_script.java:29)
```

**Comment by gauravphoenix** [comment]
I am also running into the same issue when trying to build the SQS Client. I am using sdk version `2.15.73`

**Comment by orozcoadrian** [comment]
fwiw, adding an explicit http client worked for me: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/lambda-optimize-starttime.html
New dependency added: `software.amazon.awssdk:url-connection-client`

**Comment by bmamatkadyr** [comment]
@orozcoadrian It works for me 👍🏻

**Comment by travispeloton** [comment]
Was vexed by this. Reason was that I was explicitly using an `AsyncHttpClient` and removed the synchronous `HttpClient` dependency, but I still had some AWS clients being instantiated (e.g., secrets, sts)  that were expecting the non-async one by default.

The error messages are terrible, and this should be in the AWS documentation.
