### ISSUE TITLE
Supports builder that generated from immutables for @DynamoDbImmutable

### ISSUE THREAD

**Issue by doubleseo** [aws/aws-sdk-java-v2#2245]
Supports builder that generated from immutables for @DynamoDbImmutable
See more information about Immutables see here: https://immutables.github.io/

## Expected Behavior
DDB Enhanced Client does not throws validation error when builder has more than one initialize methods per attribute.

## Current Behavior
Immutables's builder generates couple of special methods to initialize collection or optional attributes:
https://immutables.github.io/immutable.html#array-collection-and-map-attributes
https://immutables.github.io/immutable.html#optional-attributes

However, DDB Enhanced Client throws IllegalStateException exception due to Duplicate Key on the special methods.

```
java.lang.IllegalStateException: Duplicate key ...
    at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
    at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
    at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at software.amazon.awssdk.enhanced.dynamodb.internal.immutable.ImmutableIntrospector.filterAndIndexBuilderMethods(ImmutableIntrospector.java:164)
    at software.amazon.awssdk.enhanced.dynamodb.internal.immutable.ImmutableIntrospector.introspect(ImmutableIntrospector.java:67)
    at software.amazon.awssdk.enhanced.dynamodb.internal.immutable.ImmutableIntrospector.getImmutableInfo(ImmutableIntrospector.java:60)
    at software.amazon.awssdk.enhanced.dynamodb.mapper.ImmutableTableSchema.createStaticImmutableTableSchema(ImmutableTableSchema.java:154)
    at software.amazon.awssdk.enhanced.dynamodb.mapper.ImmutableTableSchema.create(ImmutableTableSchema.java:125)
```

## Context
We use Immutables to define the object to immutable and generate builder automatically. We do not use lombok due to a policy for the code generation. If we cannot use Immutables, then we should copy-paste and hard code builder on the model in order to use @DynamoDbImmutable.

## Your Environment

* AWS Java SDK version used: v2 AWS SDK
* JDK version used: JDK11
* Operating System and version:

**Comment by debora-ito** [comment]
@doubleseo thank you for reaching out, and apologies for the long delay in reply. Marking as a feature request.

Can you share a sample code showing a class using `immutables` that gives you the exception?

**Comment by icaria** [comment]
The error you're seeing comes from this line:

https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/immutable/ImmutableIntrospector.java#L164

The Java stream is trying to normalize the method and put them into a map key'd by just the method name - so you end up with duplicate keys when trying to parse through the default "from" methods generated by Immutables. I'm honestly surprised they doesn't cause more issues overall.

**Comment by jkatnik** [comment]
I'm aware that this is quite an old issue.
I'd like to share a solution for anyone else who like me came here looking for help.

The fix is easy - just annotate the overloaded method with `@DynamoDbIgnore`.

Here is an example of my DynaomDB entity class (check `setSubscriptionId` method):

```
@DynamoDbImmutable(builder = Subscription.Builder::class)
class Subscription(
  @get:DynamoDbPartitionKey val ssoId: Long,
  @get:DynamoDbSortKey val sortKey: String,
  val subscriberId: String,
  val subscriptionId: UUID,
  val eventType: EventType,
  val endpoint: URL,
  val status: SubscriptionStatus
) : DynamoDbKeyMapProvider {

  @DynamoDbIgnore
  override fun getPrimaryKeyAsMap(): Map<String, AttributeValue> = mapOf(
    "ssoId" to AttributeValue.builder().n(ssoId.toString()).build(),
    "sortKey" to AttributeValue.builder().s(sortKey).build()
  )

  class Builder {
    private var ssoId: Long? = null
    private var eventType: EventType? = null
    private var endpoint: URL? = null
    private var subscriberId: String? = null
    private var status: SubscriptionStatus = SubscriptionStatus.DRAFT
    private var subscriptionId: UUID = UUID.randomUUID()

    fun setSsoId(ssoId: Long) = apply { this.ssoId = ssoId }
    fun setEventType(eventType: EventType) = apply { this.eventType = eventType }
    fun setEndpoint(endpoint: URL): Builder = apply { this.endpoint = endpoint }
    fun setSubscriberId(subscriberId: String): Builder = apply { this.subscriberId = subscriberId }
    fun setSubscriptionId(subscriptionId: UUID): Builder = apply { this.subscriptionId = subscriptionId }
    @DynamoDbIgnore
    fun setSubscriptionId(subscriptionId: String): Builder = apply { this.subscriptionId = UUID.fromString(subscriptionId) }

    /**
     * Those two methods even if not used are needed because of @DynamoDbImmutable annotation.
     * This is a workaround for an issue, which is reported under: https://github.com/aws/aws-sdk-java-v2/issues/2096
     */
    fun setStatus(status: SubscriptionStatus): Builder = apply { this.status = status }
    fun setSortKey(sortKey: String): Builder = apply { }

    fun build() = Subscription(
      status = status,
      subscriberId = subscriberId ?: throw IllegalStateException("subscriberId was not initialized"),
      subscriptionId = subscriptionId,
      ssoId = ssoId ?: throw IllegalStateException("ssoId was not initialized"),
      eventType = eventType ?: throw IllegalStateException("eventType was not initialized"),
      endpoint = endpoint ?: throw IllegalStateException("endpoint was not initialized"),
      sortKey = "EVENT#$eventType#SUBSCRIBER#$subscriberId"
    )
  }
}
```
