### ISSUE TITLE
DynamoDbEnhancedClient Syntax error; token: "-", near: "#AMZN_MAPPED

### ISSUE THREAD

**Issue by bufistov** [aws/aws-sdk-java-v2#2310]
## Describe the bug

I am using the enhanced client to read Map<String, String> from dynamodb field "mymap". The map keys are dates in yyyy-mm-dd format.
So I am trying to read path "mymap.2021-03-03" today. The request I build is:
`QueryEnhancedRequest.builder()
                .queryConditional(QueryConditional.sortBeginsWith(Key.builder()
                        .partitionValue(key.getPartitionKey())
                        .sortValue(key.getSortKey())
                        .addNestedAttributesToProject(NestedAttributeName.create("mymap", "2021-03-03"))
                        .build()))
`
## Expected Behavior

I expect the dynamoDbEnhanced client correctly extract value from the Map.

## Current Behavior

software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Invalid ProjectionExpression: Syntax error; token: "-", near: "#AMZN_MAPPED_2021-0" (Service: DynamoDb, Status Code: 400

Stack trace:

`
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Invalid ProjectionExpression: Syntax error; token: "-", near: "#AMZN_MAPPED_2021-0" (Service: DynamoDb, Status Code: 400, Request ID: 04JG3LI42IPTIUHJCEF8VNH3JBVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)

	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:133)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:159)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:112)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.query(DefaultDynamoDbClient.java:3994)
	at software.amazon.awssdk.services.dynamodb.paginators.QueryIterable$QueryResponseFetcher.nextPage(QueryIterable.java:134)
	at software.amazon.awssdk.services.dynamodb.paginators.QueryIterable$QueryResponseFetcher.nextPage(QueryIterable.java:125)
	at software.amazon.awssdk.core.pagination.sync.PaginatedResponsesIterator.next(PaginatedResponsesIterator.java:58)
	at software.amazon.awssdk.enhanced.dynamodb.internal.TransformIterator.next(TransformIterator.java:44)
	at software.amazon.awssdk.core.pagination.sync.PaginatedItemsIterable$ItemsIterator.<init>(PaginatedItemsIterable.java:58)
	at software.amazon.awssdk.core.pagination.sync.PaginatedItemsIterable.iterator(PaginatedItemsIterable.java:48)
	at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
`

## Steps to Reproduce

Execute request where child json field has '-' in names.

## Possible Solution

It seems the enhanced client uses field name to generate eventual low lever projection expression. I see this in debugger

`
ProjectionExpression=#AMZN_MAPPED_mymap.#AMZN_MAPPED_2021-03-03
`

We should sanityze somehow attribute names in the expressions.

## Context

I am trying to reduce read bandwidth by reading only necessary keys from map.
It is possible to use DDB low level api to generate projections and variables names keys but will kill all my tomorrow morning.

I hope I just miss something and either doing something wrong or there is an easy correction for my query! :)

Thanks for reading.

**Comment by debora-ito** [comment]
Hi @bufistov thank you for reporting this, I can reproduce the issue. Your analysis is correct, we need to remove the non-alphanumeric characters from the placeholder names.

**Comment by bufistov** [comment]
Hi! Thanks for fast reply, @debora-ito . Is there any estimation when this might be fixed?

**Comment by debora-ito** [comment]
No timeline yet, will add an update here when we have one. PRs are welcome.

**Comment by cenedhryn** [comment]
Thanks for finding this issue. Only top-level attributes were "sanitized" with non-compliant characters replaced by '_' when the projection expression was created. This should now work on all nested levels.

**Comment by debora-ito** [comment]
@bufistov the fix was released in SDK version 2.16.39, please try it out and let us know if you see any further issues.
