### ISSUE TITLE
Maven dependency conflicts with netty-all

### ISSUE THREAD

**Issue by GingerMoon** [aws/aws-sdk-java-v2#2398]
## Describe the issue
I am using S3AsyncClient as below:
```
S3AsyncClient client = S3AsyncClient.builder()
                .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
                .endpointOverride(URI.create(configExt.getString(HOSTNAME)))
                .region(region)
                .build();
```
Due to maven depedency conflicts, I exclude some dependencies
```
             <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
                <exclusions>... more below...</exclusions>
```
Then I got a runtime error as below:
```
	 Caused by:java.lang.NoClassDefFoundError: io/netty/channel/ChannelFactory
```
## Steps to Reproduce

When I added S3's dependency to an existing project, which depends on 
```
io.netty:netty-all:jar:4.0.36.Final:compile
```
I need to exclude some dependency as below to fix dependcy conflicts:
```
(the maven dependency conflict)

  Found in:
    io.netty:netty-transport:jar:4.1.61.Final:runtime
    io.netty:netty-all:jar:4.0.36.Final:compile
  Duplicate classes:...
```

```
<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>netty-handler</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>netty-codec-http</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>netty-transport-native-unix-common</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>netty-buffer</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>netty-transport</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>netty-codec</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>netty-common</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>netty-transport-native-epoll</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```
After fixing the dependency errors I got the mentioned runtime error.

## Current Behavior

The call stack is below:
```
	Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/netty/channel/ChannelFactory
		at software.amazon.awssdk.http.nio.netty.SdkEventLoopGroup.resolveChannelFactory(SdkEventLoopGroup.java:145)
		at software.amazon.awssdk.http.nio.netty.SdkEventLoopGroup.<init>(SdkEventLoopGroup.java:79)
		at software.amazon.awssdk.http.nio.netty.SdkEventLoopGroup.<init>(SdkEventLoopGroup.java:62)
		at software.amazon.awssdk.http.nio.netty.SdkEventLoopGroup$DefaultBuilder.build(SdkEventLoopGroup.java:207)
		at software.amazon.awssdk.http.nio.netty.internal.SharedSdkEventLoopGroup.get(SharedSdkEventLoopGroup.java:57)
		at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient$$Lambda$234/28553945.get(Unknown Source)
		at java.util.Optional.orElseGet(Optional.java:267)
		at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient.eventLoopGroup(NettyNioAsyncHttpClient.java:148)
		at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient.<init>(NettyNioAsyncHttpClient.java:89)
		at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient.<init>(NettyNioAsyncHttpClient.java:67)
		at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient$DefaultBuilder.buildWithDefaults(NettyNioAsyncHttpClient.java:680)
		at software.amazon.awssdk.core.internal.http.loader.DefaultSdkAsyncHttpClientBuilder.lambda$buildWithDefaults$0(DefaultSdkAsyncHttpClientBuilder.java:43)
		at software.amazon.awssdk.core.internal.http.loader.DefaultSdkAsyncHttpClientBuilder$$Lambda$232/19846366.apply(Unknown Source)
		at java.util.Optional.map(Optional.java:215)
		at software.amazon.awssdk.core.internal.http.loader.DefaultSdkAsyncHttpClientBuilder.buildWithDefaults(DefaultSdkAsyncHttpClientBuilder.java:43)
		at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveAsyncHttpClient$8(SdkDefaultClientBuilder.java:285)
		at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$Lambda$226/24154826.get(Unknown Source)
		at java.util.Optional.orElseGet(Optional.java:267)
		at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveAsyncHttpClient(SdkDefaultClientBuilder.java:285)
		at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeAsyncConfiguration(SdkDefaultClientBuilder.java:236)
		at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:181)
		at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:28)
		at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:22)
		at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:129)
```

## Your Environment

* AWS Java SDK version used:
```
<dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.16.40</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.reactivestreams</groupId>
                <artifactId>reactive-streams</artifactId>
                <version>1.0.3</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-http</artifactId>
                <version>4.1.61.Final</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.netty/netty-handler -->
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-handler</artifactId>
                <version>4.1.61.Final</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.netty/netty-codec-http -->
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-http</artifactId>
                <version>4.1.61.Final</version>
            </dependency>
```
* JDK version used: openjdk version "1.8.0_41"
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
@GingerMoon If you are using S3 Async client you don't have to explicitly declare the netty dependencies in the pom file. Try the following to add S3 as a dependency to your project:

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.16.40</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>
    </dependencies>
```

Note that the `bom` artifact is under `dependencyManagement`. 
Maven should be able resolve the version conflicts without you having to manually exclude the duplicate classes.

**Comment by GingerMoon** [comment]
@debora-ito Thanks for the reply.
I did do the same as you mentioned but still had the error.
Our company's policy (maven enforce) requires that all projects must depend on netty-all.jar, which has conflicts with aws-sdk-java-v2. 
Some of the maven errors are bleow:
```
  Found in:
    io.netty:netty-handler:jar:4.1.43.Final:runtime
    io.netty:netty-all:jar:4.0.36.Final:compile
  Duplicate classes:
    io/netty/handler/timeout/IdleStateHandler.class
```

**Comment by debora-ito** [comment]
Hi @GingerMoon this repo is for issues related to the SDK itself. Your issue is how to make maven enforce plugin work with conflicting versions of dependencies. I'd look for suggestions on community hubs like StackOverflow and the plugin documentation.

**Comment by GingerMoon** [comment]
Hi @debora-ito , the problem is, the dependecies of the SDK itself have conflicts and I think these conflicts can have problem if some big companies have similar enforce plugin rules.
![2021-04-20_9-11-20](https://user-images.githubusercontent.com/8342412/115322341-71c93c00-a1b8-11eb-98fc-38019e0e4671.png)

**Comment by snehal-kolte** [comment]
@GingerMoon I am facing the same issue. As shown in the above screenshot, Would you please share how i can verify conflict dependencies? I am using intellij idk.
