### ISSUE TITLE
SsoProfileCredentialsProviderFactory should use an SsoAsyncClient

### ISSUE THREAD

**Issue by jtjeferreira** [aws/aws-sdk-java-v2#2401]
`SsoProfileCredentialsProviderFactory` should be able to use an async client. 

## Describe the Feature
`software.amazon.awssdk.services.sso.auth.SsoProfileCredentialsProviderFactory` should use an `software.amazon.awssdk.services.sso.SsoAsyncClient` instead of `software.amazon.awssdk.services.sso.SsoClient`. Alternatively it should try to use the sync client, and fallback to the async one.

## Is your Feature Request related to a problem?
I am using the `DefaultCredentialsProvider`, but when I use it with a profile which is configured with sso I get the following error:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(): Unable to load an HTTP implementation from any provider in the chain. You must declare a dependency on an appropriate HTTP implementation or pass in an SdkHttpClient explicitly to the client builder., ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Unable to load credentials from service endpoint.]
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:112)
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:104)
```

The important part is 
```
ProfileCredentialsProvider(): Unable to load an HTTP implementation from any provider in the chain. You must declare a dependency on an appropriate HTTP implementation or pass in an SdkHttpClient explicitly to the client builder.
```

This is happening because in my classpath I only have a `SdkAsyncHttpClient` and not a `SdkHttpClient` because I excluded the netty client and I am using https://github.com/matsluni/aws-spi-akka-http

## Your Environment
* AWS Java SDK version used: 2.15.60
* JDK version used: 11.0.8
* Operating System and version: Linux 5.11.10-1-MANJARO

**Comment by debora-ito** [comment]
Currently, all the Credential resolving process makes blocking calls, even in async clients. We have a task in our backlog to add support to async clients.

Related to https://github.com/aws/aws-sdk-java-v2/issues/2360.
