### ISSUE TITLE
[EC2 BUG] execution.interceptors not found

### ISSUE THREAD

**Issue by pixelable** [aws/aws-sdk-java-v2#2418]
JAR entry software/amazon/awssdk/services/ec2/execution.interceptors not found in my exported jar or on the github repository.

## Describe the bug
Getting a console error for described above class paths.

## Expected Behavior
Not get this error and load instead.

## Current Behavior
Reports the error to the console as missing.

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to instantiate execution interceptor chain.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98) ~[?:?]
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptorFromResource(ClasspathInterceptorChainFactory.java:108) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269) ~[?:1.8.0_282]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_282]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_282]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_282]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_282]
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptorsFromClasspath(ClasspathInterceptorChainFactory.java:64) ~[?:?]
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.getInterceptors(ClasspathInterceptorChainFactory.java:51) ~[?:?]
	at software.amazon.awssdk.services.ec2.DefaultEc2BaseClientBuilder.finalizeServiceConfiguration(DefaultEc2BaseClientBuilder.java:57) ~[?:?]
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:132) ~[?:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:157) ~[?:?]
	at software.amazon.awssdk.services.ec2.DefaultEc2ClientBuilder.buildClient(DefaultEc2ClientBuilder.java:27) ~[?:?]
	at software.amazon.awssdk.services.ec2.DefaultEc2ClientBuilder.buildClient(DefaultEc2ClientBuilder.java:22) ~[?:?]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:129) ~[?:?]
	at **REDACTED**.Quotoshard.<init>(Quotoshard.java:33) ~[?:?]
	at **REDACTED**.ServerManager.<init>(ServerManager.java:27) ~[?:?]
	at **REDACTED**.Rep.onEnable(Rep.java:20) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:391) ~[?:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:762) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1933) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1776) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1729) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1051) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1044) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1028) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:960) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3042-Spigot-a25e8ed-3512408]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.io.FileNotFoundException: JAR entry software/amazon/awssdk/services/ec2/execution.interceptors not found in /Users/nathanna/Desktop/projects/serv/presets/lobby/plugins/LobbyCore.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144) ~[?:1.8.0_282]
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152) ~[?:1.8.0_282]
	at java.net.URL.openStream(URL.java:1068) ~[?:1.8.0_282]
	at software.amazon.awssdk.core.interceptor.ClasspathInterceptorChainFactory.createExecutionInterceptorFromResource(ClasspathInterceptorChainFactory.java:89) ~[?:?]
```

**Redacted File Lines**
Quotoshard.java:33
```java
protected Ec2Client ac = Ec2Client.builder().region(Region.US_EAST_1).credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("SECRET", "SECRET"))).build();
```
ServerManager.java:27
```java
Quotoshard shardList = new Quotoshard();
```
Rep.java:20
```java
serverManagerCmd = new ServerManager(this);
```

## Steps to Reproduce
Require EC2Client.

## Tried Solutions
I tried including one in my own java code but it couldn't find that one either even though it showed up in java decompilers.

## Context
Unable to load or do anything with v2 and v1 has an external bug with the aws api or something so now i have no SDK that works.

## Your Environment
* AWS Java SDK version used: EC2 - 2.16.43
* JDK version used: openjdk-8
* Operating System and version: MacOS Big Sur - 11.2.3
* Running on Java as a Minecraft Server Plugin part.

**Comment by debora-ito** [comment]
@pixelable the code is looking for a file in `software/amazon/awssdk/services/ec2/execution.interceptors` but it's not finding one.

According to the [ExecutionInterceptor](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/interceptor/ExecutionInterceptor.html) docs:
> Service Interceptors are interceptors loaded from the classpath for a particular service's clients. When a service client is created by a client builder, all jars on the classpath (from the perspective of the current thread's classloader) are checked for a file named '/software/amazon/awssdk/services/{service}/execution.interceptors', where {service} is the package name of the service client. Any interceptors listed in these files (new line separated) are instantiated using their default constructor and loaded into the client.

How is the jar `/Users/nathanna/Desktop/projects/serv/presets/lobby/plugins/LobbyCore.jar` being created?

**Comment by pixelable** [comment]
Using Maven, I used https://jdec.app/ to open the compiled jar that is loaded in the Minecraft server and it showed the file with the same lines as the one on github but it kepted throwing the same error.

**Comment by pixelable** [comment]
> Using Maven, I used https://jdec.app/ to open the compiled jar that is loaded in the Minecraft server and it showed the file with the same lines as the one on github but it kepted throwing the same error.
@debora-ito

**Comment by pixelable** [comment]
@debora-ito ?

**Comment by debora-ito** [comment]
@pixelable I'm sorry for the lack of response in here.

When you decompiled the jar, probably the classes referenced in the interceptor files were not extracted/added to the classpath.
To avoid such issues, we recommend building you project using building tools like Maven or Gradle, we have instructions in our Developer Guide - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup-project-maven.html
