### ISSUE TITLE
S3Client.listObjects("bucketName") does throw S3Exception with an existing bucket

### ISSUE THREAD

**Issue by DiesDasJenes** [aws/aws-sdk-java-v2#2447]
I used for my local setup the latest localstack and created a bucket with awscli and I am able to list the buckets via `aws s3 ls --endpoint="http://localhost:4566" --no-sign-request --no-cli-pager  --region eu-central-1`.  I added a file to the bucket also via the awscli. I tried to list the objects within a bucket with the AWS Java SDK but I get an Exception with `null` as message and status `404`.  I checked that the bucket name is correct and there is an object within the bucket. 

## Expected Behavior
Method should return an ListObjectsRequest with a List<S3Object>. 

## Current Behavior
Method throws:
`null (Service: S3, Status Code: 404, Request ID: null, Extended Request ID: null)`

LocalS3ClientConfiguration
```
@Bean
  @Primary
  public S3Client s3Client(AwsCredentialsProvider awsCredentialsProvider) {
    Region region = Region.EU_CENTRAL_1;
    String port = "4566";
    String host = "localhost";
    URI uri = URI.create(String.format("http://%s:%s",host,port));

    return S3Client.builder().serviceConfiguration(
        S3Configuration.builder()
            .pathStyleAccessEnabled(true)
            .chunkedEncodingEnabled(false)
            .build())
        .credentialsProvider(awsCredentialsProvider)
        .endpointOverride(uri)
        .region(region)
        .build();
  }
```

AWSCredentialsProvider
```
@Bean
  @Primary
  public AwsCredentialsProvider awsCredentialsProvider() {
    AwsBasicCredentials basicCredentials = AwsBasicCredentials
        .create("doesn't matter", "it's localstack");
    return StaticCredentialsProvider.create(basicCredentials);
  }
```

Stacktrace:
```
null (Service: S3, Status Code: 404, Request ID: null, Extended Request ID: null)
software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 404, Request ID: null, Extended Request ID: null)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:106)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:84)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:42)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:94)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$6(BaseClientHandler.java:270)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:135)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:161)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:114)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:169)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:95)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.s3.DefaultS3Client.listObjects(DefaultS3Client.java:5941)
```

## Steps to Reproduce
```
ListObjectsRequest listObjectsRequest = ListObjectsRequest.builder().bucket(bucketName).build();
s3Client.listObjects(listObjectsRequest).contents();
```

## Your Environment
* AWS Java SDK version used: 3.9.0
* JDK version used: 11
* Operating System and version: MacOs 10.15.7

**Comment by debora-ito** [comment]
@DiesDasJenes I think the error might be related to the path-style configuration. Any reason you need to use path-style? Do the bucket or key names have any special characters?

Can you provide the [verbose wire logs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) of the call? We can get additional information from the data being sent in the request and response. Please make sure to redact any sensitive information from the logs.

**Comment by debora-ito** [comment]
@DiesDasJenes thank you for the logs. This looks like a configuration or communication issue with localstack, I'm not able to properly help you out. I suggest you open an issue in their repository: https://github.com/localstack/localstack

**Comment by DiesDasJenes** [comment]
Thanks for the support. I opened an issue on the localstack page (https://github.com/localstack/localstack/issues/4005)

**Comment by debora-ito** [comment]
I'll go ahead and close this. Feel free to reach out if you have any other question.
