### ISSUE TITLE
NettyNioAsyncHttpClient Error

### ISSUE THREAD

**Issue by hanymorcos** [aws/aws-sdk-java-v2#2449]
How do I make NettyNioAsyncHttpClient trust all certifiactes? 

  SdkAsyncHttpClient customClient = NettyNioAsyncHttpClient.builder().maxConcurrency(100).sslProvider(SslProvider.JDK).tlsKeyManagersProvider(NoneTlsKeyManagersProvider.getInstance()).buildWithDefaults(mapWithTrustAllCerts());
         

2021-04-30 12:52:27,134 94279 [DefaultMessageListenerContainer-1] 1bccbe1e992a4d7d80a56c7eb9e403f3  WARN  software.amazon.awssdk.http.SystemPropertyTlsKeyManagersProvider Unable to create KeyManagers from javax.net.ssl.keyStore property value '/opt/usr/test/keystore.pfx' java.lang.NullPointerExceptionu2028	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:374) ~[?:1.8.0_282]u2028	... 74 moreu2028Wrapped by: java.security.UnrecoverableKeyException: Get Key failed: nullu2028	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:438) ~[?:1.8.0_282]u2028	at java.security.KeyStore.getKey(KeyStore.java:1023) ~[?:1.8.0_282]u2028	at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:145) ~[?:1.8.0_282]u2028	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70) ~[?:1.8.0_282]u2028	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256) ~[?:1.8.0_282]u2028	at software.amazon.awssdk.internal.http.AbstractFileStoreTlsKeyManagersProvider.createKeyManagers(AbstractFileStoreTlsKeyManagersProvider.java:46) ~[http-client-spi-2.16.49.jar:?]u2028	at software.amazon.awssdk.http.SystemPropertyTlsKeyManagersProvider.lambda$keyManagers$1(SystemPropertyTlsKeyManagersProvider.java:59) [http-client-spi-2.16.49.jar:?]u2028	at software.amazon.awssdk.http.SystemPropertyTlsKeyManagersProvider$$Lambda$348/0x00000000a58567e0.apply(Unknown Source) [http-client-spi-2.16.49.jar:?]u2028	at java.util.Optional.map(Optional.java:215) [?:1.8.0_282]u2028	at software.amazon.awssdk.http.SystemPropertyTlsKeyManagersProvider.keyManagers(SystemPropertyTlsKeyManagersProvider.java:54) [http-client-spi-2.16.49.jar:?]

**Comment by debora-ito** [comment]
@hanymorcos it looks like TLSKeyManagersProvider was able to read the javax.net.ssl.keyStore system property but is hitting a null value somewhere in the process. I'm afraid you'll have to investigate/debug your application to check what value is null when it shouldn't.

A quick internet search showed people experiencing NullPointerException when they were not providing the key store password.

**Comment by hanymorcos** [comment]
Thanks Debora,
Yeah. I'm guessing that's the case as well.  But I'm passing no TLS provider. Accept all certificates why does it still load the keystore.

**Comment by debora-ito** [comment]
Hi @hanymorcos 

I'm going through some old issues, found this one. Are you still experiencing the issue?

**Comment by akperrine** [comment]
Did anybody ever find a solution to this problem? I have come across the exact same problem and any information on this problem is sparse to say the least.
