### ISSUE TITLE
DynamoDbException: null (Service: DynamoDb, Status Code: 500, Request ID: null, Extended Request ID: null)

### ISSUE THREAD

**Issue by bigunyak** [aws/aws-sdk-java-v2#2456]
# Application fails with unclear error

## Describe the bug
`DynamoDbEnhancedClient.batchWriteItem(BatchWriteItemEnhancedRequest request)` call fails with error which hard to understand and fix.

## Expected Behavior
Error message should reveal the root cause of an issue.

## Current Behavior
In my SpringBoot application tests I use `batchWriteItem()` method to delete all table records after test method is complete. To get all table records I first call table scan and then `batchWriteItem()` method in a loop for no more that 25 records per one call.
The following code implements desired logic.
```java
    private void deleteBatch(List<MyRecord> records) {
        WriteBatch.Builder<MyRecord> writeBatchBuilder = WriteBatch.builder(MyRecord.class)
                .mappedTableResource(myTable);
        records.forEach(writeBatchBuilder::addDeleteItem);

        BatchWriteItemEnhancedRequest batchWriteItemEnhancedRequest =
                BatchWriteItemEnhancedRequest.builder()
                        .writeBatches(writeBatchBuilder.build())
                        .build();
        BatchWriteResult batchResults = enhancedClient.batchWriteItem(batchWriteItemEnhancedRequest);

        List<Key> unprocessed = batchResults.unprocessedDeleteItemsForTable(myTable);
        if (!unprocessed.isEmpty()) {
            String keys = unprocessed.stream()
                    .map(key -> key.toString())
                    .collect(Collectors.joining(", "));
            throw new RuntimeException("Couldn't delete some of batch items: [" + keys + "]");
        }
    }
```

This code is then called from method annotated with `@AfterEach` annotation to run it after every test method in the class.

Below is the stack trace I get.
```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: null (Service: DynamoDb, Status Code: 500, Request ID: null, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:135)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:161)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:114)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:169)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:95)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.batchWriteItem(DefaultDynamoDbClient.java:768)
	at software.amazon.awssdk.enhanced.dynamodb.internal.operations.DatabaseOperation.execute(DatabaseOperation.java:82)
	at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbEnhancedClient.batchWriteItem(DefaultDynamoDbEnhancedClient.java:74)
```

## Steps to Reproduce
Unfortunately this problem occurs only in my Jenkins environment, I can't reproduce it locally on my machine.

## Possible Solution
There should be more debug information available to understand root cause of the issue.

## Context
As mentioned earlier I use `batchWriteItem()` to clean-up test data in unit tests. The setup is using localstack to run DynamoDB service locally.

## Your Environment
* AWS Java SDK version used: 2.16.54
* JDK version used: 1.8.0_275
* Operating System and version:

**Comment by debora-ito** [comment]
@bigunyak thank you for reaching out. Status code 500 is for InternalServerError, an error occurred on the server side. I agree that the stacktrace doesn't show a helpful message but we'll need more info to understand the cause of the issue. 

- Is it possible to turn on the [verbose wire logs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) on your Jenkins environment? Information on the wire logs will help us in the investigation of a cause. It's not recommended if it's a production environment though.
- Have you noticed anything specific about the dynamodb items you are deleting, something we can use to try to reproduce the issue?
- Has the error always occurred, or has it started recently?

**Comment by bigunyak** [comment]
Thanks for looking into it @debora-ito.
The problem with this issue is that I can't reproduce it even in Jenkins now, it's just disappeared and everything works again. We're guessing it could be related to how DynamoDB is run in localstack but we can't debug it further at the moment.

The reason I raised this issue though, is not the original root cause of the problem, which is still unknown to me, but the absent error message in DynamoDbException exception which makes it hard to debug any issue.
Even if error occurred on the server side as you suggest, there still must be something to include in the error message like RequestID and response message. Or in case the connection got closed unexpectedly, then that can be communicated as well. I can't think of a situation when you'd end up without any error details whatsoever, unless you drop/lose them somewhere in the code. And this is what this report suggests to look into and address if possible.

Regarding dynamodb items, there is definitely nothing special about them, as we have no problems deleting them on by one in separate delete calls.
The issue occurred out of nowhere because all the same code worked just fine, and same code works again now when the issue has disappeared. Really weird. :(

**Comment by debora-ito** [comment]
@bigunyak I completely understand your point. The SDK usually is able to unmarshall the errors in the response, that's why I asked for the wire logs, so we could get the information that was sent in the wire and check why the SDK didn't show a useful message in this case. For example, the message showed `requestID: null` because probably the response didn't have one - requestIDs are sent by the service. If the issue was an unexpected closed connection, the SDK would show something like `Unable to execute HTTP request` or  `TimeoutException`, this was not a networking problem.

Internal server errors are intermittent in most cases. Also, as you pointed out, the issue can be related to localstack.

Since you are not seeing the issue anymore I'll mark this to autoclose soon. Feel free to reach out if you have further questions or if you start getting the error again.
