### ISSUE TITLE
Amazon TranscribeStreamingAsyncClient: Your stream is too big

### ISSUE THREAD

**Issue by mrknmc** [aws/aws-sdk-java-v2#2550]
## Describe the bug

We see following errors in our logs when using `TranscribeStreamingAsyncClient` client:

```
  |   | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[parrot-live-all.jar:?]
  |   | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1300) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1253) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1504) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2FrameCodec$FrameListener.onDataRead(Http2FrameCodec.java:646) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2FrameCodec.onHttp2Frame(Http2FrameCodec.java:707) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.Http2MultiplexHandler.channelRead(Http2MultiplexHandler.java:181) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.AbstractHttp2StreamChannel.fireChildRead(AbstractHttp2StreamChannel.java:555) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doRead0(AbstractHttp2StreamChannel.java:901) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:42) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:49) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.onDataRead(Http2ToHttpInboundAdapter.java:84) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.LastHttpContentHandler.channelRead(LastHttpContentHandler.java:43) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:173) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:199) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:228) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[parrot-live-all.jar:?]
  |   | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.channelRead(HandlerPublisher.java:383) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:407) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:221) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:270) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.utils.ExceptionHandlingUtils.tryCatch(ExceptionHandlingUtils.java:40) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.lambda$onNext$2(ResponseHandler.java:270) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.awscore.eventstream.EventStreamAsyncResponseTransformer$ByteSubscriber.onNext(EventStreamAsyncResponseTransformer.java:350) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.awscore.eventstream.EventStreamAsyncResponseTransformer$ByteSubscriber.onNext(EventStreamAsyncResponseTransformer.java:374) ~[parrot-live-all.jar:?]
  |   | at software.amazon.eventstream.MessageDecoder.feed(MessageDecoder.java:85) ~[parrot-live-all.jar:?]
  |   | at software.amazon.eventstream.MessageDecoder.feed(MessageDecoder.java:137) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.awscore.eventstream.EventStreamAsyncResponseTransformer.handleMessage(EventStreamAsyncResponseTransformer.java:276) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:42) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:63) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.unmarshall(AwsJsonProtocolErrorUnmarshaller.java:89) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.services.transcribestreaming.model.BadRequestException$BuilderImpl.build(BadRequestException.java:79) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.services.transcribestreaming.model.BadRequestException$BuilderImpl.build(BadRequestException.java:119) ~[parrot-live-all.jar:?]
  |   | Caused by: software.amazon.awssdk.services.transcribestreaming.model.BadRequestException: Your stream is too big. Reduce the frame size and try your request again. (Service: transcribe, Status Code: 400, Request ID: 345ea701-b0d8-47b7-8651-5c46287e391c, Extended Request ID: null)
  |   | at java.lang.Thread.run(Unknown Source) [?:?]
  |   | at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
  |   | at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
  |   | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) [?:?]
  |   | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) [?:?]
  |   | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) [?:?]
  |   | at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:209) ~[parrot-live-all.jar:?]
  |   | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
  |   | at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:104) ~[parrot-live-all.jar:?]
  |   | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
  |   | at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:74) ~[parrot-live-all.jar:?]
  |   | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
  |   | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:125) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:144) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:85) ~[parrot-live-all.jar:?]
  |   | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
  |   | at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:74) ~[parrot-live-all.jar:?]
  |   | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
  |   | at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
  |   | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51) ~[parrot-live-all.jar:?]
  |   | at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:60) ~[parrot-live-all.jar:?]
  |   | java.util.concurrent.CompletionException: software.amazon.awssdk.services.transcribestreaming.model.BadRequestException: Your stream is too big. Reduce the frame size and try your request again. (Service: transcribe, Status Code: 400, Request ID: 345ea701-b0d8-47b7-8651-5c46287e391c, Extended Request ID: null)
```

It seems that this is related to the size of the frame used for HTTP/2 transport. However, I could not find any way to configure the frame size in AWS SDK. Moreover, this feels like something that should be set by the client.

## Expected Behavior

The client should either set the frame size or allow for configuration so consumers of SDK can configure it.

## Current Behavior

See exception stack trace above. I do not have the data that we were sending when this exception happened.

## Steps to Reproduce

Not sure how to reproduce. We send chunks of about 2KB in size to Amazon Transcribe. This issue occurs rarely.

## Context

Our Amazon Transcribe Streaming session is closed which means we have to stop the transcription.

## Your Environment

* AWS Java SDK version used: 2.16.88
* JDK version used: Java 16
* Operating System and version: MacOS Big Sur (dev) as well as Linux (production)

**Comment by debora-ito** [comment]
@mrknmc apologies for taking this long to get a response.

Are you still seeing the errors?
I see the error occurs rarely, are you able to identify if there's anything different or unique when the error shows up?

**Comment by mrknmc** [comment]
@debora-ito sadly? we're not seeing this error anymore so I guess we can close this issue
