### ISSUE TITLE
Unable to run aws sdk for getting KinesisAsyncClient on mac

### ISSUE THREAD

**Issue by lakshmi-auth0** [aws/aws-sdk-java-v2#2601]
Unable to get KinesisAsyncClient working in my environment

## Describe the bug
Trying to get KinesisAsyncClient for kinesis stream arn:aws:kinesis:us-west-2:200643466137:stream/auth0-user-events
using the sample code @ https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/javav2/example_code/kinesis/src/main/java/com/example/kinesis/KinesisStreamRxJavaEx.java. This is not working and giving classdefnotfound error
I have added the following dependencies in my project as well
     <dependency>
            <groupId>software.amazon.kinesis</groupId>
            <artifactId>amazon-kinesis-client</artifactId>
            <version>2.2.9</version>
        </dependency>

as well as tried various combination of the netty nio clients
software.amazon.awssdk:netty-nio-client:2.16.101
io.netty:netty-tcnative-boringssl-static:2.0.19.Final
io.grpc:grpc-netty:1.8.0

O/S mac

## Expected Behavior
This should work OOTB for all environments including MACOS.
I should be able to connect Kinesis using Java SDK and send and receive data from the stream

## Current Behavior

The code gives error with stack trace 
Caused by: java.lang.NoClassDefFoundError: io/netty/internal/tcnative/SSLPrivateKeyMethod

	at software.amazon.awssdk.http.nio.netty.internal.AwaitCloseChannelPoolMap.newPool(AwaitCloseChannelPoolMap.java:119)
	at software.amazon.awssdk.http.nio.netty.internal.AwaitCloseChannelPoolMap.newPool(AwaitCloseChannelPoolMap.java:49)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at software.amazon.awssdk.http.nio.netty.internal.SdkChannelPoolMap.get(SdkChannelPoolMap.java:44)
	at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient.createRequestContext(NettyNioAsyncHttpClient.java:140)
	at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient.execute(NettyNioAsyncHttpClient.java:121)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$NonManagedSdkAsyncHttpClient.execute(SdkDefaultClientBuilder.java:463)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.doExecuteHttpRequest(MakeAsyncHttpRequestStage.java:219)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.executeHttpRequest(MakeAsyncHttpRequestStage.java:191)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$execute$1(MakeAsyncHttpRequestStage.java:100)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.execute(MakeAsyncHttpRequestStage.java:96)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.execute(MakeAsyncHttpRequestStage.java:61)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallAttemptMetricCollectionStage.execute(AsyncApiCallAttemptMetricCollectionStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallAttemptMetricCollectionStage.execute(AsyncApiCallAttemptMetricCollectionStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.attemptExecute(AsyncRetryableStage.java:110)

## Steps to Reproduce

Create simple kinesis stream with 1 shard on AWS
Download aws samples https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javav2/example_code/kinesis
Create a consumer ARN for the stream using command line
aws kinesis  register-stream-consumer --stream-arn "XYZ" --consumer-name indexer
Run code for https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/javav2/example_code/kinesis/src/main/java/com/example/kinesis/KinesisStreamRxJavaEx.java
after updating to your consumer ARN.

Error occurs.

## Possible Solution

Its possible that the error occurs due to different version/missing libraries

## Context
Trying to use simple kinesis stream (with 1 shard) to get data about shard and consume the data in the shard

## Your Environment

* AWS Java SDK version used  
software.amazon.awssdk:kinesis:2.16.99  
* JDK version used:
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
* Operating System and version:  MAC OS 
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1217

**Comment by debora-ito** [comment]
Hi @lakshmi-auth0, 

Having `software.amazon.kinesis:amazon-kinesis-client:2.2.9` should be sufficient to run the `KinesisStreamRxJavaEx.java` example as it is.

Looking at the example, I'm not sure exactly where `io/netty/internal/tcnative/SSLPrivateKeyMethod` is needed, but for the sake of running the example successfully, you can try to add the following dependency and see if the error goes away?

```
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative</artifactId>
      <version>2.0.40.Final</version>
</dependency>
```

**Comment by lakshmi-auth0** [comment]
Thanks this worked for me after I added the tcnative and the corresponding io.netty:netty-tcnative-boringssl-static:2.0.40.Final .
