### ISSUE TITLE
AWS IOT Client throws "ProtocolException: Invalid HTTP method: PATCH" with UpdateThing API

### ISSUE THREAD

**Issue by ramakrishnanjayaraman** [aws/aws-sdk-java-v2#2670]
## Describe the bug
When invoking the AwsIOTClient::UpdateThing api with the UrlConnectionHttpClient, the SDK throws the following exception:

Exception in thread "main" java.io.UncheckedIOException: java.net.ProtocolException: Invalid HTTP method: PATCH

If we switch the http client to ApacheHttpClient it works fine. 

The codes is as follows:
IotClient iotClient = IotClient.builder()
                .region(Region.US_EAST_1)
                .credentialsProvider(ProfileCredentialsProvider.create("xyz"))
                .httpClient(UrlConnectionHttpClient.builder().build())
                .build();

  iotClient.updateThing(UpdateThingRequest.builder()
                                .thingName("test")
                                .attributePayload(
                                        AttributePayload.builder().attributes(
                                                Map.of("attr1", "test",
                                                       "attr2", "test")
                                        ).merge(Boolean.FALSE).build()
                                ).build());

## Expected Behavior
updateThing should succeed

## Current Behavior
updateThing throws unsupported protocol exception

Exception in thread "main" java.io.UncheckedIOException: java.net.ProtocolException: Invalid HTTP method: PATCH
	at software.amazon.awssdk.utils.FunctionalUtils.asRuntimeException(FunctionalUtils.java:180)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeRunnable$5(FunctionalUtils.java:126)
	at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:140)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient.createAndConfigureConnection(UrlConnectionHttpClient.java:133)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient.prepareRequest(UrlConnectionHttpClient.java:114)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$NonManagedSdkHttpClient.prepareRequest(SdkDefaultClientBuilder.java:425)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:67)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:128)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:154)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:107)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:162)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:91)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.iot.DefaultIotClient.updateThing(DefaultIotClient.java:16681)
	at com.xyz.lambda.handler.StartupHandler.main(StartupHandler.java:52)
Caused by: java.net.ProtocolException: Invalid HTTP method: PATCH
	at java.base/java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:487)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(HttpURLConnection.java:570)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestMethod(HttpsURLConnectionImpl.java:370)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient.lambda$createAndConfigureConnection$2(UrlConnectionHttpClient.java:133)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeRunnable$5(FunctionalUtils.java:124)
	... 41 more

## Steps to Reproduce
IotClient iotClient = IotClient.builder()
                .region(Region.US_EAST_1)
                .credentialsProvider(ProfileCredentialsProvider.create("xyz"))
                .httpClient(UrlConnectionHttpClient.builder().build())
                .build();

  iotClient.updateThing(UpdateThingRequest.builder()
                                .thingName("test")
                                .attributePayload(
                                        AttributePayload.builder().attributes(
                                                Map.of("attr1", "test",
                                                       "attr2", "test")
                                        ).merge(Boolean.FALSE).build()
                                ).build());

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
Hi @ramakrishnanjayaraman thank you for reaching out.

IoT updateThing is a PATCH method (see [here](https://docs.aws.amazon.com/iot/latest/apireference/API_UpdateThing.html) in the API Reference) and HttpURLConnection does not support the PATCH HTTP method: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/HttpURLConnection.html#setRequestMethod(java.lang.String)

To be able to call `updateThing` using the SDK you'll need to use ApacheHttpClient or the Netty-based Async client.

**Comment by ramakrishnanjayaraman** [comment]
Hi @debora-ito thanks for the quick feedback. If we do that then we will need to include apache-client that will increase cold start time. Why does IoT updateThing use PATCH vs other clients that do not use it ?

**Comment by debora-ito** [comment]
The HTTP method used is defined in the API design, it depends on what the API operation will do. Each HTTP method has a set of requirements defined in the Specification document - see [Method Definitions](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9)  in RFC 2616 and [RFC 5789](https://datatracker.ietf.org/doc/html/rfc5789) where PATCH method is specified. 

`UpdateThing` uses PATCH method because it's a good match for what the operation does with a `Thing`, you only need to provide the attributes that you want to update and it won't affect the other attributes.

**Comment by debora-ito** [comment]
Going ahead and closing this. Feel free to reach out if you have any other question.
