### ISSUE TITLE
SageMakerA2IRuntimeClient - DescribeHumanLoopResponse: Error parsing timestamp in response

### ISSUE THREAD

**Issue by OpenGaet** [aws/aws-sdk-java-v2#2671]
## Describe the bug

 Using SageMakerA2IRuntimeClient, "DescribeHumanLoopResponse" stores the "creation time" as a "timestamp". When the SageMakerA2IRuntimeClient makes the request it tries to parse the returned timestamp through the function "parseUnixTimestampInstant". This function uses native Java function "BigDecimal", which is having trouble parsing the data given to it. 

```
ERROR 1484 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Unable to parse date : 2021-08-12T23:52:14.723Z). Response Code: 200, Response Text: OK] with root 
cause

java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:577) ~[na:na]
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:401) ~[na:na]
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:834) ~[na:na]
        at software.amazon.awssdk.utils.DateUtils.parseUnixTimestampInstant(DateUtils.java:135) ~[utils-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:72) ~[protocol-core-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:54) ~[protocol-core-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:32) ~[protocol-core-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller$SimpleTypeJsonUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:161) ~[aws-json-protocol-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:213) ~[aws-json-protocol-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:199) ~[aws-json-protocol-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:169) ~[aws-json-protocol-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:82) ~[aws-json-protocol-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36) ~[aws-json-protocol-2.16.29.jar:na]
        at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:44) ~[aws-json-protocol-2.16.29.jar:na]
        at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:94) ~[aws-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$7(BaseClientHandler.java:269) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:97) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:72) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:133) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:159) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:112) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[sdk-core-2.16.29.jar:na]
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55) ~[aws-core-2.16.29.jar:na]
        at software.amazon.awssdk.services.sagemakera2iruntime.DefaultSageMakerA2IRuntimeClient.describeHumanLoop(DefaultSageMakerA2IRuntimeClient.java:197) ~[sagemakera2iruntime-2.16.43.jar:na]
```

## Steps to Reproduce

Code snippet:
```
import software.amazon.awssdk.services.sagemakera2iruntime.SageMakerA2IRuntimeClient;
import software.amazon.awssdk.services.sagemakera2iruntime.model.DescribeHumanLoopRequest;
import software.amazon.awssdk.services.sagemakera2iruntime.model.DescribeHumanLoopResponse;
import software.amazon.awssdk.regions.Region;

public class Main {
    public static void main(String[] args) {
      SageMakerA2IRuntimeClient sagemakerA2IClient = SageMakerA2IRuntimeClient.builder()
			.region(Region.US_EAST_1)
			.build();
      DescribeHumanLoopRequest request = DescribeHumanLoopRequest.builder()
			.humanLoopName("humanLoopName")
			.build();
      DescribeHumanLoopResponse response = sagemakerA2IClient.describeHumanLoop(request);
    }
}
```

## Possible Solution

Similar problem was solved here: https://github.com/aws/aws-sdk-java-v2/issues/2160

## Your Environment

* AWS Java SDK version used:
```
<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>sagemakera2iruntime</artifactId>
			<version>2.16.43</version>
</dependency>

```
* JDK version used:
```
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9-LTS, mixed mode)
```
* Operating System and version: Microsoft Windows 10 Enterprise 10.0.18363

**Comment by debora-ito** [comment]
Hi @OpenGaet thank you for reaching out, I can repro the issue.

You're correct, the root cause is the same of #2160, the `CreationTime` on the service response does not match the timestamp format expected by the client. I will reach out to the service team and ask for a fix.

**Comment by OpenGaet** [comment]
Hello @debora-ito, thank you for reaching out to the service team. Has there been an update from their side?

**Comment by OpenGaet** [comment]
@debora-ito Seeing as how its been several months, will this ever be fixed?

**Comment by OpenGaet** [comment]
Thank you

**Comment by vleandersson** [comment]
# Issue seen in state machine SDK integration as well
Using the state machine SDK I am facing the same issue trying to describe the Human Loop using the SDK integration `arn:aws:states:::aws-sdk:sagemakera2iruntime:describeHumanLoop`. Reaching out to the internal AWS enterprise support they have confirmed that the issue is not lying within the step function SDK integration: 
_"This issue does not originate from the Step Functions integration to the SDK, it is actually within the SageMaker AI SDK, and at the present moment there is no workaround."_
The support references this issue as a bug that now propagates over to the Step Function integration with SDK.

The current workaround is to use a lambda for a custom integration, but this is not optimal moving forward with production systems as it adds extra maintenance, instability and less observability than the native SDK integration gives.

## Error returned to the state machine
```
{
    "id": "14",
    "type": "TaskFailed",
    "details": {
        "cause": "Unable to parse date : 2022-04-24T20:14:22.850Z",
        "error": "SageMakerA2IRuntime.SdkClientException",
        "resource": "describeHumanLoop",
        "resourceType": "aws-sdk:sagemakera2iruntime"
    },
    "previous_event_id": "13",
    "event_timestamp": "1650831265161",
    "execution_arn": "arn:aws:states:eu-west-2:439675880352:execution:OCR_HIL_TEST:4c19ea1e-5545-2d24-c186-752639a40ef2"
}
```

## State machine example
```
{
  "Comment": "A description of my state machine",
  "StartAt": "Generate HumanLoopName",
  "States": {
    "Generate HumanLoopName": {
      "Type": "Pass",
      "Parameters": {
        "humanLoopName.$": "$$.Execution.Name"
      },
      "Next": "StartHumanLoop"
    },
    "StartHumanLoop": {
      "Type": "Task",
      "Parameters": {
        "FlowDefinitionArn": "arn:aws:sagemaker:eu-west-2:xxxxx:flow-definition/test",
        "HumanLoopInput": {
          "InputContent": "{\"name\":\"john\", \"age\":22, \"class\":\"mca\"}"
        },
        "HumanLoopName.$": "$.humanLoopName"
      },
      "ResultPath": null,
      "Resource": "arn:aws:states:::aws-sdk:sagemakera2iruntime:startHumanLoop",
      "Next": "Wait"
    },
    "Wait": {
      "Type": "Wait",
      "Seconds": 2,
      "Next": "DescribeHumanLoop"
    },
    "DescribeHumanLoop": {
      "Type": "Task",
      "Parameters": {
        "HumanLoopName.$": "$.humanLoopName"
      },
      "Resource": "arn:aws:states:::aws-sdk:sagemakera2iruntime:describeHumanLoop",
      "ResultSelector": {
        "HumanLoopStatus.$": "$.HumanLoopStatus"
      },
      "OutputPath": "$.HumanLoopStatus",
      "End": true
    }
  }
}
```

**Comment by debora-ito** [comment]
For visibility to other SDKs, I'm moving this to the  `aws-sdk` repository.
