### ISSUE TITLE
error 403 in transfer manager when upload big file

### ISSUE THREAD

**Issue by chipironVacilon** [aws/aws-sdk-java-v2#2699]
Transfer manager is returning a 403 error when trying to upload files bigger than 800MB.

## Describe the bug

In a multi-module project the parent pom is configured like this:
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>bom</artifactId>
            <version>2.17.34</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency> 
</dependencyManagement>
```

and the child pom dependencies are:
```
<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>software.amazon.awssdk</groupId>
                    <artifactId>netty-nio-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-crt-client</artifactId>
            <version>2.17.34-PREVIEW</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3-transfer-manager</artifactId>
            <version>2.17.34-PREVIEW</version>
        </dependency>
```

So default crt http client is used. The implementation of the upload code:

```
S3TransferManager transferManager = S3TransferManager.builder()
                    .s3ClientConfiguration(b -> b.credentialsProvider( StaticCredentialsProvider.create(AwsBasicCredentials.create(this.key, this.secret) ))                       
                            .region(Region.of(this.region)))
                    .build();

            Upload upload = transferManager.upload(
                    b -> b.source(file.toPath()).putObjectRequest(r -> r.bucket(bucket).key(finalKey))
            );
            CompletedUpload completedUpload =
                     upload.completionFuture().join();

            System.out.println("PutObjectResponse: " + completedUpload.response());
```

Several configurations of maxConcurrency, minimumPartSizeInBytes and targetThroughputInGbps has been tested with same results.

The related policy is full access to s3 resources:
```
{
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

## Expected Behavior
The target file is upoloaded to the bucket.

## Current Behavior
Several files has been tested (zip, avi and pdf formats). Files with size lower than  800MB uploads fine. Bigger files throws a 403 error:
```
java.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.S3Exception: Invalid response status from request

	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at software.amazon.awssdk.transfer.s3.internal.DefaultS3CrtAsyncClient.lambda$putObject$3(DefaultS3CrtAsyncClient.java:137)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.amazonaws.s3.S3NativeClient$3.onFinished(S3NativeClient.java:271)
	at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:19)
Caused by: software.amazon.awssdk.services.s3.model.S3Exception: Invalid response status from request
	at software.amazon.awssdk.services.s3.model.S3Exception$BuilderImpl.build(S3Exception.java:95)
	at software.amazon.awssdk.services.s3.model.S3Exception$BuilderImpl.build(S3Exception.java:55)
	at software.amazon.awssdk.transfer.s3.internal.CrtErrorHandler.getServiceSideException(CrtErrorHandler.java:71)
	at software.amazon.awssdk.transfer.s3.internal.CrtErrorHandler.lambda$transformException$0(CrtErrorHandler.java:55)
	at java.util.Optional.map(Optional.java:215)
	at software.amazon.awssdk.transfer.s3.internal.CrtErrorHandler.transformException(CrtErrorHandler.java:55)
	at software.amazon.awssdk.transfer.s3.internal.DefaultS3CrtAsyncClient.lambda$putObject$3(DefaultS3CrtAsyncClient.java:138)
	... 6 more
Caused by: software.amazon.awssdk.crt.s3.CrtS3RuntimeException: Invalid response status from request AWS_ERROR_S3_INVALID_RESPONSE_STATUS(9223)
	at com.amazonaws.s3.S3NativeClient$3.onFinished(S3NativeClient.java:263)
	... 1 more
```

## Steps to Reproduce
Use the configuration and code described above.

## Your Environment

* AWS Java SDK version used: 2.17.34
* JDK version used: jdk1.8.0_181
* Operating System and version: Manjaro Linux. Kernel 5.9.16-1

**Comment by debora-ito** [comment]
Hi @chipironVacilon thank you for reaching out.

With the message `Invalid response status from request` it looks like the client is having problems to unmarshall the response. Are you able to reproduce it reliably? Can you provide the [verbose wirelogs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) of the problematic call? Make sure to redact any sensitive information, like access key Ids.

**Comment by zoewangg** [comment]
Hi @chipironVacilon, are you able to upload the same object (>800MB) using the low level S3 client directly?
Just curious, how did you find out it was 403? I did not see it from the stacktrace.

**Comment by debora-ito** [comment]
@chipironVacilon I've removed the link to the instructions on how to get the verbose wirelogs from my comment above, because TransferManager uses the CRT-based HTTP client and requires different steps. There's two options: 

1.  Adding a Log method in code: `Log.initLoggingToFile(Log.LogLevel.Error, "log.txt")`  ([example](https://github.com/awslabs/aws-crt-java/blob/main/src/test/java/com/amazonaws/test/AwsClientTestFixture.java#L29))

2.  Or using the `aws.crt.log.destination` system property (seen [here](https://github.com/awslabs/aws-crt-java/blob/main/src/main/java/software/amazon/awssdk/crt/Log.java#L22)).

The verbose wirelogs would provide more insights on the response.

**Comment by chipironVacilon** [comment]
Thanks for your responses.
I think I've found the bug. It is not related to size, but to the file key encoding.

**Comment by zoewangg** [comment]
Thank you for the detailed report! We will look into it. Do you have any other feedback on transfer manager? We'd love to hear your thoughts. 🙂

**Comment by chipironVacilon** [comment]
@debora-ito thanks for the logger info. It will be quite useful. I spend several hours trying to make it work following your first indications XD. 
@zoewangg New transfer manager works faster and is easier to implement. Quite useful for me. I write applications that makes massive uploads to S3 so processes has been boosted. I´m happy with this :)

**Comment by chipironVacilon** [comment]
I've enabled wirelogs as @debora-ito suggested and do some tests. Hope that helps.

original file: big crunch (2021).zip

1 - Upload as is:

POST
/test/big crunch (2021).zip

```
[ERROR] [2021-09-10T07:34:22Z] [00007fdcb17fa640] [http-stream] - id=static: Request path is invalid
[ERROR] [2021-09-10T07:34:22Z] [00007fdcb17fa640] [http-connection] - id=0x7fdc94107ac0: Cannot create request stream, error 2054 (AWS_ERROR_HTTP_INVALID_PATH)
[ERROR] [2021-09-10T07:34:22Z] [00007fdcb17fa640] [S3MetaRequest] - id=0x7fdd60e44fc0: Could not make HTTP request 0x7fdc98000e80
[DEBUG] [2021-09-10T07:34:22Z] [00007fdcb17fa640] [S3MetaRequest] - id=0x7fdd60e44fc0: Request 0x7fdc98000e80 finished with error code 2054 and response status 0
[ERROR] [2021-09-10T07:34:22Z] [00007fdcb17fa640] [S3MetaRequest] - id=0x7fdd60e44fc0 Meta request failed from error 2054 (Path is invalid.). (request=0x7fdc98000e80, response status=0). Try to setup a retry.
```

2 - Upload pre-processing last part of the path, replacing spaces and encoding: 

```
finalKey = finalKey.replace(" ", "_");
encodedKey = finalKey
            .replace(finalKey.split("/")[finalKey.split("/").length - 1 ], URLEncoder.encode(finalKey.split("/")[finalKey.split("/").length - 1 ], "UTF-8"));
```

```
PUT
/test/big_crunch_%282021%29.zip 
```

result: big_crunch_(2021).zip Upload successful.


3 - Upload pre-processing last part of the path, just encoding:  

```
encodedKey = finalKey
            .replace(finalKey.split("/")[finalKey.split("/").length - 1 ], URLEncoder.encode(finalKey.split("/")[finalKey.split("/").length - 1 ], "UTF-8"));
```

```
POST
/0000000000000toolboxtest/big+crunch+%282021%29.zip
```

```
[DEBUG] [2021-09-10T08:08:58Z] [00007fce06ffd640] [S3MetaRequest] - id=0x7fce50e2bad0 Incoming body for request 0x7fcd68000c20. Response status: 403. Data Size: 2122. connection: 0x7fcd680015e0.
[DEBUG] [2021-09-10T08:08:58Z] [00007fce06ffd640] [http-stream] - id=0x7fcd6c11d4f0: Client request complete, response status: 403 (Forbidden).
[DEBUG] [2021-09-10T08:08:58Z] [00007fce06ffd640] [S3MetaRequest] - id=0x7fce50e2bad0: Request 0x7fcd68000c20 finished with error code 9223 and response status 403
[ERROR] [2021-09-10T08:08:58Z] [00007fce06ffd640] [S3MetaRequest] - id=0x7fce50e2bad0 Meta request cannot recover from error 9223 (Invalid response status from request). (request=0x7fcd68000c20, response status=403)
[INFO] [2021-09-10T08:08:58Z] [00007fce06ffd640] [http-connection] - id=0x7fcd6c107aa0: Shutting down connection with error code 0 (AWS_ERROR_SUCCESS).
[DEBUG] [2021-09-10T08:08:58Z] [00007fce06ffd640] [task-scheduler] - id=0x7fcd6c001700: Scheduling channel_shutdown task for immediate execution
[DEBUG] [2021-09-10T08:08:58Z] [00007fce06ffd640] [connection-manager] - id=0x7fce50c84cb0: Releasing connection (id=0x7fcd6c107aa0)
[DEBUG] [2021-09-10T08:08:58Z] [00007fce06ffd640] [connection-manager] - id=0x7fce50c84cb0: snapshot - state=1, idle_connection_count=0, pending_acquire_count=0, pending_connect_count=0, vended_connection_count=0, open_connection_count=1, ref_count=1
[INFO] [2021-09-10T08:08:58Z] [00007fce06ffd640] [connection-manager] - id=0x7fce50c84cb0: Releasing connection (id=0x7fcd6c107aa0)
[DEBUG] [2021-09-10T08:08:58Z] [00007fce06ffd640] [channel] - id=0x7fcd6c001500: Channel shutdown is already pending, not scheduling another.
```
