### ISSUE TITLE
Getting validation error on GetResourceMetricsRequest for serviceType RDS in AWS Performance Insights API

### ISSUE THREAD

**Issue by harry9111985** [aws/aws-sdk-java-v2#2792]
### Describe the issue

Hi Guys ,

I am sending a request to performance insights using java client and I am getting a validation error on serviceType . Can someone guide me please as to why am I getting a validation error ? 

**Request** 

```
GetResourceMetricsRequest
                        .builder()
                        .serviceType("RDS")
                        .identifier(dbInformation.instanceData?.dbiResourceId)
                        .periodInSeconds(3600)
                        .maxResults(10)
                        .metricQueries(
                            getMetricQueryForResourceMetricType(resourceMetricsType)
                        )
                        .startTime(Instant.now().minus(Duration.ofDays(-1)))
                        .endTime(Instant.now())

P.S : I tried the same request with ServiceType Enum as well.

```

**Response** 

software.amazon.awssdk.services.pi.model.PiException: Validation error(s) detected: Value at 'serviceType' failed to satisfy constraints. (Service: Pi, Status Code: 400, Request ID: fd280081-fb61-4242-bf46-1ead342f43c0, Extended Request ID: null)

### Steps to Reproduce

a) Just Fire a GetResourceMetricsRequest for a DB Identifier and serviceType = RDS 

### Current behavior

```
software.amazon.awssdk.services.pi.model.PiException: Validation error(s) detected: Value at 'serviceType' failed to satisfy constraints. (Service: Pi, Status Code: 400, Request ID: 28b9f6a6-23d2-4d43-b63c-e89ecc11d3a1, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.pi.DefaultPiClient.getResourceMetrics(DefaultPiClient.java:250)
	at software.amazon.awssdk.services.pi.PiClient.getResourceMetrics(PiClient.java:330)

```

### AWS Java SDK version used

2.17.65

### JDK version used

11

### Operating System and version

AWS Linux

**Comment by harry9111985** [comment]
Hi @debora-ito ,

The issue comes when we try converting the GetResourceMetricsRequest to string using object mapper before sending the request to AWS PI . Instead of using object mapper if I just rely on toString() representation of the request object , I don't get the error.

I was performing the conversion using objectmapper for adding logs to my execution request.

Regards,
Harish

**Comment by debora-ito** [comment]
> The issue comes when we try converting the GetResourceMetricsRequest to string using object mapper before sending the request to AWS PI.

Can you share a code sample?

And have you enabled the wirelogs I mentioned in my previous comment?
