### ISSUE TITLE
com.amazonaws.opensdk.internal.protocol.ApiGatewayErrorResponseHandler safeUnmarshall

### ISSUE THREAD

**Issue by sarmaas** [aws/aws-sdk-java-v2#2873]
### Describe the bug

I am getting follow error while using java SDK while handling 403 exception.

java.lang.reflect.InaccessibleObjectException: Unable to make final void java.lang.Throwable.setCause(java.lang.Throwable) accessible: module java.base does not "opens java.lang" to unnamed module @2ef5e5e3

Tried suggestions given in 
https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m

https://stackoverflow.com/questions/66974846/java-lang-exceptionininitializererror-with-java-16-j-l-classformaterror-access

### Expected behavior

Should be able to parse the message

### Current behavior

Exception in thread "main" com.amazonaws.SdkClientException: Unable to unmarshall error response (null). Response Code: 403, Response Text: Forbidden
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1347)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)

### Steps to Reproduce

Create Lambda to return 403
Add Error template in api gateway
Download SDK and try to get data.

### AWS Java SDK version used

2

### JDK version used

8,16,17

### Operating System and version

MAC OS

**Comment by debora-ito** [comment]
@sarmaas thank you for reaching out. I need more context to better understand the issue you are seeing.

Can you provide a self-contained repro case? Ideally would be a piece of code that I can copy + paste and run to reproduce the error.
And can you share the full stacktrace?
