### ISSUE TITLE
ProxyConfiguration.toBuilder throws NullPointerException

### ISSUE THREAD

**Issue by mosche** [aws/aws-sdk-java-v2#2884]
### Describe the bug

`ProxyConfiguration.toBuilder` throws `NullPointerException` if `nonProxyHosts` is unset:
```java
java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:119)
	at software.amazon.awssdk.http.apache.ProxyConfiguration$DefaultClientProxyConfigurationBuilder.nonProxyHosts(ProxyConfiguration.java:368)
	at software.amazon.awssdk.http.apache.ProxyConfiguration.toBuilder(ProxyConfiguration.java:163)
```

The problematic code this:

```
        @Override
        public Builder nonProxyHosts(Set<String> nonProxyHosts) {
            this.nonProxyHosts = new HashSet<>(nonProxyHosts);
            return this;
        }
```

### Expected behavior

`ProxyConfiguration.toBuilder` should work on any possible `ProxyConfiguration`.

### Current behavior

Throws exception

### Steps to Reproduce

```java
    ProxyConfiguration proxyConfiguration =
        ProxyConfiguration.builder()
            .endpoint(URI.create("http://localhost:8080"))
            .username("username")
            .password("password")
            .build();
    proxyConfiguration.toBuilder();
```

### AWS Java SDK version used

Latest

### JDK version used

1.8

### Operating System and version

-

**Comment by debora-ito** [comment]
Thank you for reporting this @mosche. We'll fix it.
