### ISSUE TITLE
CloudWatchMetricPublisher does not play nicely with XRay

### ISSUE THREAD

**Issue by Kurru** [aws/aws-sdk-java-v2#2919]
### Describe the bug

When using CloudWatchMetricPublisher and XRay simultaneously, we get a large number of log statements from the x-ray `LogErrorContextMissingStrategy`due to there not being any XRay segment in context when CloudWatch publisher attempts to push metrics into CloudWatch. 

```
[cloud-watch-metric-publisher-11-1] ERROR com.amazonaws.xray.strategy.LogErrorContextMissingStrategy - Suppressing AWS X-Ray context missing exception (SegmentNotFoundException): Failed to begin subsegment named 'CloudWatch': segment cannot be found.
```

This may also be because we have 
```
implementation "com.amazonaws:aws-xray-recorder-sdk-aws-sdk-v2-instrumentor:2.9.1"
```
 in our classpath, which attempts to automatically instrument RPCs to AWS services within our code.

### Expected behavior

No XRay log messages are created, perhaps a no-op segment is added to these requests, or the internal executor for CloudWatchMetricPublisher is exposed so that I am able to correct the state in the executor's threads.

### Current behavior

Unwanted log message every 1 minute when the MetricPublisher pushes metrics into CloudWatch.

### Steps to Reproduce

Run Java jar with xray deps

```
    implementation "com.amazonaws:aws-xray-recorder-sdk-core:2.9.1"
    implementation "com.amazonaws:aws-xray-recorder-sdk-aws-sdk-v2:2.9.1"
    implementation "com.amazonaws:aws-xray-recorder-sdk-aws-sdk-v2-instrumentor:2.9.1"
```

Send custom metric to CloudWatch

```
  public static final SdkMetric<Integer> RPC_CALL_COUNT =
      SdkMetric.create("RpcCount", Integer.class, MetricLevel.INFO, MetricCategory.CUSTOM);

--- 
CloudWatchMetricPublisher metricPublisher = CloudWatchMetricPublisher.builder()
        .namespace("Grpc")
        .cloudWatchClient(asyncClient)
        .build()
MetricCollector metricCollector = MetricCollector.create("Server RPC");
metricCollector.reportMetric(RPC_CALL_COUNT, 1);
metricPublisher.publish(metricCollector.collect());
```

### Possible Solution

Expose access to the executor to allow clients to call

```
AWSXRay.getGlobalRecorder().beginNoOpSegment();
```

I've worked around this currently using Reflection:

```
try {
  // Disable XRay segments for the executor pushing CloudWatch Metric updates.
  Field executorField = CloudWatchMetricPublisher.class.getDeclaredField("executor");
  executorField.setAccessible(true);
  Executor executor = (Executor) executorField.get(cloudWatchMetricPublisher);
  executor.execute(() -> {AWSXRay.getGlobalRecorder().beginNoOpSegment();});
} catch (NoSuchFieldException | IllegalAccessException e) {
  logger.warn("Failed to fix CloudWatchMetricPublisher's executor for XRay", e);
}
```

in the executor's thread.

### AWS Java SDK version used

2.9.1

### JDK version used

11

### Operating System and version

mac 12

**Comment by debora-ito** [comment]
@Kurru apologies for taking so long fo reply. I'm getting familiar with the XRay agent so I can try to repro this.

**Comment by debora-ito** [comment]
I'm not able to reproduce the issue @Kurru, but it may be due to my inaptitude to configure XRay.

Can you provide a code sample showing how you are using XRay? I ran the CloudWatchMetricPublisher code you provided in the description and "sandwiched" it between calls of `AWSXRay.beginSegment("my-segment")` and `AWSXRay.endSegment()`. 

I can see my requests reached both XRay and CloudWatch (for the client-side metrics) successfully.

**Comment by Kurru** [comment]
I have set the ContextMissingStrategy to be the logging strategy which may be missing for you? 

```
AWSXRay.getGlobalRecorder().setContextMissingStrategy(new LogErrorContextMissingStrategy());
```

When this is set, any segments that are attempted to be made would log a message warning of such. I believe the executor which periodically publishes the metrics runs in this separate executor, triggers the logging message for every metric publish.

At least, when the `implementation "com.amazonaws:aws-xray-recorder-sdk-aws-sdk-v2-instrumentor:2.9.1"` runtime dep is present.

**Comment by debora-ito** [comment]
After spending this afternoon trying to reproduce without success, I took a break and was looking into a different issue related to the S3 async client, and then this shows in my logs:

`
Exception in thread "main" com.amazonaws.xray.exceptions.SegmentNotFoundException: Failed to begin subsegment named 'S3': segment cannot be found.
`

So my theory is that when you have the XRay Instrumentation in the classpath, the SDK will load and execute the XRay interceptors when it shouldn't have to. 

Can you paste the full stacktrace with the error you're seeing with CloudWatch?

**Comment by Kurru** [comment]
> So my theory is that when you have the XRay Instrumentation in the classpath, the SDK will load and execute the XRay interceptors when it shouldn't have to.

Yes, this is the case. The classpath dependency `com.amazonaws:aws-xray-recorder-sdk-aws-sdk-v2-instrumentor:2.9.1` is what enables XRay subsegment generation for AWS client api calls (s3, cloudwatch etc) to enable automatic instrumentation of these RPCs into XRay. 

There isn't a stacktrace per-se but the error log:
`[cloud-watch-metric-publisher-11-1] ERROR com.amazonaws.xray.strategy.LogErrorContextMissingStrategy - Suppressing AWS X-Ray context missing exception (SegmentNotFoundException): Failed to begin subsegment named 'CloudWatch': segment cannot be found.`

This log occurs because there is no segment present when trying to create the subsegment for the AWS API call. Segments are tracked in a ThreadLocal variable and if you dont have a segment in the threadlocal context, it logs the error above. 

In general, the way this is handled (as best I know), is you would create a `segment` in the thread before generating Subsegments. Perhaps a no-op segment.

Relavent documentation:
- [xray-troubleshooting](https://docs.aws.amazon.com/xray/latest/devguide/xray-troubleshooting.html#troubleshooting-java)
- [instrumenting startup code](https://docs.aws.amazon.com/xray/latest/devguide/scorekeep-startup.html)

**Comment by debora-ito** [comment]
Yes but we cannot create segments in the SDK as the XRay Instrumentation tool is not part of the project.

I can reproduce the issue with S3 so I'm considering this a bug. If you can provide the full stacktrace of the error with Cloudwatch later on please do, I will help us to see if the error is being thrown from the same place.

**Comment by Kurru** [comment]
The S3 log message is likely not a bug, but rather a symptom of a misconfigured environment? When someone is using the xray-instrumentor package, it is assumed they want to use x-ray and thus, must configure their threads or RPCs with the appropriate segments. 

In this case, the library doesn't make this possible, as CloudWatchMetricPublisher creates an Executor internally which calls AWS APIs, but doesn't either: 

1. Enable clients to control/admin/interact with this executor
2. Internally populate the x-ray segment to something reasonable. You could do a reflection based technique to detect if they have the AWSXray class in their classpath before calling `AWSXRay.getGlobalRecorder().beginNoOpSegment()` in the internal executor. 

The xray team might have an option on how best to handle this type of thing...

For this issue, there is no stacktrace, but a warning from the x-ray instrumentation. The rpc in this issue goes to CloudWatch without issue

**Comment by Kurru** [comment]
Oh, full stacktrace for this issue:


```
[sdk-async-response-0-3] WARN software.amazon.awssdk.metrics.publishers.cloudwatch - Failed while publishing some or all AWS SDK client-side metrics to CloudWatch.
java.util.concurrent.CompletionException: software.amazon.awssdk.services.cloudwatch.model.InvalidParameterValueException: The collection MetricData.member.1.Values must not have a size greater than 150. (Service: CloudWatch, Status Code: 400, Request ID: 51f0a1fc-4ea9-42db-9fa7-7b2215174cef)
        at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:62)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:181)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:167)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: software.amazon.awssdk.services.cloudwatch.model.InvalidParameterValueException: The collection MetricData.member.1.Values must not have a size greater than 150. (Service: CloudWatch, Status Code: 400, Request ID: 51f0a1fc-4ea9-42db-9fa7-7b2215174cef)
        at software.amazon.awssdk.services.cloudwatch.model.InvalidParameterValueException$BuilderImpl.build(InvalidParameterValueException.java:118)
        at software.amazon.awssdk.services.cloudwatch.model.InvalidParameterValueException$BuilderImpl.build(InvalidParameterValueException.java:78)
        at software.amazon.awssdk.protocols.query.internal.unmarshall.AwsXmlErrorUnmarshaller.unmarshall(AwsXmlErrorUnmarshaller.java:99)
        at software.amazon.awssdk.protocols.query.unmarshall.AwsXmlErrorProtocolUnmarshaller.handle(AwsXmlErrorProtocolUnmarshaller.java:102)
        at software.amazon.awssdk.protocols.query.unmarshall.AwsXmlErrorProtocolUnmarshaller.handle(AwsXmlErrorProtocolUnmarshaller.java:82)
        at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
        at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64)
        at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)
        at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:89)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:132)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:513)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:249)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:74)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:370)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:402)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:338)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 1 more
```

**Comment by debora-ito** [comment]
> The S3 log message is likely not a bug, but rather a symptom of a misconfigured environment? When someone is using the xray-instrumentor package, it is assumed they want to use x-ray and thus, must configure their threads or RPCs with the appropriate segments.

I'm thinking of the use case where I use the xray-instrumentor package somewhere in my code but not when calling S3, so I don't add the Xray segments to the S3 portion on purpose. In my case it was not a warning log, it's an exception, the run was interrupted:
```
Exception in thread "main" com.amazonaws.xray.exceptions.SegmentNotFoundException: Failed to begin subsegment named 'S3': segment cannot be found.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.amazonaws.xray.strategy.RuntimeErrorContextMissingStrategy.contextMissing(RuntimeErrorContextMissingStrategy.java:32)
	at com.amazonaws.xray.contexts.ThreadLocalSegmentContext.beginSubsegment(ThreadLocalSegmentContext.java:40)
	at com.amazonaws.xray.AWSXRayRecorder.beginSubsegment(AWSXRayRecorder.java:616)
	at com.amazonaws.xray.interceptors.TracingInterceptor.beforeExecution(TracingInterceptor.java:225)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$beforeExecution$1(ExecutionInterceptorChain.java:62)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.beforeExecution(ExecutionInterceptorChain.java:62)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.runInitialInterceptors(AwsExecutionContextBuilder.java:167)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:109)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:69)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:78)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:5438)
```

It's interesting that in your case the CloudWatch metric gets published successfully. 

I'll ask someone from the SDK team to help clearing the confusion.

**Comment by Kurru** [comment]
Oh yes, the XRay library by default does throw exceptions if you dont have a segment in context when you attempt to interact with the AWS apis, this behavior can be changed to log warnings only using:

```
AWSXRay.getGlobalRecorder().setContextMissingStrategy(new LogErrorContextMissingStrategy());
```

I've been calling this at server startup so that x-ray failures dont cause complete outages.

**Comment by Kurru** [comment]
Yeah, I dont want the failures or logging of failures. To achieve that right now, I've had to use reflection to gain access to the hidden executor, but it would be great if this was either natively supported, or if there was a supported way of accessing the executor to setup the noop xray recorder.

**Comment by millems** [comment]
I'm not super familiar with x-ray, so excuse my silly questions. How are you setting up the no-op x-ray recorder? Based on how you are setting it up, I might be able to suggest a way that doesn't require hacks. If not, we can add something.

**Comment by millems** [comment]
I see, a less hacky workaround could be to use an execution interceptor on the cloudwatch client to start the no-op segment:

```java
ExecutionInterceptor disableXrayInterceptor = new ExecutionInterceptor() {
    @Override
    public void beforeExecution(Context.BeforeExecution context, 
                                ExecutionAttributes executionAttributes) {
        AWSXRay.getGlobalRecorder().beginNoOpSegment();
    }
};

CloudWatchAsyncClient cloudWatchAsyncClient =
    CloudWatchAsyncClient.builder()
                         .overrideConfiguration(c -> c.addExecutionInterceptor(disableXrayInterceptor))
                         .build();

CloudWatchMetricPublisher publisher =
    CloudWatchMetricPublisher.builder()
                             .cloudWatchClient(cloudWatchAsyncClient)
                             .build();
```

Does this work for you?

**Comment by Kurru** [comment]
Interesting! Never knew this was a feature.

Unfortunately it didn't work. It seems my interceptor was executed after the X-Ray subsegment was attempted to be created.

I guess this approach could be used to only have 1 error log message, which is better than every time I suppose.

**Comment by millems** [comment]
Darn, okay. We should have a way to notify x-ray internally that something is a background process of the SDK so that they can disable recording automatically. Not only for this, but for things like the STS credentials providers in async mode.

I can't think of any other workarounds for you, other than wrapping the cloudwatch client itself, which is probably more work than your current hack.

**Comment by millems** [comment]
Created https://github.com/aws/aws-xray-sdk-java/issues/330 to follow-up with the x-ray SDK to provide a built-in fix. Let's follow up on that issue, because it's not something we can do without x-ray SDK support.
