### ISSUE TITLE
DynamoDb error: converter not found for EnhancedType(java.util.Optional)

### ISSUE THREAD

**Issue by marcogramy** [aws/aws-sdk-java-v2#2937]
### Describe the issue

I'm trying to write to DynamoDb my object model with an Optional field, but it does not work.
If I exclude the Optional field from my model I can successfully save it to DynamoDb.

### Steps to Reproduce

```
private final String notificationText;

public Optional<String> getNotificationText() {
    return Optional.ofNullable(notificationText);
}

public void setNotificationText(Optional<String> notificationText) {
    // Do nothing, this is a derived attribute
}
```

### Current behavior

I'm obtaining this error:
`java.lang.IllegalStateException: Converter not found for EnhancedType(java.util.Optional)`

I'm trying to create my custom ConvertProvider implementing AttributeConverterProvider and using the [OptionalAttributeConverter](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/OptionalAttributeConverter.html) but I don't understand how to use it.
Can someone help me?

### AWS Java SDK version used

dynamodb-enhanced version 2.17.102

### JDK version used

openjdk version "1.8.0_312"

### Operating System and version

Linux 5.4.0-91-generic #102-Ubuntu

**Comment by aaoswal** [comment]
Hi @marcogramy,
Thank you for reaching out.

Can you provide a code sample we can use to reproduce?
And can you share the full stack-trace of the error?

**Comment by marcogramy** [comment]
Hi @aaoswal,
here you can find a sample project, which reproduces my project structure: [https://github.com/marcogramy/dynamodbdemo](https://github.com/marcogramy/dynamodbdemo)
As you can see, project run fails with error
`Converter not found for EnhancedType(java.util.Optional<java.lang.String>)`

Full error stack-trace:
```
Caused by: java.lang.IllegalStateException: Converter not found for EnhancedType(java.util.Optional<java.lang.String>)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.lambda$converterFor$0(DefaultAttributeConverterProvider.java:134) ~[dynamodb-enhanced-2.17.102.jar:na]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_312]
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.converterFor(DefaultAttributeConverterProvider.java:134) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.ImmutableAttribute.converterFrom(ImmutableAttribute.java:166) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.ImmutableAttribute.resolve(ImmutableAttribute.java:162) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.lambda$new$0(StaticImmutableTableSchema.java:153) ~[dynamodb-enhanced-2.17.102.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_312]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[na:1.8.0_312]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_312]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_312]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313) ~[na:1.8.0_312]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[na:1.8.0_312]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[na:1.8.0_312]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.<init>(StaticImmutableTableSchema.java:159) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.<init>(StaticImmutableTableSchema.java:77) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema$Builder.build(StaticImmutableTableSchema.java:425) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema.<init>(StaticTableSchema.java:66) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema.<init>(StaticTableSchema.java:64) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema$Builder.build(StaticTableSchema.java:255) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.createStaticTableSchema(BeanTableSchema.java:208) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:129) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:121) ~[dynamodb-enhanced-2.17.102.jar:na]
	at software.amazon.awssdk.enhanced.dynamodb.TableSchema.fromBean(TableSchema.java:81) ~[dynamodb-enhanced-2.17.102.jar:na]
	at com.example.dynamodbdemo.EntityRepository.<init>(EntityRepository.java:16) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_312]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_312]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.14.jar:5.3.14]
```

Any help is appreciated! Thank you in advance!

**Comment by aaoswal** [comment]
Hi @marcogramy,
Some good references that would be useful in creating a `CustomAttributeConverter` are:
- [`CustomAttributeConverter implementation example using AttributeConverter`](https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/AttributeConverterBean.java#L73)
- [Passing the `AttributeConverter` to the `OptionalAttributeConverter`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/OptionalAttributeConverter.html)

Using the above references should solve the issue you are facing.

Hope this helps!

**Comment by marcogramy** [comment]
Following your advices I've created a `CustomAttributeConverterProvider` with `OptionalAttributeConverter<String>` and now it works!
I've updated my demo project for any future references: [https://github.com/marcogramy/dynamodbdemo](https://github.com/marcogramy/dynamodbdemo)

Thank you for your help!
