### ISSUE TITLE
Can't access Secrets Manager using EKS pod's role

### ISSUE THREAD

**Issue by cristidima-mstar** [aws/aws-sdk-java-v2#2961]
### Describe the issue

I have an EKS pod running a Java app which I'm trying to use to read some secrets using the `SecretsManagerClient`. The pod is using an IAM role which is configured correctly (AWS CLI works, .NET Core SDK works on another pod with same role).

My bit of code is as follows:
```
Region region = Region.of(regionName);

SecretsManagerClient secretsClient = SecretsManagerClient.builder()
        .region(region)
        .build();

GetSecretValueRequest valueRequest = GetSecretValueRequest.builder()
        .secretId(secretName)
        .build();

GetSecretValueResponse valueResponse = secretsClient.getSecretValue(valueRequest);
```

As far as I understand, I'm supposed to use the `InstanceProfileCredentialsProvider`, which is part of the default credential provider chain. When I run my code I get the following error:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): To use web identity tokens, the 'sts' service module must be on the class path., ProfileCredentialsProvider(): Profile file contained no credentials for profile 'default': ProfileFile(profiles=[REDACTED]), ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Unable to load credentials from service endpoint.]
```

At this point I tried to bypass the default credentials provider chain and use `IstanceProfileCredentialsProvider`, but I then get this error:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from service endpoint.
  at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
  at software.amazon.awssdk.auth.credentials.HttpCredentialsProvider.refreshCredentials(HttpCredentialsProvider.java:110)
  at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:132)
  at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:89)
  at java.util.Optional.map(Optional.java:215)
  at software.amazon.awssdk.auth.credentials.HttpCredentialsProvider.resolveCredentials(HttpCredentialsProvider.java:146)
  at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:76)
  at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
  at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:93)
  at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:162)
  at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:91)
  at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
  at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
  at software.amazon.awssdk.services.secretsmanager.DefaultSecretsManagerClient.getSecretValue(DefaultSecretsManagerClient.java:1085)
  at my.project.getSecretValue(SecretsManagerWrapper.java:22)
  at Processor.processRow(Unknown Source)
  at org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClass.processRow(UserDefinedJavaClass.java:1019)
  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:607)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
  at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
  at sun.net.www.http.HttpClient.New(HttpClient.java:339)
  at sun.net.www.http.HttpClient.New(HttpClient.java:357)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
  at software.amazon.awssdk.regions.internal.util.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:45)
  at software.amazon.awssdk.regions.util.HttpResourcesUtils.readResource(HttpResourcesUtils.java:110)
  at software.amazon.awssdk.regions.util.HttpResourcesUtils.readResource(HttpResourcesUtils.java:89)
  at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider$InstanceProviderCredentialsEndpointProvider.endpoint(InstanceProfileCredentialsProvider.java:120)
  at software.amazon.awssdk.regions.util.HttpResourcesUtils.readResource(HttpResourcesUtils.java:110)
  at software.amazon.awssdk.regions.util.HttpResourcesUtils.readResource(HttpResourcesUtils.java:89)
  at software.amazon.awssdk.auth.credentials.HttpCredentialsProvider.refreshCredentials(HttpCredentialsProvider.java:74)
  ... 17 more
```

### Steps to Reproduce

Run the code I provided in an EKS pod with a configured IAM role.

### Current behavior

The method throws an exception instead of retrieving a secret from the Secrets Manager.

### AWS Java SDK version used

2.17.108

### JDK version used

1.8.0_302

### Operating System and version

Amazon Linux 2

**Comment by cristidima-mstar** [comment]
Hi @aaoswal,

Just inspected our pod more closely and it seems it is an Amazon Linux 2 image with `openJDK 1.8.0_302`. Sorry for the confusion, I thought it was Alpine Linux like all our other pods.

The role is the same as on other pods and, as far as I can tell, has the appropriate permissions since I can run AWS CLI and retrieve the secrets.

I'm not sure how the pods are set up (I don't do this myself), but I'm pretty sure they're set up via the console.

Thanks for the quick reply and sorry again for misreporting the image type.

**Comment by RajeshAle** [comment]
Hi @cristidima-mstar  , am also facing the same issue. I see that you updated your dependencies but did you made any changes on the coding side ?? Can you let me know what changes you made.

Fyi: we are trying to fetch secrets from AWS EKS (which has role tied to Secrets Manager)
