### ISSUE TITLE
HeadObjectRequest exception

### ISSUE THREAD

**Issue by codylerum** [aws/aws-sdk-java-v2#297]
**Expected Behavior**

A S3 HeadObjectRequest for a missing object throws NoSuchKeyException

**Current Behavior**

A S3 HeadObjectRequest for a missing object throws NPE

**Possible Solution**

Make behavior match v1.

**Context**

Using a HeadObjectRequest to check if the same object already exists before doing a put as to prevent an overwrite.

**Your Environment**

AWS Java SDK version used: https://mvnrepository.com/artifact/software.amazon.awssdk/bom/2.0.0-preview-5
JDK version used: Oracle JDK 1.8.0_u151
Operating System and version: Win 10 in Wildfly 11.0.0.Final Application Server

```
2017-11-18 19:24:47,259 INFO  [software.amazon.awssdk.core.http.DefaultErrorResponseHandler] (EJB default - 1) Unable to read input stream to string (Invocation Id:016f1163-c297-ab01-0f2a-1ddf21c4694b): java.lang.NullPointerException
        at software.amazon.awssdk.utils.IoUtils.toByteArray(IoUtils.java:46)
        at software.amazon.awssdk.utils.IoUtils.toString(IoUtils.java:60)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.contentToString(DefaultErrorResponseHandler.java:115)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.documentFromContent(DefaultErrorResponseHandler.java:105)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.createAse(DefaultErrorResponseHandler.java:83)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:70)
        at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:45)
        at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:52)
        at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:43)
        at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:31)
        at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:119)
        at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:76)
        at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:61)
        at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:44)
        at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.core.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:40)
        at software.amazon.awssdk.core.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:30)
        at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:141)
        at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:107)
        at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:66)
        at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:47)
        at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.core.http.StreamManagingStage.execute(StreamManagingStage.java:62)
        at software.amazon.awssdk.core.http.StreamManagingStage.execute(StreamManagingStage.java:46)
        at software.amazon.awssdk.core.http.pipeline.stages.FailureProgressPublishingStage.execute(FailureProgressPublishingStage.java:41)
        at software.amazon.awssdk.core.http.pipeline.stages.FailureProgressPublishingStage.execute(FailureProgressPublishingStage.java:30)
        at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.executeWithTimer(ClientExecutionTimedStage.java:69)
        at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:53)
        at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:37)
        at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
        at software.amazon.awssdk.core.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:35)
        at software.amazon.awssdk.core.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:24)
        at software.amazon.awssdk.core.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:325)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.doInvoke(SyncClientHandlerImpl.java:142)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.invoke(SyncClientHandlerImpl.java:124)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:99)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:75)
        at software.amazon.awssdk.core.client.SdkClientHandler.execute(SdkClientHandler.java:47)
        at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:1620)
```

**Comment by zoewangg** [comment]
related to #123 #147

**Comment by codylerum** [comment]
@zoewangg This still causes issues with preview 7

```
19:06:44,946 INFO  [software.amazon.awssdk.core.http.DefaultErrorResponseHandler] (EE-ManagedExecutorService-default-Thread-2) Unable to read input stream to string (Invocation Id:37f13030-22e0-6662-beba-0eeecc8ccc2c): java.lang.NullPointerException
	at software.amazon.awssdk.utils.IoUtils.toByteArray(IoUtils.java:46)
	at software.amazon.awssdk.utils.IoUtils.toString(IoUtils.java:60)
	at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.contentToString(DefaultErrorResponseHandler.java:115)
	at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.documentFromContent(DefaultErrorResponseHandler.java:105)
	at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.createServiceException(DefaultErrorResponseHandler.java:83)
	at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:70)
	at software.amazon.awssdk.core.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:45)
	at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handleServiceException(AwsErrorResponseHandler.java:53)
	at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:44)
	at software.amazon.awssdk.core.internal.http.response.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:32)
	at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:113)
	at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:72)
	at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:57)
	at software.amazon.awssdk.core.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
	at software.amazon.awssdk.core.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:30)
	at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:139)
	at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:105)
	at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:66)
	at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:47)
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
	at software.amazon.awssdk.core.http.StreamManagingStage.execute(StreamManagingStage.java:55)
	at software.amazon.awssdk.core.http.StreamManagingStage.execute(StreamManagingStage.java:41)
	at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.executeWithTimer(ClientExecutionTimedStage.java:71)
	at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:55)
	at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:39)
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
	at software.amazon.awssdk.core.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:35)
	at software.amazon.awssdk.core.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:24)
	at software.amazon.awssdk.core.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:281)
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.doInvoke(SyncClientHandlerImpl.java:149)
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.invoke(SyncClientHandlerImpl.java:131)
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:100)
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:76)
	at software.amazon.awssdk.core.client.SdkClientHandler.execute(SdkClientHandler.java:45)
	at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:1623)```

**Comment by zoewangg** [comment]
Are you sure the object doesn't exist in that bucket? Because from my understanding, when the object doesn't exist for `headObject`, it should throw `S3Exception`. https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/it/java/software/amazon/awssdk/services/s3/ExceptionUnmarshallingIntegrationTest.java#L86. 

From looking at the logs, it looks like s3 is not returning anything in the error response . Could you enable [wirelogging](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) and paste it here (be sure to redact any sensitive information)

**Comment by codylerum** [comment]
Yeah I'm sure the object does not exist as the key is a type4 uuid and it's reproducible.

Javadoc says it should throw a NoSuchKeyException

It does throw a S3Expcetion with a 404 status code

software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3Client; Status Code: 404; Request ID: null)

I'm operating in an application server so enabling the logging isn't so easy.

**Comment by zoewangg** [comment]
Right, that's the limitation of HEAD request, because they don't return an XML body containing the error details, there's no easy way to map the error response to the correct exception. As a result, `headObject` will not throw `NoSuchKeyException`, similarly, `headBucket` will not throw `NoSuchBucketException`, instead, `S3Exception` with 404 will be thrown. We will work on updating the Javadoc. 

The workaround to check if the object exists would be catch S3Exception and check the status code.

But I'm not sure how NPE gets thrown from doing headObject with non-existing key. The logs you pasted are just from `s3.headObject(...)`?

**Comment by codylerum** [comment]
Correct just from a headObject(...)

**Comment by zoewangg** [comment]
Now I understand, the NPE is swallowed in `documentFromContent()` and `S3Expcetion` is the exception thrown, which is expected. As I mentioned earlier,  this is a limitation on the service side and we will work on updating the Javadoc.

**Comment by codylerum** [comment]
Can you prevent the  `INFO  [software.amazon.awssdk.core.http.DefaultErrorResponseHandler] (EE-ManagedExecutorService-default-Thread-2) Unable to read input stream to string (Invocation Id:37f13030-22e0-6662-beba-0eeecc8ccc2c): java.lang.NullPointerException` from beling logged?

**Comment by zoewangg** [comment]
Yup, that's definitely confusing and we will work on that!

**Comment by codylerum** [comment]
@zoewangg Thanks. Overall liking v2

Still hoping you are able to find a way to map the S3Exception with 404 to a NoSuchKeyException to make things easier and more consistent with v1.

The only reason I use a head right now is prevent overwriting some objects. So I check to see if they exist before doing a put. I don't think their is a way to do a put that doesn't allow overwriting so doing the head makes the most sense.
