### ISSUE TITLE
CrtS3RuntimeException: Invalid response status from request AWS_ERROR_S3_INVALID_RESPONSE_STATUS(14343)  on Centos 7

### ISSUE THREAD

**Issue by harvey2738** [aws/aws-sdk-java-v2#2973]
### Describe the issue

I use S3 to upload files, use the S3TransferManager method of AWS-java2, and the test is OK in the windows development environment, but on Centos7 on the server, the abnormal error as shown in the figure is generated .
![image](https://user-images.githubusercontent.com/93361376/149736452-6bfe81e8-0011-4261-b2ca-2d7181976948.png)

### Steps to Reproduce

@Service
public class AwsS3FileHandler {

	@Autowired
	private AwsCredentialsProvider awsCredentialsProvider;
	
	@Autowired
	private AwsConfigure awsConfigure;
	
	private S3TransferManager  initS3TransferManager () {
		return S3TransferManager.builder()
                .s3ClientConfiguration(cfg ->cfg.region(Region.of(awsConfigure.getRegion()))
                        .credentialsProvider(StaticCredentialsProvider.create(awsCredentialsProvider.resolveCredentials()))
                        .targetThroughputInGbps(20.0)
                        .minimumPartSizeInBytes(10l))
                .build();
	}
	
	public CompletableFuture<String> uploadObject(File tempFile) {
		try (S3TransferManager tf = initS3TransferManager()) {
			return uploadObjectTM(tf, awsConfigure.getS3Bucket(), URLEncoder.encode(tempFile.getName(),"UTF-8"), tempFile.getPath());
		} catch (UnsupportedEncodingException e) {
			throw new BusinessException(e.getMessage());
		}
	}
	
	private CompletableFuture<String> uploadObjectTM(S3TransferManager transferManager,  String bucketName,  String objectKey, String objectPath) {
		FileUpload upload =
                transferManager.uploadFile(u -> u.source(Paths.get(objectPath))
                        .putObjectRequest(p -> p.bucket(bucketName).key(objectKey)));
        return upload.completionFuture().thenApply(cf->
        {
        	cf.response().eTag();
        	return attURL(objectKey);
        });
    }
	
	private String attURL(String objectKey) {
		return String.format(awsConfigure.getDomain(), awsConfigure.getS3Bucket(),awsConfigure.getRegion(),objectKey);
	}
}

### Current behavior

Exception：
 at software.amazon.awssdk.services.s3.model.S3Exception$BuilderImpl.build(S3Exception.java:95)
                at software.amazon.awssdk.services.s3.model.S3Exception$BuilderImpl.build(S3Exception.java:55)
                at software.amazon.awssdk.transfer.s3.internal.CrtErrorHandler.getServiceSideException(CrtErrorHandler.java:71)
                at software.amazon.awssdk.transfer.s3.internal.CrtErrorHandler.lambda$transformException$0(CrtErrorHandler.java:55)
                at java.util.Optional.map(Optional.java:215)
                at software.amazon.awssdk.transfer.s3.internal.CrtErrorHandler.transformException(CrtErrorHandler.java:55)
                at software.amazon.awssdk.transfer.s3.internal.DefaultS3CrtAsyncClient.lambda$putObject$3(DefaultS3CrtAsyncClient.java:138)
                at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
                at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
                at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
                at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
                at com.amazonaws.s3.S3NativeClient$3.onFinished(S3NativeClient.java:321)
                at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:19)
Caused by: software.amazon.awssdk.crt.s3.CrtS3RuntimeException: Invalid response status from request AWS_ERROR_S3_INVALID_RESPONSE_STATUS(14343)
        at com.amazonaws.s3.S3NativeClient$3.onFinished(S3NativeClient.java:313)
        at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:19)

### AWS Java SDK version used

2.17.109

### JDK version used

Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

### Operating System and version

Centos 7

**Comment by aru1001** [comment]
What was the resolution to this? Seeing this in Ubuntu (host) + docker (jdk) ?
