### ISSUE TITLE
AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by saraswat40** [aws/aws-sdk-java-v2#2981]
### Describe the issue

I am using the following code sample:
`Region region = Region.of("US-WEST-2");
        AwsCredentialsProvider creds = StaticCredentialsProvider.create(AwsBasicCredentials.create(AWSAccessKey, AWSSecretKey));
        Ec2Client ec2 = Ec2Client.builder()
                .region(region)
                .credentialsProvider(creds)
                .build();

        DescribeInstancesResponse describeInstancesResponse = ec2.describeInstances();`

This fails with the error:
AWS was not able to validate the provided access credentials

With the same credentials on AWS SDK V1, the following works:
`BasicAWSCredentials creds = new BasicAWSCredentials(AWSAccessKey, AWSSecretKey);

        AmazonEC2 amazonEC2Client = AmazonEC2ClientBuilder.standard().withRegion(Regions.US_WEST_2).withCredentials(new AWSStaticCredentialsProvider(creds)).build();
        DescribeInstancesResult describeInstancesResult = amazonEC2Client.describeInstances();`

What did I miss?

### Steps to Reproduce

Just run the code provided ago. The credentials have EC2FullAccess.

### Current behavior

AWS was not able to validate the provided access credentials ( 401 )

### AWS Java SDK version used

2.17.115

### JDK version used

1.8

### Operating System and version

Ubuntu 21.10

**Comment by saraswat40** [comment]
I have also done clock synchronization etc as described here: https://stackoverflow.com/questions/27685288/aws-was-not-able-to-validate-the-provided-access-credentials

**Comment by debora-ito** [comment]
@saraswat40 can you share the full stacktrace?
Are you running the code in an EC2 instance?

**Comment by saraswat40** [comment]
@debora-ito No, on my local.

**Comment by saraswat40** [comment]
This problem is reproducible in a very simple maven project with just one dependency and one class. Here is the pom:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.thetalake</groupId>
    <artifactId>awssdkv2test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>ec2</artifactId>
            <version>2.17.112</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <repositories>
    <repository>
        <id>default</id>
        <name>Maven Repository Switchboard</name>
        <layout>default</layout>
        <url>http://repo.maven.org/maven2</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

        </plugins>

    </build>
</project>
```

Here is the class:
```
import software.amazon.awssdk.auth.credentials.*;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.ec2.Ec2Client;
import software.amazon.awssdk.services.ec2.model.*;

public class HelloWorld {

    public static void main(String[] args){
        String AWSAccessKey = "XXXX";

        String AWSSecretKey = "XXXXX";

        Region region = Region.of("US-WEST-2");
        AwsCredentialsProvider creds = StaticCredentialsProvider.create(AwsBasicCredentials.create(AWSAccessKey, AWSSecretKey));
        Ec2Client ec2 = Ec2Client.builder()
                .region(region)
                .credentialsProvider(creds)
                .build();

        DescribeInstancesResponse describeInstancesResponse = ec2.describeInstances();
    }
}
```

**Comment by debora-ito** [comment]
It is weird you're seeing this error... maybe there's something to do with the regional endpoints.

Can you enable the verbose wire logging and share the logs?
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose

Please make sure to redact any sensitive information.

**Comment by saraswat40** [comment]
Changing to a regional endpoint gives the same result. 
```
Ec2Client ec2 = Ec2Client.builder()
                .region(region)
                .endpointOverride(new URI("https://api.ec2.us-west-2.aws"))
                .credentialsProvider(creds)
                .build();
```

Here are the full wire logs:
```
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "POST / HTTP/1.1[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Host: api.ec2.us-west-2.aws[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-invocation-id: 7340012f-d036-1e0a-ad91-a2aebedc5b1a[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-retry: 0/0/500[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=XXXXX/20220125/US-WEST-2/ec2/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;x-amz-date, Signature=b60890d36d4e5c72e71474ef2f7d12d2b42fd7ed38243ca35579d0dc13b2a592[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Type: application/x-www-form-urlencoded; charset=utf-8[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "User-Agent: aws-sdk-java/2.1.0 Linux/5.13.0-27-generic Java_HotSpot_TM__64-Bit_Server_VM/25.311-b11 Java/1.8.0_311[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "X-Amz-Date: 20220125T211455Z[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Length: 43[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:87 - http-outgoing-0 >> "Action=DescribeInstances&Version=2016-11-15"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "HTTP/1.1 401 Unauthorized[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "x-amzn-RequestId: 80e0cae2-907d-4aeb-8694-94516c156028[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Cache-Control: no-cache, no-store[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Strict-Transport-Security: max-age=31536000; includeSubDomains[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "vary: accept-encoding[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Content-Type: text/xml;charset=UTF-8[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Date: Tue, 25 Jan 2022 21:14:54 GMT[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Keep-Alive: timeout=20[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Server: AmazonEC2[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "fe[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>80e0cae2-907d-4aeb-8694-94516c156028</RequestID></Response>[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "0[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "POST / HTTP/1.1[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Host: api.ec2.us-west-2.aws[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-invocation-id: 7340012f-d036-1e0a-ad91-a2aebedc5b1a[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-retry: 1/80/495[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=XXXXXX/20220125/US-WEST-2/ec2/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;x-amz-date, Signature=59094bb797c0980203ba46f8fd929e648322cd32ac9031b2766961ccc4063eaf[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Type: application/x-www-form-urlencoded; charset=utf-8[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "User-Agent: aws-sdk-java/2.1.0 Linux/5.13.0-27-generic Java_HotSpot_TM__64-Bit_Server_VM/25.311-b11 Java/1.8.0_311[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "X-Amz-Date: 20220125T211457Z[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Length: 43[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:87 - http-outgoing-0 >> "Action=DescribeInstances&Version=2016-11-15"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "HTTP/1.1 401 Unauthorized[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "x-amzn-RequestId: 200b46bc-3109-4ba0-8953-e9a988e8d304[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Cache-Control: no-cache, no-store[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Strict-Transport-Security: max-age=31536000; includeSubDomains[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "vary: accept-encoding[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Content-Type: text/xml;charset=UTF-8[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Date: Tue, 25 Jan 2022 21:14:55 GMT[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Keep-Alive: timeout=20[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Server: AmazonEC2[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "fe[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>200b46bc-3109-4ba0-8953-e9a988e8d304</RequestID></Response>[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "0[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "POST / HTTP/1.1[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Host: api.ec2.us-west-2.aws[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-invocation-id: 7340012f-d036-1e0a-ad91-a2aebedc5b1a[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-retry: 2/98/490[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=XXXXXX/20220125/US-WEST-2/ec2/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;x-amz-date, Signature=16778be7302f795053bbbba395f0fc5ef481da44621c803ca47b595ffcff5bf3[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Type: application/x-www-form-urlencoded; charset=utf-8[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "User-Agent: aws-sdk-java/2.1.0 Linux/5.13.0-27-generic Java_HotSpot_TM__64-Bit_Server_VM/25.311-b11 Java/1.8.0_311[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "X-Amz-Date: 20220125T211456Z[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Length: 43[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "[\r][\n]"
2022-01-25 16:14:55 [main] DEBUG org.apache.http.wire:87 - http-outgoing-0 >> "Action=DescribeInstances&Version=2016-11-15"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "HTTP/1.1 401 Unauthorized[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "x-amzn-RequestId: 5b48c718-a402-4c2f-b776-8ebea01ae49d[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Cache-Control: no-cache, no-store[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Strict-Transport-Security: max-age=31536000; includeSubDomains[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "vary: accept-encoding[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Content-Type: text/xml;charset=UTF-8[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Date: Tue, 25 Jan 2022 21:14:55 GMT[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Keep-Alive: timeout=20[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Server: AmazonEC2[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "fe[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>5b48c718-a402-4c2f-b776-8ebea01ae49d</RequestID></Response>[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "0[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "POST / HTTP/1.1[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Host: api.ec2.us-west-2.aws[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-invocation-id: 7340012f-d036-1e0a-ad91-a2aebedc5b1a[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "amz-sdk-retry: 3/178/485[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=XXXXX/20220125/US-WEST-2/ec2/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;x-amz-date, Signature=e57bcd5a0d95b12b75cd3ff8710d6f5e03cee35dcd71cac010781481af069b6c[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Type: application/x-www-form-urlencoded; charset=utf-8[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "User-Agent: aws-sdk-java/2.1.0 Linux/5.13.0-27-generic Java_HotSpot_TM__64-Bit_Server_VM/25.311-b11 Java/1.8.0_311[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "X-Amz-Date: 20220125T211458Z[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Content-Length: 43[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 >> "[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:87 - http-outgoing-0 >> "Action=DescribeInstances&Version=2016-11-15"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "HTTP/1.1 401 Unauthorized[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "x-amzn-RequestId: ea01d0c4-c280-406d-b784-6cb9d35ac505[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Cache-Control: no-cache, no-store[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Strict-Transport-Security: max-age=31536000; includeSubDomains[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "vary: accept-encoding[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Content-Type: text/xml;charset=UTF-8[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Date: Tue, 25 Jan 2022 21:14:55 GMT[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Keep-Alive: timeout=20[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "Server: AmazonEC2[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "fe[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>ea01d0c4-c280-406d-b784-6cb9d35ac505</RequestID></Response>[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "0[\r][\n]"
2022-01-25 16:14:56 [main] DEBUG org.apache.http.wire:73 - http-outgoing-0 << "[\r][\n]"
Exception in thread "main" software.amazon.awssdk.services.ec2.model.Ec2Exception: AWS was not able to validate the provided access credentials (Service: Ec2, Status Code: 401, Request ID: ea01d0c4-c280-406d-b784-6cb9d35ac505)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:115)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:115)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:88)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:44)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:51)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:33)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:79)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:25)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.ec2.DefaultEc2Client.describeInstances(DefaultEc2Client.java:6883)
	at software.amazon.awssdk.services.ec2.Ec2Client.describeInstances(Ec2Client.java:11833)
	at HelloWorld.main(HelloWorld.java:25)
```

**Comment by debora-ito** [comment]
@saraswat40 I cannot think of any reason other than your credentials do not have the right permission to access EC2. Have you double-check that?

Can you use the same credentials in the `aws-cli`? Try to put the access key and secret key in the `.aws/credentials` file and use the profile name - https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
`$ aws ec2 describe-instances --profile my_profile`
