### ISSUE TITLE
AWS v2 SDK not working without https proxy specified

### ISSUE THREAD

**Issue by xiangfei8** [aws/aws-sdk-java-v2#2983]
### Describe the issue

configure proxy pathway as what is inside the IF statement below is working fine.
if (isProxyDefined) {
   httpClient = ApacheHttpClient.builder()
                          .proxyConfiguration(ProxyConfiguration.builder()
                                .useSystemPropertyValues(false)
                                .endpoint(URI.create((new StringBuffer().append("http://")
                                 .append(envHttpsProxyHost)
                                 .append(":")
                                 .append(envHttpsProxyPort)).toString()))
                                 .build())
                           .build();
        } else {
            httpClient = ApacheHttpClient.builder()
                                         .build();
        }

I recently try to deploy the software to an environment without proxy needed, and I confirm it is getting inside the ELSE statement. But I am consistently getting the following stack trace.  Why is the sdk giving a "java.lang.NumberFormatException"  trying to look for a port that is not defined anyway?  Is there another API call I should be using instead for a no proxy environment?

                java.lang.NumberFormatException: For input string: ""
                    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
                    at java.base/java.lang.Integer.parseInt(Integer.java:662)
                    at java.base/java.lang.Integer.parseInt(Integer.java:770)
                    at java.base/java.util.Optional.map(Optional.java:265)
                    at software.amazon.awssdk.http.apache.ProxyConfiguration.resolvePort(ProxyConfiguration.java:199)
                    at software.amazon.awssdk.http.apache.ProxyConfiguration.<init>(ProxyConfiguration.java:66)
                    at software.amazon.awssdk.http.apache.ProxyConfiguration.<init>(ProxyConfiguration.java:38)
                    at software.amazon.awssdk.http.apache.ProxyConfiguration$DefaultClientProxyConfigurationBuilder.build(ProxyConfiguration.java:407)
                    at software.amazon.awssdk.http.apache.ProxyConfiguration$DefaultClientProxyConfigurationBuilder.build(ProxyConfiguration.java:298)
                    at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.<init>(ApacheHttpClient.java:427)
                    at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.<init>(ApacheHttpClient.java:425)
                    at software.amazon.awssdk.http.apache.ApacheHttpClient.builder(ApacheHttpClient.java:133)
                    at 

As you can see, this issue is coming from software.amazon.awssdk.http.apache.ProxyConfiguration.

### Steps to Reproduce

Make a STS call in an environment that have no proxy set up.

    StsClient getStsClient(AwsBasicCredentials awsCreds) {
        return StsClient.builder()
                        .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
                        .region(Region.of(awsS3BucketRegion))
                        .build();
    }

OR 

    StsClient getStsClient(AwsBasicCredentials awsCreds) {
        return StsClient.builder()
                        .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
                        .region(Region.of(awsS3BucketRegion))
                        .httpClient(ApacheHttpClient.builder().build())
                        .build();
    }

### Current behavior

get runtime exception:  java.lang.NumberFormatException: For input string: ""
detail stack is in the description

### AWS Java SDK version used

2.14.18, I also tried 2.17.115

### JDK version used

openjdk-11-5-5

### Operating System and version

debian:10.3-slim

**Comment by debora-ito** [comment]
Hi @xiangfei8 this is indeed a confusing issue, I think `ProxyConfguration` is only called if they are declared in the client builder.

All clients are immutable after creation. Is it possible your code is running into a situation where it's unintentionally trying to change a client built with a proxy config?

**Comment by xiangfei8** [comment]
@debora-ito - I only create the ApacheHttpClient once in @PostConstruct  in my code
httpClient = ApacheHttpClient.builder()
.build();

And I got this exception from that spot.

**Comment by debora-ito** [comment]
```
if (isProxyDefined) {
httpClient = ApacheHttpClient.builder()
.proxyConfiguration(ProxyConfiguration.builder()
.useSystemPropertyValues(false)
.endpoint(URI.create((new StringBuffer().append("http://")
.append(envHttpsProxyHost)
.append(":")
.append(envHttpsProxyPort)).toString()))
.build())
.build();
} else {
httpClient = ApacheHttpClient.builder()
.build();
}
```

In the description you showed this snippet, how is this used? Can you show a code sample?

**Comment by xiangfei8** [comment]
1)    @PostConstruct
    void initSetup() {
        initProxy();

2) the above snippet of building the httpClient is inside the initProxy() method 

3) Then the httpClient is used by various method call inside the bean, for example, 
S3Client s3 = S3Client.builder()
                                       .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
                                       .region(Region.of(awsS3BucketRegion))
                                       .httpClient(httpClient())
                                       .build()) {

OR

StsClient.builder()
                        .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
                        .region(Region.of(awsS3BucketRegion))
                        .httpClient(httpClient())
                        .build();

**Comment by debora-ito** [comment]
If you remove the logic from initSetup() and put it on the client builders, do you still see the error?

My guess is the httpClient is being built once with ProxyConfiguration, and being reused later on in environments that may not have proxy configured. You should check how the httpclient is being created initially when the error is thrown, taking the `@PostConstruct` and the HttpClient immutability into consideration.

**Comment by xiangfei8** [comment]
If you remove the logic from initSetup() and put it on the client builders, do you still see the error? yes
My guess is the httpClient is being built once with ProxyConfiguration, and being reused later on in environments that may not have proxy configured. - no the case, the httpClient is created and used in the same container

**Comment by xiangfei8** [comment]
We need to find another way to address this issue. Can you reproduce this in an environment without proxy defined on your end?

**Comment by debora-ito** [comment]
> Can you reproduce this in an environment without proxy defined on your end?

With the information provided so far I can't reproduce. For example, if I run the following code without proxy defined I don't see any errors because the code does not go through `software.amazon.awssdk.http.apache.ProxyConfiguration.resolvePort()`.
```
StsClient.builder()
    .region(Region.US_WEST_2)
    .httpClient(ApacheHttpClient.builder().build())
    .build();
```

I can't really use the other code snippets because they contain variables that are not in the code (like `isProxyDefined`), I don't know how they are created. 

If you can provide a [self-contained, minimal code sample](http://sscce.org) that shows the issue, we can investigate it further. For now, it doesn't look like it's an issue with the SDK.

**Comment by xiangfei8** [comment]
use the other code, I double tripled verified that it is this piece of code only "httpClient = ApacheHttpClient.builder()" that is throwing an exception in an environment that don't use proxy and have no proxy information defined.

the isProxyDefined = true path everything works fine and we are in production with that code.

**Comment by debora-ito** [comment]
@xiangfei8 As I explained, I can't use the code snippets without knowing how the variables are being defined. If you provide a self-contained minimal code example we can simply copy and paste and reproduce the issue, we can help you better.

**Comment by xiangfei8** [comment]
Can you also check this?
S3Client s3 = S3Client.builder()
.credentialsProvider(StaticCredentialsProvider.create(awsCreds))
.region(Region.of(awsS3BucketRegion))
.httpClient(ApacheHttpClient.builder().build())
.build())

If both of these are working for you, then have the support people (Case 9507447281) send us the spec for your environment settings (no proxy setup), it maybe something to do with our build environment setup, which I will need to get people that knows those environment involved. Hope you understand. Thanks!

**Comment by debora-ito** [comment]
I could not reproduce in my local environment which is MacOS 11.6.3, using Java 11 (Corretto-11.0.13+8) and no proxy settings.

Regardless of the value of `isProxyDefined` in the code, the error indicates that the proxy port environment variable is set with an empty value, something like 
```
http.proxyPort=
```
so this is something worth checking.

**Comment by xiangfei8** [comment]
yes, from the beginning I know it is trying to parse empty port,  but the question is why though? which part of your code is  picking out this empty port?

As I mentioned before as well, it is working fine in all environments including prod and my local. It is only happening in the new environment we are going to move to, my understanding is aws eks environment.  I am also waiting to hear back the exact spec of that environment relate that information to here

**Comment by xiangfei8** [comment]
I did not set any proxy port, the only thing I call is ApacheHttpClient.builder().build().
The other route of proxy host and proxy port setting is working fine.
So where is AWS API getting the empty proxy port from?

**Comment by debora-ito** [comment]
So I had another look. Providing a Java system property with an empty httpPort in my local tests: `-Dhttp.proxyPort` I can see the same `NumberFormatException`. The error is being thrown by the default Apache client builder:

https://github.com/aws/aws-sdk-java-v2/blob/03b58f98f66decff1eb1df6606fe355c9212f24c/http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java#L451-L453

`ProxyConfiguration.builder().build()` looks for proxy configuration in the system properties and try to parse the value to an Int. In this case the value is an empty string "", that's why we see the error.

So the empty port is probably being picked up as a system property in your EKS environment. Let us know if this helps.

**Comment by xiangfei8** [comment]
So we are back to my original question, which is - is there a way in the AWS API to set to not check any system property for proxy host and proxy port?  I am not setting and/or passing anything from the code, and I have no control over what the EKS environment system properties is being set to.

**Comment by xiangfei8** [comment]
I just also added a test to check System Property for both "http.proxyPort" and "https.proxyPort" in the EKS environment and the result is negative, which means there is no such System Property exist in that environment.  

the check is 
        String httpProxy = System.getProperty("http.proxyPort");
        String httpsProxy = System.getProperty("https.proxyPort");
        System.out.println(LOG_PREFIX + "SystemPropertyHttpProxyPort" + LOG_SUFFIX + (httpProxy == null ? "missing" : "present"));
        System.out.println(LOG_PREFIX + "SystemPropertyHttpsProxyPort" + LOG_SUFFIX + (httpsProxy == null ? "missing" : "present"));

and I am getting "missing" on both System property; AND YET STILL GETTNG  the same exception NumberFormatException in from that environment.  Thoughts?

**Comment by debora-ito** [comment]
Note that setting an empty System Property is different than not setting the property at all.

If you set an empty system property `-Dhttp.proxyPort`, `String httpProxy = System.getProperty("http.proxyPort");` will be an empty String `""`.

If you don't set the system property then you'll have httpProxy null.

The easiest way to work around this is to remove the empty property, but I understand the pain if you don't have control over the environment System Properties. I'll discuss with the team if we should add some checks around empty properties.

**Comment by royli-applovin** [comment]
Is there any update on this issue? Got the same problem when using AWS v2 SDK.

**Comment by royli-applovin** [comment]
@xiangfei8 Do you mean create a service client like the following?
```
ProxyConfiguration proxyConfiguration = ProxyConfiguration.builder()
                .useSystemPropertyValues( false )
                .endpoint( null )
                .build();
SdkHttpClient httpClient = ApacheHttpClient.builder()
                .proxyConfiguration(proxyConfiguration)
                .build();
S3Client s3 = S3Client.builder()
                .region( REGION )
                .credentialsProvider( StaticCredentialsProvider.create( awsCredentials ) )
                .httpClient( httpClient )
                .build();
```

**Comment by rabhowmi** [comment]
I'm facing the same issue. 
@xiangfei8 @royli-applovin: How did you solve this problem? Can you please post your code snippet?

**Comment by rabhowmi** [comment]
@debora-ito @yasminetalby Can you please comment on the status of this issue? What's an ETA for the fix?
