### ISSUE TITLE
Not sure if retries are happening in aws sdk 2

### ISSUE THREAD

**Issue by ssalamov** [aws/aws-sdk-java-v2#2988]
### Describe the issue

Hello,

We use aws sdk2 http client in Spring 5 (Webflux). `DynamoDbAsyncClient` configuration creation set in `Steps to Reproduce` section.

And timeout values are set like this:

```
apiCallAttemptTimeoutInMilliseconds = 80 ms
apiCallTimeoutInMilliseconds = 1000ms
```

We get such error stacktrace - shared in `Current behavior` section.

Hope you can explain why we see such stacktrace indicating that call was timeout after 80ms? Not sure if retires are happening.
 
Regards,
Samir Salamov

### Steps to Reproduce

```
 private DynamoDbAsyncClient buildDynamoDbAsyncClient(int apiCallAttemptTimeoutInMilliseconds, int apiCallTimeoutInMilliseconds) {
        return DynamoDbAsyncClient.builder()
                .region(Region.of(region))
                .httpClientBuilder(configureHttpClient())
                .overrideConfiguration(createDynamoDBClientConfiguration(apiCallAttemptTimeoutInMilliseconds, apiCallTimeoutInMilliseconds))
                .build();
    }

    private SdkAsyncHttpClient.Builder<NettyNioAsyncHttpClient.Builder> configureHttpClient() {
        return NettyNioAsyncHttpClient.builder()
                .tcpKeepAlive(true)
                .maxConcurrency(maxConcurrentConnectionCount)
                .tlsNegotiationTimeout(Duration.ofMillis(tlsNegotiationTimeoutInMilliSeconds))
                .connectionMaxIdleTime(Duration.ofMillis(maxLifeTimeInMilliseconds))
                .connectionMaxIdleTime(Duration.ofMillis(maxIdleTimeInMilliseconds))
                .connectionTimeout(Duration.ofMillis(CONNECTION_TIMEOUT_IN_MILLI_SECONDS))
                .readTimeout(Duration.ofMillis(READ_AND_WRITE_TIMEOUT_IN_MILLI_SECONDS))
                .writeTimeout(Duration.ofMillis(READ_AND_WRITE_TIMEOUT_IN_MILLI_SECONDS))
                .maxPendingConnectionAcquires(maxPendingConnectionCount)
                .connectionAcquisitionTimeout(Duration.ofMillis(connectionAcquisitionTimeout));
    }

    private ClientOverrideConfiguration createDynamoDBClientConfiguration(int apiCallAttemptTimeoutInMilliseconds, int apiCallTimeoutInMilliseconds) {
        ClientOverrideConfiguration.Builder builder = ClientOverrideConfiguration.builder()
                .apiCallAttemptTimeout(Duration.ofMillis(apiCallAttemptTimeoutInMilliseconds))
                .apiCallTimeout(Duration.ofMillis(apiCallTimeoutInMilliseconds))
                .retryPolicy(RetryPolicy.builder()
                        .numRetries(MAX_RETRY)
                        .throttlingBackoffStrategy(getBackoffStrategy())
                        .backoffStrategy(getBackoffStrategy())
                        .retryCapacityCondition(RetryCondition.none())
                        .build());
        return builder.build();
    }

    private BackoffStrategy getBackoffStrategy() {
        return FullJitterBackoffStrategy.builder()
                .baseDelay(Duration.ofMillis(BASE_DELAY_IN_MILLI_SECONDS))
                .maxBackoffTime(Duration.ofMillis(BACKOFF_DELAY_IN_MILLI_SECONDS))
                .build();
    }
```

### Current behavior

```
software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException: HTTP request execution did not complete before the specified timeout configuration: 80 millis
	at software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException$BuilderImpl.build(ApiCallAttemptTimeoutException.java:88)
	at software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException.create(ApiCallAttemptTimeoutException.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$setupAttemptTimer$5(MakeAsyncHttpRequestStage.java:259)
	at software.amazon.awssdk.core.internal.http.timers.AsyncTimeoutTask.run(AsyncTimeoutTask.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### AWS Java SDK version used

awssdk 2.17.114

### JDK version used

openjdk:11

### Operating System and version

pact-1.81.0-linux-x86_64.tar.gz

**Comment by ssalamov** [comment]
Putting another parameters from the above configuration:
```
private static final int MAX_RETRY = 3;
private static final int BASE_DELAY_IN_MILLI_SECONDS = 50;
private static final int BACKOFF_DELAY_IN_MILLI_SECONDS = 50;
```

**Comment by debora-ito** [comment]
Hi @ssalamov, 

The exception would still appear in the stacktrace, even if retries were in place. Is that the concern?

If you can to enable Request/Response debug logs, you should see the retries in the records explicitly.
Another option is to enable the SDK client-side metrics - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics.html
