### ISSUE TITLE
S3 PutObjectRequest fails given empty Tagging object

### ISSUE THREAD

**Issue by mbenson** [aws/aws-sdk-java-v2#3026]
### Describe the bug

When `TaggingAdapter#adapt()` is given an empty `Tagging` object an `IndexOutOfBoundsException` is thrown due to to indiscriminate attempt to retrieve the first tag pair: https://github.com/aws/aws-sdk-java-v2/blob/e0328b7b95ae5ba6b602c7551948720b072a23e7/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/TaggingAdapter.java#L44

### Expected behavior

Request should complete with no tags applied.

### Current behavior

```
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1347)
	at software.amazon.awssdk.services.s3.internal.TaggingAdapter.adapt(TaggingAdapter.java:44)
	at software.amazon.awssdk.services.s3.model.PutObjectRequest$BuilderImpl.tagging(PutObjectRequest.java:2510)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at Script1$_run_closure4.doCall(Script1.groovy:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
	at groovy.lang.Closure.call(Closure.java:418)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:113)
	at jdk.proxy5/jdk.proxy5.$Proxy98.accept(Unknown Source)
	at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
	at software.amazon.awssdk.services.s3.S3Client.putObject(S3Client.java:16733)
```

### Steps to Reproduce

`s3.putObject(b -> b.bucket('foo').key('xxx').tagging(Tagging.builder().tagSet().build()), RequestBody.fromString("whatever"))`

### Possible Solution

It would be an implementation detail whether to modify `TaggingAdapter#adapt` to accept an empty `Tagging` returning an appropriate `String` representation (empty? null?) or whether it should throw `IllegalArgumentException` and have the calling code opt not to call it at all for an empty `Tagging` object.

### Context

Creating a library for S3 integration with [Apache Ant](https://ant.apache.org). I will be forced to manually check for empty tag sets when performing put operations until this bug is addressed, which will unnecessarily clutter my code.

### AWS Java SDK version used

2.17.129

### JDK version used

java version "1.8.0_231" Java(TM) SE Runtime Environment (build 1.8.0_231-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

### Operating System and version

macOS Monterey Version 12.1

**Comment by debora-ito** [comment]
Thank you for reaching out @mbenson, we'll work on a fix.
