### ISSUE TITLE
API Gateway update usage plan fails with message: Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by plamen-paskov** [aws/aws-sdk-java-v2#3046]
### Describe the bug

In order to delete an usage plan attached to an API Stage I have to detach the stage from the usage plan. I'm doing this by sending an update usage plan request and what I receive is: java.net.ProtocolException: Invalid HTTP method: PATCH
The usage plan is attached to one api/stage

### Expected behavior

The API stage is removed from the usage plan

### Current behavior

The usage plan is not detached from the API stage

Stack trace:
`java.net.ProtocolException: Invalid HTTP method: PATCH: java.io.UncheckedIOException
java.io.UncheckedIOException: java.net.ProtocolException: Invalid HTTP method: PATCH
	at software.amazon.awssdk.utils.FunctionalUtils.asRuntimeException(FunctionalUtils.java:180)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeRunnable$5(FunctionalUtils.java:126)
	at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:140)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient.createAndConfigureConnection(UrlConnectionHttpClient.java:135)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient.prepareRequest(UrlConnectionHttpClient.java:116)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$NonManagedSdkHttpClient.prepareRequest(SdkDefaultClientBuilder.java:464)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:68)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:56)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.apigateway.DefaultApiGatewayClient.updateUsagePlan(DefaultApiGatewayClient.java:8416)
	at tv.ioio.live.blueprints.handler.endpoint.DeleteOrganizationHandler.handle(DeleteOrganizationHandler.java:100)
	at tv.ioio.live.blueprints.handler.endpoint.AbstractHandler.handleRequest(AbstractHandler.java:42)
	at tv.ioio.live.blueprints.handler.endpoint.DeleteOrganizationHandler.handleRequest(DeleteOrganizationHandler.java:22)
	at tv.ioio.live.blueprints.handler.endpoint.AbstractHandler.handleRequest(AbstractHandler.java:13)
Caused by: java.net.ProtocolException: Invalid HTTP method: PATCH
	at java.base/java.net.HttpURLConnection.setRequestMethod(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestMethod(Unknown Source)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient.lambda$createAndConfigureConnection$3(UrlConnectionHttpClient.java:135)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeRunnable$5(FunctionalUtils.java:124)
	... 44 more`

### Steps to Reproduce

`
apiGatewayClient.updateUsagePlan(UpdateUsagePlanRequest.builder()
                .usagePlanId(usagePlanId)
                .patchOperations(PatchOperation.builder()
                        .op(Op.REMOVE)
                        .path("/apiStages")
                        .value("API_ID:API_STAGE")
                        .build()
                )
                .build()
        );
`

### AWS Java SDK version used

2.17.133

### JDK version used

11

### Operating System and version

AWS Lambda

**Comment by debora-ito** [comment]
ApiGateway updateUsagePlan is a PATCH method (see [here](https://docs.aws.amazon.com/apigateway/api-reference/resource/usage-plan/) in the API Reference) and HttpURLConnection client does not support PATCH: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/HttpURLConnection.html#setRequestMethod(java.lang.String)

You'll need to use ApacheHttpClient or the Netty-based Async client to call PATCH operations.

**Comment by plamen-paskov** [comment]
Hey @debora-ito ,
I wasn't expecting a "low level" exception to bubble up. Thanks for helping me out!
