### ISSUE TITLE
NoSuchFieldError on files with delete marker

### ISSUE THREAD

**Issue by elenigen** [aws/aws-sdk-java-v2#3089]
### Describe the bug

On a S3 bucket with versioning enabled, if a file is deleted (the current version has a delete marker), the `getObject` will return `java.lang.NoSuchFieldError`:

```
[Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: HTTP_CHECKSUM] with root cause"
java.lang.NoSuchFieldError: HTTP_CHECKSUM
	at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:4489) ~[s3-2.17.146.jar:?]
	at software.amazon.awssdk.services.s3.S3Client.getObject(S3Client.java:7889) ~[s3-2.17.146.jar:?]
```

### Expected behavior

The documentation in version 2.17.146 mentions only about:
```
If the current version of the object is a delete marker, Amazon S3 behaves as if the object was deleted and includes x-amz-delete-marker: true in the response.
```
It should mention about an exception and it should be some kind of S3 exception.

### Current behavior

`getObject` will return `java.lang.NoSuchFieldError`:

```
[Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: HTTP_CHECKSUM] with root cause"
java.lang.NoSuchFieldError: HTTP_CHECKSUM
	at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:4489) ~[s3-2.17.146.jar:?]
	at software.amazon.awssdk.services.s3.S3Client.getObject(S3Client.java:7889) ~[s3-2.17.146.jar:?]
```

### Steps to Reproduce

In kotlin:
```
            s3Client.getObject(
                GetObjectRequest.builder()
                    .bucket("my-bucket-name")
                    .key(filename)
                    .build()
            )
                .reader()
                .readText()
```

### Possible Solution

Since the entry is removed, maybe `NoSuchKeyException`, not sure how we could distinguish a deleted file vs a file which never existed in that bucket.

### AWS Java SDK version used

11

### JDK version used

11

### Operating System and version

Linux

**Comment by elenigen** [comment]
Now I have the same issue with `DefaultS3Client.putObject`: `java.lang.NoSuchFieldError: HTTP_CHECKSUM] with root cause"` which means it's probably an issue related to aws sdk versions conflict.

**Comment by elenigen** [comment]
Confirmed, it was just a version conflict
