### ISSUE TITLE
AttributeValue is not serializable

### ISSUE THREAD

**Issue by nirtsruya** [aws/aws-sdk-java-v2#3143]
### Describe the bug

The AttributeValue class implements the Serializable interface. However, when trying to serialize it using java.io.ObjectOutputStream writeObject method I get the following error:
java.io.NotSerializableException: software.amazon.awssdk.core.util.DefaultSdkAutoConstructList

The reason is that the AttributeValue.Builder the constructor sets DefaultSdkAutoConstructList (which is not serializable) to all list type properties such as "l", "ss", "ns", and "bs"

### Expected behavior

AttributeValue should be serializable, and not throw an exception during serialization.

### Current behavior

An exception - java.io.NotSerializableException: software.amazon.awssdk.core.util.DefaultSdkAutoConstructList is thrown when trying to serialize it using java.io.ObjectOutputStream writeObject method

```
Caused by: java.io.NotSerializableException: software.amazon.awssdk.core.util.DefaultSdkAutoConstructList
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
```

### Steps to Reproduce

Simple code:
```
AttributeValue attributeValue = AttributeValue.builder()
                .n("123")
                .build();

try (ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
     ObjectOutputStream objectOutputStream = new ObjectOutputStream(byteArrayOutputStream)) {

    objectOutputStream.writeObject(attributeValue);

} catch (IOException e) {
    throw new RuntimeException(e);
}
```

### Possible Solution

software.amazon.awssdk.core.util.DefaultSdkAutoConstructList should implement Serializable

### AWS Java SDK version used

2.17.161

### JDK version used

11.0.14.1

### Operating System and version

Ubuntu 20.04.4 LTS

**Comment by debora-ito** [comment]
@nirtsruya thank you for reaching out. Your analysis is correct, AttributeValue won't be serializable due to the list structures. This was not a planned use case for AttributeValue, so I'm considering this a feature request.

**Comment by maiken2051** [comment]
This breaks other things too .. `S3Object` is no longer Serializable (despite having the Serializable marker) because this class is not Serializable.

**Comment by kevnzhao** [comment]
Any update or plan to fix this issue?

**Comment by alecuba16** [comment]
+1 Waiting for this feature, I was able to serialize before v2.

**Comment by aljazdolenc** [comment]
+1 waiting for this feature

**Comment by ryucc** [comment]
@bhoradc Want to ask if I can try to fix this issue. Is there any process to submit pull requests/ discuss solutions?

**Comment by ryucc** [comment]
The DefaultSdkAutoConstructList was trivially serializable, because it uses a singleton pattern.

The correct solution should be using the readResolve().

There are documents online for this.

https://www.baeldung.com/java-serialization-readobject-vs-readresolve

https://stackoverflow.com/questions/3930181/how-to-deal-with-singleton-along-with-serialization

**Comment by bhoradc** [comment]
> [@bhoradc](https://github.com/bhoradc) Want to ask if I can try to fix this issue. Is there any process to submit pull requests/ discuss solutions?

Hi @ryucc, 

We appreciate your interest in contributing to this feature request. I would like to inform you that our internal team is actively working on implementing this feature. However, at this time, I cannot provide an estimated timeline for its completion.

Regards, 
Chaitanya

**Comment by ryucc** [comment]
@bhoradc 

I've created a PR according to the [CONTRIBUTING](CONTRIBUTING.md) document.

Please review if possible, or see if the suggested code changes helps your internal development.

Thanks.

**Comment by debora-ito** [comment]
Change released in Java SDK `2.31.1`.
