### ISSUE TITLE
Getting "request signature" mismatch error trying to use 2.17.194-PREVIEW version of transfer manager to upload a file.

### ISSUE THREAD

**Issue by wtbcode** [aws/aws-sdk-java-v2#3206]
### Describe the bug

I am trying to use the S3TransferManager to upload files to an S3 bucket.

The "2.17.16-PREVIEW" version as described in the (https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html) page works fine, but the "2.17.194-PREVIEW" version (and some other sampled releases from the last few months do not.

Getting errors like this:

```
Caused by: software.amazon.awssdk.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: S3, Status Code: 403, Request ID: 03MJAEQN9PV8E1P2, Extended Request ID: vSKJkOSruzFKmLZZVpf1A3d5b4pXYxBX4oxecIQEkbuqqO7Mqalg+6cuErdk6pW1fxVg5bIXwWs=)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:245)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:89)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:132)
	at software.amazon.awssdk.transfer.s3.internal.S3CrtDataPublisher.handleTerminalEvent(S3CrtDataPublisher.java:110)
	at software.amazon.awssdk.transfer.s3.internal.S3CrtDataPublisher.flushBuffer(S3CrtDataPublisher.java:135)
	at software.amazon.awssdk.transfer.s3.internal.S3CrtDataPublisher.notifyStreamingFinished(S3CrtDataPublisher.java:68)
	at software.amazon.awssdk.transfer.s3.internal.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:82)
	at software.amazon.awssdk.transfer.s3.internal.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:72)
	at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:19)
```

Downloading files in the 2.17.194-PREVIEW version works fine and I am using the "aws sso login" for credentials.

My code looks like this (and I have played around with a few different options:

```
S3TransferManager transferManager = S3TransferManager.builder().s3ClientConfiguration(b -> b.region(REGION)).build();
FileUpload upload = transferManager.uploadFile(u -> u.source(FILE).putObjectRequest(p -> p.bucket(BUCKET).key(KEY)))
upload.completionFuture().join();
```

The REGION, BUCKET, and KEY variables I am using work when downloading objects and uploading with the 2.17.16-PREVIEW version. I can upload files to the bucket through the S3 API without error like this:

```
S3Client.builder().region(REGION).build().putObject(PutObjectRequest.builder().bucket(BUCKET).key(KEY).build(), RequestBody.fromFile(FILE));
```

### Expected Behavior

File is uploaded with the transfer manager without error.

### Current Behavior

S3Exception is raised.

### Reproduction Steps

Snippet from my POM file.

```
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>software.amazon.awssdk</groupId>
				<artifactId>bom</artifactId>
				<version>2.17.194</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>s3</artifactId>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>s3-transfer-manager</artifactId>
            <version>2.17.194-PREVIEW</version>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>dynamodb</artifactId>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>dynamodb-enhanced</artifactId>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>sso</artifactId>
		</dependency>
	</dependencies>
```

### AWS Java SDK version used

2.17.194

### JDK version used

1.8.0_171

### Operating System and version

Windows 10

**Comment by debora-ito** [comment]
Hi @wtbcode thank you for reaching out.

How consistent do you see the signature mismatch error? Does it happen with every file you try to upload with version 2.17.194-PREVIEW?
Is there anything special with the file in terms of content or special characters in the name?

**Comment by wtbcode** [comment]
I have since worked around the issue by not using the "transfer manager" to upload files, but when I was testing all files I attempted to upload using the transfer manager failed with this error all of the time. When I switched to the uploading without using the transfer manager, I could upload these same files to the same bucket without error.

**Comment by wtbcode** [comment]
The files are ZIP files and the names only use lower case alpha, digits and the dash character.

**Comment by debora-ito** [comment]
@wtbcode I cannot reproduce the error using the same SDK version you're using...

Can you please enable the CRT debug logs? Add the following line to the code:

```
Log.initLoggingToFile(Log.LogLevel.Debug, <filename>);
```
