### ISSUE TITLE
Unicode whitespace results in non-helpful error messaging

### ISSUE THREAD

**Issue by rli** [aws/aws-sdk-java-v2#3214]
### Describe the bug

The ProfileFileReader is unable to handle treat Unicode whitespace as an empty line

### Expected Behavior

Any type of whitespace to be treated as an empty line, or helpful messaging stating the issue

### Current Behavior

```
java.lang.IllegalArgumentException: Expected an '=' sign defining a property on line 5
at software.amazon.awssdk.utils.Validate.isTrue(Validate.java:76)
at software.amazon.awssdk.profiles.internal.ProfileFileReader.parsePropertyDefinition(ProfileFileReader.java:250)
at software.amazon.awssdk.profiles.internal.ProfileFileReader.readPropertyDefinitionLine(ProfileFileReader.java:132)
at software.amazon.awssdk.profiles.internal.ProfileFileReader.parseLine(ProfileFileReader.java:78)
at software.amazon.awssdk.profiles.internal.ProfileFileReader.lambda$parseFile$0(ProfileFileReader.java:58)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
at software.amazon.awssdk.profiles.internal.ProfileFileReader.parseFile(ProfileFileReader.java:58)
at software.amazon.awssdk.profiles.ProfileFile$BuilderImpl.build(ProfileFile.java:266)
at software.amazon.awssdk.profiles.ProfileFile.lambda$addCredentialsFile$0(ProfileFile.java:142)
at java.base/java.util.Optional.ifPresent(Optional.java:183)
at software.amazon.awssdk.profiles.ProfileFile.addCredentialsFile(ProfileFile.java:139)
at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
at software.amazon.awssdk.profiles.ProfileFile.defaultProfileFile(ProfileFile.java:90)
```

### Reproduction Steps

Buggy profile:
```
$ echo '\n[profile buggyProfile]\n\xc2\xa0\nregion = us-west-2' >> ~/.aws/config
```

![image](https://user-images.githubusercontent.com/742829/170381378-b329f069-666a-4b2b-a00f-b00ff4541449.png)

### Additional Information/Context

Also see:
* https://github.com/aws/aws-toolkit-jetbrains/issues/3162
and #2248

### AWS Java SDK version used

2.17.138

### JDK version used

Runtime version: 11.0.14.1+1-b2043.45 x86_64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### Operating System and version

macOS 11.6.5

**Comment by rli** [comment]
The customer issue reported in the JetBrains toolkit queue is slightly different, (I think they have a Unicode equals-like sign instead of the ASCII equals; not sure what else it could be), but I've asked them to confirm. I'd appreciate some hints on other avenues to explore if that was not the issue.

**Comment by ashishdhingra** [comment]
@rli AWS CLI command appears to be working. Could you please share on how you are using `ProfileFileReader`, may be a sample code?
