### ISSUE TITLE
S3TransferManager creation fails on Windows + Spring Boot

### ISSUE THREAD

**Issue by alibenmessaoud** [aws/aws-sdk-java-v2#3295]
### Describe the bug

Instantiation of S3TransferManager fails

### Expected Behavior

S3TransferManager is instantiated, file is uploaded.

### Current Behavior

	2022-07-12 18:13:59.502  INFO 18368 --- [           main] com.s3t.S3tApplication                : No active profile set, falling back to 1 default profile: "default"
	Unable to unpack AWS CRT lib: java.io.IOException: Unable to open library in jar for AWS CRT: /windows/x86_64/aws-crt-jni.dll
	java.io.IOException: Unable to open library in jar for AWS CRT: /windows/x86_64/aws-crt-jni.dll
		at software.amazon.awssdk.crt.CRT.extractAndLoadLibrary(CRT.java:161)
		at software.amazon.awssdk.crt.CRT.loadLibraryFromJar(CRT.java:226)
		at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:33)
		at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:104)
		at software.amazon.awssdk.transfer.s3.internal.S3NativeClientConfiguration.<init>(S3NativeClientConfiguration.java:60)
		at software.amazon.awssdk.transfer.s3.internal.S3NativeClientConfiguration$Builder.build(S3NativeClientConfiguration.java:208)
		at software.amazon.awssdk.transfer.s3.internal.S3CrtAsyncHttpClient.<init>(S3CrtAsyncHttpClient.java:61)
		at software.amazon.awssdk.transfer.s3.internal.S3CrtAsyncHttpClient.<init>(S3CrtAsyncHttpClient.java:47)
		at software.amazon.awssdk.transfer.s3.internal.S3CrtAsyncHttpClient$Builder.build(S3CrtAsyncHttpClient.java:243)
		at software.amazon.awssdk.transfer.s3.internal.DefaultS3CrtAsyncClient.<init>(DefaultS3CrtAsyncClient.java:66)
		at software.amazon.awssdk.transfer.s3.internal.DefaultS3CrtAsyncClient.<init>(DefaultS3CrtAsyncClient.java:54)
		at software.amazon.awssdk.transfer.s3.internal.DefaultS3CrtAsyncClient$DefaultS3CrtClientBuilder.build(DefaultS3CrtAsyncClient.java:223)
		at software.amazon.awssdk.transfer.s3.internal.DefaultS3TransferManager.initializeS3CrtClient(DefaultS3TransferManager.java:111)
		at software.amazon.awssdk.transfer.s3.internal.DefaultS3TransferManager.<init>(DefaultS3TransferManager.java:75)
		at software.amazon.awssdk.transfer.s3.internal.DefaultS3TransferManager$DefaultBuilder.build(DefaultS3TransferManager.java:425)
		at com.s3t.AwsS3Configuration.s3TransferManager(AwsS3Configuration.java:42)
		at com.s3t.AwsS3Configuration$$EnhancerBySpringCGLIB$$2502a608.CGLIB$s3TransferManager$0(<generated>)
		at com.s3t.AwsS3Configuration$$EnhancerBySpringCGLIB$$2502a608$$FastClassBySpringCGLIB$$133958ce.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
		at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
		at com.s3t.AwsS3Configuration$$EnhancerBySpringCGLIB$$2502a608.s3TransferManager(<generated>)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
		at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
		at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
		at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
		at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
		at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
		at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
		at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
		at com.s3t.S3tApplication.main(S3tApplication.java:11)

### Reproduction Steps

    S3TransferManager s3TransferManager() {

        S3ClientConfiguration s3ClientConfiguration =
                S3ClientConfiguration.builder()
                        .region(Region.of(region))
                        .credentialsProvider(this::getAwsBasicCredentials)
                        .build();

        return S3TransferManager
                .builder()
                .s3ClientConfiguration(s3ClientConfiguration)
                .build();
    }

    AwsBasicCredentials getAwsBasicCredentials() {
        return AwsBasicCredentials.create(accessKeyId, secretAccessKey);
    }

    ...
    var putObjectRequest = PutObjectRequest.builder()
                        .bucket(bucketName)
                        .key(objectKey)
                        .build();

    var request = UploadFileRequest.builder()
                .source(file.toPath())
                .putObjectRequest(putObjectRequest)
                .overrideConfiguration(builder -> builder.addListener(LoggingTransferListener.create()))
                .build();

    var upload = s3TransferManager().uploadFile(request);
    ...

### Possible Solution

Use version 1 of the SDK to upload a large file

### Additional Information/Context

I tried the new transfer manager to upload a file to S3 bucket. The transfer manager relies on CRT which does not ship with the maven dependency and causes the error above.

### AWS Java SDK version used

2.17.209 / 2.17.209-PREVIEW

### JDK version used

17.0.3-zulu

### Operating System and version

Windows 10 Pro 21H2 - 10.0.19044 - Build 19044.1806

**Comment by debora-ito** [comment]
@alibenmessaoud thank you for reaching out.

S3TransferManager should be working fine on Windows, I'll try to reproduce the error.
In the meantime, can you provide the CRT logs?

You can enable by adding this line to the code before the TransferManager instantiation:

```
Log.initLoggingToFile(Log.LogLevel.Debug, "log.txt")

```
