### ISSUE TITLE
S3TransferManager SdkClientException: Failed to send the request: Retry cannot be attempted because the retry strategy has prevented

### ISSUE THREAD

**Issue by rzhang90** [aws/aws-sdk-java-v2#3372]
### Describe the bug

Sometimes large files (1GB ) upload failed with SDKClientException "Failed to send the request: Retry cannot be attempted because the retry strategy has prevented". 

The S3 Transfer Manager is configured as:
```
    this.transferManager =
        S3TransferManager.builder()
            .s3ClientConfiguration(
                cfg ->
                    cfg.credentialsProvider(awsCredentialsProvider)
                        .region(Region.of(s3Region))
                        .targetThroughputInGbps(20.0)
                        .minimumPartSizeInBytes(5 * SizeConstant.MB))
                .build();
```
I didn't prevent the retry strategy. I'm wondering if this is prevented by default.

### Expected Behavior

Files could be uploaded successfully.

### Current Behavior

Exceptions thrown:
```
Caused by: java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: Retry cannot be attempted because the retry strategy has prevented the operation.
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:181)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:165)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: Retry cannot be attempted because the retry strategy has prevented the operation.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43)
	at software.amazon.awssdk.transfer.s3.internal.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:93)
	at software.amazon.awssdk.transfer.s3.internal.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:73)
	at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:19)
```

### Reproduction Steps

This issue may be caused by unstable network and is hard to reproduce.

### AWS Java SDK version used

2.17.191-PREVIEW

### JDK version used

1.8.0_311

### Operating System and version

macOS Monterey 12.5.1

**Comment by yasminetalby** [comment]
Hello @rzhang90 ,

Thank you very much for your submission. 
I can not reproduce this issue with the sample and information provided.
Could you share the CRT Trace logs to help investigating the origin of this behavior? You can enable CRT Trace logs by adding the following to your code:

`Log.initLoggingToFile(Log.LogLevel.Trace, <filename>);`

_Note : make sure to redact any sensitive information before sharing the file here._

Best,

Yasmine

**Comment by rzhang90** [comment]
Hi @yasminetalby ，thank you for your quick reply. Here is the log I got. The file is over 100MB and couldn't be uploaded. So I compress it. Thank you for you help!
[crt_log.txt.zip](https://github.com/aws/aws-sdk-java-v2/files/9418432/crt_log.txt.zip)

**Comment by yasminetalby** [comment]
Hello @rzhang90 ,

Thank you very much for providing the CRT logs.
The error you are encountering seems to be sent by the CRT client which is used by the S3TransferManager in AWS Java SDK v2 but handled by the CRT Team.
I have contacted the team about this issue and will keep you updated on here. I was wondering if you could provide your full reproducible upload logic code? I was also wondering if you have attempted the upload again/what is the behavior experienced in the case of another attempt?

Best,

Yasmine

**Comment by rzhang90** [comment]
Hello @yasminetalby ,

Thank you for  your followups. The logic code is:
```
  public void save(File from, UUID id) {
    try {
      String key = id.toString() + "/" + to.getFilename();
      FileUpload upload =
          transferManager.uploadFile(
              u -> u.source(from.toPath()).putObjectRequest(p -> p.bucket(bucketName).key(key)));
      upload.completionFuture().join();
    } catch (Exception e) {
      throw new RuntimeException(
          String.format("Failed to upload %s to cloud storage @ %s", from, id), e);
    }
  }
```
Very simple usage of TransferManager.

My colleague encountered this problem when he had poor network. And I could only reproduce this problem by connecting the hotspot of my phone. So I think the issue is related to unstable and poor network. 

Hope this helps. Looking forward to your updates.

**Comment by TingDaoK** [comment]
For a poor network, you set target througput to be 20 Gbps as `.targetThroughputInGbps(20.0)`.

The program will spins bunch of connections to try to reach 20Gbps, however, your network doesn't support that.
As a result, lot of request will failed with `RequestTimeout`. And the client will retry for those request.

As read from the log, the retry is happening too much in a short time and we have a limit of 500 times of retry to happen concurrently. And the exception you seen is that the limit was hit. `Failed to send the request: Retry cannot be attempted because the retry strategy has prevented the operation.`

So, don't push too much on the poor network, probably.

**Comment by rzhang90** [comment]
@TingDaoK Thank you for your feedback. Do you have any suggestions on the setting of targetThroughputInGbps? In most of our cases, data will be uploaded from a EC2 instance. But sometimes, the upload to S3 may start from developers' laptop.

**Comment by TingDaoK** [comment]
Ideally it can match the thoughput of your network. 
So, for EC2 instance, it's the Network Bandwidth you have. For other use case, it depends on your local environment.

**Comment by zoewangg** [comment]
@TingDaoK Is there any way we can improve the error message? The current message "Failed to send the request: Retry cannot be attempted because the retry strategy has prevented the operation." does not provide much information. If CRT could return a specific error code for this case, we can add the guidance in the error message.

**Comment by TingDaoK** [comment]
The cause of the failure is the retry strategy blocks the retry that should happen. 

I understand that user doesn't have the visibility of retries happening under the hood unless looking into the log.

But, I don't think we can convert this error message to something else, like we don't really know it's because of the poor network or the server is down somehow. 

I think the guidance we need to add should be around the configuration from user. Something like:
> If the `targetThroughputInGbps` is way higher than your network bandwidth, you may see `Retry cannot be attempted because the retry strategy has prevented the operation`, As too many requests are timed out and retried.

**Comment by rzhang90** [comment]
Thank you, @TingDaoK. I'm wondering if there is a default value for this config. Is it useful to set it?

**Comment by zoewangg** [comment]
I think we should provide the root cause of the issue in the message because there's not much users could do right now other than reaching out to us when they see the message, and it's not a good customer experience to ask users to enable logs for troubleshooting, not to mention that not every user is able to enable DEBUG logs especially in production. 

I understand network may not be the only root cause. I was thinking we can provide some hints like 

```
This can be due to slow network. Consider taking any of the following actions to mitigate the issue: 
1. reduce targetThroughutInGbps 2...
```

If CRT can provide an error code in the exception. We can add the guidance in the SDK

**Comment by TingDaoK** [comment]
> If CRT can provide an error code in the exception. We can add the guidance in the SDK
What error code you referring to here? Do you mean error code from S3?

**Comment by yasminetalby** [comment]
Hello @rzhang90 ,

It seems that the CRT Team now plans to report the error that is causing the retry (see PR [#207](https://github.com/awslabs/aws-c-s3/pull/207) submission above).
Let me know if there is any other information you need.

Thank you very much for bringing this to our attention.

Best,

Yasmine

**Comment by rzhang90** [comment]
Hi @yasminetalby. Thank you for the follow ups. I think that's everything I need for now. This issue could be closed. Thanks again for your help. @TingDaoK @zoewangg

**Comment by zoewangg** [comment]
Hi @rzhang90, you are very welcome! Let us know if you have any other feedback on Transfer Manager :) 

To close the previous conversation with @TingDaoK, CRT team will make the change to report the last error, and once that's released, we will add more guidance in the error message.
