### ISSUE TITLE
[IAM/STS] client doesn't work with customized endpoint 

### ISSUE THREAD

**Issue by yuanyuanzhang87** [aws/aws-sdk-java-v2#3387]
### Describe the bug

I tried to use v2 SDK to send AssumeRole request to my own STS service with below code, I configured endpoint to my own sts app, but the request finally just send to `https://host-ip` , path is missing which cause the request can't be send to right service

```
AttributeMap clientAttrs = AttributeMap.builder()
                .put(SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES, true)
                .build();
        SdkHttpClient sdkHttpClient = new DefaultSdkHttpClientBuilder().buildWithDefaults(clientAttrs);
        final StsClient stsClient = StsClient.builder()
                .region(Region.US_EAST_1)
                .credentialsProvider(StaticCredentialsProvider.create(cred))
                .endpointOverride(URI.create("https://host-ip/sts"))
                .httpClient(sdkHttpClient)
                .build();
```
Traced SDK code, found the cause is [https://github.com/aws/aws-sdk-java-v2/blob/master/core/protocols/aws-query-protoc[…]/protocols/query/internal/marshall/QueryProtocolMarshaller.java](https://github.com/aws/aws-sdk-java-v2/blob/master/core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/internal/marshall/QueryProtocolMarshaller.java#L55) 
it hardcoded path as empty string here. 
```
private SdkHttpFullRequest.Builder fillBasicRequestParams(OperationInfo operationInfo) {
        return ProtocolUtils.createSdkHttpRequest(operationInfo, endpoint)
                            .encodedPath("")
                            .putRawQueryParameter("Action", operationInfo.operationIdentifier())
                            .putRawQueryParameter("Version", operationInfo.apiVersion());
    }``` 

### Expected Behavior

expect request can save correct path provided through endpointOverride interface 

### Current Behavior

QueryProtocolMarshaller.java#L55) 
it hardcoded path as empty string

### Reproduction Steps

check in bug description

### Possible Solution

QueryProtocolMarshaller.java#L55) 
it hardcoded path as empty string here.  **I think it's better to get from `endpoint`**  , 
```
private SdkHttpFullRequest.Builder fillBasicRequestParams(OperationInfo operationInfo) {
        return ProtocolUtils.createSdkHttpRequest(operationInfo, endpoint)
                            .encodedPath("")
                            .putRawQueryParameter("Action", operationInfo.operationIdentifier())
                            .putRawQueryParameter("Version", operationInfo.apiVersion());
    }``` 

### AWS Java SDK version used

V2

### JDK version used

java version "11.0.12" 2021-07-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### Operating System and version

SUSE15

**Comment by yasminetalby** [comment]
Hello @yuanyuanzhang87 ,

Thank you very much for your submission.
The team is aware of this behavior and the item has been added to the backlog for AWS Java SDK v2.

Thank you very much for bringing this up to our attention.
I will post all updates about this here.

Best regards,

Yasmine

**Comment by amsocloud** [comment]
Hello

We are facing an issue with the sdk java 2 in our environment configuration. We are using pyspark with https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore.

Usually we don’t have issues by mocking Glue inside our SparkContext and using the Catalog.

```# SESSION WITHOUT ICEBERG
# Glue object is mocked with Fake dummy AWS credentials.
@pytest.fixture(scope="session", autouse=True)
def spark_context(glue):
    conf = (
        SparkConf()
        .setMaster("local[2]")
        .setAppName("pytest-pyspark-local-testing")
        .set(
            "spark.driver.extraJavaOptions",
            f"-Daws.glue.endpoint=http://127.0.0.1/:5301 -Daws.glue.disable-udf=true",
        )
    )
		spark = (
        SparkSession.builder.config(conf=conf)
        .enableHiveSupport()
        .getOrCreate()
    )
		database="my_glue_db"
		table_name="table_source"
    spark = SparkSession.builder.config(conf=conf).enableHiveSupport().getOrCreate()
		example_df = spark.read.csv((data_directory / "csv" / file_name).as_posix())
		example_df.write.saveAsTable(f"{database}.{table_name}", path=output_path, mode="overwrite")
		assert glue.get_table(DatabaseName=database, Name="test")["ResponseMetadata"]["HTTPStatusCode"] == 200
		yield spark
```

But we have soon decided to move on Iceberg and we are facing the following issue since we try to access our local glue catalog named `glue`:

```raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o75.sql.
: software.amazon.awssdk.services.glue.model.GlueException: The security token included in the request is invalid. (Service: Glue, Status Code: 400, Request ID: 5e36e8f6-73e4-4a67-8e9e-9922158a24fa)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.glue.DefaultGlueClient.getDatabase(DefaultGlueClient.java:6254)
	at org.apache.iceberg.aws.glue.GlueCatalog.loadNamespaceMetadata(GlueCatalog.java:499)
	at org.apache.iceberg.spark.SparkCatalog.loadNamespaceMetadata(SparkCatalog.java:439)
	at org.apache.spark.sql.connector.catalog.SupportsNamespaces.namespaceExists(SupportsNamespaces.java:98)
	at org.apache.spark.sql.execution.datasources.v2.CreateNamespaceExec.run(CreateNamespaceExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:622)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
```


We have added the following configuration to our spark Session to enable Iceberg (following the documentation https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-format-iceberg.html):

```# Glue object is mocked with Fake dummy AWS credentials.
@pytest.fixture(scope="session", autouse=True)
def spark_context(glue):
    conf = (
        SparkConf()
        .setMaster("local[2]")
        .setAppName("pytest-pyspark-local-testing")
				.set("spark.sql.catalog.glue", "org.apache.iceberg.spark.SparkCatalog")
				.set("spark.sql.catalog.glue.warehouse", "/tmp/warehouse/iceberg")
				.set("spark.sql.catalog.glue.catalog-impl", "org.apache.iceberg.aws.glue.GlueCatalog")
				.set("spark.sql.catalog.glue.io-impl", "org.apache.iceberg.aws.s3.S3FileIO")
        .set(
            "spark.driver.extraJavaOptions",
            f"-Daws.glue.endpoint=http://127.0.0.1/:5301 -Daws.glue.disable-udf=true",
        )
    )
		spark = (
        SparkSession.builder.config(conf=conf)
        .enableHiveSupport()
        .getOrCreate()
    )
		spark.sql("CREATE DATABASE IF NOT EXISTS glue.unitests") # -> Generates the error seen upper
		yield spark
```

As soon as we define our glue catalog via our Spark conf, the mocked glue context is not supported at all. It tries to go directly through Glue by loading AWS environment variables.
As we are on a test session it is obvious that the connection will not pass. 
Is there a way to override the Glue session with an endpoint URL corresponding to our mocked session?
Do you know why our `-Daws.glue.endpoint` settings isn't taken into account ?

@yasminetalby, do you think there is a way around ?

@yuanyuanzhang87, by curiosity have you developed a patch meanwhile ?

Thank you in advance,

# Environment:
Spark: 3.3.2
Iceberg Version: 1.1.0
[Aws sdk](https://mvnrepository.com/artifact/software.amazon.awssdk/aws-sdk-java/2.18.31): 2.18.31
[Glue connector](https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/tree/branch-1.10.0): branch-1.10.0

**Comment by laurateixeir** [comment]
I also came across this issue when upgrading a service to Spring Boot 3 and to the aws sdk v2. In my case my application wasn't able to send messages threw SNS because the path was reseted to an empty string.

Until the bug is fixed there is a workaround to modfiy the http request in the configuration.
To fix this you will need a ClientOverrideConfiguration in the config to add it to your client. There you will have the possibilty to add an ExecutionInterceptor where the encodedPath can be set to the desired value.



```
private SnsClient snsClient() {
        return SnsClient.builder()
                .credentialsProvider(getCredentialsProvider())
                .endpointOverride(URI.create(host))
                .overrideConfiguration(clientConfiguration())
                .build();
    }


private ClientOverrideConfiguration clientConfiguration() {

        return ClientOverrideConfiguration.builder()
                .addExecutionInterceptor(new SnsHttpPathInterceptor(encodedPath))
                .build();
    }

```

This only acts as an workaround till the bug is fixed but for now it works.

```
    private static class SnsHttpPathInterceptor implements ExecutionInterceptor {

        private final String encodedPath;

         public SnsHttpPathInterceptor(String encodedPath) {
         this.encodedPath = encodedPath;
        }

        @Override
        public SdkHttpRequest modifyHttpRequest(final Context.ModifyHttpRequest context,
                final ExecutionAttributes executionAttributes) {
            return context.httpRequest().toBuilder().encodedPath(encodedPath).build();
        }

    }
    
  ```

**Comment by ianroberts** [comment]
Still a problem four years on from the original report.

In my case I'm trying to use the AWS SDK with Minio Operator, where the STS endpoint is of the form `https://sts.minio-operator.svc.cluster.local:4223/sts/{namespace}`, the above workaround with the `ExecutionInterceptor` works but can anyone explain why it was made to junk the path components in the first place?
