### ISSUE TITLE
NullpointerException in NettyUtils.closedChannelMessage

### ISSUE THREAD

**Issue by steven-sheehy** [aws/aws-sdk-java-v2#3435]
### Describe the bug

Received a NPE when attempting to download/get a file from S3 using the SDK. When this occurs my `future.get()` never completes as though the completion or error signal is not bubbled up to the application.
```bash
2022-09-21T11:37:19.889-0600 WARN aws-java-sdk-NettyEventLoop-0-5 i.n.u.c.DefaultPromise An exception was thrown by software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor$$Lambda$2847/0x0000000801ae7098.operationComplete() java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.closedChannelMessage(NettyUtils.java:135)
at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.decorateException(NettyUtils.java:71)
at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:310)
at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.makeRequestListener(NettyRequestExecutor.java:189)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.lang.Thread.run(Unknown Source)
```

### Expected Behavior

No exception

### Current Behavior

NPE

### Reproduction Steps

I'm not sure the exact scenario for which it occurs as it occurs sporadically.
```java
        var request = GetObjectRequest.builder()
                .bucket(properties.getBucketName())
                .key(s3Key)
                .requestPayer(RequestPayer.REQUESTER)
                .build();
        var future = s3AsyncClient.getObject(request, AsyncResponseTransformer.toBytes());
        var response = future.get();
```

### AWS Java SDK version used

2.17.261

### JDK version used

eclipse-temurin:17.0.3_7-jre

### Operating System and version

Linux AMD64 Docker

**Comment by zoewangg** [comment]
The fix has been merged in https://github.com/aws/aws-sdk-java-v2/pull/3574 
Could you try with the latest version?
