### ISSUE TITLE
Compiler error when aws-java-sdk in pom.xml was updated from V to V2

### ISSUE THREAD

**Issue by pjonnlagadda** [aws/aws-sdk-java-v2#3436]
### Describe the bug

As i am trying to migrate aws-sdk-java from V1 to V2, 
to make start i have replaced the artifacts in pom.xml accordingly for S3, STS, SQS and IAM etc.. . Later when i am trying to build, getting few of the compile errors saying that, classes like AmazonSQS, SQSActions are missing and many other compile errors for few other classes. Seems the package "com.amazonaws.auth.policy" is missing.
**Ex:-**
constructor S3BucketResource in class com.amazonaws.auth.policy.resources.S3BucketResource cannot be applied to given types;
  required: java.lang.String
  found: java.lang.String,java.lang.String

### Expected Behavior

Is there any smooth way to replace V2 from V1?

### Current Behavior

getting few of the compile errors saying that, classes like AmazonSQS, SQSActions are missing

### Reproduction Steps

Replace the artifacts in pom.xml accordingly for S3, STS, SQS and IAM etc.

### AWS Java SDK version used

AWS SDK for Java 2.0

### JDK version used

java 1.8

### Operating System and version

Windows 11 Enterprise

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Thank you very much for your submission.
Could you please clarify the following:
Is the only step you have took to migrate modifying the pom.xml file with v2 artifact?

There exists multiple changes between the two versions. You would need to update your code appropriately while migrating from v1 to v2. 

The Developer Guide describes the [main changes to be aware of ](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-whats-different.html) when converting an application from using the AWS SDK for Java version 1.x to version 2.x.

The[ 1.11 to 2.0 Changelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md) is also a good resource to see changes between the two versions.

If your application depends on libraries that have not yet been released in version 2.x, see [Using both SDKs side-by-side](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-side-by-side.html) to learn how to configure your pom.xml to use both 1.x and 2.x.

Best,

Yasmine

**Comment by pjonnlagadda** [comment]
Hi @yasminetalby ,
Thank you for the response. 
regarding your question "Is the only step you have took to migrate modifying the pom.xml file with v2 artifact?"
Yes, The very first step i started with replacing the pom.xml entries only. 
Not modified any code changes before changing form V1 to V2

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Thank you very much for the information.

You will need to update your code based on the changes between the two version of the SDK. 
You can find most documentation on the resources I have shared above!

Another good resource to look at for an overview of the use of different services in AWS Java SDK v2 is in [aws-docs/aws-doc-sdk-examples/javav2/example_code](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javav2/example_code).

This does not seems like a bug but more a documentation question so I will change the label on the issue.
Let me know if you have any question or if there is any information that is not provided by the documentation that I can help with!

Sincerely,

Yasmine

**Comment by pjonnlagadda** [comment]
Hi @yasminetalby,
Thank you very much for the valuable info.

So the final conclusion you mean, 
**Step 1:-** Start using side – by side
**Step 2:-** Start making the code changes for migration of the services which we are using  from V1 to V2(Ex:- to  S3, SQS, IAM, STS etc..)
**Step 3:-**In future Once all the changes are migrated from V1 to V2(long process),  we can completely remove the V1 entries from Pom.xml if everything is supported in V2

As I we have policy related classed in V1 com.amazonaws.auth.policy are found in the V2 test folder. But not all. Any idea where I can found them all or any examples like how can we start using them in the V2? 
or the usage of Statement, Principal, Condition, Policy etc..

Thanks in Advance.

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Yes exactly!

This is the V1 package [com.amazonaws.auth.policy](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/policy/package-summary.html)

Here is the V2 package [software.amazon.awssdk.core.auth.policy](https://sdk.amazonaws.com/java/api/2.0.0/software/amazon/awssdk/core/auth/policy/package-summary.html)

If you need example for a specific use case you can also submit a documentation request to the aws-docs team to ask for new documentation of a specific use case [here](https://github.com/awsdocs/aws-doc-sdk-examples/issues) under feature-request.

I hope these resources help!

Is there any way we can improve the documentation provided on the migration guide to facilitate migration from AWS Java SDK V1 to V2 on your end? We would love to have any feedback on your experience and what you would find helpful/valuable to support you through this process.

Sincerely,

Yasmine

**Comment by pjonnlagadda** [comment]
Hi @yasminetalby,
Once again thank you for the information.
Still i see that few of the enums are missing or not able to identify in the V2 when compare to V1. Any clue on where could i found them?
com.amazonaws.auth.policy.actions.S3Actions;
com.amazonaws.auth.policy.actions.SQSActions;
com.amazonaws.auth.policy.actions.SecurityTokenServiceActions;

Thanks in Afvance

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda,

Of course. Could you please provide the code sample you are trying to migrate to v2? 

Best,

Yasmine

**Comment by pjonnlagadda** [comment]
Hi Yasminetalby,
In the process of migration, i have started using them side by side and trying to create an S3 client with the DefaultCredentialsProvider, where i am not able to find Regions.getCurrentRegion() in the V2 support to find out the current region as i need to have few validations in this?
In the V1 i use to find in using the **Region currentRegion = Regions.getCurrentRegion();**

S3Client s3 = S3Client.builder()
        			.region(region)
        			.credentialsProvider(DefaultCredentialsProvider.create()).build();
Any help on getting this current region in V2?

Thanks in advance.

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

`Regions.getCurrentRegion()` is not supported in v2 see: [Region class name changes](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-client-region.html) in the migration guide. 
To retrieve the current region of the running EC2 instance you can use [EC2MetadataUtils.getEC2InstanceRegion](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.html#getEC2InstanceRegion()).

Let me know if you have any further questions!

Best,

Yasmine

**Comment by pjonnlagadda** [comment]
Hi Yasmine,
Thank you for the response and i am clear with the S3Client part.
Another problem in the area of SqsClient where as i am trying to migrate from V1 to V2 and in the part of sqsClient.deleteMessageBatch().
Here i am trying to create an objects for DeleteMessageBatchRequestEntry and DeleteMessageBatchRequest to make an batch delete from the queue.
Using the below code snippet i am trying to create an objects and not able to understand how to pass the BuilderImpl to the constructor there i am getting compile error and not allowing further. Can you please help on clearing the same??
`software.amazon.awssdk.services.sqs.model.DeleteMessageBatchRequestEntry entry = new software.amazon.awssdk.services.sqs.model.DeleteMessageBatchRequestEntry**()**.builder()
				.id(String.format("%d", counter))
				.receiptHandle(message.receiptHandle())
				.build();`

`software.amazon.awssdk.services.sqs.model.DeleteMessageBatchRequest deleteRequest = new software.amazon.awssdk.services.sqs.model.DeleteMessageBatchRequest**()**.builder()
					.queueUrl(sqsQueueURL).entries(deleteEntries).build();`

**Comment by pjonnlagadda** [comment]
Hi Yasmine,
Thanks you for the given clarification on S3Client.
Another area where as i am trying to migrate the KinesisClient from V1 to V2 and here in the V1 we are set setting up the EndpointConfiguration to the KinesisClientBuilder where as am not able to make it in the V2 and i dont fund any information in the code examples or in the catalog. Any idea on make it this happen?
In the V1 i am using like 
`AmazonKinesisClientBuilder clientBuilder = AmazonKinesisClientBuilder.standard();
clientBuilder.setEndpointConfiguration(new EndpointConfiguration(<endpoint>, <region>));`

In V2 migration to the below class i am not able to find any thing related to end point configuration except the "endpointOverride" where we cannot set the region and for **.statndared** also bydefault support?
`KinesisClientBuilder kinesisClientBuilder = KinesisClient.builder();`

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Of course!

This is documented in the[1.11 to 2.0 Changelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md) provided earlier. 

You can find this information under : [AWS Client Configuration: Custom Regions, Credentials and Endpoints](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#12-aws-client-configuration-custom-regions-credentials-and-endpoints)

The example provided is for DynamoDBClient but this documentation is relevant for general endpoint configuration.

See the v1.11.x endpoint configuration syntax:

`AmazonDynamoDBClientBuilder.standard()
.withEndpointConfiguration(new EndpointConfiguration(endpoint, signingRegion))
.build();`

And the v2.0 endpoint configuration syntax:

`DynamoDbClient.builder()
.region(signingRegion)
.endpointOverride(endpoint)
.build()`

Looking at the documentation for the [KinesisClientBuilder](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/kinesis/KinesisClientBuilder.html) in v2 you can find both region and endpointOverride method used in the syntax above.

Best,

Yasmine

**Comment by pjonnlagadda** [comment]
Hi @yasminetalby,
Thank you for response. and using the ..endpointOverride(endpoint) .build(), i have configured the KinesisClient and make a call to finding out the stream status where as i am ending up with some error. here is the below code snippet i am using on V1 vs V2
**In the V1 my code is 100% working as expected**
 

> `BasicAWSCredentials awsCreds = new BasicAWSCredentials(kiStreamDef.getAccessKeyId(), secertKey);
		AWSStaticCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(awsCreds);
		AmazonKinesisClientBuilder clientBuilder = AmazonKinesisClientBuilder.standard();
		clientBuilder.setEndpointConfiguration(new EndpointConfiguration(endpoint, region));
		clientBuilder.setCredentials(credentialsProvider);
		KinesisClient kinesisClient = clientBuilder.build();
		

> DescribeStreamRequest describeStreamRequest = new DescribeStreamRequest();
> describeStreamRequest.setStreamName(streamName);
> 
> DescribeStreamResponse response = kinesisClient.describeStream(describeStreamRequest);`

**What i see in the V1 log**
`Sending Request: POST http://localhost:59628/stream / 
Headers: (amz-sdk-invocation-id: 6acc15ee-c89c-132a-267e-279842498c99, 
			Content-Length: 41, 
			Content-Type: application/x-amz-json-1.1, 
			User-Agent: aws-sdk-java/1.12.308 Windows_10/10.0 OpenJDK_64-Bit_Server_VM/25.322-b06 java/1.8.0_322 vendor/Amazon.com_Inc. cfg/retry-mode/legacy, X-Amz-Target: Kinesis_20131202.DescribeStream, ) `

**In V2**
Following is the code I have replaced with V2 from V1 where as i am getting error "49 - RESTEASY002010: Failed to execute
javax.ws.rs.NotSupportedException: RESTEASY003065: Cannot consume content type"

`_

> AwsBasicCredentials awsCreds = AwsBasicCredentials.create(accessKey, secertKey);
> AwsCredentialsProvider  credentialsProvider = StaticCredentialsProvider.create(awsCreds);
> KinesisClient kinesisClient = KinesisClient.builder()
>             .region(Region.of(region))
>             .endpointOverride(URI.create(endpoint))
>             .credentialsProvider(credentialsProvider)
>             .build();
> 			
> DescribeStreamRequest describeStreamRequest = DescribeStreamRequest.builder().streamName(streamName).build();
> DescribeStreamResponse response = kinesisClient.describeStream(describeStreamRequest);

_`

**What i see in the V2 log**
`2022-10-13 17:55:11.239 [main         ] DEBUG software.amazon.awssdk.request                :  85 - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=http, host=localhost, port=61417, encodedPath=/stream/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2022-10-13 17:55:11.463 [main         ] DEBUG s.a.a.c.internal.io.SdkLengthAwareInputStream :  85 - Specified InputStream length of 39 has been reached. Returning EOF.
2022-10-13 17:55:11.590 [main         ] DEBUG software.amazon.awssdk.auth.signer.Aws4Signer :  85 - AWS4 String to sign: XXXXXXXXXXXXXX
XXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2022-10-13 17:55:14.074 [pool-3-thread-4] DEBUG org.jboss.resteasy.resteasy_jaxrs.i18n        :  49 - RESTEASY002315: PathInfo: /stream/
2022-10-13 17:55:14.084 [pool-3-thread-4] ERROR org.jboss.resteasy.resteasy_jaxrs.i18n        :  49 - RESTEASY002010: Failed to execute
javax.ws.rs.NotSupportedException: RESTEASY003065: Cannot consume content type
	at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:460)
	at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:141)
	at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43)
	at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:48)
	at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:438)
	at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:302)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:223)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:137)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:140)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:217)
	at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:83)
	at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:57)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)`

Not understanding what went wrong, is headers part something missing in the V2 where as compare to V1?, Can you please help on make this further?

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Thank you very much for your answer.
I see that the question here is a duplicate of #3498. 
Would you be ok if I close this documentation issue in favor of your bug issue submission to keep track of this issue?

Best regards,

Yasmine

**Comment by pjonnlagadda** [comment]
Hi @yasminetalby,
Please keep open this documentation issue for the further assistance in the feature migration portion. If anything related to the documentation, i can place it here and keep on track them.

Regards,
Praveen

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Thank you very much for your response.
I will keep this issue open for documentation related question regarding migration.

Best regards,

Yasmine.

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

I hope that you are doing well. I was wondering if you would be ok for me to transfer this GitHub Issue to General Discussion.
I think this could be a great resource for other users who are attempting to migrate from v1 to v2.

Let me know if that is ok with you!

Best,

Yasmine

**Comment by pjonnlagadda** [comment]
I am OK to make it general. But i want to continue this thread for my further migration activities also.

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Thank you very much for your response.
Of course! This thread and previous discussion will not be lost, It will just be transferred under General Discussion and will stay open for any further questions or guidance request you might have throughout the migration process.

Sincerely,

Yasmine
