### ISSUE TITLE
LambdaClient - LambdaException: Unable to fetch Lambda archive 

### ISSUE THREAD

**Issue by kyght** [aws/aws-sdk-java-v2#3582]
### Describe the bug

I'm using `group: 'software.amazon.awssdk', name: 'lambda', version: '2.18.29' ` and connecting to LocalStack using an endpoint override. 

Our Jenkins server has a proxy server configured, so I use that ApacheHttpClient. SSM, DynamoDB, IAM, S3 and Lambda client all bypass the proxy and connect to LocalStack on a host 0.0.0.0

When creating a function, if I encode a jar file into the FunctionCode
```
           InputStream is = Files.newInputStream(Paths.get(codeFile.getAbsolutePath()));
           SdkBytes fileToUpload = SdkBytes.fromInputStream(is);
           function = function.zipFile(fileToUpload);
```
The LambdaClient creates the function and executes it just fine.

However, if I encode the jar as being located in S3
```
            function = function
                    .s3Bucket(s3url.getBucket())
                    .s3Key(s3url.getKey());
```
The LambdaClient fails to create the function with exception
software.amazon.awssdk.services.lambda.model.LambdaException: Unable to fetch Lambda archive from s3://...

                    
                    

### Expected Behavior

I expect the lambda function to be created and be usable

### Current Behavior

The LambdaClient throws an exception
```
software.amazon.awssdk.services.lambda.model.LambdaException: Unable to fetch Lambda archive from s3://releases/testfolder/testing-1.0.4.jar: Failed to connect to proxy URL: "[http://proxy.us-west-2.company.com:3128"](http://proxy.us-west-2.company.com:3128/) (Service: Lambda, Status Code: 404, Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[sdk-core-2.18.29.jar:?]
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56) ~[aws-core-2.18.29.jar:?]
	at software.amazon.awssdk.services.lambda.DefaultLambdaClient.createFunction(DefaultLambdaClient.java:882) ~[lambda-2.18.29.jar:?]
```

### Reproduction Steps

- Set Proxy Environment Variables that AwsSyncClientHandler will fail with. 
- Build Lambda Client using ApacheHttpClient, which will not use Proxy
```
    public static LambdaClient getLambdaClient(String lambdaEndpoint)
    {
        LambdaClientBuilder builder = LambdaClient.builder();
        builder.httpClient(ApacheHttpClient.builder().build());
        if (!StringUtils.isNullOrEmpty(lambdaEndpoint))
        {
            log.info(String.format("Using Lambda Endpoint %s", lambdaEndpoint));
            try {
                builder = builder.endpointOverride(new URI(lambdaEndpoint));
            } catch (URISyntaxException e) {
                throw new RuntimeException(e);
            }
        }
        return builder.build();
    }
```
Create a Lambda Function using S3 stored file
```
            FunctionCode.Builder function = FunctionCode.builder();
            function = function
                        .s3Bucket(s3url.getBucket())
                        .s3Key(s3url.getKey());
            FunctionCode code = function.build();

            CreateFunctionRequest functionRequest = CreateFunctionRequest.builder()
                    .functionName(functionName)
                    .description("Created by the Verafin Cloud Runner via Java API")
                    .code(code)
                    .handler(handler)
                    .runtime(Runtime.JAVA8)
                    .role(lambdaRole)
                    .memorySize(8000)
                    .timeout(900)
                    .build();

            CreateFunctionResponse functionResponse = awsLambda.createFunction(functionRequest);
```

    

### Possible Solution

If the LambdaClient needs to connect to S3, it should pass along the same httpClient it uses.  
Alternatively, allow an S3ClientBuilder to be passed into the LambdaClient builder so it can build an S3 client that works in the environment.

### AWS Java SDK version used

2.18.29

### JDK version used

1.8

### Operating System and version

macos/linux

**Comment by debora-ito** [comment]
Hi @kyght, apologies for taking so long to send a response.

The access to the s3 object is made on the service side, not on the client side. The Lambda client does not have an underlying S3 client.

If the "Unable to fetch Lambda archive" error is coming from LocalStack, it indicates that LocalStack tried to access the s3 object and it was unable to.
