### ISSUE TITLE
`DefaultAttributeConverterProvider` throws `IndexOutOfBoundException` on `List` class

### ISSUE THREAD

**Issue by eduardo-rdgz** [aws/aws-sdk-java-v2#3626]
### Describe the bug

Similar to #2296 

Class `DefaultAttributeConverterProvider` throws `IndexOutOfBoundException` when using the `List` class. This for the `TableSchema` builder.

If I have a `List<String>` field in the class:

```
private List<String> faceMatchErrors;
```

Then for the `TableSchema.builder()`:

```
.addAttribute(List.class, a ->
                    a.name("faceMatchErrors").getter(Transaction::getFaceMatchErrors).setter(Transaction::setFaceMatchErrors))
```

### Expected Behavior

This should return the `(AttributeConverter<T>) ListAttributeConverter.create(innerConverter)` for the `List<String>` field.

### Current Behavior

This throws: 

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4483)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.findConverterInternal(DefaultAttributeConverterProvider.java:163)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.findConverter(DefaultAttributeConverterProvider.java:143)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.converterFor(DefaultAttributeConverterProvider.java:135)
```

This is caused by line 163 in `DefaultAttributeConverterProvider`

```
EnhancedType<T> innerType = (EnhancedType<T>) type.rawClassParameters().get(0);
```

Since `rawClassParameters` is an `Empty List`.

### Reproduction Steps

Just create a table schema builder with a `List.class` attribute.

### Possible Solution

I had to manually create the `AttributeConverter`
```
(AttributeConverter) ListAttributeConverter.create(StringAttributeConverter.create()))
```
```
.addAttribute(List.class, a ->
                    a.name("faceMatchErrors").getter(Transaction::getFaceMatchErrors).setter(Transaction::setFaceMatchErrors)
                            .attributeConverter( (AttributeConverter) ListAttributeConverter.create(StringAttributeConverter.create())) )
```
Based on the default provider code, this has to be done automatically.

### Additional Information/Context

I'm not using annotations due to introspection problems and compatibility with Micronaut and GraalVM. Using the `TableSchema.fromClass(Transaction.class)` gets this field right without problems.

### AWS Java SDK version used

2.17.271

### JDK version used

openjdk version "11.0.15"

### Operating System and version

Linux

**Comment by eduardo-rdgz** [comment]
Yes it works like that. I figured it out a day after this ticket.
This is the key part:
```
EnhancedType.listOf(String.class)
```
I did not see it in the main documentation, I had to check other repos/answers for this example. 
Thanks.
