### ISSUE TITLE
Sdk swallows exception, client hangs when too many queued responses for async requests

### ISSUE THREAD

**Issue by coekie** [aws/aws-sdk-java-v2#3652]
### Describe the bug

When the capacity of the queue for handling responses to async requests is exceeded (RejectedExecutionException), calls just hang: CompletableFutures never complete. The exception is silently swallowed by the sdk.

This can happen when a client sends a lot of requests, but is (temporarily) slow at handling the responses. 

### Expected Behavior

The CompletableFuture should complete exceptionally.

### Current Behavior

The CompletableFuture never completes, making the user code wait forever.

### Reproduction Steps

We send a large number of requests to dynamodb, where _initially_ the handling of the response is slow, causing too many responses to queue up. We then wait for all other responses.

For me, this reliably reproduces the issue:
```
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient;

public class HangTest {
  public static void main(String[] args) {
    // connect to a running dynamodb-local instance
    DynamoDbAsyncClient client = DynamoDbAsyncClient.builder()
        .httpClient(NettyNioAsyncHttpClient.create())
        .endpointOverride(URI.create("http://localhost:1025"))
        .region(Region.US_WEST_2)
        .credentialsProvider(
            StaticCredentialsProvider.create(AwsBasicCredentials.create("default", "default")))
        .build();

    int iterations = 2000; // for me 1000 works but 2000 makes it hang
    int initialSlownessMillis = 5_000; // have initial handling of responses take 5 seconds
    List<CompletableFuture<?>> futures = new ArrayList<>();
    long startTime = System.currentTimeMillis();

    for (int i = 0; i < iterations; i++) {
      futures.add(
          // using listTables here for simplicity. it's the same for any other request.
          client.listTables().thenRun(() -> {
            try {
              if (System.currentTimeMillis() - startTime < initialSlownessMillis) {
                Thread.sleep(initialSlownessMillis);
              }
            } catch (InterruptedException e) {
              throw new RuntimeException(e);
            }
          }));
    }

    // wait for all requests to complete. hangs forever.
    futures.forEach(CompletableFuture::join);
  }
}
```

### Additional Information/Context

Here's the stacktrace of the exception that is being swallowed. I got this using a debugger, by putting a breakpoint in ThreadPoolExecutor.reject.

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$UniWhenComplete@3f66b4e7 rejected from java.util.concurrent.ThreadPoolExecutor@3d948866[Running, pool size = 64, active threads = 64, queued tasks = 80, completed tasks = 1067]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:854)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:132)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:513)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:250)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:75)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:371)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:402)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:338)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### AWS Java SDK version used

1.12.270

### JDK version used

17.0.3

### Operating System and version

Presumably all. Reproduced on macOS 13.0.1.

**Comment by coekie** [comment]
We can work around this issue by overriding the executor that the sdk uses, like this:
```
DynamoDbAsyncClient.builder()
    .asyncConfiguration(ClientAsyncConfiguration.builder()
        .advancedOptions(Map.of(SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR,
            createFutureCompletionExecutor()))
        .build())
    ...
```

We can create an executor similar to [what the sdk creates by default in SdkDefaultClientBuilder](https://github.com/aws/aws-sdk-java-v2/blob/30390d796740e6246060caaffe149adca5687292/core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java#L386-L396) , but two possible changes to avoid the issue:
* increasing the size of the LinkedBlockingQueue. but that's just making it less likely to happen.
* creating the executor with `new ThreadPoolExecutor.CallerRunsPolicy()`. that way when the size limit is reached, it does not throw a RejectedExecutionException. This has the same effect as using Runnable::run (as suggested in [FUTURE_COMPLETION_EXECUTOR javadoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/client/config/SdkAdvancedAsyncClientOption.html#FUTURE_COMPLETION_EXECUTOR) ), but only when the queue is full.

**Comment by stevenzyang** [comment]
Looks like this issue has been fixed? https://github.com/aws/aws-sdk-java-v2/blob/55383d3bcff003a5630ab21fff6a5329f01f0b50/CHANGELOG.md#L1002

**Comment by debora-ito** [comment]
Seems like the PR https://github.com/aws/aws-sdk-java-v2/pull/4009 tackled this issue - thanks @stevenzyang for the catch.

@coekie can you test version `2.20.68` or greater and see if the problem still persists?

**Comment by coekie** [comment]
Indeed, #4009 describes exactly this problem.
I've tested with version 2.20.116, and I cannot reproduce the problem anymore.
Thank you!
