### ISSUE TITLE
S3TransferManager.upload can hang indefinitely on certain exceptions

### ISSUE THREAD

**Issue by alexwlchan** [aws/aws-sdk-java-v2#3693]
### Describe the bug

I'm trying to upload an InputStream using S3TransferManager, but when I call `S3TransferManager.upload(…).completionFuture().join()`, I've found that some exceptions can cause this to hang indefinitely, blocking the rest of the program.

(It's possible this is a bug in my code, because I don't understand Java concurrency super well and I couldn't find sample code, but flagging just in case.)

### Expected Behavior

The future completes and throws an exception.

### Current Behavior

The future hangs, and the program never continues.

## Sample program #​1

I've found several programs that exhibit this behaviour; this is the smallest example that I've found.

I'm trying to upload an InputStream to a bucket using an S3TransferManager, but I'm addressing the bucket incorrectly. I see an S3Exception get logged, but the program never completes – there's a `print "Done!"` at the bottom which never runs.

```java
package example;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.concurrent.Executors;
import software.amazon.awssdk.core.async.AsyncRequestBody;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;
import software.amazon.awssdk.transfer.s3.S3TransferManager;
import software.amazon.awssdk.transfer.s3.model.CompletedUpload;
import software.amazon.awssdk.transfer.s3.model.UploadRequest;

public class Example {
  public static void main(String[] args) {
    String bucketName = "doesnotexist";
    String key = "example.bin";

    S3TransferManager transferManager = S3TransferManager.builder().build();

    InputStream byteArrayInputStream = new ByteArrayInputStream("Hello world!".getBytes());

    PutObjectRequest putObjectRequest =
      PutObjectRequest.builder()
        .bucket(bucketName)
        .key(key)
        .contentLength(1L)
        .build();

    ExecutorService executorService = Executors.newSingleThreadExecutor();

    AsyncRequestBody asyncRequestBody =
      AsyncRequestBody.fromInputStream(
        byteArrayInputStream,
        1L,
        Executors.newSingleThreadExecutor()
      );

    UploadRequest uploadRequest =
      UploadRequest.builder()
        .putObjectRequest(putObjectRequest)
        .requestBody(asyncRequestBody)
        .build();

    CompletedUpload completedUpload =
      transferManager
        .upload(uploadRequest)
        .completionFuture()
        .join();

    System.out.println("Done!");
  }
}
```

<details><summary>pom.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>net.alexwlchan</groupId>
  <artifactId>s3-transfer-manager-v2-repro</artifactId>
  <packaging>jar</packaging>
  <version>1.0.0</version>

  <!-- https://spring.io/guides/gs/maven/ -->
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.2.4</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer
                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>example.Example</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <!-- https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html -->
  <properties>
    <aws.sdk.version>2.19.16</aws.sdk.version>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>${aws.sdk.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>s3-transfer-manager</artifactId>
    </dependency>
    <dependency>
      <groupId>software.amazon.awssdk.crt</groupId>
      <artifactId>aws-crt</artifactId>
      <version>0.21.0</version>
    </dependency>
  </dependencies>
</project>
```

</details>

I'm running this with `mvn package; java -jar target/s3-transfer-manager-v2-repro-1.0.0.jar`.

When I run the code as above, I get an S3Exception "The bucket you are attempting to access…", but I never get to the "Done!" line. The program just hangs forever. I've included all the log output below:

<details><summary>Log output from <code>java -jar target/s3-transfer-manager-v2-repro-1.0.0.jar</code></summary>

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.S3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: S3, Status Code: 301, Request ID: 26HWJVH4MFC5JKQ1, Extended Request ID: 3nATiToRzqKPUwGaNgg/1zJZbUHHlnXEdWmHWist9WUi3z+M0VuxoZWab5n0BWN+h5qioVaONew=)
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:170)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: software.amazon.awssdk.services.s3.model.S3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: S3, Status Code: 301, Request ID: 26HWJVH4MFC5JKQ1, Extended Request ID: 3nATiToRzqKPUwGaNgg/1zJZbUHHlnXEdWmHWist9WUi3z+M0VuxoZWab5n0BWN+h5qioVaONew=)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:266)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:89)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:132)
	at software.amazon.awssdk.utils.async.SimplePublisher.doProcessQueue(SimplePublisher.java:275)
	at software.amazon.awssdk.utils.async.SimplePublisher.processEventQueue(SimplePublisher.java:224)
	at software.amazon.awssdk.utils.async.SimplePublisher.complete(SimplePublisher.java:157)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2010)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onErrorResponseComplete(S3CrtResponseHandlerAdapter.java:135)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:124)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:93)
	at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:24)
```

</details>

I get similar hanging behaviour if I change the bucket name to something invalid (`invalid=bucket=name`) or a name which doesn't exist (`doesnotexist-2023-01-13`). I get a different S3Exception each time, but both exhibit the same hanging behaviour.

## Sample program #​2

This is a little closer to the real-world example where I originally encountered this error. In this case, the InputStream we're uploading throws an EOFException while being read. The exception gets 

```java
package example;

import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.EOFException;
import java.io.InputStream;
import java.io.IOException;
import java.util.concurrent.Executors;
import software.amazon.awssdk.core.async.AsyncRequestBody;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;
import software.amazon.awssdk.transfer.s3.S3TransferManager;
import software.amazon.awssdk.transfer.s3.model.CompletedUpload;
import software.amazon.awssdk.transfer.s3.model.UploadRequest;

public class Example {
  public static void main(String[] args) {
    String bucketName = "wellcomecollection-platform-infra";
    String key = "alex/example.bin";
    String filePath = "README.md";

    S3TransferManager transferManager = S3TransferManager.builder().build();

    InputStream byteArrayInputStream = new ByteArrayInputStream("Hello world!".getBytes());
    InputStream inputStream = new BufferedInputStream(byteArrayInputStream) {
      public int read(byte b[], int off, int len) throws IOException {
        throw new EOFException(null);
      }
    };

    PutObjectRequest putObjectRequest =
      PutObjectRequest.builder()
        .bucket(bucketName)
        .key(key)
        .contentLength(1L)
        .build();

    AsyncRequestBody asyncRequestBody =
      AsyncRequestBody.fromInputStream(
        inputStream,
        1L,
        Executors.newSingleThreadExecutor()
      );

    UploadRequest uploadRequest =
      UploadRequest.builder()
        .putObjectRequest(putObjectRequest)
        .requestBody(asyncRequestBody)
        .build();

    CompletedUpload completedUpload =
      transferManager
        .upload(uploadRequest)
        .completionFuture()
        .join();

    System.out.println("Done!");
  }
}
```

</details>
<details><summary>Log output from <code>java -jar target/s3-transfer-manager-v2-repro-1.0.0.jar</code></summary>

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "Thread-1" java.io.UncheckedIOException: java.io.EOFException
	at software.amazon.awssdk.utils.async.StoringSubscriber$Event.runtimeError(StoringSubscriber.java:181)
	at software.amazon.awssdk.utils.async.ByteBufferStoringSubscriber.transferTo(ByteBufferStoringSubscriber.java:112)
	at software.amazon.awssdk.utils.async.ByteBufferStoringSubscriber.blockingTransferTo(ByteBufferStoringSubscriber.java:134)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtRequestBodyStreamAdapter.sendRequestBody(S3CrtRequestBodyStreamAdapter.java:43)
Caused by: java.io.EOFException
	at example.Example$1.read(Example.java:26)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at software.amazon.awssdk.core.internal.io.SdkLengthAwareInputStream.read(SdkLengthAwareInputStream.java:65)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at software.amazon.awssdk.utils.async.InputStreamConsumingPublisher.doBlockingWrite(InputStreamConsumingPublisher.java:55)
	at software.amazon.awssdk.core.async.BlockingInputStreamAsyncRequestBody.writeInputStream(BlockingInputStreamAsyncRequestBody.java:76)
	at software.amazon.awssdk.core.internal.async.InputStreamWithExecutorAsyncRequestBody.doBlockingWrite(InputStreamWithExecutorAsyncRequestBody.java:108)
	at software.amazon.awssdk.core.internal.async.InputStreamWithExecutorAsyncRequestBody.lambda$subscribe$0(InputStreamWithExecutorAsyncRequestBody.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: A callback has reported failure.
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:165)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: A callback has reported failure.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:127)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:93)
	at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:24)
```

</details>

### Possible Solution

Per above, it's possible this is my mistake; I'm not super familiar with Java concurrency and ExecutorService stuff.

## Original context / sample program #​3

I originally encountered this bug in a Scala test.

We have an app that receives a compressed tar.gz archive which contains multiple files. The app is meant to extract the files and upload them as individual objects to S3.

One of our tests includes a deliberately truncated archive which cannot be successfully read ([truncated_header.tar.gz](https://github.com/aws/aws-sdk-java-v2/files/10415995/truncated_header.tar.gz)), and this causes an EOFException to be thrown. The test verifies that the app notices the failure, and reports an appropriate error to the user (*"please upload a fixed file"*).

This test was originally written against the AWS Java V1 SDK, and passed. When I upgraded the app to the Java V2 SDK, it started hanging. When left to run in CI, this test ran for 1d18h before manually stopped.

It's a bit more complicated because it involves a round of decompression/unarchiving before hitting the S3 code, which is why I tried to minimise a bit further to get the examples above, but I include this in case it's useful context.

<details><summary>Scala test</summary>

```scala
package weco.storage_service.bag_unpacker.services.s3

import grizzled.slf4j.Logging
import org.apache.commons.compress.archivers.{ArchiveEntry, ArchiveStreamFactory}
import org.apache.commons.compress.compressors.CompressorStreamFactory
import org.scalatest.funspec.AnyFunSpec
import org.scalatest.matchers.should.Matchers
import software.amazon.awssdk.auth.credentials.{AwsBasicCredentials, StaticCredentialsProvider}
import software.amazon.awssdk.core.async.AsyncRequestBody
import software.amazon.awssdk.services.s3.S3AsyncClient
import software.amazon.awssdk.services.s3.model.PutObjectRequest
import software.amazon.awssdk.transfer.s3.S3TransferManager
import software.amazon.awssdk.transfer.s3.model.UploadRequest

import java.io._
import java.net.URI
import java.util.concurrent.Executors
import scala.util.Try

class S3UnpackerTest extends AnyFunSpec with Matchers with Logging {
  it("fails if there's an error parsing the header") {
    val s3AsyncClient =
      S3AsyncClient.builder()
        .credentialsProvider(
          StaticCredentialsProvider.create(
            AwsBasicCredentials.create("accessKey1", "verySecretKey1"))
        )
        .forcePathStyle(true)
        .endpointOverride(new URI("http://localhost:33333"))
        .build()

    implicit val s3TransferManager: S3TransferManager =
      S3TransferManager.builder()
        .s3Client(s3AsyncClient)
        .build()

    val dstBucket = "vzaqvsenz5ftmvp"

    val result = Try {
      // This file was created with the following bash script:
      //
      //    for i in 1 2 3 4 5 6 7 8 9 10
      //    do
      //      dd if=/dev/urandom bs=8192 count=1 > "$i.bin"
      //    done
      //
      //    tar -cvf truncated_header.tar *.bin
      //    gzip truncated_header.tar
      //    python3 -c 'import os; os.truncate("truncated_header.tar.gz", 80000)'
      //
      // I found this particular error path by accident while trying to write
      // a regression test for https://github.com/wellcomecollection/platform/issues/4911
      //

      val uncompressedStream =
        new CompressorStreamFactory().createCompressorInputStream(getClass.getResourceAsStream("/truncated_header.tar.gz"))

      val archiveInputStream =
        new ArchiveStreamFactory()
          .createArchiveInputStream(new BufferedInputStream(uncompressedStream))

      val iterator = new Iterator[(ArchiveEntry, InputStream)] {
        private var latest: ArchiveEntry = _

        override def hasNext: Boolean = {
          latest = archiveInputStream.getNextEntry
          latest != null
        }

        override def next(): (ArchiveEntry, InputStream) =
          (latest, archiveInputStream)
      }

      iterator
        .foreach {
          case (archiveEntry, entryStream) =>
            val name = archiveEntry.getName
            val archiveEntrySize = archiveEntry.getSize

            debug(s"Uploading archive entry $name to s3://$dstBucket/$name ($archiveEntrySize bytes)")

            val putRequest =
              PutObjectRequest
                .builder()
                .bucket(dstBucket)
                .key(name)
                .contentLength(archiveEntrySize)
                .build()

            val requestBody =
              AsyncRequestBody.fromInputStream(
                entryStream,
                archiveEntrySize,
                Executors.newSingleThreadExecutor()
              )

            val uploadRequest =
              UploadRequest
                .builder()
                .putObjectRequest(putRequest)
                .requestBody(requestBody)
                .build()

            s3TransferManager
              .upload(uploadRequest)
              .completionFuture()
              .join()
        }
    }

    println(result)
  }
}
```

</details>

Couple of notes:

* This test runs against a Docker image which is simulating S3, rather than S3 proper. I haven't tested this program against S3 directly, but I did test the two Java examples against S3 proper.
* I have debug logs from this test, but they're too long to fit in a comment – I've stuck them in a Gist instead: https://gist.github.com/alexwlchan/d5b9e14efd2be6b0973324beb9a95183

### AWS Java SDK version used

2.19.16

### JDK version used

openjdk version "1.8.0_121" OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13) OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

### Operating System and version

I was using the maven:3.3-jdk-8 Docker image, which looks like Debian 8.7

**Comment by zoewangg** [comment]
Hi @alexwlchan, this is one of best bug reports I've ever seen! :) Thank you for providing the detailed information along with standalone repro cases, which helped me reproduce the issues easily.

For problem 1, I tried with the standard client `S3AsyncClient.builder().build()` with the same request and was able to reproduce the issue, so the bug is probably somewhere in the SDK core. I suspect it's in `AsyncRequestBody.fromInputStream` because `AsyncRequestBody.fromBytes("hello world".getBytes())` seems to be working fine. 

Problem 2 and problem 1 seem to be related; we are not handling exceptions elegantly with `AsyncRequestBody#fromInputStream`.

I'll work on the fix. Thanks again for reporting the issues!

**Comment by zoewangg** [comment]
Hi @alexwlchan, actually, I think the futures were completed exceptionally correctly. The reason the program did not terminate is because the ExecutorService `Executors.newSingleThreadExecutor()`(non-daemon thread) you passed to `AsyncRequestBody.fromInputStream` was not shut down, so it prevented JVM from exiting.

**Comment by alexwlchan** [comment]
> The reason the program did not terminate is because the ExecutorService `Executors.newSingleThreadExecutor()` (non-daemon thread) you passed to `AsyncRequestBody.fromInputStream` was not shut down, so it prevented JVM from exiting.

Thanks for investigating – your assessment looks correct. Like I said, I’m not super familiar with this aspect of Java, so sorry for the confusion. I’ll close this issue now, as it’s clearly not an SDK bug. (I thought I'd tested an example where I explicitly called the `.shutdown()` method on the ExecutorService, but testing it again I see the correct behaviour. I guess my earlier test was wrong.)

In case it's helpful in guiding other people away from this mistake, I got here by looking at the only example of AsyncRequestBody.fromInputStream in the tests: https://github.com/aws/aws-sdk-java-v2/blob/f3684fc240570d8d13f6ac0af473bfbea4cf9cf8/test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/BlockingAsyncRequestResponseBodyTest.java#L81-L83
