### ISSUE TITLE
S3 Transfer Manager host/endpoint mismatch

### ISSUE THREAD

**Issue by bt-wil** [aws/aws-sdk-java-v2#3721]
### Describe the bug

I'm using localstack and notice that changing the `endpointOverride` causes failures with transfer with message:
```
Cannot create meta s3 request; host header value a.b.c.d does not match endpoint override a.b.c.d:4566
```

### Expected Behavior

S3 Transfer Manager should work.

### Current Behavior

Library:
```
s3-transfer-manager v2.19.25
aws-crt v0.21.2
```

Error:
```
Exception in thread "main" java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: S3Client.aws_s3_client_make_meta_request: creating aws_s3_meta_request failed (aws_last_error: AWS_ERROR_INVALID_ARGUMENT(34), An invalid argument was passed to a function.)
    at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
...
    at software.amazon.awssdk.transfer.s3.S3TransferManager.upload(S3TransferManager.java:447)
    at org.example.TransferBug.main(TransferBug.java:31)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: S3Client.aws_s3_client_make_meta_request: creating aws_s3_meta_request failed (aws_last_error: AWS_ERROR_INVALID_ARGUMENT(34), An invalid argument was passed to a function.)
    at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
    at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
...
    at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.execute(AsyncExecutionFailureExceptionReportingStage.java:41)
    ... 18 more
Caused by: software.amazon.awssdk.crt.CrtRuntimeException: S3Client.aws_s3_client_make_meta_request: creating aws_s3_meta_request failed (aws_last_error: AWS_ERROR_INVALID_ARGUMENT(34), An invalid argument was passed to a function.) AWS_ERROR_INVALID_ARGUMENT(34)
    at software.amazon.awssdk.crt.s3.S3Client.s3ClientMakeMetaRequest(Native Method)
    at software.amazon.awssdk.crt.s3.S3Client.makeMetaRequest(S3Client.java:79)
...
    at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.attemptExecute(AsyncRetryableStage.java:144)
    ... 25 more
```

I've tried various endpoint, and got the same result:
```
[ERROR] [2023-01-27T03:21:10Z] [000000016b70b000] [S3Client] - id=0x121f0f010 Cannot create meta s3 request; host header value 127.0.0.1 does not match endpoint override 127.0.0.1:4566
```

```
[ERROR] [2023-01-27T03:21:27Z] [000000016d0e7000] [S3Client] - id=0x11ee09010 Cannot create meta s3 request; host header value fake-test-bucket.localhost does not match endpoint override fake-test-bucket.localhost:4566
```

```
[ERROR] [2023-01-27T03:21:49Z] [000000016b68f000] [S3Client] - id=0x142e0caa0 Cannot create meta s3 request; host header value fake-test-bucket.s3.localhost.localstack.cloud does not match endpoint override fake-test-bucket.s3.localhost.localstack.cloud:4566
```

### Reproduction Steps

Running the code on localstack throws the error.

```
package org.example;

import java.net.URI;

import software.amazon.awssdk.core.async.AsyncRequestBody;
import software.amazon.awssdk.crt.Log;
import software.amazon.awssdk.services.s3.S3AsyncClient;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;
import software.amazon.awssdk.transfer.s3.S3TransferManager;

public class TransferBug {
    public static void main(String... args) {
        Log.initLoggingToFile(Log.LogLevel.Error, "file-output.txt");

        var endpoint = "http://s3.localhost.localstack.cloud:4566";
        var bucket = "fake-test-bucket";
        var key = "test.txt";

        var client = S3AsyncClient.crtBuilder()
                .endpointOverride(URI.create(endpoint))
                .build();

        try (var s3TransferManager = S3TransferManager.builder()
                .s3Client(client)
                .build()
        ) {
            var putRequest = PutObjectRequest.builder()
                    .bucket(bucket).key(key)
                    .build();

            var upload = s3TransferManager.upload(b -> b.putObjectRequest(putRequest)
                    .requestBody(AsyncRequestBody.fromString("test")));

            upload.completionFuture().join();
        }
    }
}
```

docker-compose.yaml
```
services:
  # https://github.com/localstack/localstack/blob/v1.3.1/docker-compose.yml
  localstack:
    image: localstack/localstack:1.3.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Possible Solution

I downgraded `aws-crt` to `v0.21.1`, and it works for some endpoints.

* `s3.localhost.localstack.cloud` => works
* `127.0.0.1` => works
* `localhost` => fails, likely due to missing `pathStyleAccessEnabled`

The issue appears to be caused by https://github.com/awslabs/aws-crt-java/pull/581, and not sure if it is intentional.

### AWS Java SDK version used

2.19.25

### JDK version used

openjdk version "17.0.4" 2022-07-19 LTS; OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)

### Operating System and version

MacOS 12.6 (Monterey)

**Comment by michaeljohnalbers** [comment]
I'm seeing the same issue when simply using the `S3AsyncClient` (with CRT) to create a bucket with localstack.

**Comment by debora-ito** [comment]
Related to https://github.com/aws/aws-sdk-java-v2/issues/3682.
