### ISSUE TITLE
AWS S3 connections get broken shortly

### ISSUE THREAD

**Issue by bvn13** [aws/aws-sdk-java-v2#3736]
### Describe the bug

I face this exception every time I try to download a file:

```
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 13,425,689; received: 7,896)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135) ~[httpclient-4.5.14.jar:4.5.14]
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132) ~[na:na]
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132) ~[na:na]
	at software.amazon.awssdk.core.io.SdkFilterInputStream.read(SdkFilterInputStream.java:66) ~[sdk-core-2.19.7.jar:na]
	at java.base/java.io.InputStream.transferTo(InputStream.java:782) ~[na:na]
```

Using AWS Java SDK with SpringBoot in order to download to local file:

```java
        final File file = File.createTempFile(fileUid, "");
        log.info("Staring to download file from AWS: {}, {}", fileUid, fileModel.getPath());
        try (final OutputStream os = new FileOutputStream(file);
             final InputStream is = awsS3BucketFacade.getFile(fileModel.getPath())) {
            is.transferTo(os);
        } catch (NoSuchKeyException e) {
            throw new FileNotFoundException(fileUid);
        }
```

```java
class AwsS3ClientFactory {
    private final AwsS3Properties properties;
    private final AwsS3Config awsS3Config;

    private final AtomicReference<S3Client> s3Client = new AtomicReference<>();

    public S3Client createClient() {
        if (s3Client.get() == null) {
            synchronized (s3Client) {
                if (s3Client.get() == null) {
                    s3Client.set(S3Client.builder()
                            .endpointOverride(awsS3Config.getAwsServerUri())
                            .forcePathStyle(true)
                            .region(Region.of(properties.getServer().getRegion()))
                            .credentialsProvider(() ->
                                    new AwsCredentials() {
                                        @Override
                                        public String accessKeyId() {
                                            return properties.getAccess().getKeyId();
                                        }

                                        @Override
                                        public String secretAccessKey() {
                                            return properties.getAccess().getSecret();
                                        }
                                    })
                            .build());
                }
            }
        }
        return s3Client.get();
    }

}
```

```java
public class AwsS3BucketFacade implements FileStorageManager {
    private final AwsS3ClientFactory clientFactory;
    private final AwsS3Properties properties;

    public InputStream getFile(String filePath) {
        try (final S3Client s3Client = clientFactory.createClient()) {
            final GetObjectRequest request = GetObjectRequest.builder()
                    .bucket(properties.getBucketName())
                    .key(filePath)
                    .build();
            return s3Client.getObject(request, ResponseTransformer.toInputStream());
        }
    }
}
```

### Expected Behavior

no exception

### Current Behavior

exception

### Reproduction Steps

see above

### AWS Java SDK version used

implementation "software.amazon.awssdk:s3:2.19.7"

### JDK version used

Oracle OpenJDK 17.0.2 

### Operating System and version

Fedora Linux 37 (Workstation Edition)

**Comment by debora-ito** [comment]
@bvn13 apologies for the delay in replying here.

> org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body

The error indicates that the connection from the server was closed before the entire response could be read. The SDK will not close connections when requests are in flight. Make sure nothing in your application or your environment is unexpectedly closing the connection or the client.
