### ISSUE TITLE
Configured Request Timeouts Are Not Honored

### ISSUE THREAD

**Issue by dasmowenator** [aws/aws-sdk-java-v2#3763]
### Describe the bug

I've created an SDK client using the `DefaultsMode.IN_REGION` configuration, which [as can be seen here](https://github.com/aws/aws-sdk-java-v2/blob/master/codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/defaultsmode/defaults-mode-configuration.java) should set the connection timeout to 1000 milliseconds:

```
EcsClient ecs = EcsClient.builder()
    .credentialsProvider(credentialsProvider)
    .region(Region.of(region))
    .httpClient(UrlConnectionHttpClient.builder().build())
    .defaultsMode(DefaultsMode.IN_REGION)
    .build();
```

However, I see cases in our logs where requests aren't timing out for 60+ seconds!

### Expected Behavior

The request should timeout and retry after ~1000 ms.

### Current Behavior

Here's an example request using this client which didn't timeout for about **90 seconds**:

```
2023-02-15T01:04:44,039 [INFO] com.mypackage.MyClass: Calling ECS DescribeTaskDefinition...
2023-02-15T01:05:14,104 [DEBUG] software.amazon.awssdk.request: Retryable error detected. Will retry in 5ms. Request attempt number 2
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Read timed out
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:223) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:83) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56) ~[AwsJavaSdk-Core-AwsCore-2.0.jar:?]
        at software.amazon.awssdk.services.ecs.DefaultEcsClient.describeTaskDefinition(DefaultEcsClient.java:1511) ~[AwsJavaSdk-Ecs-2.0.jar:?]
        at com.mypackage.MyClass.fetchTaskDefinition(MyClass.java:293) ~[MyPackage-1.0.jar:?]
Caused by: javax.net.ssl.SSLException: Read timed out
        at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:1.8.0_362]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[?:1.8.0_362]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:1.8.0_362]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[?:1.8.0_362]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:138) ~[?:1.8.0_362]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397) ~[?:1.8.0_362]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305) ~[?:1.8.0_362]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440) ~[?:1.8.0_362]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_362]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197) ~[?:1.8.0_362]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167) ~[?:1.8.0_362]
        at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:291) ~[AwsJavaSdk-HttpClient-UrlConnectionClient-2.0.jar:?]
        at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:269) ~[AwsJavaSdk-HttpClient-UrlConnectionClient-2.0.jar:?]
        at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:63) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:77) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:56) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81) ~[AwsJavaSdk-Core-2.0.jar:?]
        ... 40 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_362]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_362]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_362]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_362]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464) ~[?:1.8.0_362]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165) ~[?:1.8.0_362]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109) ~[?:1.8.0_362]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397) ~[?:1.8.0_362]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305) ~[?:1.8.0_362]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440) ~[?:1.8.0_362]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_362]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197) ~[?:1.8.0_362]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167) ~[?:1.8.0_362]
        at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:291) ~[AwsJavaSdk-HttpClient-UrlConnectionClient-2.0.jar:?]
        at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:269) ~[AwsJavaSdk-HttpClient-UrlConnectionClient-2.0.jar:?]
        at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:63) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:77) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:56) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36) ~[AwsJavaSdk-Core-2.0.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81) ~[AwsJavaSdk-Core-2.0.jar:?]
        ... 40 more
2023-02-15T01:05:14,119 [DEBUG] software.amazon.awssdk.request: Retrying Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=ecs.us-east-1.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])
2023-02-15T01:05:14,172 [DEBUG] software.amazon.awssdk.request: Received successful response: 200, Request ID: cf0919b4-26bf-4b7f-9252-ff50e056cad0, Extended Request ID: not available
2023-02-15T01:05:14,257 [INFO] 2023-02-15T01:04:44,039 [INFO] com.mypackage.MyClass: ECS DescribeTaskDefinition completed successfully
```

### Reproduction Steps

This can be hard to reproduce because it only happens on one out of every several thousand requests, but it happens relatively frequently in our largest regions (a few times per hour).

### AWS Java SDK version used

2.0

### JDK version used

1.8.0_362

### Operating System and version

Amazon Linux 2

**Comment by zoewangg** [comment]
Hi @dasmowenator, could you try passing the HTTP client builder `.httpClientBuilder` instead? Connection timeout is configured on the HTTP client level. If you provide an HTTP client instance to the SDK client, it is not possible for the SDK to change the timeout.

```
EcsClient ecs = EcsClient.builder()
    .credentialsProvider(credentialsProvider)
    .region(Region.of(region))
    .httpClientBuilder(UrlConnectionHttpClient.builder())
    .defaultsMode(DefaultsMode.IN_REGION)
    .build();
```

**Comment by dasmowenator** [comment]
I @zoewangg, I just tried doing as you suggested, but experienced the same behavior -- the 1000 ms timeout wasn't honored.

**Comment by dasmowenator** [comment]
After talking with Zoe offline, there were a few conclusions we drew:

- Setting the connection and socket timeouts on the HTTP client itself solves the problem: `.httpClientBuilder(UrlConnectionHttpClient.builder().socketTimeout(Duration.ofSeconds(2)).connectionTimeout(Duration.ofSeconds(2)))`
- Setting the request timeout using the ApiCallAttemptTimeout also works, but it's not a great solution because this is just a best-effort attempt by the main thread to interrupt the connection, but it's not guaranteed to work or be efficient: `.overrideConfiguration(ClientOverrideConfiguration.builder().apiCallAttemptTimeout(Duration.ofSeconds(2)).build())`
- I should probably be using the `ApacheHttpClient` instead of the `UrlConnectionHttpClient` since `UrlConnectionHttpClient` is just recommended for Lambdas, but this is an EC2 application.  However, changing the client didn't fix/change this timeout behavior.
- The SDK doesn't have default socket timeouts configured in the `DefaultsMode` because it depends on each service API you're calling... there's a project to add service-specific defaults, but it's not implemented yet.  (Personally I find this to be a remarkable oversight, there are probably thousands of customers who are being intermittently affected by this issue and aren't even aware of it or don't know how to debug it.)
- The SDK's default socket timeout is 30 seconds, so it's unclear why my requested didn't timeout until 90 seconds.  The reason behind this is still unknown.

For now, I've got a path to fix my immediate problem, but it still seems like there are some underlying issues that might require further investigation and ought to be fixed.

**Comment by zoewangg** [comment]
I was not able to reproduce the issue. I tried to send requests with the default `UrlConnectionHttpClient` to a local mock server and stubbed 60-second server delay and the SDK threw socket timeout exception after 30 seconds.
