### ISSUE TITLE
Bucket name cannot contain  “." (dot)  when use Java V2 SDK

### ISSUE THREAD

**Issue by ydcode** [aws/aws-sdk-java-v2#382]
## General summary:
   Example Bucket Name:  "**sub.exampledomain.com**"
   this name contains dots.

1. AWS web ui create bucket  with "."(dot)  is ok. 
2. Java V2 sdk  create bucket with "."(dot)  is NOT ok.

## Expected Behavior
   Java V2 SDK create bucket,  bucket  name should can contain dot.

## Current Behavior

```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <testsubdomain.testdomain.com.s3-us-west-1.amazonaws.com> doesn't match any of the subject alternative names: [s3-us-west-1.amazonaws.com, *.s3-us-west-1.amazonaws.com, s3.us-west-1.amazonaws.com, *.s3.us-west-1.amazonaws.com, s3.dualstack.us-west-1.amazonaws.com, *.s3.dualstack.us-west-1.amazonaws.com, *.s3.amazonaws.com]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:467) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.3.jar:4.5.3]
	at software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory.connectSocket(SdkTlsSocketFactory.java:118) ~[apache-client-2.0.0-preview-7.jar:?]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at software.amazon.awssdk.http.apache.internal.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:78) ~[apache-client-2.0.0-preview-7.jar:?]
	at com.sun.proxy.$Proxy223.connect(Unknown Source) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar:4.5.3]
	at software.amazon.awssdk.http.apache.internal.impl.ApacheSdkClient.execute(ApacheSdkClient.java:70) ~[apache-client-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:90) ~[apache-client-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.http.apache.ApacheHttpClient.access$000(ApacheHttpClient.java:47) ~[apache-client-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:68) ~[apache-client-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:65) ~[apache-client-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:56) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:47) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:32) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:40) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:30) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:139) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:105) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:66) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:47) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.StreamManagingStage.execute(StreamManagingStage.java:55) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.StreamManagingStage.execute(StreamManagingStage.java:41) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.executeWithTimer(ClientExecutionTimedStage.java:71) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:55) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:39) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:35) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:24) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:281) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.doInvoke(SyncClientHandlerImpl.java:149) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.invoke(SyncClientHandlerImpl.java:131) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:100) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:76) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.core.client.SdkClientHandler.execute(SdkClientHandler.java:45) ~[core-2.0.0-preview-7.jar:?]
	at software.amazon.awssdk.services.s3.DefaultS3Client.createBucket(DefaultS3Client.java:493) ~[s3-2.0.0-preview-7.jar:?]

```

## Possible Solution

https://stackoverflow.com/questions/39762760/javax-net-ssl-sslexception-certificate-doesnt-match-any-of-the-subject-alterna

## Steps to Reproduce (for bugs)
```
bucket name contain dot,  like :    abcdxyz.domain.com
```
```
    public CreateBucketResponse createBucket(String bucketName) {
        CreateBucketRequest createBucketRequest = CreateBucketRequest
                .builder()
                .bucket(bucketName)
                .build();
        return s3Client.createBucket(createBucketRequest);
    }

```

## Your Environment
* AWS Java SDK version used:  2.0.0-preview-7
* JDK version used:  1.8.0_131
* Operating System and version:  CentOS 7

**Comment by spfink** [comment]
This problem is explained in the [s3 bucket restrictions doc](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html):

> When using virtual hosted–style buckets with SSL, the SSL wildcard certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic. We recommend that you do not use periods (".") in bucket names. 

Will discuss this with the team to see if we want to include mitigations for this in the SDK.

**Comment by ydcode** [comment]
Yeah, I see . Thank you!
