### ISSUE TITLE
Bug: CRT-based S3AsyncClient getObject with byte Range

### ISSUE THREAD

**Issue by JJRdec** [aws/aws-sdk-java-v2#3907]
### Describe the bug

I'm are trying to take advanced of CRT-based S3AsyncClient to improve proformance for one of our apps. https://aws.amazon.com/blogs/developer/introducing-crt-based-s3-client-and-the-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/

I want to download a byte range from a object stored in S3. 

Once I enabled CRT async client and try use getObject with a bytes range an error thrown.

**Gralde snippet:**
```
implementation 'software.amazon.awssdk.crt:aws-crt:0.21.10'
implementation 'software.amazon.awssdk:s3:2.20.44'
```

**Client config snippet:**
```
S3AsyncClient s3Client = S3AsyncClient
        .crtBuilder()
        .credentialsProvider(StaticCredentialsProvider.create(credentials))
        .forcePathStyle(true)
        .endpointOverride(new URI(endpoint))
        .region(region)
        .targetThroughputInGbps(20.0)
        .build();
```

**GetObject snippet:**
```
GetObjectRequest getObjectRequest = GetObjectRequest.builder()
        .bucket(bucketName)
        .key(key)
        .build();

byte [] fileBytes = s3Client.getObject(getObjectRequest, AsyncResponseTransformer.toBytes())
        .thenApply(ResponseBytes::asByteArray)
        .join();
```

### Expected Behavior

Return the byte range from the object.

### Current Behavior

**Error thrown:**
```
software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: Response missing required Content-Range header.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[deciphex-tiff-parser-1.0.3.jar:unspecified]
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43) ~[deciphex-tiff-parser-1.0.3.jar:unspecified]
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:127) ~[deciphex-tiff-parser-1.0.3.jar:unspecified]
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:93) ~[deciphex-tiff-parser-1.0.3.jar:unspecified]
	at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:24) ~[deciphex-tiff-parser-1.0.3.jar:unspecified]

```

### Reproduction Steps

1. Import dependencies (SDK & aws-crt)
2. Setup CRT-based S3AsyncClient as shown
3. Make a getObject request with a byte range specified

### AWS Java SDK version used

2.20.44

### JDK version used

17.0.3

### Operating System and version

Windows

**Comment by debora-ito** [comment]
I see you are overriding the endpoint in the s3 client, are you using a third-party solution?

``` 
       .endpointOverride(new URI(endpoint))
```
