### ISSUE TITLE
NullPointerException in AbstractChannelHandlerContext

### ISSUE THREAD

**Issue by steven-sheehy** [aws/aws-sdk-java-v2#3909]
### Describe the bug

Get a NPE when concurrent threads list S3 and get files and S3 potentially rate limits or times out some threads.

```console
2023-04-13T06:23:49.365323086Z stdout F 2023-04-13T00:23:49.365-0600 WARN aws-java-sdk-NettyEventLoop-0-6 s.a.a.h.n.n.i.FutureCancelHandler [Channel: 33859f6c] Received a cancellation exception on a channel that doesn't have an execution Id attached. Exception's execution ID is null. Exception is being ignored. Closing the channel |  
-- | --
  |   | 2023-04-13 01:23:49.442 | 2023-04-13T06:23:49.410123343Z stdout F 2023-04-13T00:23:49.396-0600 WARN aws-java-sdk-NettyEventLoop-0-6 i.n.c.AbstractChannelHandlerContext An exception 'java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.http.nio.netty.internal.RequestContext.channelPool()" because "requestContext" is null' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception: software.amazon.awssdk.http.nio.netty.internal.FutureCancelledException: java.util.concurrent.CancellationException\\n	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.lambda$null$3(NettyRequestExecutor.java:136)\\n	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)\\n	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)\\n	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)\\n	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)\\n	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)\\n	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)\\n	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\\n	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\\n	at java.base/java.lang.Thread.run(Unknown Source)\\nCaused by: java.util.concurrent.CancellationException\\n	at java.base/java.util.concurrent.CompletableFuture.cancel(Unknown Source)\\n	at reactor.core.publisher.MonoCompletionStage$1.cancel(MonoCompletionStage.java:60)\\n	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.cancel(FluxMapFuseable.java:176)\\n	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2254)\\n	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2222)\\n	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2034)\\n	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.cancel(FluxTimeout.java:251)\\n	at reactor.core.publisher.SerializedSubscriber.cancel(SerializedSubscriber.java:157)\\n	at reactor.core.publisher.SerializedSubscriber.cancel(SerializedSubscriber.java:157)\\n	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2254)\\n	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2222)\\n	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2034)\\n	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:144)\\n	at reactor.core.publisher.Operators.set(Operators.java:1197)\\n	at reactor.core.publisher.FluxMergeSequential$MergeSequentialInner.cancel(FluxMergeSequential.java:601)\\n	at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.cancelAll(FluxMergeSequential.java:290)\\n	at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.drain(FluxMergeSequential.java:394)\\n	at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.innerError(FluxMergeSequential.java:319)\\n	at reactor.core.publisher.FluxMergeSequential$MergeSequentialInner.onError(FluxMergeSequential.java:579)\\n	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)\\n	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)\\n	at reactor.core.publisher.Operators.error(Operators.java:198)\\n	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)\\n	at reactor.core.publisher.Mono.subscribe(Mono.java:4490)\\n	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)\\n	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)\\n	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)\\n	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219)\\n	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)\\n	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:90)\\n	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)\\n	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)\\n	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)\\n	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:54)\\n	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)\\n	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:67)\\n	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)\\n	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)\\n	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)\\n	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)\\n	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)\\n	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)\\n	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)\\n	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)\\n	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)\\n	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)\\n	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)\\n	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:165)\\n	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\\n	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)\\n	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\\n	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\\n	... 1 more
```

### Expected Behavior

No stacktrace

### Current Behavior

NPE stacktrace

### Reproduction Steps

Not sure. Our app just does a S3 list followed by multiple gets.

### AWS Java SDK version used

2.20.37

### JDK version used

temurin 17.0.6

### Operating System and version

Linux

**Comment by debora-ito** [comment]
Can you share a sample code we can use to reproduce?
Without a reproducible code is hard to investigate possible causes.

**Comment by steven-sheehy** [comment]
The [code](https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/S3StreamFileProvider.java) is all open source, but I doubt seeing it will help much. I don't know how to reproduce the problem, it happens sporadically.

**Comment by debora-ito** [comment]
Does the error occur with `listObjectsV2` or `getObject`?
Do you see any pattern in the objects?
I'm also wondering if the NullPointerException is related to the use of Reactor...

**Comment by debora-ito** [comment]
Marking to auto close soon.

**Comment by gregsh** [comment]
I also see this exception couple of times a week on version `2.28.2`.

Happens more likely on a high load.


```
08:06:32]	08:06:32.536 [aws-java-sdk-NettyEventLoop-0-9] WARN io.netty.channel.AbstractChannelHandlerContext -- An exception 'java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.http.nio.netty.internal.RequestContext.channelPool()" because "requestContext" is null' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
[08:06:32]	software.amazon.awssdk.http.nio.netty.internal.FutureCancelledException: java.util.concurrent.CancellationException
[08:06:32]		at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.lambda$createExecutionFuture$3(NettyRequestExecutor.java:135)
[08:06:32]		at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
[08:06:32]		at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
[08:06:32]		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[08:06:32]		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[08:06:32]		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[08:06:32]		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[08:06:32]		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
[08:06:32]		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:06:32]		at java.base/java.lang.Thread.run(Thread.java:840)
[08:06:32]	Caused by: java.util.concurrent.CancellationException: null
[08:06:32]		at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
[08:06:32]		at kotlinx.coroutines.future.FutureKt$await$2$1.invoke(Future.kt:172)
[08:06:32]		at kotlinx.coroutines.future.FutureKt$await$2$1.invoke(Future.kt:171)
[08:06:32]		at kotlinx.coroutines.CancelHandler$UserSupplied.invoke(CancellableContinuationImpl.kt:667)
[08:06:32]		at kotlinx.coroutines.CancellableContinuationImpl.callCancelHandler(CancellableContinuationImpl.kt:239)
[08:06:32]		at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:209)
[08:06:32]		at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:221)
[08:06:32]		at kotlinx.coroutines.ChildContinuation.invoke(CancellableContinuationImpl.kt:696)
[08:06:32]		at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1603)
[08:06:32]		at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:826)
[08:06:32]		at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:786)
[08:06:32]		at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:702)
[08:06:32]		at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:668)
[08:06:32]		at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1578)
[08:06:32]		at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1603)
[08:06:32]		at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:826)
[08:06:32]		at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:786)
[08:06:32]		at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:702)
[08:06:32]		at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:668)
[08:06:32]		at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1578)
[08:06:32]		at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1603)
[08:06:32]		at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:826)
[08:06:32]		at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:786)
[08:06:32]		at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:702)
[08:06:32]		at kotlinx.coroutines.JobSupport.childCancelled(JobSupport.kt:682)
[08:06:32]		at kotlinx.coroutines.ChildHandleNode.childCancelled(JobSupport.kt:1579)
[08:06:32]		at kotlinx.coroutines.JobSupport.cancelParent(JobSupport.kt:352)
[08:06:32]		at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:326)
[08:06:32]		at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:931)
[08:06:32]		at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:894)
[08:06:32]		at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:859)
[08:06:32]		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:98)
[08:06:32]		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
[08:06:32]		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
[08:06:32]		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
[08:06:32]		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:816)
[08:06:32]		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
[08:06:32]		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```
