### ISSUE TITLE
NoSuchMethodError when using SQS async client

### ISSUE THREAD

**Issue by nadavamami** [aws/aws-sdk-java-v2#394]
When trying to send batch request using the async client an exception NoSuchMethodError is thrown:

Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 2015.0 failed 1 times, most recent failure: Lost task 1.0 in stage 2015.0 (TID 8013, localhost): java.lang.NoSuchMethodError: io.netty.handler.codec.http.DefaultHttpRequest.<init>(Lio/netty/handler/codec/http/HttpVersion;Lio/netty/handler/codec/http/HttpMethod;Ljava/lang/String;Lio/netty/handler/codec/http/HttpHeaders;)V
	at software.amazon.awssdk.http.nio.netty.internal.RequestAdapter.adapt(RequestAdapter.java:33)
	at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient.prepareRequest(NettyNioAsyncHttpClient.java:100)
	at software.amazon.awssdk.core.http.pipeline.stages.MakeAsyncHttpRequestStage.executeHttpRequest(MakeAsyncHttpRequestStage.java:85)
	at software.amazon.awssdk.core.http.pipeline.stages.MakeAsyncHttpRequestStage.execute(MakeAsyncHttpRequestStage.java:70)
	at software.amazon.awssdk.core.http.pipeline.stages.MakeAsyncHttpRequestStage.execute(MakeAsyncHttpRequestStage.java:46)
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.doExecute(AsyncRetryableStage.java:164)
	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:111)
	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:105)
	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:68)
	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:47)
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
	at software.amazon.awssdk.core.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:239)
	at software.amazon.awssdk.core.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.execute(AsyncExecutionFailureExceptionReportingStage.java:36)
	at software.amazon.awssdk.core.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.execute(AsyncExecutionFailureExceptionReportingStage.java:25)
	at software.amazon.awssdk.core.http.AmazonAsyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonAsyncHttpClient.java:208)
	at software.amazon.awssdk.core.client.AsyncClientHandlerImpl.doInvoke(AsyncClientHandlerImpl.java:220)
	at software.amazon.awssdk.core.client.AsyncClientHandlerImpl.invoke(AsyncClientHandlerImpl.java:199)
	at software.amazon.awssdk.core.client.AsyncClientHandlerImpl.execute(AsyncClientHandlerImpl.java:142)
	at software.amazon.awssdk.core.client.AsyncClientHandlerImpl.execute(AsyncClientHandlerImpl.java:77)
	at software.amazon.awssdk.core.client.SdkAsyncClientHandler.execute(SdkAsyncClientHandler.java:46)
	at software.amazon.awssdk.services.sqs.DefaultSQSAsyncClient.sendMessageBatch(DefaultSQSAsyncClient.java:1177)
	at com.simpool.simulator.functions.WriteDbFunction.call(WriteDbFunction.java:95)
	at com.simpool.simulator.functions.WriteDbFunction.call(WriteDbFunction.java:36)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:218)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:218)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:883)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:883)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1897)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1897)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

when looking in the sources seems that the DefaultHttpRequest expects a bollean validateHeaders however the RequestAdapter in software.amazon.awssdk.http.nio.netty.internal is creating the request with HttpHeaders instead so the creation fails.

i am using the 2.0.0-preview-7 version.

Thanks,
Nadav

**Comment by millems** [comment]
Could you let us know which version of netty is on your classpath?

**Comment by nadavamami** [comment]
the netty version  is 3.8.0.final, but there are other netty components that are from version 4.1.17.final, it comes as a dependency of the aws sdk verson 2.0.0-preview-7 i use

**Comment by zoewangg** [comment]
@nadavamami Apologies for the long delay, are you still seeing this issue? Can you try with the latest SDK version?

**Comment by zoewangg** [comment]
Closing due to no response. Feel free to reopen if you continue to see the issue with the latest SDK version.
