### ISSUE TITLE
listobject throw NullPointerException: host must not be null

### ISSUE THREAD

**Issue by wlscu** [aws/aws-sdk-java-v2#3987]
### Describe the bug

When I use aws-sdk-v2 to list objects, if the bucket name contains dots(.), a null pointer exception is thrown, indicating that host must not be null.

### Expected Behavior

When I use aws-sdk-v2 to list objects, if the bucket name contains dots(.), a null pointer exception is thrown, indicating that host must not be null. But when I use aws-sdk-v1 to list objects, when bucket names contain dots(.), the objects can be listed normally.

### Current Behavior

java.lang.NullPointerException: host must not be null.
	at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:156)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:56)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:44)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:482)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:250)
	at software.amazon.awssdk.services.s3.endpoints.internal.AwsEndpointProviderUtils.setUri(AwsEndpointProviderUtils.java:178)
	at software.amazon.awssdk.services.s3.endpoints.internal.S3RequestSetEndpointInterceptor.modifyHttpRequest(S3RequestSetEndpointInterceptor.java:35)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyHttpRequestAndHttpContent(ExecutionInterceptorChain.java:90)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.runModifyHttpRequestAndHttpContentInterceptors(BaseClientHandler.java:157)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:83)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:151)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.s3.DefaultS3Client.listObjects(DefaultS3Client.java:6340)

### Reproduction Steps

        S3Client s3Client = S3Client.builder()
            .credentialsProvider(buildS3V2Credentials(obsCredential))
            .endpointOverride(getEndPointUri())
            .httpClientBuilder(getHttpClientBuilder())
            .forcePathStyle(addressingModel.isPathStyle())
            .region(Region.US_EAST_1)
            .build();
        ListObjectsResponse listObjectsResponse = s3Client.listObjects(
            ListObjectsRequest.builder().bucket("aa.bb").maxKeys(1000).build());
        System.out.println(listObjectsResponse);

### AWS Java SDK version used

2.20.1

### JDK version used

11.0.7

### Operating System and version

Win10

**Comment by bhoradc** [comment]
Hello @wlscu,

Based on the stack trace, there may be an issue with the endpoint URI being passed to the S3Client builder. 

Can you provide the `getEndPointUri()` details? We need to verify that this method is returning a valid endpoint URI. 

Additionally, if you could enable the [verbose wire logging](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) and share the logs, that would help. Kindly redact any sensitive information the logs may contain. 

Regards, 
Chaitanya

**Comment by wlscu** [comment]
private URI getEndPointUri() {
        String address = getEndPoint().toAddress();
        try {
            return new URI(address);
        } catch (URISyntaxException e) {
            throw new ConnectException(StringFormatUtils.format("endpoint [{}] syntax error.", address), e);
        }
    }


address is http://129.124.76.81:80

**Comment by bhoradc** [comment]
Hello @wlscu,

Can you also enable the [verbose wire logging](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) and share the logs please?

Regards, 
Chaitanya

**Comment by wlscu** [comment]
hello @bhoradc ,

**I've enabled the log，when i list object in a bucket name is s3v2, the log :**
2023-05-15 15:52:08,463 DEBUG http-nio-8080-exec-1 request - Sending Request: DefaultSdkHttpFullRequest(httpMethod=GET, protocol=http, host=129.124.76.81, port=5080, encodedPath=/s3v2, headers=[amz-sdk-invocation-id, User-Agent], queryParameters=[])
2023-05-15 15:52:08,514 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "GET /s3v2 HTTP/1.1[\r][\n]"
2023-05-15 15:52:08,514 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "Host: 129.124.76.81:5080[\r][\n]"
2023-05-15 15:52:08,514 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "amz-sdk-invocation-id: d229c70c-ff5a-46ef-d7de-49600a5c713e[\r][\n]"
2023-05-15 15:52:08,514 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "amz-sdk-request: attempt=1; max=4[\r][\n]"
2023-05-15 15:52:08,514 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=B6D90CEE3285B69D4EA7/20230515/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=4bb6d6e41c75ec82140ff402a7f8d1f453788405ddd377fc6466cacab72063ab[\r][\n]"
2023-05-15 15:52:08,515 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "User-Agent: aws-sdk-java/2.20.63 Windows_Server_2012_R2/6.3 OpenJDK_64-Bit_Server_VM/11.0.7+0-Cloud-Compiler-JDK-V100R002C00SPC010B001 Java/11.0.7 kotlin/1.4.10-release-411 (1.4.10) vendor/Huawei_Technologies_Co.__Ltd io/sync http/Apache cfg/retry-mode/legacy[\r][\n]"
2023-05-15 15:52:08,515 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
2023-05-15 15:52:08,515 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "X-Amz-Date: 20230515T075208Z[\r][\n]"
2023-05-15 15:52:08,515 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2023-05-15 15:52:08,515 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "Server: OBS[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "x-amz-request-id: 000001881E62E500E414750EAA898A26[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "x-reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "x-amz-bucket-region: defaultRegion[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "x-amz-id-2: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSHJLOxt1d6Vs72pPgamhDI5FaqrS5pp[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "Content-Type: application/xml[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "Date: Mon, 15 May 2023 07:49:37 GMT[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "Content-Length: 794[\r][\n]"
2023-05-15 15:52:08,572 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "[\r][\n]"
2023-05-15 15:52:08,573 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ListBucketResult xmlns="http://obs.myhwclouds.com/doc/2015-06-30/"><Name>s3v2</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>a-1/</Key><LastModified>2023-05-10T09:44:33.557Z</LastModified><ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag><Size>0</Size><Owner><ID>000001843285B69DE414788FA30148F8</ID><DisplayName>wl1</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>a-2/</Key><LastModified>2023-05-10T09:44:33.593Z</LastModified><ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag><Size>0</Size><Owner><ID>000001843285B69DE414788FA30148F8</ID><DisplayName>wl1</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>"
2023-05-15 15:52:08,607 DEBUG http-nio-8080-exec-1 request - Received successful response: 200, Request ID: 000001881E62E500E414750EAA898A26, Extended Request ID: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSHJLOxt1d6Vs72pPgamhDI5FaqrS5pp

**when i list object in a bucket name is aa.bb, the log :**
java.lang.NullPointerException: host must not be null.
	at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:156)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:56)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:44)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:482)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:250)
	at software.amazon.awssdk.services.s3.endpoints.internal.AwsEndpointProviderUtils.setUri(AwsEndpointProviderUtils.java:178)
	at software.amazon.awssdk.services.s3.endpoints.internal.S3RequestSetEndpointInterceptor.modifyHttpRequest(S3RequestSetEndpointInterceptor.java:35)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyHttpRequestAndHttpContent(ExecutionInterceptorChain.java:90)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.runModifyHttpRequestAndHttpContentInterceptors(BaseClientHandler.java:157)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:83)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:151)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.s3.DefaultS3Client.listObjects(DefaultS3Client.java:6448)
	at com.test.migrate.obs.service.S3V2Service.listBucketObjects(S3V2Service.java:32)

so when i user the bucket s3v2，it can send request, but when i use the bucket aa.bb, it can't send request and failed when prepare request, so i think ist's the bug of sdk.

**Comment by wlscu** [comment]
hello @bhoradc ,

**I've enabled the log，when i list object in a bucket name is s3v2, the log :**
2023-05-15 16:31:06,179 DEBUG http-nio-8080-exec-1 request - Sending Request: DefaultSdkHttpFullRequest(httpMethod=GET, protocol=http, host=129.124.76.81, port=5080, encodedPath=/s3v2, headers=[amz-sdk-invocation-id, User-Agent], queryParameters=[])
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "GET /s3v2 HTTP/1.1[\r][\n]"
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "Host: 129.124.76.81:5080[\r][\n]"
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "amz-sdk-invocation-id: 4d0c9df0-a945-1467-1177-c41623d2fa37[\r][\n]"
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "amz-sdk-request: attempt=1; max=4[\r][\n]"
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=B6D90CEE3285B69D4EA7/20230515/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=9a7a6fd5b58d964421ebb60f62611b46badfc0b66ac69c5f6d5f3d4e05b64081[\r][\n]"
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "User-Agent: aws-sdk-java/2.20.63 Windows_Server_2012_R2/6.3 OpenJDK_64-Bit_Server_VM/17.0.4+8 Java/17.0.4 kotlin/1.4.10-release-411 (1.4.10) vendor/Eclipse_Adoptium io/sync http/Apache cfg/retry-mode/legacy[\r][\n]"
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "X-Amz-Date: 20230515T083106Z[\r][\n]"
2023-05-15 16:31:06,222 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2023-05-15 16:31:06,223 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 >> "[\r][\n]"
2023-05-15 16:31:06,290 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2023-05-15 16:31:06,290 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "Server: OBS[\r][\n]"
2023-05-15 16:31:06,290 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "x-amz-request-id: 000001881E86909FE41486A6AD419CEC[\r][\n]"
2023-05-15 16:31:06,290 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "x-reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc[\r][\n]"
2023-05-15 16:31:06,290 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "x-amz-bucket-region: defaultRegion[\r][\n]"
2023-05-15 16:31:06,290 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "x-amz-id-2: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSPjGq8VuiSpdNKxhT6CzpQzhgr0et3z[\r][\n]"
2023-05-15 16:31:06,290 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "Content-Type: application/xml[\r][\n]"
2023-05-15 16:31:06,291 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "Date: Mon, 15 May 2023 08:28:35 GMT[\r][\n]"
2023-05-15 16:31:06,291 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "Content-Length: 794[\r][\n]"
2023-05-15 16:31:06,291 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "[\r][\n]"
2023-05-15 16:31:06,291 DEBUG http-nio-8080-exec-1 wire - http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ListBucketResult xmlns="http://obs.myhwclouds.com/doc/2015-06-30/"><Name>s3v2</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>a-1/</Key><LastModified>2023-05-10T09:44:33.557Z</LastModified><ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag><Size>0</Size><Owner><ID>000001843285B69DE414788FA30148F8</ID><DisplayName>wl1</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>a-2/</Key><LastModified>2023-05-10T09:44:33.593Z</LastModified><ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag><Size>0</Size><Owner><ID>000001843285B69DE414788FA30148F8</ID><DisplayName>wl1</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>"
2023-05-15 16:31:06,320 DEBUG http-nio-8080-exec-1 request - Received successful response: 200, Request ID: 000001881E86909FE41486A6AD419CEC, Extended Request ID: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSPjGq8VuiSpdNKxhT6CzpQzhgr0et3z

**when i list object in a bucket name is aa.bb, the log :**
java.lang.NullPointerException: host must not be null.
	at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:156)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:56)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:44)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:482)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:250)
	at software.amazon.awssdk.services.s3.endpoints.internal.AwsEndpointProviderUtils.setUri(AwsEndpointProviderUtils.java:178)
	at software.amazon.awssdk.services.s3.endpoints.internal.S3RequestSetEndpointInterceptor.modifyHttpRequest(S3RequestSetEndpointInterceptor.java:35)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyHttpRequestAndHttpContent(ExecutionInterceptorChain.java:90)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.runModifyHttpRequestAndHttpContentInterceptors(BaseClientHandler.java:157)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:83)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:151)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.s3.DefaultS3Client.listObjects(DefaultS3Client.java:6448)
	at com.test.migrate.obs.service.S3V2Service.listBucketObjects(S3V2Service.java:32)

so when i user the bucket s3v2，it can send request, but when i use the bucket aa.bb, it can't send request and failed when prepare request, so i think ist's the bug of sdk.

**Comment by bhoradc** [comment]
Hello @wlscu, 

Thank you for the logs. Are you sending the requests to an S3 endpoint or a third-party solution?

![image](https://github.com/aws/aws-sdk-java-v2/assets/122290643/d0c5c9fd-6500-4515-924d-356079eaf99c)

If it's not an AWS S3 endpoint, we recommend you reach out to the third-party vendor support team. 

Although AWS SDK for Java might work with third-party products simulating AWS services most of the time, we don’t support troubleshooting of issues related to usage of AWS SDKs with third-party products.

Regards, 
Chaitanya

**Comment by wlscu** [comment]
@bhoradc ,
thanks for you reply, I also found out that https endpoint can list object in bucket aa.bb，but throw nullpoint with http endpoint.

**Comment by bhoradc** [comment]
Hi @wlscu,

Here is a list of [Amazon S3 endpoints](https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_region) and their supported protocols. I can confirm that both HTTP and HTTPS works fine for me if overridden to any one of the AWS S3 standard endpoint. For instance: endpoint override to s3.us-east-1.amazonaws.com for bucket `aa.bb` works fine. 

Can you please confirm if you are using an S3 endpoint or a third-party solution?

Regards, 
Chaitanya

**Comment by wlscu** [comment]
@bhoradc 
 it's a third-party solution，I understand that s3-sdk-v2 does not support third-party solutions when I use http to connect buckets with dots in the name, I will look for other solutions to this problem, thanks for your reply.

**Comment by lyf110** [comment]
## I have an idea that can solve this problem.

### code

```java
package com.amazon.s3.v2;

import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.AwsCredentials;
import software.amazon.awssdk.core.client.config.ClientOverrideConfiguration;
import software.amazon.awssdk.core.interceptor.Context;
import software.amazon.awssdk.core.interceptor.ExecutionAttributes;
import software.amazon.awssdk.core.interceptor.ExecutionInterceptor;
import software.amazon.awssdk.core.interceptor.SdkInternalExecutionAttribute;
import software.amazon.awssdk.endpoints.Endpoint;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.S3Configuration;
import software.amazon.awssdk.services.s3.model.ListObjectsV2Request;
import software.amazon.awssdk.services.s3.model.S3Object;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.Optional;

public class S3ClientDemo {
    private static final ExecutionInterceptor ENDPOINT_HANDLER_EXECUTION_INTERCEPTOR = new ExecutionInterceptor() {

        @Override
        public void beforeMarshalling(Context.BeforeMarshalling context, ExecutionAttributes executionAttributes) {
            Endpoint endpoint = executionAttributes.getAttribute(SdkInternalExecutionAttribute.RESOLVED_ENDPOINT);
            if (endpoint != null) {
                Optional<String> bucketOption = context.request().getValueForField("Bucket", String.class);
                bucketOption.ifPresent(bucketName -> {
                    if (bucketName.contains(".")) {
                        URI clientUrl = executionAttributes.getAttribute(SdkInternalExecutionAttribute.CLIENT_ENDPOINT);

                        URI url = endpoint.url();
                        String host = url.getHost();
                        if (host == null || host.isEmpty()) {
                            String scheme = url.getScheme();
                            String userInfo = url.getUserInfo();
                            host = clientUrl.getHost();
                            int port = url.getPort() == -1 ? clientUrl.getPort() : url.getPort();
                            String path = url.getPath();
                            path = path == null || path.isEmpty() ? "/" + bucketName : path;
                            String query = url.getQuery();
                            String fragment = url.getFragment();

                            try {
                                URI newUrl = new URI(scheme, userInfo, host, port, path, query, fragment);
                                Endpoint newEndpoint = endpoint.toBuilder().url(newUrl).build();
                                executionAttributes.putAttribute(SdkInternalExecutionAttribute.RESOLVED_ENDPOINT, newEndpoint);
                            } catch (URISyntaxException e) {
                                e.printStackTrace();
                            }
                        }
                    }
                });
            }

        }
    };


    public static S3Client createS3Client(String endPoint,
                                          String region,
                                          String accessKey,
                                          String secretKey) throws URISyntaxException {
        AwsCredentials credentials = AwsBasicCredentials.create(accessKey, secretKey);
        return S3Client.builder()
                .region(Region.of(region))
                .credentialsProvider(() -> credentials)
                .endpointOverride(new URI(endPoint))
                .serviceConfiguration(S3Configuration.builder()
                        .pathStyleAccessEnabled(false)
                        .chunkedEncodingEnabled(false)
                        .build())
                .overrideConfiguration(ClientOverrideConfiguration.builder()
                        .addExecutionInterceptor(ENDPOINT_HANDLER_EXECUTION_INTERCEPTOR)
                        .build())
                .build();
    }

    public static void main(String[] args) throws URISyntaxException {
        String endPoint = "your endPoint";
        String region = "your region";
        String accessKey = "your accessKey";
        String secretKey = "your secretKey";
        String bucketName = "your bucketName";
        S3Client s3Client = createS3Client(endPoint, region, accessKey, secretKey);
        System.out.printf("bucket [%s]\n", bucketName);
        for (S3Object content : s3Client.listObjectsV2(ListObjectsV2Request.builder().bucket(bucketName).build()).contents()) {
            System.out.printf("content [%s]\n", content);
        }
    }
}
```

**Comment by wlscu** [comment]
> ## I have an idea that can solve this problem.
> ### code
> ```java
> package com.amazon.s3.v2;
> 
> import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
> import software.amazon.awssdk.auth.credentials.AwsCredentials;
> import software.amazon.awssdk.core.client.config.ClientOverrideConfiguration;
> import software.amazon.awssdk.core.interceptor.Context;
> import software.amazon.awssdk.core.interceptor.ExecutionAttributes;
> import software.amazon.awssdk.core.interceptor.ExecutionInterceptor;
> import software.amazon.awssdk.core.interceptor.SdkInternalExecutionAttribute;
> import software.amazon.awssdk.endpoints.Endpoint;
> import software.amazon.awssdk.regions.Region;
> import software.amazon.awssdk.services.s3.S3Client;
> import software.amazon.awssdk.services.s3.S3Configuration;
> import software.amazon.awssdk.services.s3.model.ListObjectsV2Request;
> import software.amazon.awssdk.services.s3.model.S3Object;
> 
> import java.net.URI;
> import java.net.URISyntaxException;
> import java.util.Optional;
> 
> public class S3ClientDemo {
>     private static final ExecutionInterceptor ENDPOINT_HANDLER_EXECUTION_INTERCEPTOR = new ExecutionInterceptor() {
> 
>         @Override
>         public void beforeMarshalling(Context.BeforeMarshalling context, ExecutionAttributes executionAttributes) {
>             Endpoint endpoint = executionAttributes.getAttribute(SdkInternalExecutionAttribute.RESOLVED_ENDPOINT);
>             if (endpoint != null) {
>                 Optional<String> bucketOption = context.request().getValueForField("Bucket", String.class);
>                 bucketOption.ifPresent(bucketName -> {
>                     if (bucketName.contains(".")) {
>                         URI clientUrl = executionAttributes.getAttribute(SdkInternalExecutionAttribute.CLIENT_ENDPOINT);
> 
>                         URI url = endpoint.url();
>                         String host = url.getHost();
>                         if (host == null || host.isEmpty()) {
>                             String scheme = url.getScheme();
>                             String userInfo = url.getUserInfo();
>                             host = clientUrl.getHost();
>                             int port = url.getPort() == -1 ? clientUrl.getPort() : url.getPort();
>                             String path = url.getPath();
>                             path = path == null || path.isEmpty() ? "/" + bucketName : path;
>                             String query = url.getQuery();
>                             String fragment = url.getFragment();
> 
>                             try {
>                                 URI newUrl = new URI(scheme, userInfo, host, port, path, query, fragment);
>                                 Endpoint newEndpoint = endpoint.toBuilder().url(newUrl).build();
>                                 executionAttributes.putAttribute(SdkInternalExecutionAttribute.RESOLVED_ENDPOINT, newEndpoint);
>                             } catch (URISyntaxException e) {
>                                 e.printStackTrace();
>                             }
>                         }
>                     }
>                 });
>             }
> 
>         }
>     };
> 
> 
>     public static S3Client createS3Client(String endPoint,
>                                           String region,
>                                           String accessKey,
>                                           String secretKey) throws URISyntaxException {
>         AwsCredentials credentials = AwsBasicCredentials.create(accessKey, secretKey);
>         return S3Client.builder()
>                 .region(Region.of(region))
>                 .credentialsProvider(() -> credentials)
>                 .endpointOverride(new URI(endPoint))
>                 .serviceConfiguration(S3Configuration.builder()
>                         .pathStyleAccessEnabled(false)
>                         .chunkedEncodingEnabled(false)
>                         .build())
>                 .overrideConfiguration(ClientOverrideConfiguration.builder()
>                         .addExecutionInterceptor(ENDPOINT_HANDLER_EXECUTION_INTERCEPTOR)
>                         .build())
>                 .build();
>     }
> 
>     public static void main(String[] args) throws URISyntaxException {
>         String endPoint = "your endPoint";
>         String region = "your region";
>         String accessKey = "your accessKey";
>         String secretKey = "your secretKey";
>         String bucketName = "your bucketName";
>         S3Client s3Client = createS3Client(endPoint, region, accessKey, secretKey);
>         System.out.printf("bucket [%s]\n", bucketName);
>         for (S3Object content : s3Client.listObjectsV2(ListObjectsV2Request.builder().bucket(bucketName).build()).contents()) {
>             System.out.printf("content [%s]\n", content);
>         }
>     }
> }
> ```

Using your solution successfully solved my problem, thank you very much.
