### ISSUE TITLE
InstanceProfileCredentialsProvider credentials fail

### ISSUE THREAD

**Issue by elbin-pixelscope** [aws/aws-sdk-java-v2#4071]
### Describe the bug

I am using a Role to authenticate AWS S3 credentials.
During the initial deployment, there were no issues with the operation. However, the AWS credentials renewal is failing in the InstanceProfileCredentialsProvider.

### Expected Behavior

Successfully renewed credentials in InstanceProfileCredentialsProvider and successfully executed putObject.

### Current Behavior

```


2023-06-07T15:08:03.941+09:00 | 2023-06-07 06:08:03 [http-nio-80-exec-3] DEBUG software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider:96 - Ignoring non-fatal exception while attempting to load metadata token from instance profile.
-- | --
  | 2023-06-07T15:08:03.941+09:00 | java.net.SocketException: Invalid argument
  | 2023-06-07T15:08:03.941+09:00 | at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at java.net.Socket.connect(Socket.java:633) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.http.HttpClient.<init>(HttpClient.java:246) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.http.HttpClient.New(HttpClient.java:351) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.http.HttpClient.New(HttpClient.java:373) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057) ~[?:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.regions.internal.util.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:45) ~[regions-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.regions.util.HttpResourcesUtils.readResource(HttpResourcesUtils.java:112) ~[regions-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.getToken(InstanceProfileCredentialsProvider.java:223) ~[auth-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.createEndpointProvider(InstanceProfileCredentialsProvider.java:201) ~[auth-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.refreshCredentials(InstanceProfileCredentialsProvider.java:148) ~[auth-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$3(CachedSupplier.java:284) ~[utils-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.utils.cache.CachedSupplier$PrefetchStrategy.fetch(CachedSupplier.java:420) ~[utils-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:199) ~[utils-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:128) ~[utils-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.resolveCredentials(InstanceProfileCredentialsProvider.java:139) ~[auth-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:50) ~[sdk-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.resolveCredentials(AwsCredentialsAuthorizationStrategy.java:100) ~[aws-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.addCredentialsToExecutionAttributes(AwsCredentialsAuthorizationStrategy.java:77) ~[aws-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:123) ~[aws-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:69) ~[aws-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:78) ~[sdk-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179) ~[sdk-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76) ~[sdk-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[sdk-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56) ~[aws-core-2.20.79.jar!/:?]
  | 2023-06-07T15:08:03.941+09:00 | at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:9394) ~[s3-2.20.79.jar!/:?]



```

### Reproduction Steps

```
    @Bean
    fun prod(): S3Client {
        return S3Client.builder()
            .credentialsProvider(InstanceProfileCredentialsProvider.create())
            .region(Region.AP_NORTHEAST_2)
            .build()
    }
```

### AWS Java SDK version used

2.20.79

### JDK version used

openjdk:17.0.2-slim

### Operating System and version

Amazon ECS Linux

**Comment by debora-ito** [comment]
I don't remember seeing "java.net.SocketException: Invalid argument" before...

Got some questions:
1. Can you reproduce it reliably every time, or is it intermittent?
2. Are you using proxy?
3. If you are able to reproduce it in a non-production environment, can you enable the [verbose wirelogs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose)?

**Comment by elbin-pixelscope** [comment]
> I don't remember seeing "java.net.SocketException: Invalid argument" before...
> 
> Got some questions:
> 
> 1. Can you reproduce it reliably every time, or is it intermittent?
> 2. Are you using proxy?
> 3. If you are able to reproduce it in a non-production environment, can you enable the [verbose wirelogs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose)?

Hello, this is debora-ito, and here is my response:

1. It is possible every time. (error occurs when executing the S3 putObject operation.)
2. I do not use a proxy.(network configuration is ALB -> ECS)
3. The above log history is verbose wirelogs. The general log history is as follows.

```
software.amazon.awssdk.core.exception.SdkClientException: Failed to load credentials from IMDS.
--
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.refreshCredentials(InstanceProfileCredentialsProvider.java:157)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$3(CachedSupplier.java:284)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.utils.cache.CachedSupplier$PrefetchStrategy.fetch(CachedSupplier.java:420)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:199)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:128)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.resolveCredentials(InstanceProfileCredentialsProvider.java:139)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:50)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.resolveCredentials(AwsCredentialsAuthorizationStrategy.java:100)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.addCredentialsToExecutionAttributes(AwsCredentialsAuthorizationStrategy.java:77)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:123)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:69)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:78)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
  | 2023-06-09T10:13:09.037+09:00 | at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:9394)
```

**Comment by debora-ito** [comment]
For question number 3, those are not the verbose wirelogs, those are regular stacktraces. The verbose wirelogs will contain the request and response headers, along with any request body. 

I also noted that your last comment shows a "Failed to load credentials from IMDS" error, which is different from the "java.net.SocketException: Invalid argument" reported initially. Do you get a different error every time? "Failed to load credentials from IMDS" can indicate the IMDS endpoint is not available. The wirelogs will show more info.
