### ISSUE TITLE
Gets write time out error when uploading big payloads using S3TransferManager 

### ISSUE THREAD

**Issue by raymondchen625** [aws/aws-sdk-java-v2#4306]
### Describe the bug

When I upload a file greater than ~30M using `S3TransferManager`, I got `Write time out` errors.

### Expected Behavior

Should not throw errors for payloads >~30M.

### Current Behavior

Error stack:

```
java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Write timed out
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.completeResponseFuture(MakeAsyncHttpRequestStage.java:240)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Write timed out
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:223)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:218)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:182)
	... 23 more
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 1 failure: Unable to execute HTTP request: Write timed out
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 2 failure: Unable to execute HTTP request: Write timed out
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 3 failure: Unable to execute HTTP request: Write timed out
Caused by: java.io.IOException: Write timed out
	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.decorateException(NettyUtils.java:75)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.exceptionCaught(ResponseHandler.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerSubscriber.exceptionCaught(HandlerSubscriber.java:184)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.handler.logging.LoggingHandler.exceptionCaught(LoggingHandler.java:214)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at software.amazon.awssdk.http.nio.netty.internal.UnusedChannelExceptionHandler.exceptionCaught(UnusedChannelExceptionHandler.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at software.amazon.awssdk.http.nio.netty.internal.FutureCancelHandler.exceptionCaught(FutureCancelHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:424)
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
	at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:145)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:1115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.handler.timeout.WriteTimeoutHandler.writeTimedOut(WriteTimeoutHandler.java:180)
	at io.netty.handler.timeout.WriteTimeoutHandler$WriteTimeoutTask.run(WriteTimeoutHandler.java:209)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more
Caused by: io.netty.handler.timeout.WriteTimeoutException
```

### Reproduction Steps

 The code with `S3TransferManager` which doesn't work:

```
static void upload(String bucket, String filePath, String key) {
    S3AsyncClientBuilder s3AsyncClientBuilder = S3AsyncClient.builder();
    S3AsyncClient s3AsyncClient = s3AsyncClientBuilder.build();
    try (S3TransferManager transferManager =
        S3TransferManager.builder()
            .s3Client(s3AsyncClient)
            .build()) {
      UploadFileRequest uploadFileRequest =
          UploadFileRequest.builder()
              .putObjectRequest(b -> b.bucket(bucket).key(key))
              .addTransferListener(LoggingTransferListener.create())
              .source(Paths.get(filePath))
              .build();
      FileUpload fileUpload = transferManager.uploadFile(uploadFileRequest);
      try {
        CompletedFileUpload uploadResult = fileUpload.completionFuture().join();
        System.out.println("upload result etag:" + uploadResult.response().eTag());
      }
      catch (Exception e) {
        e.printStackTrace();
      }
      System.out.println("Done");
    }
  }
```

Run it with a file around 50M, we will get the exceptions.

Smaller files work well. I could upload the file through CLI (v2.13.9) or use S3AsyncClient directly. Below code with S3AsyncClient works well:

```
static void uploadByS3AsyncClient(String bucket, String filePath, String key) {
    S3AsyncClientBuilder s3AsyncClientBuilder = S3AsyncClient.builder();
    try (S3AsyncClient s3AsyncClient = s3AsyncClientBuilder.build()) {
      PutObjectRequest putObjectRequest = PutObjectRequest.builder().key(key).bucket(bucket).build();
      CompletableFuture<PutObjectResponse> future = s3AsyncClient.putObject(putObjectRequest, AsyncRequestBody.fromFile(Paths.get(filePath)));
      PutObjectResponse response = future.join();
      System.out.println("upload result etag:" + response.eTag());
    }
    catch (Exception e) {
      e.printStackTrace();
    }
    System.out.println("Done");
  }
```

### AWS Java SDK version used

2.20.121

### JDK version used

Temurin-17.0.4+8

### Operating System and version

macOS 13.5

**Comment by raymondchen625** [comment]
I ran the same test again on an AWS EC2 instance without any issues. It's still reproducible in my local, which has less bandwidth. It's probably related to time.

**Comment by debora-ito** [comment]
Hi @raymondchen625 I see you are using the default s3AsyncClient, which does not have the ability to choose multipart operations.

If you change to use the CRT-based S3 async client, it will use multipart APIs automatically, depending on the minimum part size configured (default is 8MB).

```
    S3AsyncClient s3CrtBuilderClient = S3AsyncClient.crtBuilder()
                        .region(Region.US_WEST_2)
                        .minimumPartSizeInBytes(5 * MB)
                        .build();
```

Multipart uploads are done in parallel, so you should see performance improvement when compared to the default s3 async client.

You can reference our Dev Guide for more information on the CRT-based S3 client and S3TransferManager:
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/crt-based-s3-client.html

**Comment by raymondchen625** [comment]
Does that mean there is an existing bug in S3TransferManager used with the default S3AsyncClient?

**Comment by debora-ito** [comment]
It's not a bug, I'm sorry, I should've been more clear. As you noticed, you don't see the timeout exception when you use an environment with better resources. Bigger files will take more time to upload, and you can eventually reach the configured connection timeout. 

To overcome timeout issues, you have some options:

- Tweak the HTTP client configurations (like connectionTimeout, maxConcurrency, writeTimeout, etc) to values tailored to your use case and environment limits. If you expect the upload to take more time than the configured default writeTimeout, try increasing its value. You can check our [Developer Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration.html) for examples on how to customize the settings in the HTTP clients. `NettyNioAsyncHttpClient` is the default HTTP client used in the S3transferManager.
- Use parallel multipart upload instead of single part. This can be achieved out-of-the-box by using the CRT-based S3 client in the S3transferManager. You can also write your own logic and call the low-level multipart APIs.

**Comment by raymondchen625** [comment]
> * Tweak the HTTP client configurations (like connectionTimeout, maxConcurrency, writeTimeout, etc)

I tried to set all of these to very large values. The `write timeout` still occurred. As I mentioned in my code snippet which uses the default `S3AsyncClient`. it works well. While the `S3AsyncClient` with the same default configuration doesn't work when it's used by the `S3TransferManager`. I suspect the problem is on the `S3TransferManager` side or at least it's the interaction between `S3TransferManager` and the setting of `NettyNioAsyncHttpClient`.

Were you able to reproduce the issue? If yes, can you point me to the `NettyNioAsyncHttpClient` setting to make it work?

**Comment by debora-ito** [comment]
I can't reproduce. I ran both code samples with a 50MB file, both uploads were successful. 

I'm thinking of other ways to move the investigation forward.

1. Have you enabled the client-side metrics? I'm wondering what the metrics will show if we compare the S3TransferManager code run with the one without S3TransferManager. https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics.html
2. Do you have a hard requirement to use the default Netty Async client? Have you tested using S3TransferManager and the CRT client to see if the timeout errors still occur?

**Comment by raymondchen625** [comment]
I just tested again with AWS SDK `2.20.139`. I still got the same result. I added a test of `S3TransferManager + S3AsyncClient with CRT`. It also worked well. So the only failed combination is the default S3AsyncClient + S3TransferManager.
In an unrelated test, we compared the performance of the different clients. We found the CRT client sometimes performs well, but sometimes it could be much worse. For example, an upload with the S3Client constantly takes 12s. The CRT can make it to 5 seconds, but occasionally takes 18s.
