### ISSUE TITLE
Issue :: AWS Java SDK For Amazon Rekognition - upgradation

### ISSUE THREAD

**Issue by ravi-codeprism** [aws/aws-sdk-java-v2#4321]
### Describe the bug

AWS Java SDK For Amazon Rekognition - is of javax package made on Apache License, Version 2.0.

Current latest of Apache tomcat is of 10 and which takes jakarta package instead of javax. Even in latest dependency could not provide. i.e Association is getting failure with  'entity.Tags.videos' targets the type 'com.amazonaws.services.rekognition.model.Video' which is not an '@Entity' type 

### Expected Behavior

Must work with jakarta and also old dependency is javax

### Current Behavior

could not able to migrate from java 11 to java 17
Association 'org.entity.Tags.videos' targets the type 'com.amazonaws.services.rekognition.model.Video' which is not an '@Entity' type
	at org.hibernate.boot.model.internal.CollectionBinder.detectManyToManyProblems(CollectionBinder.java:2484)
	at org.hibernate.boot.model.internal.CollectionBinder.bindManyToManySecondPass(CollectionBinder.java:2079)
	at org.hibernate.boot.model.internal.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:1550)
	at org.hibernate.boot.model.internal.CollectionBinder$1.secondPass(CollectionBinder.java:1534)
	at org.hibernate.boot.model.internal.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:45)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1857)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1814)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:328)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1380)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1451)

### Reproduction Steps

Higher version of java must also work

### Additional Information/Context

Not like bug also. take it as feature request

### AWS Java SDK version used

'com.amazonaws:aws-java-sdk-rekognition:1.12.530'

### JDK version used

java version "17.0.8" 2023-07-18 LTS Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211) Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

### Operating System and version

Mac os

**Comment by debora-ito** [comment]
@ravi-codeprism I see you are using Java SDK v1, we are tracking the feature request here - https://github.com/aws/aws-sdk-java/issues/2527. The team's focus is in working in v2 features, so releasing this in v1 has very low priority. Will close this as a duplicate.

Java SDK v2 already supports jakarta namespaces, the recommendation is to upgrade to v2.

**Comment by ravi-codeprism** [comment]
@debora-ito Java SDK v2 got released. if so, can you share that dependency ?

**Comment by debora-ito** [comment]
Here's an example using maven:

```
    <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>rekognition</artifactId>
    </dependency>
```

Our Java SDK v2 Developer Guide goes through more examples of how to set up build config files to use the SDK v2:
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup-project-maven.html
