### ISSUE TITLE
SDK is exporting netty dependencies as transitive dependencies

### ISSUE THREAD

**Issue by REASY** [aws/aws-sdk-java-v2#4434]
When I updated AWS SKD Java V2 from 2.20.93 to 2.20.133, I started getting runtime exception
```
java.lang.UnsatisfiedLinkError: 'int io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH()'
	at io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH(Native Method)
	at io.netty.channel.unix.Errors.<clinit>(Errors.java:62)
	at io.netty.channel.unix.Socket.connect(Socket.java:351)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
	at io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:144)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632)
	at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655)
	at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:637)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I have other dependencies that transitively bring Netty.
- [grpc-netty 1.47.1](https://mvnrepository.com/artifact/io.grpc/grpc-netty/1.47.1) brings 4.1.72.Final
- [netty-nio-client/2.20.133](https://mvnrepository.com/artifact/software.amazon.awssdk/netty-nio-client/2.20.133) brings 4.1.94.Final
- [Spark 3.4.1](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.13/3.4.1) brings 4.1.87.Final

### Expected Behavior

With shaded netty would be easier to integrate with existing codebases

### Current Behavior

Runtime exception due to conflict with existing netty dependencies, getting
```
java.lang.UnsatisfiedLinkError: 'int io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH()'
	at io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH(Native Method)
	at io.netty.channel.unix.Errors.<clinit>(Errors.java:62)
	at io.netty.channel.unix.Socket.connect(Socket.java:351)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
	at io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:144)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632)
	at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655)
	at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:637)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Reproduction Steps

Having a project that has different version of netty

### Possible Solution

Shade netty libraries that come from netty-nio-client

### AWS Java SDK version used

2.20.133

### JDK version used

openjdk 11.0.20.1 2023-08-24 OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04) OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

### Operating System and version

Ubuntu 20.04, Linux 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by debora-ito** [comment]
@REASY I'm sorry you're getting bit by this, but it's not a particular issue with the AWS SDK for Java, it's [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell) situation. 

We recently upgraded the netty version due to a CVE - https://github.com/aws/aws-sdk-java-v2/pull/4133. We don't have immediate plans to shade netty.

Let us know if you have any other question.

**Comment by REASY** [comment]
Hi, @debora-ito, thank you for the reply.

I do know about JAR/dependency hell, at the same time there is practical workaround for it in JVM world to shade dependencies. Also note that AWS SDK v1 shades netty, https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-bundle/pom.xml#L47

**Comment by debora-ito** [comment]
Java SDK 2.x is different than 1.x in this aspect. 

In 2.x you have the option to use different http clients if you want, and you can exclude the netty dependency if you're using a different async http client like the crt-based client. You won't be able to exclude a dependency if it is shaded.

As I said in the previous comment, we don't have plans to shade netty.

**Comment by gregkonush** [comment]
so what's the workaround for this exception though?
