### ISSUE TITLE
Not providing a proper region string to the Region.of function returns java.lang.NullPointerException: host must not be null. .

### ISSUE THREAD

**Issue by drocsid** [aws/aws-sdk-java-v2#453]
Not providing a proper region string to the Region.of function returns `java.lang.NullPointerException: host must not be null. `.

But this is not intuitive. The message should be `region not found` or otherwise, because I didn't realize `host` referred to `region`.

Someone else had a similar issue described in #401 

Here's a full example from my gitter chat session.

Hi I'm not doing anything terribly interesting, just trying to use the s3client to list objects. I'm getting Exception in thread "main" java.lang.NullPointerException: host must not be null. but not sure what host should be set. I was looking at the examples as a reference https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/javav2/example_code/s3/src/main/java/com/example/s3/S3ObjectOperations.java
Heres what threw the exception:

def listObjects(bucketName: String,regionName: String): List[String] = {
    val region = Region.of(regionName)
    val s3client = S3Client.builder().region(region).build()
    val listObjectsV2Request = ListObjectsV2Request.builder()
      .bucket(bucketName).build()
    val listObjectsV2Iterable: ListObjectsV2Iterable = s3client.listObjectsV2Paginator(listObjectsV2Request)
    val iterable: SdkIterable[S3Object] = listObjectsV2Iterable.contents()
    val scalaIterable = iterable.asScala
    val list = scalaIterable.map(x=>x.key()).toList
    list
  }

Exception in thread "main" java.lang.NullPointerException: host must not be null.                       
        at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:118)                        
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:5
2)                                                                                                      
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:4
0)                                                                                                      
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest
.java:294)                                                                                              
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest
.java:155)                                                                                              
        at software.amazon.awssdk.core.http.SdkHttpFullRequestAdapter.toHttpFullRequest(SdkHttpFullReque
stAdapter.java:39)                                                                                      
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:9
5)
        at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:7
6)
        at software.amazon.awssdk.core.client.SdkClientHandler.execute(SdkClientHandler.java:45)        
        at software.amazon.awssdk.services.s3.DefaultS3Client.listObjectsV2(DefaultS3Client.java:2009)  
        at software.amazon.awssdk.services.s3.paginators.ListObjectsV2Iterable$ListObjectsV2ResponseFetc
her.nextPage(ListObjectsV2Iterable.java:166)                                                            
        at software.amazon.awssdk.services.s3.paginators.ListObjectsV2Iterable$ListObjectsV2ResponseFetc
her.nextPage(ListObjectsV2Iterable.java:157)                                                            
        at software.amazon.awssdk.core.pagination.PaginatedResponsesIterator.next(PaginatedResponsesIter
ator.java:52)
        at software.amazon.awssdk.core.pagination.PaginatedItemsIterable$ItemsIterator.<init>(PaginatedI
temsIterable.java:55)                                                                                   
        at software.amazon.awssdk.core.pagination.PaginatedItemsIterable.iterator(PaginatedItemsIterable
.java:45)                                                                                               
        at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:54)               
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)                           
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)

drocsid
@drocsid
13:11
I added credentials providers and tried not converting the collection to scala but still get host must not be null

import software.amazon.awssdk.core.auth.{AwsCredentialsProvider, EnvironmentVariableCredentialsProvider, InstanceProfileCredentialsProvider, ProfileCredentialsProvider}
import software.amazon.awssdk.core.pagination.SdkIterable
import software.amazon.awssdk.core.regions.Region
import software.amazon.awssdk.services.s3.S3Client
import software.amazon.awssdk.services.s3.model.{ListObjectsV2Request, S3Object}
import software.amazon.awssdk.services.s3.paginators.ListObjectsV2Iterable

object S3Util extends Logger {

  def listObjects(bucketName: String,regionName: String,credentialsProvider: AwsCredentialsProvider): Unit = {
    val region = Region.of(regionName)
    val s3client = S3Client.builder().credentialsProvider(credentialsProvider)
      .region(region).build()
    val listObjectsV2Request = ListObjectsV2Request.builder()
      .bucket(bucketName).build()
    val listObjectsV2Iterable: ListObjectsV2Iterable = s3client.listObjectsV2Paginator(listObjectsV2Request)
    val iterable: SdkIterable[S3Object] = listObjectsV2Iterable.contents()
    val iterator = iterable.iterator()
    while(iterator.hasNext){
      logError(iterator.next().key())
    }
    //val scalaIterable = iterable.asScala
    //val list = scalaIterable.map(x=>x.key()).toList

  }

  def getCredentialsProvider(providerType: String, profileString: String = "None"): AwsCredentialsProvider = {
    providerType match {
      case "ENV" => EnvironmentVariableCredentialsProvider.create()
      case "PROFILE" => ProfileCredentialsProvider.create(profileString)
      case "INSTANCE" => InstanceProfileCredentialsProvider.create()
      case _ => throw new IllegalArgumentException("Not a valid Credentials Provider")
    }
  }

}

drocsid
@drocsid
13:45
Hmm maybe I was running into this: aws/aws-sdk-java-v2#401
drocsid
@drocsid
13:58
A better exception might be helpful. Didn't realize host referred to region and was using the value US_WEST_2 like the enum value vs us-west-2

**Comment by spfink** [comment]
Hmm, we'll try and figure something out here. The Region.of method allows any value to be passed to it to allow users to use regions that we don't yet have published in the latest version of our SDK or simply aren't available in the version that the customer is using. In that regard, it will be hard to say explicitly region not found. We can definitely reword that error message and hopefully attempt to check if the error is explicitly because of the region passed.

**Comment by zoewangg** [comment]
Did a quick test with the latest version and now it throws UnknownHostException. 
```
Exception in thread "main" software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: xxx.s3.foo-bar.amazonaws.com
Caused by: java.net.UnknownHostException: xxx.s3.foo-bar.amazonaws.com
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:793)
```

Can you try with the latest version? Closing the issue. Feel free to reopen if you have further questions.
