### ISSUE TITLE
DynamoDB Local has jetty version incompatible with upcoming Spring Boot 3.2 jetty version

### ISSUE THREAD

**Issue by artur1211** [aws/aws-sdk-java-v2#4573]
### Describe the feature

There is an incompatibility between jetty versions in the upcoming Spring Boot 3.2 (it brings 12.0.1 jetty with it) and DynamoDB Local (contains jetty in version 11.0.15). When one tries to run DynamoDB Local on the jetty (12.0.1) taken from Spring Boot 3.2 it leads to the following exception:
`java.lang.IllegalAccessError: class com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer tried to access protected method 'void org.eclipse.jetty.server.Handler$AbstractContainer.<init>()' (com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer and org.eclipse.jetty.server.Handler$AbstractContainer are in unnamed module of loader 'app')
	at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.setUpHandler(DynamoDBProxyServer.java:50)
	at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.<init>(DynamoDBProxyServer.java:37)
        at...`

### Use Case

I cannot run DynamoDB Local with newest Spring Boot 3.2 

### Proposed Solution

Update Jetty to 12.0.1

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

DynamoDB Local 2.0.0

### JDK version used

OpenJDK Runtime Environment Temurin-17.0.2+8

### Operating System and version

macOS Ventura 13.6

**Comment by debora-ito** [comment]
@artur1211 

Issues with `DynamoDB Local` should be created in the https://github.com/awslabs/amazon-dynamodb-local-samples repo, there you'll get replies from the DynamoDB Local team directly.

Unfortunately I can't transfer this issue, so you'll have to open a new one over there. Let us know if you have questions.

**Comment by artur1211** [comment]
@debora-ito 
Thanks for the information. I have added it here https://github.com/awslabs/amazon-dynamodb-local-samples/issues/4
