### ISSUE TITLE
DynamoDB Autogenerated Update Expression Is Too Large

### ISSUE THREAD

**Issue by DaltonWorsnup** [aws/aws-sdk-java-v2#4597]
### Describe the bug

When generating update expressions via enhanced client tables, every name and value in the name and value maps are set to the name of their corresponding field prefixed by `"AMZN_MAPPED_"`. This causes problems when the number of attributes grows large.  Changing the names of the fields on the class is not a suitable solution because it breaks readability of the code. Further, changing the names of the attributes in the dynamo table is not a suitable solution because that will require refactoring all services that interact with the table and may require migrating the table. 

Consider the class below:

```
@Data
@DynamoDbBean
@NoArgsConstructor
@AllArgsConstructor
public class MyBean {
    @Getter(onMethod_ = @DynamoDbPartitionKey)
    private int id;
    private String stringField;
    private Integer integerField;
}
```

### Expected Behavior

Performing an `updateItem` on a `DynamoDbTable<MyBean>` with an instance of `MyBean` results in the following, minified update expression:

`SET #n0 = :v0, #n1 = :v1`

with a name map:

`#n0 -> stringField, #n1 -> integerField`

and with a value map:

`:v0 -> <value of stringField>, :v1 -> <value of integerField>`

### Current Behavior

Performing an `updateItem` on a `DynamoDbTable<MyBean>` with an instance of `MyBean` results in the following update expression, which is too large in some applications:

`SET #AMZN_MAPPED_stringField = :AMZN_MAPPED_stringField, #AMZN_MAPPED_integerField = :AMZN_MAPPED_integerField`

with a name map:

`#AMZN_MAPPED_stringField -> stringField, #AMZN_MAPPED_integerField -> integerField`

and with a value map:

`:AMZN_MAPPED_stringField -> <value of stringField>, :AMZN_MAPPED_integerField -> <value of integerField>`

### Reproduction Steps

Create a `DynamoDbBean` with a large number of fields. Create an instance of that bean. Perform a update item request using a `DynamoDbTable` from the enhanced client. The size of the item may be well within the limits of DynamoDB, but the update expression is too large to properly update it. 

### Possible Solution

Minify the names of fields when creating the update expression.

### Additional Information/Context

I'm filing this as a bug since it's technically possible for this to break production code given that one is using the ignoreNulls option if some of null values on the bean are set for the first time. If this is better suited for a feature request, let me know and I will recreate it as such.

### AWS Java SDK version used

2.20.157

### JDK version used

Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190

### Operating System and version

Windows 10 Home - 22H2

**Comment by debora-ito** [comment]
> The size of the item may be well within the limits of DynamoDB, but the update expression is too large to properly update it.

Are you experiencing an actual error, or is this to prevent an issue in the future?
If it's the former, can you provide a stacktrace?

**Comment by DaltonWorsnup** [comment]
Sure thing, here is the stack trace up to my invocation of `updateItem`:

```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Invalid UpdateExpression: Expression size has exceeded the maximum allowed size; (Service: DynamoDb, Status Code: 400, Request ID: 37ac2a87-8835-4acd-b23c-d9d81285929f)

	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:198)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.updateItem(DefaultDynamoDbClient.java:6103)
	at software.amazon.awssdk.enhanced.dynamodb.internal.operations.CommonOperation.execute(CommonOperation.java:114)
	at software.amazon.awssdk.enhanced.dynamodb.internal.operations.TableOperation.executeOnPrimaryIndex(TableOperation.java:59)
	at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbTable.updateItem(DefaultDynamoDbTable.java:319)
	at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbTable.updateItem(DefaultDynamoDbTable.java:327)
	at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbTable.updateItem(DefaultDynamoDbTable.java:332)

```

**Comment by DaltonWorsnup** [comment]
In my case, I have 144 fields being updated at once. Using the debugger, I was able to extract the update expression generated by the SDK, and it has a size of 8434 bytes, well over the 4 KB limit. Removing the `AMZN_MAPPED_` prefix drops the size of the update expression to 4978 bytes - still too large. A fully minified update expression such as the example I gave above is only 1942 bytes, which should allow the update to go through.

**Comment by debora-ito** [comment]
I see, thank you for the additional details. 

I guess this is an enhancement more than a bug, so I'll change this to a feature request. The reason I think it's an enhancement is because 4KB is a [limit on the service side](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#limits-expression-parameters), so you can reach the limit even if we remove the AMZN_MAPPED prefix and use the minified names.

**Comment by inspingcc** [comment]
> I see, thank you for the additional details.
> 
> I guess this is an enhancement more than a bug, so I'll change this to a feature request. The reason I think it's an enhancement is because 4KB is a [limit on the service side](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#limits-expression-parameters), so you can reach the limit even if we remove the AMZN_MAPPED prefix and use the minified names.我想这与其说是一个错误，不如说是一个增强，所以我会把它改成一个功能请求。我认为这是一项增强功能的原因是 4KB 是 服务端的限制 ，因此即使我们删除 AMZN_MAPPED 前缀并使用缩小的名称，您也可以达到限制。

What is the best solution to this problem? Split the table and use transactions?

**Comment by DaltonWorsnup** [comment]
This is still causing problems for us two years later
