### ISSUE TITLE
Trying to use Iceberg in Managed Flink Studio facing NoSuchMethodError in for a SdkProtectedApi

### ISSUE THREAD

**Issue by FranMorilloAWS** [aws/aws-sdk-java-v2#4616]
### Describe the bug

In order to use Apache Iceberg in the Manage Service for Apache Flink, you need to add the AWS SDK AWS Core Jar.  However one of its methods its under @sdkprotectedAPI   and when the code uses the dependencies i get this error:

Caused by: java.lang.NoSuchMethodError: 'boolean software.amazon.awssdk.awscore.endpoints.authscheme.SigV4AuthScheme.isDisableDoubleEncodingSet()'

I have added all the dependencies in the core folder. 

Im using 2..21.2

### Expected Behavior

Be able to use AWS SDK when using Iceberg in KDA Studio

### Current Behavior

Error

### Reproduction Steps

Set up a Managed Flink Application Studio on AWS and follow the instructions to create an Iceberg Table using Flink SQL

### Possible Solution

Removing the protectedAPI for the method

### AWS Java SDK version used

2.21.1

### JDK version used

11

### Operating System and version

Zepelling Interpreter for Flink

**Comment by debora-ito** [comment]
@FranMorilloAWS can you paste the full stacktrace? I'd like to see which method is originally calling `SigV4AuthScheme.isDisableDoubleEncodingSet( )`

> you need to add the AWS SDK AWS Core Jar

This is an unusual way to consume the SDK. Are you using only the core module but no service client?

**Comment by FranMorilloAWS** [comment]
Hello, thank you for reaching out! So i wanted to use the bundle for the SDK but its to big for Managed Service for Apache Flink.  Im using S3, KMS, Glue.  I havent been able to find the Core Jar that includes all of the (Annotations, sdk-core etc)

In Maven it just shows a Pom file

**Comment by FranMorilloAWS** [comment]
at org.apache.flink.table.factories.FactoryUtil.createDynamicTableSink(FactoryUtil.java:262)
	at org.apache.flink.table.factories.FactoryUtil.createDynamicTableSink(FactoryUtil.java:287)
	at org.apache.flink.connectors.hive.HiveDynamicTableFactory.createDynamicTableSink(HiveDynamicTableFactory.java:76)
	at org.apache.flink.table.factories.FactoryUtil.createDynamicTableSink(FactoryUtil.java:259)
	... 33 more
Caused by: java.lang.NoSuchMethodError: 'boolean software.amazon.awssdk.awscore.endpoints.authscheme.SigV4AuthScheme.isDisableDoubleEncodingSet()'
	at software.amazon.awssdk.services.s3.endpoints.internal.S3ResolveEndpointInterceptor.authSchemeWithEndpointSignerProperties(S3ResolveEndpointInterceptor.java:886)
	at software.amazon.awssdk.services.s3.endpoints.internal.S3ResolveEndpointInterceptor.modifyRequest(S3ResolveEndpointInterceptor.java:167)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyRequest(ExecutionInterceptorChain.java:68)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.runInitialInterceptors(AwsExecutionContextBuilder.java:176)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:112)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:69)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:8975)
	at org.apache.iceberg.aws.s3.S3OutputStream.completeUploads(S3OutputStream.java:438)
	at org.apache.iceberg.aws.s3.S3OutputStream.close(S3OutputStream.java:265)
	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:341)
	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:161)
	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:255)
	at org.apache.iceberg.TableMetadataParser.$closeResource(TableMetadataParser.java:131)
	at org.apache.iceberg.TableMetadataParser.internalWrite(TableMetadataParser.java:131)
	at org.apache.iceberg.TableMetadataParser.overwrite(TableMetadataParser.java:114)
	at org.apache.iceberg.BaseMetastoreTableOperations.writeNewMetadata(BaseMetastoreTableOperations.java:170)
	at org.apache.iceberg.BaseMetastoreTableOperations.writeNewMetadataIfRequired(BaseMetastoreTableOperations.java:160)
	at org.apache.iceberg.aws.glue.GlueTableOperations.doCommit(GlueTableOperations.java:155)
	at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:135)
	at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:199)
	at org.apache.iceberg.CachingCatalog$CachingTableBuilder.lambda$create$0(CachingCatalog.java:261)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.apache.iceberg.CachingCatalog$CachingTableBuilder.create(CachingCatalog.java:257)
	at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:75)
	at org.apache.iceberg.flink.FlinkCatalog.createIcebergTable(FlinkCatalog.java:416)
	at org.apache.iceberg.flink.FlinkDynamicTableFactory.createTableLoader(FlinkDynamicTableFactory.java:190)
	at org.apache.iceberg.flink.FlinkDynamicTableFactory.createDynamicTableSink(FlinkDynamicTableFactory.java:118)
	at org.apache.flink.table.factories.FactoryUtil.createDynamicTableSink(FactoryUtil.java:259)

**Comment by debora-ito** [comment]
Can you share your dependency tree? In maven the command is `mvn dependency:tree`.

"NoSuchMethodError" usually indicates a version mismatch between modules of the SDK. Ideally all SDK modules should be in the same version. 

You can use the BOM artifactId to help with this, take a look at the example in our Developer Guide -
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup-project-maven.html#sdk-as-dependency

> So i wanted to use the bundle for the SDK but its to big for Managed Service for Apache Flink. Im using S3, KMS, Glue. 

Using the full bundle is NOT recommended, we recommend adding only the services you are going to use as dependencies. 

> I havent been able to find the Core Jar that includes all of the (Annotations, sdk-core etc)

If you add the service module (like S3 and KMS), the internal dependencies will be added automatically, you don't need to add them explicitly.
