### ISSUE TITLE
Don't know what error it is

### ISSUE THREAD

**Issue by Plestar-suresh** [aws/aws-sdk-java-v2#4772]
### Describe the bug

FATAL EXCEPTION: AsyncTask #1
                                                                                                    Process: com.example.phonecall, PID: 8063
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$4.done(AsyncTask.java:415)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
                                                                                                    	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.lambda$getPreferredSocketFactory$0$software-amazon-awssdk-http-apache-ApacheHttpClient$ApacheConnectionManagerFactory(ApacheHttpClient.java:678)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at java.util.Optional.orElseGet(Optional.java:263)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheHttpClient.java:678)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.create(ApacheHttpClient.java:657)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.createClient(ApacheHttpClient.java:151)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:125)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:104)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.buildWithDefaults(ApacheHttpClient.java:649)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$0(DefaultSdkHttpClientBuilder.java:42)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder$$ExternalSyntheticLambda1.apply(Unknown Source:4)
                                                                                                    	at java.util.Optional.map(Optional.java:211)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:42)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$14$software-amazon-awssdk-core-client-builder-SdkDefaultClientBuilder(SdkDefaultClientBuilder.java:398)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at java.util.Optional.orElseGet(Optional.java:263)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:398)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$finalizeSyncConfiguration$2$software-amazon-awssdk-core-client-builder-SdkDefaultClientBuilder(SdkDefaultClientBuilder.java:285)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$ExternalSyntheticLambda13.get(Unknown Source:4)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder.$r8$lambda$hKhiZl312B6vnl897y_oikb6tUA(Unknown Source:0)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder$$ExternalSyntheticLambda0.accept(Unknown Source:4)
                                                                                                    	at java.util.ArrayList.forEach(ArrayList.java:1262)
2023-12-12 15:10:06.629  8063-8370  AndroidRuntime          com.example.phonecall                E  	at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
                                                                                                    	at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:232)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:287)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:189)
                                                                                                    	at software.amazon.awssdk.services.pinpoint.DefaultPinpointClientBuilder.buildClient(DefaultPinpointClientBuilder.java:37)
                                                                                                    	at software.amazon.awssdk.services.pinpoint.DefaultPinpointClientBuilder.buildClient(DefaultPinpointClientBuilder.java:25)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155)
                                                                                                    	at com.example.phonecall.OtpVerificationActivity$sendotps.doInBackground(OtpVerificationActivity.java:310)
                                                                                                    	at com.example.phonecall.OtpVerificationActivity$sendotps.doInBackground(OtpVerificationActivity.java:291)

### Expected Behavior

FATAL EXCEPTION: AsyncTask #1
                                                                                                    Process: com.example.phonecall, PID: 8063
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$4.done(AsyncTask.java:415)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
                                                                                                    	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.lambda$getPreferredSocketFactory$0$software-amazon-awssdk-http-apache-ApacheHttpClient$ApacheConnectionManagerFactory(ApacheHttpClient.java:678)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at java.util.Optional.orElseGet(Optional.java:263)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheHttpClient.java:678)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.create(ApacheHttpClient.java:657)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.createClient(ApacheHttpClient.java:151)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:125)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:104)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.buildWithDefaults(ApacheHttpClient.java:649)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$0(DefaultSdkHttpClientBuilder.java:42)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder$$ExternalSyntheticLambda1.apply(Unknown Source:4)
                                                                                                    	at java.util.Optional.map(Optional.java:211)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:42)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$14$software-amazon-awssdk-core-client-builder-SdkDefaultClientBuilder(SdkDefaultClientBuilder.java:398)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at java.util.Optional.orElseGet(Optional.java:263)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:398)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$finalizeSyncConfiguration$2$software-amazon-awssdk-core-client-builder-SdkDefaultClientBuilder(SdkDefaultClientBuilder.java:285)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$ExternalSyntheticLambda13.get(Unknown Source:4)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder.$r8$lambda$hKhiZl312B6vnl897y_oikb6tUA(Unknown Source:0)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder$$ExternalSyntheticLambda0.accept(Unknown Source:4)
                                                                                                    	at java.util.ArrayList.forEach(ArrayList.java:1262)
2023-12-12 15:10:06.629  8063-8370  AndroidRuntime          com.example.phonecall                E  	at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
                                                                                                    	at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:232)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:287)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:189)
                                                                                                    	at software.amazon.awssdk.services.pinpoint.DefaultPinpointClientBuilder.buildClient(DefaultPinpointClientBuilder.java:37)
                                                                                                    	at software.amazon.awssdk.services.pinpoint.DefaultPinpointClientBuilder.buildClient(DefaultPinpointClientBuilder.java:25)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155)
                                                                                                    	at com.example.phonecall.OtpVerificationActivity$sendotps.doInBackground(OtpVerificationActivity.java:310)
                                                                                                    	at com.example.phonecall.OtpVerificationActivity$sendotps.doInBackground(OtpVerificationActivity.java:291)

### Current Behavior

FATAL EXCEPTION: AsyncTask #1
                                                                                                    Process: com.example.phonecall, PID: 8063
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$4.done(AsyncTask.java:415)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
                                                                                                    	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.lambda$getPreferredSocketFactory$0$software-amazon-awssdk-http-apache-ApacheHttpClient$ApacheConnectionManagerFactory(ApacheHttpClient.java:678)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at java.util.Optional.orElseGet(Optional.java:263)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheHttpClient.java:678)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.create(ApacheHttpClient.java:657)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.createClient(ApacheHttpClient.java:151)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:125)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:104)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.buildWithDefaults(ApacheHttpClient.java:649)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$0(DefaultSdkHttpClientBuilder.java:42)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder$$ExternalSyntheticLambda1.apply(Unknown Source:4)
                                                                                                    	at java.util.Optional.map(Optional.java:211)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:42)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$14$software-amazon-awssdk-core-client-builder-SdkDefaultClientBuilder(SdkDefaultClientBuilder.java:398)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at java.util.Optional.orElseGet(Optional.java:263)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:398)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$finalizeSyncConfiguration$2$software-amazon-awssdk-core-client-builder-SdkDefaultClientBuilder(SdkDefaultClientBuilder.java:285)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$ExternalSyntheticLambda13.get(Unknown Source:4)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder.$r8$lambda$hKhiZl312B6vnl897y_oikb6tUA(Unknown Source:0)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder$$ExternalSyntheticLambda0.accept(Unknown Source:4)
                                                                                                    	at java.util.ArrayList.forEach(ArrayList.java:1262)
2023-12-12 15:10:06.629  8063-8370  AndroidRuntime          com.example.phonecall                E  	at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
                                                                                                    	at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:232)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:287)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:189)
                                                                                                    	at software.amazon.awssdk.services.pinpoint.DefaultPinpointClientBuilder.buildClient(DefaultPinpointClientBuilder.java:37)
                                                                                                    	at software.amazon.awssdk.services.pinpoint.DefaultPinpointClientBuilder.buildClient(DefaultPinpointClientBuilder.java:25)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155)
                                                                                                    	at com.example.phonecall.OtpVerificationActivity$sendotps.doInBackground(OtpVerificationActivity.java:310)
                                                                                                    	at com.example.phonecall.OtpVerificationActivity$sendotps.doInBackground(OtpVerificationActivity.java:291)

### Reproduction Steps

FATAL EXCEPTION: AsyncTask #1
                                                                                                    Process: com.example.phonecall, PID: 8063
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$4.done(AsyncTask.java:415)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
                                                                                                    	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.lambda$getPreferredSocketFactory$0$software-amazon-awssdk-http-apache-ApacheHttpClient$ApacheConnectionManagerFactory(ApacheHttpClient.java:678)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at java.util.Optional.orElseGet(Optional.java:263)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheHttpClient.java:678)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.create(ApacheHttpClient.java:657)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.createClient(ApacheHttpClient.java:151)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:125)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient.<init>(ApacheHttpClient.java:104)
                                                                                                    	at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.buildWithDefaults(ApacheHttpClient.java:649)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$0(DefaultSdkHttpClientBuilder.java:42)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder$$ExternalSyntheticLambda1.apply(Unknown Source:4)
                                                                                                    	at java.util.Optional.map(Optional.java:211)
                                                                                                    	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:42)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$14$software-amazon-awssdk-core-client-builder-SdkDefaultClientBuilder(SdkDefaultClientBuilder.java:398)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$ExternalSyntheticLambda1.get(Unknown Source:4)
                                                                                                    	at java.util.Optional.orElseGet(Optional.java:263)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:398)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$finalizeSyncConfiguration$2$software-amazon-awssdk-core-client-builder-SdkDefaultClientBuilder(SdkDefaultClientBuilder.java:285)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$ExternalSyntheticLambda13.get(Unknown Source:4)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder.$r8$lambda$hKhiZl312B6vnl897y_oikb6tUA(Unknown Source:0)
                                                                                                    	at software.amazon.awssdk.utils.AttributeMap$Builder$$ExternalSyntheticLambda0.accept(Unknown Source:4)
                                                                                                    	at java.util.ArrayList.forEach(ArrayList.java:1262)
2023-12-12 15:10:06.629  8063-8370  AndroidRuntime          com.example.phonecall                E  	at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
                                                                                                    	at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:232)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:287)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:189)
                                                                                                    	at software.amazon.awssdk.services.pinpoint.DefaultPinpointClientBuilder.buildClient(DefaultPinpointClientBuilder.java:37)
                                                                                                    	at software.amazon.awssdk.services.pinpoint.DefaultPinpointClientBuilder.buildClient(DefaultPinpointClientBuilder.java:25)
                                                                                                    	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155)
                                                                                                    	at com.example.phonecall.OtpVerificationActivity$sendotps.doInBackground(OtpVerificationActivity.java:310)
                                                                                                    	at com.example.phonecall.OtpVerificationActivity$sendotps.doInBackground(OtpVerificationActivity.java:291)

### AWS Java SDK version used

mplementation ("software.amazon.awssdk:pinpoint:2.21.43")

### JDK version used

mplementation ("software.amazon.awssdk:pinpoint:2.21.43")

### Operating System and version

Android 12

**Comment by debora-ito** [comment]
Hi @Plestar-suresh,

`NoSuchFieldError` indicates a version mismatch between SDK modules. Check your dependency tree and make sure all the modules are using the same version.

If you search for "NoSuchFieldError" in this repo you can find it's a common misconfiguration.

One additional note: Android environments are not supported by the Java SDK, we recommend you use the AWS Amplify -
https://docs.amplify.aws/android/start/getting-started/introduction/
