### ISSUE TITLE
File upload using S3 Transfer Manager with the AWS CRT-based S3 client is not functioning on Linux

### ISSUE THREAD

**Issue by fivetran-rahulprakash** [aws/aws-sdk-java-v2#4790]
### Describe the bug

After updating to S3 version 2, we attempted to upload Parquet files using the S3 Transfer Manager with the AWS CRT-based client. During testing on Linux, I encountered the following error: `java.lang.IllegalArgumentException: transferredBytes (16777216) must not be greater than totalBytes (9187648)`. The same code, which I used on UNIX (Mac) with java version 11, is working fine.

### Expected Behavior

Should be able to upload

### Current Behavior

Getting the following exception.
`Exception in thread "Thread-2" java.lang.IllegalArgumentException: transferredBytes (16777216) must not be greater than totalBytes (9187648)
	at software.amazon.awssdk.utils.Validate.isTrue(Validate.java:76)
	at software.amazon.awssdk.transfer.s3.internal.progress.DefaultTransferProgressSnapshot.<init>(DefaultTransferProgressSnapshot.java:45)
	at software.amazon.awssdk.transfer.s3.internal.progress.DefaultTransferProgressSnapshot.<init>(DefaultTransferProgressSnapshot.java:34)
	at software.amazon.awssdk.transfer.s3.internal.progress.DefaultTransferProgressSnapshot$Builder.build(DefaultTransferProgressSnapshot.java:173)
	at software.amazon.awssdk.transfer.s3.internal.progress.DefaultTransferProgressSnapshot$Builder.build(DefaultTransferProgressSnapshot.java:134)
	at software.amazon.awssdk.utils.builder.ToCopyableBuilder.copy(ToCopyableBuilder.java:45)
	at software.amazon.awssdk.transfer.s3.internal.progress.DefaultTransferProgress.lambda$updateAndGet$0(DefaultTransferProgress.java:51)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at software.amazon.awssdk.transfer.s3.internal.progress.DefaultTransferProgress.updateAndGet(DefaultTransferProgress.java:51)
	at software.amazon.awssdk.transfer.s3.internal.progress.TransferProgressUpdater.incrementBytesTransferred(TransferProgressUpdater.java:183)
	at software.amazon.awssdk.transfer.s3.internal.progress.TransferProgressUpdater.access$100(TransferProgressUpdater.java:42)
	at software.amazon.awssdk.transfer.s3.internal.progress.TransferProgressUpdater$2.subscriberOnNext(TransferProgressUpdater.java:124)
	at software.amazon.awssdk.transfer.s3.internal.progress.TransferProgressUpdater$2.subscriberOnNext(TransferProgressUpdater.java:116)
	at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onProgress(S3CrtResponseHandlerAdapter.java:176)
	at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onProgress(S3MetaRequestResponseHandlerNativeAdapter.java:32)`

### Reproduction Steps

Create a Parquet file and use the following code in Linux to upload it to an S3 bucket.

```
S3AsyncClient s3AsyncClient =
            S3AsyncClient.crtBuilder()
                    .credentialsProvider(
                            StaticCredentialsProvider.create(
                                    AwsBasicCredentials.create(
                                            "<key>", "<secret>")))
                    .build();

S3TransferManager s3TransferManager = S3TransferManager.builder().s3Client(s3AsyncClient).build();

UploadFileRequest uploadFileRequest =
                    UploadFileRequest.builder()
                            .putObjectRequest(b -> b.bucket("<bucket_name>").key("<file_name>.parquet"))
                            .addTransferListener(LoggingTransferListener.create())
                            .source(Paths.get(<file_to_upload>))
                            .build();

s3TransferManager.uploadFile(uploadFileRequest).completionFuture().join();
```

### AWS Java SDK version used

software.amazon.awssdk:s3-transfer-manager:2.21.26,  software.amazon.awssdk.crt:aws-crt:0.21.16

### JDK version used

17

### Operating System and version

Ubuntu 22.04.2 LTS

**Comment by debora-ito** [comment]
Hi @fivetran-rahulprakash 

`s3-transfer-manager` 2.21.26 was released using `aws-crt` version 0.28.0:
https://github.com/aws/aws-sdk-java-v2/blob/17bbde8eb5241987d37722fe90753835ca64764e/pom.xml#L119

1. Can you upgrade to `software.amazon.awssdk.crt:aws-crt:0.28.0` and see if you still see the error?
2. What's the size of the parquet file?
