### ISSUE TITLE
Compatibility Issue with Play 2.5.9

### ISSUE THREAD

**Issue by playtowork** [aws/aws-sdk-java-v2#485]
I have seen this similar issue at https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2813. Perhaps the solution there can inform the solution for this issue as well. I have a Play framework project (version 2.5.9).

I append the following in its build.sbt's libraryDependencies:
`"software.amazon.awssdk"          % "s3"       % "2.0.0-preview-9"`

Then I run `sbt clean && sbt "project frontend" run`. Instead of the app starting, it errors with the following:

--- (Running the application, auto-reloading is enabled) ---

java.lang.NoSuchFieldError: DEFAULT_MAX_PENDING_TASKS
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at play.core.server.NettyServer.<init>(NettyServer.scala:77)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:279)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:235)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:65)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:64)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:54)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:234)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)

**Comment by stkeky** [comment]
I'm having the similar issue with `"software.amazon.awssdk" % "s3" % "2.0.0-preview-9"` and Play `2.5.x`. Apparently Play Framework isn't using Netty `4.1.x`,  so the SDK is practically unusable with Play `2.5.x` at the moment.

**Comment by dagnir** [comment]
Hi, one possible solution is to use the [bundle dependency](https://github.com/aws/aws-sdk-java-v2/tree/2.0.0-preview-10/bundle) which shades the dependencies and relocates them to a different namespace so the SDK's dependencie's won't conflict with those from other components. Will this work for you? @playtowork @stkeky

**Comment by dagnir** [comment]
Yep, the bundle is available in Maven:

https://search.maven.org/#artifactdetails|software.amazon.awssdk|bundle|2.0.0-preview-10|jar

It contains both the sync and async classes.

**Comment by aaronlee29** [comment]
@dagnir Thanks! It appears to work so far. At least my Play 2.5.x app is not crashing at startup now that I'm using the bundle. Next step will be to test the functionality out.

**Comment by aaronlee29** [comment]
Hi @dagnir,

It appears the bundle does not solve the "different Netty versions" problem. The AWS client, on executing a network request, fails with `java.lang.NoSuchMethodError: io.netty.handler.codec.http.DefaultHttpRequest.<init>(Lio/netty/handler/codec/http/HttpVersion;Lio/netty/handler/codec/http/HttpMethod;Ljava/lang/String;Lio/netty/handler/codec/http/HttpHeaders;)V`

I did a debug-run of my server and it fails at Netty's `RequestAdapter.java`, line 33: `DefaultHttpRequest request = new DefaultHttpRequest(HttpVersion.HTTP_1_1, method, uri, headers);`

It is trying to create a `DefaultHttpRequest` with the following constructor: `public DefaultHttpRequest(HttpVersion httpVersion, HttpMethod method, String uri, HttpHeaders headers)`

This constructor exists in the bundle's Netty, but not in Play 2.5.x's Netty, which has two different, incompatible constructors:
`public DefaultHttpRequest(HttpVersion httpVersion, HttpMethod method, String uri)`
or
`public DefaultHttpRequest(HttpVersion httpVersion, HttpMethod method, String uri, boolean validateHeaders)`

Answers on the Internet also implicate conflicting versions of Netty dependencies [1](https://github.com/aws/aws-sdk-java/issues/1402) and [2](https://github.com/aws/aws-sdk-java/issues/1402).

Do you know if there's anything else I can do to isolate the Netty? Or a workaround?

Thanks.

**Comment by dagnir** [comment]
I took a look at the POM and it looks like it's an issue with the bundle. ATM it doesn't look like Netty is being relocated to a different package. I'll go ahead and mark this as a Bug and put up a fix soon.

https://github.com/aws/aws-sdk-java-v2/blob/3a82de31c6e98d28c6dc7cee6a63592a2fe058a1/bundle/pom.xml#L80-L101

**Comment by dagnir** [comment]
Opened #542 to fix this

**Comment by dagnir** [comment]
#542 has been merged and should be released as part of `2.0.0-preview-11`

**Comment by dagnir** [comment]
Closing as this is fixed in `master`.
