### ISSUE TITLE
Profile File custom location not working

### ISSUE THREAD

**Issue by csteger81590** [aws/aws-sdk-java-v2#5431]
### Describe the bug

I am working with an application that requires specific directories for read access, and unfortunately, the default location for AWS credentials (%user%.aws/credentials) is not accessible with my current software setup. I have tried various approaches, but I ideally want to use AwsBasicCredentials.

Locally, this setup works fine, but when compiling and running with the application, I encounter the following error: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\WINDOWS\system32\config\systemprofile\.aws\credentials" "read"). It seems that the provider chain is attempting to access the .aws/credentials file first and failing, which prevents it from using the AwsBasicCredentials I’ve provided.

I also attempted to use the DefaultCredentialsProvider with a custom profileFile, but encountered the same issue. I would appreciate any guidance on how to resolve this and ensure that my application can use AwsBasicCredentials directly without encountering access issues.

### Expected Behavior

The SDK should not attempt to access the ~/.aws/credentials file when credentials are provided via StaticCredentialsProvider. With AwsBasicCredentials and a static provider, I expect the SDK to bypass the .aws/credentials file and use the provided access and secret keys exclusively.

Similarly, when using DefaultCredentialsProvider and specifying a custom profile file location, I anticipate that it should locate the profile file correctly and proceed without throwing any exceptions.

### Current Behavior

In both scenarios, I encounter the following error: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\WINDOWS\system32\config\systemprofile\.aws\credentials" "read").

### Reproduction Steps

Try to create a client with AwsBasicCredentials, and use StaticCredentialsProvider. Call trace shows that it's trying to read ProfileFile('~/.aws/credentials').

Try to use the DefaultCredentialsProvider  and set the 'profileFile' to a different location

### Additional Information/Context

` 
DefaultCredentialsProvider defaultCredentialsProvider = DefaultCredentialsProvider.builder()
                .profileName("default")
                .profileFile(ProfileFile.builder().type(ProfileFile.Type.CREDENTIALS).content(creds.toPath()).build())
                .build();

        URI ticketyUri = URI.create("https://global.api.tickety.amazon.dev");

        ClientOverrideConfiguration clientOverrideConfiguration = ClientOverrideConfiguration.builder()
                .retryPolicy(RetryMode.ADAPTIVE)
                .putAdvancedOption(SdkAdvancedClientOption.SIGNER, DefaultAwsCrtV4aSigner.builder().defaultRegionScope(RegionScope.GLOBAL).build())
                .build();

        ticketyClient = (TicketyClient) TicketyClient.builder()
                .credentialsProvider((AwsCredentialsProvider) defaultCredentialsProvider)
                .endpointOverride(ticketyUri)
                .overrideConfiguration(clientOverrideConfiguration)
                .build();`

### AWS Java SDK version used

2.26.20

### JDK version used

1.8

### Operating System and version

Windows 11

**Comment by debora-ito** [comment]
@csteger81590 I could not reproduce any of the errors. Moving the credentials file to a different place and setting the new path in the profileFile succeeds:

```Java
DefaultCredentialsProvider defaultCredentialsProvider = DefaultCredentialsProvider.builder()
        .profileName("default")
        .profileFile(ProfileFile.builder().type(ProfileFile.Type.CREDENTIALS).content(creds.toPath()).build())
        .build();
```

I also tested using basic credentials, not DefaultCredentialsProvider, and it doesn't try to access the credential file e.g.:

```Java
S3Client s3Client = S3Client.builder()
        .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("foo", "bar")))
        .region(Region.US_WEST_2)
        .build();
```

Maybe there's some disconnection between the error in the logs and the actual call?

`AwsBasicCredentials` is not part of the default credential provider chain, so you need to set it explicitly. It's a weird behavior if the SDK is trying to access the credentials file when using basic credentials.

**Comment by gerrymurphysse** [comment]
Hi,
I am having the same issue and I have set my client to use AwsBasicCredentials but it still looks for the windows file, below is my client build.. I am using variable to store my Access Key and Secret Access Key.


s3Client = S3Client.builder()
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(accessKey, secretAccessKey)))
                .region(Region.EU_WEST_1)
                .build();

Here is my stack trace..

java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\WINDOWS\system32\config\systemprofile\.aws\credentials" "read")
 at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
 at java.security.AccessController.checkPermission(AccessController.java:886)
 at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
 at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
 at sun.nio.fs.WindowsPath.checkRead(WindowsPath.java:792)
 at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:49)
 at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
 at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
 at java.nio.file.Files.readAttributes(Files.java:1737)
 at java.nio.file.Files.isRegularFile(Files.java:2229)
 at software.amazon.awssdk.profiles.ProfileFileLocation.lambda$resolveIfExists$2(ProfileFileLocation.java:90)
 at java.util.Optional.filter(Optional.java:178)
 at software.amazon.awssdk.profiles.ProfileFileLocation.resolveIfExists(ProfileFileLocation.java:90)
 at software.amazon.awssdk.profiles.ProfileFileLocation.credentialsFileLocation(ProfileFileLocation.java:77)
 at software.amazon.awssdk.profiles.ProfileFile.addCredentialsFile(ProfileFile.java:151)
 at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
 at software.amazon.awssdk.profiles.ProfileFile.defaultProfileFile(ProfileFile.java:99)
 at software.amazon.awssdk.utils.Lazy.getValue(Lazy.java:50)
 at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$mergeGlobalDefaults$3(SdkDefaultClientBuilder.java:287)
 at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:604)
 at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:593)
 at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:400)
 at java.util.ArrayList.forEach(ArrayList.java:1259)
 at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
 at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:224)
 at software.amazon.awssdk.core.client.config.SdkClientConfiguration.merge(SdkClientConfiguration.java:98)
 at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.mergeGlobalDefaults(SdkDefaultClientBuilder.java:283)
 at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:199)
 at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:37)
 at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:26)
 at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:169)
 at com.sse.gmAWSUtil.AwsS3Service.<init>(AwsS3Service.java:36)
 at com.sse.gmAWSUtil.BAwsFile.doSendRequest(BAwsFile.java:301)
 at auto.com_sse_gmAWSUtil_BAwsFile.invoke(AutoGenerated)
 at com.tridium.sys.schema.ComponentSlotMap.invoke(ComponentSlotMap.java:1921)
 at com.tridium.sys.engine.EngineUtil.doInvoke(EngineUtil.java:62)
 at com.tridium.sys.engine.EngineManager.checkAsyncActions(EngineManager.java:471)
 at com.tridium.sys.engine.EngineManager.execute(EngineManager.java:272)
 at com.tridium.sys.engine.EngineManager$EngineThread.run(EngineManager.java:911)

Please can you point out if I am doing something wrong here.

I am running this in Java8 on a JVM as I would like to use this on a Tridium Niagara JACE which has no windows filesystem and is pretty locked down.
