### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by asantoz** [aws/aws-sdk-java-v2#5449]
### Describe the bug

Using the latest `2.26.27` sdk version, when I'm getting this error on a SSM get
eg.
`val client = SecretsManagerClient.builder().region(Region.US_EAST_1).build()
  val result = client.getSecretValue(GetSecretValueRequest.builder().secretId(path).build()).secretString()`

### Expected Behavior

Result the secret path requested

### Current Behavior

An exception or error caused a run to abort: AWS_PARTITIONS_FILE 
java.lang.NoSuchFieldError: AWS_PARTITIONS_FILE
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.DefaultPartitionDataProvider.systemSettingPartitionsFile(DefaultPartitionDataProvider.java:42)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.DefaultPartitionDataProvider.loadPartitions(DefaultPartitionDataProvider.java:36)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.RulesFunctions.loadPartitionData(RulesFunctions.java:158)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.RulesFunctions$LazyValue.value(RulesFunctions.java:191)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.RulesFunctions.awsPartition(RulesFunctions.java:100)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.DefaultSecretsManagerEndpointProvider.endpointRule6(DefaultSecretsManagerEndpointProvider.java:107)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.DefaultSecretsManagerEndpointProvider.endpointRule5(DefaultSecretsManagerEndpointProvider.java:100)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.DefaultSecretsManagerEndpointProvider.endpointRule0(DefaultSecretsManagerEndpointProvider.java:58)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.DefaultSecretsManagerEndpointProvider.resolveEndpoint(DefaultSecretsManagerEndpointProvider.java:36)
	at software.amazon.awssdk.services.secretsmanager.endpoints.internal.SecretsManagerResolveEndpointInterceptor.modifyRequest(SecretsManagerResolveEndpointInterceptor.java:60)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyRequest(ExecutionInterceptorChain.java:65)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.runInitialInterceptors(AwsExecutionContextBuilder.java:242)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:132)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:67)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
	at software.amazon.awssdk.services.secretsmanager.DefaultSecretsManagerClient.getSecretValue(DefaultSecretsManagerClient.java:1129)

### Reproduction Steps

`val client = SecretsManagerClient.builder().region(Region.US_EAST_1).build()
  val result = client.getSecretValue(GetSecretValueRequest.builder().secretId(path).build()).secretString()`
with version

### AWS Java SDK version used

2.26.27

### JDK version used

11

### Operating System and version

MacOs and Linux

**Comment by debora-ito** [comment]
`NoSuchFieldError` indicates you have SDK modules with mismatching versions in your classpath.

Check our Troubleshooting guide: [How do I fix a NoClassDefFoundError, NoSuchMethodError or NoSuchFieldError?](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/troubleshooting.html#faq-classpath-errors)

Moving this to Github Discussions.
