### ISSUE TITLE
Consistently encountering Crc32MismatchException 

### ISSUE THREAD

**Issue by fivetran-jaekim** [aws/aws-sdk-java-v2#5625]
### Describe the bug

I am getting a Crc32MismatchException exception consistently when calling DynamoDbClient.scan(). Expected and actual calculated checksum values are consistent across multiple failures in different processes. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Scan completes without an error and returns a ScanResponse object. 

### Current Behavior

```java
software.amazon.awssdk.core.exception.Crc32MismatchException: Expected 1878142776 as the Crc32 checksum but the actual calculated checksum was 2970300582
                at software.amazon.awssdk.core.exception.Crc32MismatchException$BuilderImpl.build(Crc32MismatchException.java:97)
                at software.amazon.awssdk.core.internal.util.Crc32ChecksumValidatingInputStream.validateChecksum(Crc32ChecksumValidatingInputStream.java:90)
                at software.amazon.awssdk.core.internal.util.Crc32ChecksumValidatingInputStream.close(Crc32ChecksumValidatingInputStream.java:54)
                at java.base/java.io.FilterInputStream.close(FilterInputStream.java:179)
                at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeRunnable$5(FunctionalUtils.java:124)
                at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:140)
                at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.lambda$handle$2(JsonResponseHandler.java:87)
                at java.base/java.util.Optional.ifPresent(Optional.java:178)
                at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:87)
                at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
                at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
                at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
                at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:99)
                at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:92)
                at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)
                at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:93)
                at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$8(BaseClientHandler.java:296)
                at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:99)
                at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:75)
                at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
                at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
                at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
                at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
                at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
                at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
                at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
                at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
                at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
                at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:224)
                at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
                at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)
                at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
                at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
                at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
                at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
                at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
                at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.scan(DefaultDynamoDbClient.java:4991)

``` 

### Reproduction Steps

```java
DynamoDbClient dynamoDbClient = DynamoDbClient.builder().httpClientBuilder(ApacheHttpClient.builder()).build();

ScanRequest.Builder scanRequestBuilder = ScanRequest.builder().tableName(table);
        scanRequestBuilder.totalSegments(totalSegments);
        scanRequestBuilder.segment(segment);

dynamoDbClient.scan(scanRequestBuilder.build());
``` 

### AWS Java SDK version used

2.25.64

### JDK version used

17

### Operating System and version

Ubuntu 22.04

**Comment by fivetran-jonathansavas** [comment]
I have been more investigation on this issue with @fivetran-jaekim. I wrote an ExecutionInterceptor to write the body of the response to a file when we encounter a response with the header checksum that has been consistently failing. Then I read the body through both Crc32ChecksumValidatingInputStream and a third party CRC32 calculator. Both return the expected checksum from the header. This response does not contain the header `Content-Encoding: gzip`. It is not compressed.

**Comment by fivetran-jonathansavas** [comment]
We disabled Crc32 Validation by intercepting the HTTP response and removing the header. Now we are consistently seeing this exception:

```
Caused by: java.io.UncheckedIOException: software.amazon.awssdk.thirdparty.jackson.core.exc.StreamConstraintsException: Spill-over slots in symbol table with 2045 entries, hash area of 4096 slots is now full (all 512 slots -- suspect a DoS attack based on hash collisions. You can disable the check via `JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW`
			at software.amazon.awssdk.utils.FunctionalUtils.asRuntimeException(FunctionalUtils.java:180)
			at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:110)
			at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:136)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parse(JsonNodeParser.java:82)
			at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:190)
			at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:75)
			at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
			at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
			at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
			at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:99)
			at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:92)
			at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)
			at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:93)
			at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$8(BaseClientHandler.java:296)
			at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:99)
			... 47 more
		Caused by: software.amazon.awssdk.thirdparty.jackson.core.exc.StreamConstraintsException: Spill-over slots in symbol table with 2045 entries, hash area of 4096 slots is now full (all 512 slots -- suspect a DoS attack based on hash collisions. You can disable the check via `JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW`
			at software.amazon.awssdk.thirdparty.jackson.core.sym.ByteQuadsCanonicalizer._reportTooManyCollisions(ByteQuadsCanonicalizer.java:1359)
			at software.amazon.awssdk.thirdparty.jackson.core.sym.ByteQuadsCanonicalizer._findOffsetForAdd(ByteQuadsCanonicalizer.java:1061)
			at software.amazon.awssdk.thirdparty.jackson.core.sym.ByteQuadsCanonicalizer.addName(ByteQuadsCanonicalizer.java:978)
			at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.addName(UTF8StreamJsonParser.java:2482)
			at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.parseEscapedName(UTF8StreamJsonParser.java:2117)
			at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.parseName(UTF8StreamJsonParser.java:2014)
			at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1840)
			at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:798)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseObject(JsonNodeParser.java:174)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseToken(JsonNodeParser.java:158)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseObject(JsonNodeParser.java:173)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseToken(JsonNodeParser.java:158)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseObject(JsonNodeParser.java:173)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseToken(JsonNodeParser.java:158)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseArray(JsonNodeParser.java:183)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseToken(JsonNodeParser.java:160)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseObject(JsonNodeParser.java:173)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseToken(JsonNodeParser.java:158)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parse(JsonNodeParser.java:116)
			at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.lambda$parse$0(JsonNodeParser.java:85)
			at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:108)
			... 60 more
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Index 8192 out of bounds for length 8192). Response Code: 200, Response Text: OK
		at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
		at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:110)
		at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:75)
		at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
		at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
		at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
		at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
		at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:224)
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
		at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
		at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
		at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.describeTable(DefaultDynamoDbClient.java:2407)
		... 18 more
	Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 8192 out of bounds for length 8192
		at software.amazon.awssdk.thirdparty.jackson.core.sym.ByteQuadsCanonicalizer.rehash(ByteQuadsCanonicalizer.java:1285)
		at software.amazon.awssdk.thirdparty.jackson.core.sym.ByteQuadsCanonicalizer._resizeAndFindOffsetForAdd(ByteQuadsCanonicalizer.java:1072)
		at software.amazon.awssdk.thirdparty.jackson.core.sym.ByteQuadsCanonicalizer._findOffsetForAdd(ByteQuadsCanonicalizer.java:1026)
		at software.amazon.awssdk.thirdparty.jackson.core.sym.ByteQuadsCanonicalizer.addName(ByteQuadsCanonicalizer.java:978)
		at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.addName(UTF8StreamJsonParser.java:2482)
		at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.findName(UTF8StreamJsonParser.java:2366)
		at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.parseLongName(UTF8StreamJsonParser.java:1958)
		at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.parseMediumName2(UTF8StreamJsonParser.java:1931)
		at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.parseMediumName(UTF8StreamJsonParser.java:1890)
		at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1825)
		at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:798)
		at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseObject(JsonNodeParser.java:174)
		at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseToken(JsonNodeParser.java:158)
		at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseObject(JsonNodeParser.java:173)
		at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parseToken(JsonNodeParser.java:158)
		at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parse(JsonNodeParser.java:116)
		at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.lambda$parse$0(JsonNodeParser.java:85)
		at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:108)
		at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:136)
		at software.amazon.awssdk.protocols.jsoncore.JsonNodeParser.parse(JsonNodeParser.java:82)
		at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:190)
		at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:75)
		at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
		at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
		at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
		at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:99)
		at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:92)
		at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)
		at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:93)
		at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$8(BaseClientHandler.java:296)
		at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:99)
		... 58 more
```


This was supposedly fixed by Jackson: https://github.com/FasterXML/jackson-core/issues/207

**Comment by fivetran-jonathansavas** [comment]
After disabling `software.amazon.awssdk.thirdparty.jackson.core.JsonFactory.Feature.CANONICALIZE_FIELD_NAMES`, we no longer saw this exception.
