### ISSUE TITLE
TLS Negotiation Error when Creating S3AsyncClient with crtBuilder for java sdk v2

### ISSUE THREAD

**Issue by JesusRRr** [aws/aws-sdk-java-v2#5658]
### Describe the bug

I got a TLS negotiation issue when trying to create an S3AsyncClient using crtBuilder for java sdk v2 with MinIO bucket running locally over HTTPS.

The error message I receive is: 

```
software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: TLS (SSL) negotiation failed
```

This just happend when I use https and the `S3AsyncClient.crtBuilder()`.

If I use `S3AsyncClient.builder()`works as expected 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The HTTP should work using `crtBuilder`

### Current Behavior

```
Exception in thread "main" java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: TLS (SSL) negotiation failed
        at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$execute$0(MakeAsyncHttpRequestStage.java:108)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.completeResponseFuture(MakeAsyncHttpRequestStage.java:255)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:167)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:857)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: TLS (SSL) negotiation failed
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
        at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
        at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:165)
        at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:129)
        at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:25)
```

### Reproduction Steps

1.- Generate a Self-Signed Certificate Locally 
2.- Minio Setup:

```yml
version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
      - ./certs:/root/.minio/certs
    command: server /data --console-address ":9001"
```

3.- Create a S3AsyncClient 
```java

S3AsyncClient s3AsyncClient = S3AsyncClient.crtBuilder()
                                .region(Region.of(region))
                                .endpointOverride(new URI(
                                               "https://localhost:9000/"))
                                .forcePathStyle(Boolean.TRUE)
                                .targetThroughputInGbps(
                                                new Double(targetThroughputInGbps))
                                .minimumPartSizeInBytes(
                                                minimumPartSizeInBytes)
                                .build();

transferManager = S3TransferManager.builder()
                .s3Client(s3AsyncClient)
                .build();

```

### Possible Solution

I don't know if there is a way to pass the certificate directly to the CRT client. 

### Additional Information/Context

I already included the public certificate to my SDK's cacerts. 

* SDK Version

```xml
  <properties>
        <aws.sdk.version>2.25.52</aws.sdk.version>
    </properties>
```

* Dependencies

```xml  
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3-transfer-manager</artifactId>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-crt-client</artifactId>
        </dependency>
```

### AWS Java SDK version used

2.25.52

### JDK version used

openjdk version "17.0.8.1" 2023-08-24 

### Operating System and version

macOS Sonoma 14.6.1

**Comment by debora-ito** [comment]
@JesusRRr Are you using TLS 1.3?

**Comment by JesusRRr** [comment]
> @JesusRRr Are you using TLS 1.3?

Hi @debora-ito, Yes , should I use TLS 1.2?

```
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_128_GCM_SHA256
```

**Comment by debora-ito** [comment]
Can you generate the CRT Trace logs? Instructions can be found in the Developer Guide: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose

Make sure to redact any sensitive information, like access keys, before sharing.

**Comment by debora-ito** [comment]
Another question: does the issue occurs with the s3 endpoint too, or only with minio?

**Comment by JesusRRr** [comment]
> Can you generate the CRT Trace logs? Instructions can be found in the Developer Guide: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose
> 
> Make sure to redact any sensitive information, like access keys, before sharing.

Hi @debora-ito  thank you for the details. 

I have not tried the S3 endpoint. The CRT client works properly when I use HTTP. 

I found this error in the traces. Probably we can work from there. Thank you a lot for the help!

```
[DEBUG] [2024-10-11T22:45:52Z] [000000050011f000] [socket] - id=0x10690d940 fd=152: connection failure
[DEBUG] [2024-10-11T22:45:52Z] [000000050011f000] [channel-bootstrap] - id=0x107e95200: client connection on socket 0x10690d940 completed with error 1047.
[DEBUG] [2024-10-11T22:45:52Z] [000000050011f000] [channel-bootstrap] - id=0x107e95200: recording bad address ::1.
[INFO] [2024-10-11T22:45:52Z] [000000050011f000] [dns] - id=0x107e98c60: recording failure for record ::1 for localhost, moving to bad list
[TRACE] [2024-10-11T22:45:52Z] [000000050011f000] [channel-bootstrap] - id=0x107e95200: releasing socket 0x10690d940 either because we already have a successful connection or because it errored out.
[DEBUG] [2024-10-11T22:45:52Z] [000000050011f000] [socket] - id=0x10690d940 fd=152: closing

[TRACE] [2024-10-11T22:45:52Z] [000000050011f000] [channel] - id=0x127e44400: shutting down slot 0x12910b220, with handler 0x12910d070 in read direction with error code 1029
[TRACE] [2024-10-11T22:45:52Z] [000000050011f000] [socket-handler] - id=0x12910d070: shutting down read direction with error_code 1029
[DEBUG] [2024-10-11T22:45:52Z] [000000050011f000] [channel] - id=0x127e44400: handler 0x12910d070 shutdown in read dir completed.
[DEBUG] [2024-10-11T22:45:52Z] [000000050011f000] [tls-handler] - id=0x129010540: shutting down read direction with error 1029. Flushing queues.

ERROR] [2024-10-11T22:45:52Z] [000000050011f000] [http-connection] - static: Client connection failed with error 1029 (AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE).
[WARN] [2024-10-11T22:45:52Z] [000000050011f000] [connection-manager] - id=0x107ea9350: Failed to obtain new connection from http layer, error 1029(TLS (SSL) negotiation failed)
[DEBUG] [2024-10-11T22:45:52Z] [000000050011f000] [connection-manager] - id=0x107ea9350: Failing excess connection acquisition with error code 1029
[DEBUG] [2024-10-11T22:45:52Z] [000000050011f000] [connection-manager] - id=0x107ea9350: snapshot - state=1, idle_connection_count=0, pending_acquire_count=0, pending_settings_count=0, pending_connect_count=0, vended_connection_count=0, open_connection_count=0, ref_count=1
[WARN] [2024-10-11T22:45:52Z] [000000050011f000] [connection-manager] - id=0x107ea9350: Failed to complete connection acquisition with error_code 1029(TLS (SSL) negotiation failed)
[ERROR] [2024-10-11T22:45:52Z] [000000050011f000] [S3Endpoint] - id=0x107ea47a0: Could not acquire connection due to error code 1029 (TLS (SSL) negotiation failed)

```

**Comment by JesusRRr** [comment]
Hi @debora-ito Do you know the reason of the  1047 and 1029 errors? 
Thank you in advance!

**Comment by alan2610107** [comment]
Hi @JesusRRr 

Could you please advise where I should place the SSL certificate for the S3AsyncClient.crtBuilder()? I’m unsure where to put it.

Thank you!

**Comment by JesusRRr** [comment]
> Hi @JesusRRr
> 
> Could you please advise where I should place the SSL certificate for the S3AsyncClient.crtBuilder()? I’m unsure where to put it.
> 
> Thank you!

Hi @alan2610107, you should add it into cacerts file of your java sdk.  it's located at `$JAVA_HOME/jre/lib/security/` or `$JAVA_HOME/lib/security/`

**Comment by JesusRRr** [comment]
Hi @alan2610107 , I am using this version:  `<aws.sdk.version>2.25.52</aws.sdk.version>`

**Comment by debora-ito** [comment]
@JesusRRr the place where the CRT client will look for SSL certificates will depend on the OS, the CRT client won't use the default Java Trust Store. According to the aws-crt-java [README](https://github.com/awslabs/aws-crt-java?tab=readme-ov-file#tls-behavior):

> The CRT uses native libraries for TLS, rather than Java's typical Secure Socket Extension (JSSE), KeyStore, and TrustStore. On [Windows](https://learn.microsoft.com/en-us/windows/win32/security) and [Apple](https://developer.apple.com/documentation/security) devices, the built-in OS libraries are used. On Linux/Unix/etc [s2n-tls](https://github.com/aws/s2n-tls) is used.

So check if the Amazon certificates are present in the Trust Store of the MacOS version you're using. The certificate list can be found in this 2018 AWS Security Blog post: [How to Prepare for AWS’s Move to Its Own Certificate Authority](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/).

I also suggest to test using AWS endpoints directly, in case this is an issue with minio only.

**Comment by alan2610107** [comment]
> Hi @alan2610107 , I am using this version:  `<aws.sdk.version>2.25.52</aws.sdk.version>`

Hi @JesusRRr 

Thank you so much for helping.

**Comment by alan2610107** [comment]
> @JesusRRr the place where the CRT client will look for SSL certificates will depend on the OS, the CRT client won't use the default Java Trust Store. According to the aws-crt-java [README](https://github.com/awslabs/aws-crt-java?tab=readme-ov-file#tls-behavior):
> 
> 
> 
> > The CRT uses native libraries for TLS, rather than Java's typical Secure Socket Extension (JSSE), KeyStore, and TrustStore. On [Windows](https://learn.microsoft.com/en-us/windows/win32/security) and [Apple](https://developer.apple.com/documentation/security) devices, the built-in OS libraries are used. On Linux/Unix/etc [s2n-tls](https://github.com/aws/s2n-tls) is used.
> 
> 
> 
> So check if the Amazon certificates are present in the Trust Store of the MacOS version you're using. The certificate list can be found in this 2018 AWS Security Blog post: [How to Prepare for AWS’s Move to Its Own Certificate Authority](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/).
> 
> 
> 
> I also suggest to test using AWS endpoints directly, in case this is an issue with minio only.

Hi @debora-ito 

Thank you so much for the answer.

**Comment by JesusRRr** [comment]
> @JesusRRr the place where the CRT client will look for SSL certificates will depend on the OS, the CRT client won't use the default Java Trust Store. According to the aws-crt-java [README](https://github.com/awslabs/aws-crt-java?tab=readme-ov-file#tls-behavior):
> 
> > The CRT uses native libraries for TLS, rather than Java's typical Secure Socket Extension (JSSE), KeyStore, and TrustStore. On [Windows](https://learn.microsoft.com/en-us/windows/win32/security) and [Apple](https://developer.apple.com/documentation/security) devices, the built-in OS libraries are used. On Linux/Unix/etc [s2n-tls](https://github.com/aws/s2n-tls) is used.
> 
> So check if the Amazon certificates are present in the Trust Store of the MacOS version you're using. The certificate list can be found in this 2018 AWS Security Blog post: [How to Prepare for AWS’s Move to Its Own Certificate Authority](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/).
> 
> I also suggest to test using AWS endpoints directly, in case this is an issue with minio only.

Hi @debora-ito 
Thank you a lot for the response, I will try it and let you know the results.

**Comment by JesusRRr** [comment]
Hi @debora-ito, 
After adding the certificate to the Keychain access in my macOS and trust the certificate, the CRT client worked! 
I will be doing some test in Linux and I'll let you know if I have issues, but this issue is solved in macOS.
Thank you a lot for the support.
