### ISSUE TITLE
Netty implementation wraps InterruptedException in RuntimeException, causing issues in code that uses interrupts for cleanup

### ISSUE THREAD

**Issue by iconara** [aws/aws-sdk-java-v2#5694]
### Describe the bug

We are debugging an issue where code that uses Guava's [SimpleTimeLimiter](https://github.com/google/guava/blob/9b0109c6622dde0bd97ba61a43641df3ba8e301a/guava/src/com/google/common/util/concurrent/SimpleTimeLimiter.java#L137) doesn't work properly when a process times out and as part of its cleanup closes an AWS SDK client that uses Netty as the HTTP implementation.

The reason seems to be that the `AwaitCloseChannelPoolMap#close` implementation catches `InterruptedException` and wraps it in `RuntimeException`, hiding it from the calling code. This happens here: https://github.com/aws/aws-sdk-java-v2/blob/88abec27e7d5d35b21545c7e05875a7cc3d0f46e/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java#L174-L175 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

When a thread is interrupted it should either re-throw the `InterruptedException` or mark the thread as interrupted with `Thread.currentThread().interrupt()`, but not both mark the thread as interrupted _and_ throw an exception. Throwing an generic exception means that other code that expects to either get interrupted, or to handle `InterruptedException` to do cleanup instead sees an exception they don't understand.

### Current Behavior

The thread marks the thread as interrupted _and_ throws a generic `RuntimeException`.

### Reproduction Steps

I'm not able to reproduce it in isolation, but here is a stack trace showing how an `InterruptedException` from `CompletableFuture#get` is wrapped as a `RuntimeException` by `AwaitCloseChannelPoolMap#close`:

```
java.lang.RuntimeException: java.lang.InterruptedException
	at software.amazon.awssdk.http.nio.netty.internal.AwaitCloseChannelPoolMap.close(AwaitCloseChannelPoolMap.java:175)
	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.runAndLogError(NettyUtils.java:386)
	at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient.close(NettyNioAsyncHttpClient.java:198)
	at software.amazon.awssdk.utils.IoUtils.closeQuietly(IoUtils.java:70)
	at software.amazon.awssdk.utils.IoUtils.closeIfCloseable(IoUtils.java:87)
	at software.amazon.awssdk.utils.AttributeMap.closeIfPossible(AttributeMap.java:678)
	at software.amazon.awssdk.utils.AttributeMap.access$1600(AttributeMap.java:49)
	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.close(AttributeMap.java:632)
	at java.util.HashMap$Values.forEach(HashMap.java:1065)
	at software.amazon.awssdk.utils.AttributeMap.close(AttributeMap.java:107)
	at software.amazon.awssdk.core.client.config.SdkClientConfiguration.close(SdkClientConfiguration.java:118)
	at software.amazon.awssdk.core.internal.http.HttpClientDependencies.close(HttpClientDependencies.java:82)
	at software.amazon.awssdk.core.internal.http.AmazonAsyncHttpClient.close(AmazonAsyncHttpClient.java:75)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.close(BaseAsyncClientHandler.java:254)
	at software.amazon.awssdk.services.athena.DefaultAthenaAsyncClient.close(DefaultAthenaAsyncClient.java:4906)
	(redacted)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at software.amazon.awssdk.http.nio.netty.internal.AwaitCloseChannelPoolMap.close(AwaitCloseChannelPoolMap.java:172)
```

### Possible Solution

Either call `Thread.currentThread().interrupt()` and don't throw an exception, or re-throw the `InterruptedException` (this would however require adding `InterruptedException` to the method signature).

### AWS Java SDK version used

2.27.21

### JDK version used

Multiple

### Operating System and version

Multiple

**Comment by iconara** [comment]
Here are additional cases of unsafe handling of `InterruptedException` I found by searching through the repo:

* https://github.com/aws/aws-sdk-java-v2/blob/88abec27e7d5d35b21545c7e05875a7cc3d0f46e/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java#L174-L175
* https://github.com/aws/aws-sdk-java-v2/blob/88abec27e7d5d35b21545c7e05875a7cc3d0f46e/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2MultiplexedChannelPool.java#L392-L393
* https://github.com/aws/aws-sdk-java-v2/blob/88abec27e7d5d35b21545c7e05875a7cc3d0f46e/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java#L210-L211
* https://github.com/aws/aws-sdk-java-v2/blob/88abec27e7d5d35b21545c7e05875a7cc3d0f46e/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java#L150-L151

All other cases (the vast majority!) looked safe.

**Comment by iconara** [comment]
I searched through the repo for interrupt handling to check if there were other similar cases, and found only one: https://github.com/aws/aws-sdk-java-v2/blob/88abec27e7d5d35b21545c7e05875a7cc3d0f46e/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java#L150-L151

All other cases looked safe, for example https://github.com/aws/aws-sdk-java-v2/blob/88abec27e7d5d35b21545c7e05875a7cc3d0f46e/core/auth-crt/src/main/java/software/amazon/awssdk/authcrt/signer/internal/AwsCrt4aSigningAdapter.java#L50C7-L52 seems to be the pattern used in all but the two examples above.

**Comment by iconara** [comment]
I'm no longer sure whether this is an issue with the AWS SDK or with the timeout library that we use. I'll close this until I've figured it out.
