### ISSUE TITLE
Unable to resolve credentials using DefaultCredentialsProvider due to NoSuchFieldError for USER_COUNTRY

### ISSUE THREAD

**Issue by aevans-mms** [aws/aws-sdk-java-v2#5700]
### Describe the bug

When attempting to get credentials using the DefaultCredentialsProvider I get the following error message:

java.lang.NoSuchFieldError: Class software.amazon.awssdk.utils.JavaSystemSetting does not have member field 'software.amazon.awssdk.utils.JavaSystemSetting USER_COUNTRY'

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

No error.

DefaultCredentialsProvider.create().resolveCredentials() should return the AwsCredentials object with the accessKeyId secretAccessKey, etc. populated.

### Current Behavior

When attempting to get credentials using the DefaultCredentialsProvider I get the following error message:

`
java.lang.NoSuchFieldError: Class software.amazon.awssdk.utils.JavaSystemSetting does not have member field 'software.amazon.awssdk.utils.JavaSystemSetting USER_COUNTRY'
`

with stack trace:
```
at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.getLanguageTagMetadata(DefaultSystemUserAgent.java:139)
	at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.<init>(DefaultSystemUserAgent.java:62)
	at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.getOrCreate(DefaultSystemUserAgent.java:71)
	at software.amazon.awssdk.core.util.SystemUserAgent.getOrCreate(SystemUserAgent.java:34)
	at software.amazon.awssdk.core.util.SdkUserAgent.getUserAgent(SdkUserAgent.java:70)
	at software.amazon.awssdk.core.util.SdkUserAgent.initializeUserAgent(SdkUserAgent.java:65)
	at software.amazon.awssdk.core.util.SdkUserAgent.<init>(SdkUserAgent.java:35)
	at software.amazon.awssdk.core.util.SdkUserAgent.create(SdkUserAgent.java:42)
	at software.amazon.awssdk.regions.util.ResourcesEndpointProvider.headers(ResourcesEndpointProvider.java:60)
	at software.amazon.awssdk.auth.credentials.internal.StaticResourcesEndpointProvider.<init>(StaticResourcesEndpointProvider.java:34)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.getToken(InstanceProfileCredentialsProvider.java:229)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.createEndpointProvider(InstanceProfileCredentialsProvider.java:211)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.refreshCredentials(InstanceProfileCredentialsProvider.java:158)
	at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$8(CachedSupplier.java:300)
	at software.amazon.awssdk.utils.cache.CachedSupplier$PrefetchStrategy.fetch(CachedSupplier.java:448)
	at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:208)
	at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:135)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.resolveCredentials(InstanceProfileCredentialsProvider.java:149)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54)
	at software.amazon.awssdk.identity.spi.IdentityProvider.resolveIdentity(IdentityProvider.java:60)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:109)
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:129)at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.getLanguageTagMetadata(DefaultSystemUserAgent.java:139)
	at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.<init>(DefaultSystemUserAgent.java:62)
	at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.getOrCreate(DefaultSystemUserAgent.java:71)
	at software.amazon.awssdk.core.util.SystemUserAgent.getOrCreate(SystemUserAgent.java:34)
	at software.amazon.awssdk.core.util.SdkUserAgent.getUserAgent(SdkUserAgent.java:70)
	at software.amazon.awssdk.core.util.SdkUserAgent.initializeUserAgent(SdkUserAgent.java:65)
	at software.amazon.awssdk.core.util.SdkUserAgent.<init>(SdkUserAgent.java:35)
	at software.amazon.awssdk.core.util.SdkUserAgent.create(SdkUserAgent.java:42)
	at software.amazon.awssdk.regions.util.ResourcesEndpointProvider.headers(ResourcesEndpointProvider.java:60)
	at software.amazon.awssdk.auth.credentials.internal.StaticResourcesEndpointProvider.<init>(StaticResourcesEndpointProvider.java:34)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.getToken(InstanceProfileCredentialsProvider.java:229)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.createEndpointProvider(InstanceProfileCredentialsProvider.java:211)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.refreshCredentials(InstanceProfileCredentialsProvider.java:158)
	at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$8(CachedSupplier.java:300)
	at software.amazon.awssdk.utils.cache.CachedSupplier$PrefetchStrategy.fetch(CachedSupplier.java:448)
	at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:208)
	at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:135)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.resolveCredentials(InstanceProfileCredentialsProvider.java:149)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54)
	at software.amazon.awssdk.identity.spi.IdentityProvider.resolveIdentity(IdentityProvider.java:60)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:109)
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:129)at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.getLanguageTagMetadata(DefaultSystemUserAgent.java:139)
	at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.<init>(DefaultSystemUserAgent.java:62)
	at software.amazon.awssdk.core.internal.useragent.DefaultSystemUserAgent.getOrCreate(DefaultSystemUserAgent.java:71)
	at software.amazon.awssdk.core.util.SystemUserAgent.getOrCreate(SystemUserAgent.java:34)
	at software.amazon.awssdk.core.util.SdkUserAgent.getUserAgent(SdkUserAgent.java:70)
	at software.amazon.awssdk.core.util.SdkUserAgent.initializeUserAgent(SdkUserAgent.java:65)
	at software.amazon.awssdk.core.util.SdkUserAgent.<init>(SdkUserAgent.java:35)
	at software.amazon.awssdk.core.util.SdkUserAgent.create(SdkUserAgent.java:42)
	at software.amazon.awssdk.regions.util.ResourcesEndpointProvider.headers(ResourcesEndpointProvider.java:60)
	at software.amazon.awssdk.auth.credentials.internal.StaticResourcesEndpointProvider.<init>(StaticResourcesEndpointProvider.java:34)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.getToken(InstanceProfileCredentialsProvider.java:229)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.createEndpointProvider(InstanceProfileCredentialsProvider.java:211)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.refreshCredentials(InstanceProfileCredentialsProvider.java:158)
	at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$8(CachedSupplier.java:300)
	at software.amazon.awssdk.utils.cache.CachedSupplier$PrefetchStrategy.fetch(CachedSupplier.java:448)
	at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:208)
	at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:135)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.resolveCredentials(InstanceProfileCredentialsProvider.java:149)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54)
	at software.amazon.awssdk.identity.spi.IdentityProvider.resolveIdentity(IdentityProvider.java:60)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:109)
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:129)
	...
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

### Reproduction Steps

```
    public void testGetDefaultCredentials() {

        DefaultCredentialsProvider credentialsProvider = DefaultCredentialsProvider.create();
        AwsCredentials credentials = credentialsProvider.resolveCredentials();

        var accessKeyId = credentials.accessKeyId();
        var secretAccessKey = credentials.secretAccessKey();
  }
 ```
 

### Additional Information/Context

Note that this error appears with awssdk.version

2.29.0, 2.29.7

`java.lang.NoSuchFieldError: Class software.amazon.awssdk.utils.JavaSystemSetting does not have member field 'software.amazon.awssdk.utils.JavaSystemSetting USER_COUNTRY'`

Other errors manifest for older versions:

2.28.0

`software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[profiles, sso-session], profiles=[Profile(name=default, properties=[sso_session, output, aws_access_key_id, aws_session_token, aws_secret_access_key, region, sso_role_name, sso_account_id]), Profile(name=dev, properties=[role_arn, source_profile]), Profile(name=227027150061_SystemAdministrator, properties=[aws_access_key_id, aws_session_token, aws_secret_access_key])])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[profiles, sso-session], profiles=[Profile(name=default, properties=[sso_session, output, aws_access_key_id, aws_session_token, aws_secret_access_key, region, sso_role_name, sso_account_id]), Profile(name=dev, properties=[role_arn, source_profile]), Profile(name=227027150061_SystemAdministrator, properties=[aws_access_key_id, aws_session_token, aws_secret_access_key])])): To use Sso related properties in the 'default' profile, the 'sso' service module must be on the class path., ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.]`

2.16.0, 2.18.0, 2.24.0

`java.lang.NoSuchFieldError: Class software.amazon.awssdk.core.SdkSystemSetting does not have member field 'software.amazon.awssdk.core.SdkSystemSetting AWS_ACCOUNT_ID'`

```
at software.amazon.awssdk.auth.credentials.internal.SystemSettingsCredentialsProvider.resolveCredentials(SystemSettingsCredentialsProvider.java:52)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54)
	at software.amazon.awssdk.identity.spi.IdentityProvider.resolveIdentity(IdentityProvider.java:60)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:109)
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:129)
...
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

### AWS Java SDK version used

2.29.7

### JDK version used

penjdk version "21.0.5" 2024-10-15 LTS OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

### Operating System and version

Windows 11

**Comment by debora-ito** [comment]
See our FAQ: [How do I fix a NoClassDefFoundError, NoSuchMethodError or NoSuchFieldError?](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/troubleshooting.html#faq-classpath-errors)
