### ISSUE TITLE
Not able to load the region while building S3 clients.

### ISSUE THREAD

**Issue by gaurav-gupta409** [aws/aws-sdk-java-v2#5719]
### Describe the bug

We are facing this issue in some of our environments. We are building S3 clients and STS clients of aws-sdk-v2 to talk to buckets. Even if we are explicitly passing region while building the client, we are getting 'unable to load region' error regularly. 

Note : we do not set environment variable (AWS_REGION) or  system property (aws.region) , we explicitly provide region in code while building client.

StackTrace/Exception while building S3 client:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@28429dc2: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@5796b79b: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@1276a1c4: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@5e6e71d: Unable to contact EC2 metadata service.]
    at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.regions.providers.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:70) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveRegion(AwsDefaultClientBuilder.java:293) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder.internalGet(AttributeMap.java:389) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder.access$1300(AttributeMap.java:201) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder$1.get(AttributeMap.java:399) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveEndpoint(AwsDefaultClientBuilder.java:268) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396) ~[kcfscloud-5.7.2.jar:na]
    at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_402]
    at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:232) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeAwsConfiguration(AwsDefaultClientBuilder.java:184) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:161) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:188) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:37) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:26) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155) ~[kcfscloud-5.7.2.jar:na]
    at kdc.cloudadapters.adapters.AbstractV2AmazonS3Adapter.connect(AbstractV2AmazonS3Adapter.java:401) ~[kcfscloud-5.7.2.jar:na]
```

StackTrace/Exception while building STS client:
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@b826f3a: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@71405a09: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@7ef1114c: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@7782cccf: Unable to contact EC2 metadata service.]
    at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.regions.providers.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:70) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveRegion(AwsDefaultClientBuilder.java:293) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder.internalGet(AttributeMap.java:389) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder.access$1300(AttributeMap.java:201) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder$1.get(AttributeMap.java:399) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveEndpoint(AwsDefaultClientBuilder.java:268) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:600) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:589) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:396) ~[kcfscloud-5.7.2.jar:na]
    at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_402]
    at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:232) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeAwsConfiguration(AwsDefaultClientBuilder.java:184) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:161) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:188) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:36) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:25) ~[kcfscloud-5.7.2.jar:na]
    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155) ~[kcfscloud-5.7.2.jar:na]
    at kdc.cloudadapters.adapters.AbstractV2AmazonS3Adapter.connect(AbstractV2AmazonS3Adapter.java:407) ~[kcfscloud-5.7.2.jar:na]
```

Can we get the help why sdk is not able to load the region even if it is passed in builder.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

S3 Clients should be build successfully without any region issue,

### Current Behavior

"Unable to load region" exception while building S3 clients.

### Reproduction Steps

Building S3 Client : 
```
            ClientOverrideConfiguration.Builder clientConfiguration = ClientOverrideConfiguration.builder();
            Map<SdkAdvancedClientOption<?>, String> advancedClientOptions = new HashMap<>();
            advancedClientOptions.put(SdkAdvancedClientOption.USER_AGENT_PREFIX, userAgent);
            clientConfiguration.advancedOptions(advancedClientOptions);
            
            S3Configuration.Builder s3Configuration = S3Configuration.builder();
            s3Configuration.chunkedEncodingEnabled(true);

            ApacheHttpClient.Builder httpClientBuilder = getHttpClientBuilder(adapterConfiguration.getWebProxy());

            S3ClientBuilder s3ClientBuilder = S3Client.builder()
                                      .credentialsProvider(credentialsProvider)
                                      .httpClientBuilder(httpClientBuilder)
                                      .region(Region.of(region))
                                      .endpointOverride(endpointUrl)
                                      .forcePathStyle(pathStyleAccess)
                                      .overrideConfiguration(clientConfiguration.build())
                                      .serviceConfiguration(s3Configuration.build());
            s3ClientBuilder.build();
```
Building STS client :

```
            StsClientBuilder stsClientBuilder = StsClient.builder()
                                        .httpClient(httpClientBuilder.build())
                                        .region(Region.of(region))
                                        .credentialsProvider(credentialsProvider);
            stsClientBuilder.build();
                       
```

### AWS Java SDK version used

2.25.26

### JDK version used

Java version : 8

### Operating System and version

Rocky9 Linux

**Comment by debora-ito** [comment]
@gaurav-gupta409 Which credential provider are you using? Some credential providers use an underlying STS client.

Another hint is this:

> We are facing this issue in some of our environments

If the same code is used in all the environments, this indicates an environment misconfiguration. The SDK does not change behavior if there was no code change or version change.

**Comment by gaurav-gupta409** [comment]
@debora-ito we are using static credentials provider.
```
            AwsBasicCredentials credentials = AwsBasicCredentials.create(accessKeyId, secretAccessKey);
            StaticCredentialsProvider credentialsProvider = StaticCredentialsProvider.create(credentials);
```

**Comment by debora-ito** [comment]
In this case, my guess is that there is some disconnection between that stacktrace and the code you think is throwing the error, maybe the error is not being thrown by the code you're expecting. Your assumption is correct, explicitly setting the region in the client should be sufficient.

I suggest trying to narrow down the cases where `kdc.cloudadapters.adapters.AbstractV2AmazonS3Adapter` throws the error and identify any patterns in the environment configuration.

**Comment by gaurav-gupta409** [comment]
@debora-ito ` kdc.cloudadapters.adapters.AbstractV2AmazonS3Adapter.connect` just calls the build() method , nothing else. So it throws the error while building.
Can you suggest us which environment configurations we should look for?

**Comment by debora-ito** [comment]
Anything region related, or even any aws-specific configuration. Sorry I know it's a wide net.
