### ISSUE TITLE
`Ec2MetadataClient` IMDSv2 401 Unauthorized HTTP Status Code Exceptions

### ISSUE THREAD

**Issue by Petersoj** [aws/aws-sdk-java-v2#5764]
### Describe the bug

Using `Ec2MetadataClient` to query the IMDSv2 service on an EC2 instance will eventually throw an `SdkClientException` for a `401 Unauthorized` HTTP status code as shown [here](https://github.com/aws/aws-sdk-java-v2/blob/61d16e083a27a146665aec19f14bfd31e54e9f83/core/imds/src/main/java/software/amazon/awssdk/imds/internal/DefaultEc2MetadataClient.java#L172).

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

This reproduction example should not print any errors. The `Ec2MetadataClient` should not use stale tokens, which could be the cause of the `401 Unauthorized` response.

### Current Behavior

Let it run long enough and the reproduction example produces the following log:
```
INFO  2024-12-28 18:19:58.147 UTC [pool-1-thread-1] App - MetadataResponse(body=InService)
INFO  2024-12-28 18:20:13.147 UTC [pool-1-thread-1] App - MetadataResponse(body=InService)
INFO  2024-12-28 18:20:28.147 UTC [pool-1-thread-1] App - MetadataResponse(body=InService)
DEBUG 2024-12-28 18:20:43.147 UTC [pool-1-thread-1] software.amazon.awssdk.imds.internal.DefaultEc2MetadataClient - Metadata request response body:
DEBUG 2024-12-28 18:20:43.147 UTC [pool-1-thread-1] software.amazon.awssdk.imds.internal.DefaultEc2MetadataClient - Error while executing EC2Metadata request. Total attempts: 1. The requested metadata at path '/latest/meta-data/autoscaling/target-lifecycle-state' returned Http code 401
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable - software.amazon.awssdk.core.exception.SdkClientException: The requested metadata at path '/latest/meta-data/autoscaling/target-lifecycle-state' returned Http code 401
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at software.amazon.awssdk.imds.internal.DefaultEc2MetadataClient.sendRequest(DefaultEc2MetadataClient.java:178)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at software.amazon.awssdk.imds.internal.DefaultEc2MetadataClient.get(DefaultEc2MetadataClient.java:123)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at App.lambda$new$0(App.java:58)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
ERROR 2024-12-28 18:20:43.148 UTC [pool-1-thread-1] java.lang.Throwable -        at java.base/java.lang.Thread.run(Thread.java:1583)
INFO  2024-12-28 18:20:58.149 UTC [pool-1-thread-1] App - MetadataResponse(body=InService)
INFO  2024-12-28 18:21:13.148 UTC [pool-1-thread-1] App - MetadataResponse(body=InService)
INFO  2024-12-28 18:21:28.147 UTC [pool-1-thread-1] App - MetadataResponse(body=InService)
```

### Reproduction Steps

This reproduction example uses a short token TTL, but longer TTLs produce the same errors.
```java
Ec2MetadataClient ec2Metadata = Ec2MetadataClient.builder().tokenTtl(ofMinutes(1)).build();
newSingleThreadScheduledExecutor().scheduleAtFixedRate(() -> {
    try {
        System.out.println(ec2Metadata.get("/latest/meta-data/autoscaling/target-lifecycle-state"));
    } catch (Exception exception) {
        exception.printStackTrace();
    }
}, 0, 15, SECONDS);
```

### Possible Solution

[This line](https://github.com/aws/aws-sdk-java-v2/blob/61d16e083a27a146665aec19f14bfd31e54e9f83/core/imds/src/main/java/software/amazon/awssdk/imds/internal/DefaultEc2MetadataClient.java#L120) checks if the current IMDSv2 token is expired before sending the request to the IMDS service, but perhaps there is some sort of race condition that causes a stale token to be used for the IMDS request after the expiration check. If it's not that, I'm not sure what would be causing the `401 Unauthorized`.

### AWS Java SDK version used

2.29.43

### JDK version used

OpenJDK 64-Bit Server VM Corretto-21.0.5.11.1

### Operating System and version

Ubuntu 24.04.1 LTS

**Comment by debora-ito** [comment]
According to the logs, the token should be valid until _2024-12-28T18:41:33.886487462Z_:

>DEBUG 2024-12-28 18:40:33.886 UTC [pool-1-thread-1] software.amazon.awssdk.utils.cache.CachedSupplier - (Ec2MetadataClient()) Successfully refreshed cached value. Next Prefetch Time: +1000000000-12-31T23:59:59.999999999Z. Next Stale Time: 2024-12-28T18:41:33.886487462Z

The timestamp of the error is _2024-12-28 18:41:33.811 UTC_, which is before the stale time by 75 milliseconds, but still before:

> DEBUG 2024-12-28 18:41:33.811 UTC [pool-1-thread-1] software.amazon.awssdk.imds.internal.DefaultEc2MetadataClient - Error while executing EC2Metadata request. Total attempts: 1. The requested metadata at path '/latest/meta-data/autoscaling/target-lifecycle-state' returned Http code 401

But at 18:41:33.811 the token is not actually valid anymore. So I agree, there's some timing issue in the way the token expiration is being checked. We'll investigate.

**Comment by Petersoj** [comment]
Not sure if this would work, but a potential (but hacky) solution would be to change [this](https://github.com/aws/aws-sdk-java-v2/blob/61d16e083a27a146665aec19f14bfd31e54e9f83/core/imds/src/main/java/software/amazon/awssdk/imds/internal/Token.java#L51) line from:
```java
return Instant.now().isAfter(createdTime.plus(ttl));
```
to:
```java
// Add some buffer time to the expiration check.
return Instant.now().plusSeconds(60).isAfter(createdTime.plus(ttl));
```

**Comment by Petersoj** [comment]
@debora-ito any updates on this?
