### ISSUE TITLE
S3 client throws NPE for GET request when using endpointOverride

### ISSUE THREAD

**Issue by zoewangg** [aws/aws-sdk-java-v2#612]
## Current Behavior
S3 client throws NPE for GET request throwing NPE when using `endpointOverride`
```
java.lang.NullPointerException
	at software.amazon.awssdk.auth.signer.AwsS3V4Signer.getContentLength(AwsS3V4Signer.java:237)
	at software.amazon.awssdk.auth.signer.AwsS3V4Signer.calculateContentHash(AwsS3V4Signer.java:180)
	at software.amazon.awssdk.auth.signer.AwsS3V4Signer.calculateContentHash(AwsS3V4Signer.java:40)
	at software.amazon.awssdk.auth.signer.internal.AbstractAws4Signer.doSign(AbstractAws4Signer.java:76)
	at software.amazon.awssdk.auth.signer.AwsS3V4Signer.sign(AwsS3V4Signer.java:81)
	at software.amazon.awssdk.auth.signer.AwsS3V4Signer.sign(AwsS3V4Signer.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.signRequest(SigningStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.execute(SigningStage.java:47)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.execute(SigningStage.java:33)
```

## Steps to Reproduce (for bugs)
```java
    @Rule
    public WireMockRule mockServer = new WireMockRule(0);

    private S3Client s3Client;

    @Before
    public void setup() {
        s3Client = S3Client.builder()
                           .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("test", "test")))
                           .region(Region.US_WEST_2).endpointOverride(URI.create("http://localhost:" + mockServer.port()))
                           .build();
    }


    @Test
    public void test() throws IOException {
        stubFor(get(urlEqualTo("/test?versions"))
                    .willReturn(aResponse()
                                    .withStatus(200)));
        try {
            s3Client.listObjectVersions(b -> b.bucket("test"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

## Your Environment

* AWS Java SDK version used: 
* JDK version used:
* Operating System and version:

**Comment by koneru9999** [comment]
having the same issue with `preview-11` version

**Comment by hartmut-co-uk** [comment]
<> https://github.com/aws/aws-sdk-java-v2/issues/437
