### ISSUE TITLE
NPE  during S3AsyncClient putObject() method - protocol must not be null 

### ISSUE THREAD

**Issue by siddharths067** [aws/aws-sdk-java-v2#668]
# The Issue
Afterinitializing an Asynchronous S3 Client Object (S3AsyncClient) a null pointer exception is thrown when the putObject() method is invoked.

## Expected Behavior

Upload a File Asynchronously to AWSBucket, return a PutObjectResponse Completable Future

## Current Behavior

Throws a java.lang.NullPointerException: protocol must not be null with the following stacktrace.

```

[error] Test services.storage.ObjectUploaderInterfaceTest.uploadTest failed: java.util.concurrent.CompletionException: java.lang.NullPointerException: protocol must not be null., took 0.069 sec
[error]     at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)java.lang.NullPointerException: protocol must not be null.
        at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:118)
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.standardizeProtocol(DefaultSdkHttpFullRequest.java:62)
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:51)
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:40)
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:294)
        at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:155)
        at software.amazon.awssdk.core.http.SdkHttpFullRequestAdapter.toHttpFullRequest(SdkHttpFullRequestAdapter.java:41)
        at software.amazon.awssdk.core.client.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:64)
        at software.amazon.awssdk.core.client.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:92)
        at software.amazon.awssdk.core.client.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:65)
        at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:52)
        at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.putObject(DefaultS3AsyncClient.java:3139)
        at software.amazon.awssdk.services.s3.S3AsyncClient.putObject(S3AsyncClient.java:4483)
        at services.storage.Implementation.ObjectUploaderInterfaceImpl.uploadObject(ObjectUploaderInterfaceImpl.java:46)
        at services.storage.ObjectUploaderInterfaceTest.uploadTest(ObjectUploaderInterfaceTest.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at com.novocode.junit.JUnitRunner$1.execute(JUnitRunner.java:132)
        at sbt.ForkMain$Run$2.call(ForkMain.java:300)
        at sbt.ForkMain$Run$2.call(ForkMain.java:290)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### The Class
```
public class ObjectUploaderInterfaceImpl implements ObjectUploaderInterface {


  private String AWS_ACCESS_KEY;
  private String AWS_SECRET_KEY;
  private S3AsyncClient s3Client; // Asynchronous Client for Non Blocking IO
  private AwsCredentials credentials;

  public ObjectUploaderInterfaceImpl(String awsAccessKey, String awsSecretKey) {
    this.AWS_ACCESS_KEY = awsAccessKey;
    this.AWS_SECRET_KEY = awsSecretKey;
    this.credentials = AwsBasicCredentials.create(this.AWS_ACCESS_KEY, this.AWS_SECRET_KEY);
    System.out.println("The Generated Credentials "+ this.credentials.toString());
    try {
      this.s3Client = S3AsyncClient.builder()
          .credentialsProvider(StaticCredentialsProvider.create(this.credentials))
          .region(Region.AP_SOUTHEAST_1)
          .endpointOverride(URI.create("s3-ap-southeast-1.amazonaws.com"))
          .build(); // Throws Null pointer Exception
    } catch (Exception e) {
      System.out.println("Could not create a client ");
      e.printStackTrace();
    }
  }

  @Override
  public CompletableFuture<PutObjectResponse> uploadObject(String filePath, String s3Bucket,
      String s3BucketPath) {
    CompletableFuture<PutObjectResponse> future;
    try {
      future = s3Client.putObject(
          PutObjectRequest.builder()
              .bucket(s3Bucket)
              .key(s3BucketPath)
              .build(),
          Paths.get(filePath)
      );
      future.whenComplete((resp, err) -> {
        if (resp != null) {
          System.out.println("Response from Server : " + resp);
        } else {
          err.printStackTrace();
        }
        try {
          s3Client.close();
        } catch (Exception e) {
          System.out.println(e);
        }

      });
    } catch (Exception e) {
      System.out.println(e.getMessage());
      return null;
    }
    return future;

  }
}

```
### The Testing Class

```

public class ObjectUploaderInterfaceTest {

  ObjectUploaderInterface uploader;
  public ObjectUploaderInterfaceTest(){
    this.uploader = new ObjectUploaderInterfaceImpl(
        "<Access Key>",
        "<Secret Key>");
  }

  @Test
  public void uploadTest(){
    uploader.uploadObject(
        "/test/services.storage/testFiles/uploadTestFile.txt",
        "<Bucket Name>",
        "/test/testFiles/uploadTestFile.txt").whenComplete((res, err)->{
          if(res != null){
            System.out.println(res);
          }
          else{
            err.printStackTrace();
          }
    }).join();
  }

}

```

## Context

I am trying to upload a file into an S3Bucket

## Your Environment

* AWS Java SDK version used: 2.0.0-preview-11
* JDK version used: Version 8 Update 101
* Operating System and version: Windows 10

**Comment by zoewangg** [comment]
You need to provide http protocol in the URI.

Can you try with `URI.create("https://s3-ap-southeast-1.amazonaws.com")`?

Side note, you don't need to provide endpoint override if you are using the standard s3 region.
