### ISSUE TITLE
CloundFront: UnknownHostException

### ISSUE THREAD

**Issue by ben-manes** [aws/aws-sdk-java-v2#689]
When migrating from the 1.x client, it seems that the new client fails when trying to perform an invalidation call. From the API docs, it sounds like the endpoint should be `cloudfront.amazonaws.com` and is incorrectly including the region subdomain. If I remove the region in the builder, it defaults to `us-east-1` and fails.

```java
@Provides @Singleton
CloudFrontAsyncClient providesCloudFrontClient(AwsCredentialsProvider credentials) {
  return CloudFrontAsyncClient.builder()
      .region(Region.of(config.getString("region")))
      .credentialsProvider(credentials)
      .build();
}
```

```java
/**
  * Invalidates the keys in the CDN so that they are refreshed from S3.
  *
  * @param keys the keys patterns to invalidate
  */
public void invalidate(Collection<String> keys) {
  if (keys.isEmpty() || (cdn == null)) {
    return;
  }

  var request = cloudFront.createInvalidation(CreateInvalidationRequest.builder()
      .invalidationBatch(InvalidationBatch.builder()
          .callerReference(UUID.randomUUID().toString())
          .paths(Paths.builder()
              .quantity(keys.size())
              .items(keys.stream().map(S3::normalizeKey).collect(toList()))
              .build())
          .build())
      .distributionId(distributionId)
      .build());
  request.join();
  logger.info("Invalidated CDN keys at {}", keys);
}
```

```
Failed to create connection to https://cloudfront.us-west-2.amazonaws.com/2017-03-25/distribution/<distributionId>/invalidation
java.net.UnknownHostException: cloudfront.us-west-2.amazonaws.com
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:793)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1495)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1354)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1288)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1238)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
```

**Comment by varunnvs92** [comment]
You should specify [AWS_GLOBAL](https://github.com/aws/aws-sdk-java-v2/blob/master/core/regions/src/main/java/software/amazon/awssdk/regions/Region.java#L69) for non-regionalized services like cloudfront, IAM. Let me know if it works after this change.

**Comment by ben-manes** [comment]
Perfect! Works great, thank you.

Since the error message is confusing, is it possible to update the code generator with a flag to know that the service is global? Then it could provide a more meaningful error message within the builder instead, or not provide the parameter at all. So this issue can be closed, but the error message should be improved as it wasn't obvious.

**Comment by varunnvs92** [comment]
That makes sense. I will add it to our backlog.
