### ISSUE TITLE
Non fatal exceptions accessing S3 buckets (most/all API calls)

### ISSUE THREAD

**Issue by oakad** [aws/aws-sdk-java-v2#81]
Most async calls to S3 API emit stack traces to the console, despite still performing the intended function:

Failed to parse the endpoint https://`<bucket name>`.s3.amazonaws.com, and skip re-assigning the signer region
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1931)
        at software.amazon.awssdk.util.AwsHostNameUtils.parseStandardRegionName(AwsHostNameUtils.java:157)
        at software.amazon.awssdk.util.AwsHostNameUtils.parseRegion(AwsHostNameUtils.java:82)
        at software.amazon.awssdk.util.AwsHostNameUtils.parseRegionName(AwsHostNameUtils.java:57)
        at software.amazon.awssdk.services.s3.auth.S3SignerProvider.getSigner(S3SignerProvider.java:47)
        at software.amazon.awssdk.http.pipeline.stages.SigningStage.newSigner(SigningStage.java:75)
        at software.amazon.awssdk.http.pipeline.stages.SigningStage.signRequest(SigningStage.java:55)
        at software.amazon.awssdk.http.pipeline.stages.SigningStage.execute(SigningStage.java:47)
        at software.amazon.awssdk.http.pipeline.stages.SigningStage.execute(SigningStage.java:34)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
        at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.doExecute(AsyncRetryableStage.java:222)
        at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:151)
        at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:145)
        at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:81)
        at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:55)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
        at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
        at software.amazon.awssdk.http.AmazonAsyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonAsyncHttpClient.java:301)
        at software.amazon.awssdk.client.AsyncClientHandlerImpl.doInvoke(AsyncClientHandlerImpl.java:301)
        at software.amazon.awssdk.client.AsyncClientHandlerImpl.invoke(AsyncClientHandlerImpl.java:280)
        at software.amazon.awssdk.client.AsyncClientHandlerImpl.execute(AsyncClientHandlerImpl.java:127)
        at software.amazon.awssdk.client.SdkAsyncClientHandler.execute(SdkAsyncClientHandler.java:42)
        at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.headObject(DefaultS3AsyncClient.java:1355)

**Comment by rohit2910** [comment]
When will this fix be available as SDK ? Or do you have nightly build I can use ?

**Comment by spfink** [comment]
@rohit2910, are you consuming us through Maven? If so, we can push out a release today. You can also pull down our master branch which has this fix.

**Comment by thomas-mcdonald** [comment]
@spfink Would be great if you could cut a new release with this fix in

**Comment by bisoldi** [comment]
I've noticed the same thing.  When using the client.listObjectsV2 method, it lists the objects and then through a StringIndexOutOfBoundsException.

```
try {
    ListObjectsV2Request listRequest = ListObjectsV2Request.builder().bucket(BUCKET).maxKeys(maxKeys).prefix(PREFIX).build();
    ListObjectsV2Response listObjects;

    do {
        listObjects = client.listObjectsV2(listRequest).get();
              
        List<S3Object> contents = listObjects.contents();
        for (S3Object obj : contents) {
            System.out.println(obj.key());
        }
        System.out.println("----------");
    } while (listObjects.isTruncated());
} catch (InterruptedException | ExecutionException ex) {
    ex.printStackTrace();
}
```

Here is my POM snippet:

```
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>s3</artifactId>
    <version>2.0.0-preview-2</version>
</dependency>
```


I get the following stacktrace:

```
12:52:03.279 [main] WARN  - Failed to parse the endpoint https://BUCKET-NAME.s3.amazonaws.com, and skip re-assigning the signer region
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931) ~[na:1.8.0_131]
	at software.amazon.awssdk.util.AwsHostNameUtils.parseStandardRegionName(AwsHostNameUtils.java:157) ~[core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.util.AwsHostNameUtils.parseRegion(AwsHostNameUtils.java:82) ~[core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.util.AwsHostNameUtils.parseRegionName(AwsHostNameUtils.java:57) ~[core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.services.s3.auth.S3SignerProvider.getSigner(S3SignerProvider.java:47) ~[s3-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.SigningStage.newSigner(SigningStage.java:75) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.SigningStage.signRequest(SigningStage.java:55) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.SigningStage.execute(SigningStage.java:47) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.SigningStage.execute(SigningStage.java:34) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.doExecute(AsyncRetryableStage.java:222) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:151) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:145) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:81) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:55) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.http.AmazonAsyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonAsyncHttpClient.java:301) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.client.AsyncClientHandlerImpl.doInvoke(AsyncClientHandlerImpl.java:301) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.client.AsyncClientHandlerImpl.invoke(AsyncClientHandlerImpl.java:280) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.client.AsyncClientHandlerImpl.execute(AsyncClientHandlerImpl.java:127) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.client.SdkAsyncClientHandler.execute(SdkAsyncClientHandler.java:42) [core-2.0.0-preview-2.jar:na]
	at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.listObjectsV2(DefaultS3AsyncClient.java:1565) [s3-2.0.0-preview-2.jar:na]
```
