### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by ArturEgorov** [aws/aws-sdk-java-v2#88]
SDK version 2.0.0-preview-2

Reguest:
```
S3AsyncClient s3Client = AWS2Manager.getS3AsyncClient(Region.US_EAST_1);
		s3Client.listObjectsV2(
				ListObjectsV2Request.builder()
						.bucket("bucket")
						.prefix("prefix")
						.build()
		)
```

Exception:

> java.lang.StringIndexOutOfBoundsException: String index out of range: -1
> 	at java.lang.String.substring(String.java:1931)
> 	at software.amazon.awssdk.util.AwsHostNameUtils.parseStandardRegionName(AwsHostNameUtils.java:157)
> 	at software.amazon.awssdk.util.AwsHostNameUtils.parseRegion(AwsHostNameUtils.java:82)
> 	at software.amazon.awssdk.util.AwsHostNameUtils.parseRegionName(AwsHostNameUtils.java:57)
> 	at software.amazon.awssdk.services.s3.auth.S3SignerProvider.getSigner(S3SignerProvider.java:47)
> 	at software.amazon.awssdk.http.pipeline.stages.SigningStage.newSigner(SigningStage.java:75)
> 	at software.amazon.awssdk.http.pipeline.stages.SigningStage.signRequest(SigningStage.java:55)
> 	at software.amazon.awssdk.http.pipeline.stages.SigningStage.execute(SigningStage.java:47)
> 	at software.amazon.awssdk.http.pipeline.stages.SigningStage.execute(SigningStage.java:34)
> 	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
> 	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.doExecute(AsyncRetryableStage.java:222)
> 	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:151)
> 	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:145)
> 	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:81)
> 	at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:55)
> 	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
> 	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
> 	at software.amazon.awssdk.http.AmazonAsyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonAsyncHttpClient.java:301)
> 	at software.amazon.awssdk.client.AsyncClientHandlerImpl.doInvoke(AsyncClientHandlerImpl.java:301)
> 	at software.amazon.awssdk.client.AsyncClientHandlerImpl.invoke(AsyncClientHandlerImpl.java:280)
> 	at software.amazon.awssdk.client.AsyncClientHandlerImpl.execute(AsyncClientHandlerImpl.java:127)
> 	at software.amazon.awssdk.client.SdkAsyncClientHandler.execute(SdkAsyncClientHandler.java:42)
> 	at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.listObjectsV2(DefaultS3AsyncClient.java:1565)

**Comment by ArturEgorov** [comment]
AwsHostNameUtils::parseStandardRegionName line 157

The variable fragment not contain region.
