### ISSUE TITLE
Netty Http client: exception when using shared client

### ISSUE THREAD

**Issue by oakad** [aws/aws-sdk-java-v2#91]
Actual AWS request appears to complete properly.

Caused by: software.amazon.awssdk.SdkClientException: Unable to execute HTTP request: SSLEngine closed already
                at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.handleIoException(AsyncRetryableStage.java:251)
                at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.handle(AsyncRetryableStage.java:165)
                ... 58 more
        Caused by: javax.net.ssl.SSLException: SSLEngine closed already
                at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source)

**Comment by shorea** [comment]
Are you using 2.0.0-preview-1 or 2.0.0-preview-2?

**Comment by oakad** [comment]
Git HEAD pulled yesterday.

And a bit of correction: sometimes requests complete correctly and sometimes fail.

It only appears to happen when the same instance of client is shared between multiple requesting threads. When there's only one thread doing a sequence of requests nothing bad happens.

Also, I'm not at all sure that my way of using it is the intended way at all, but with netty there are major economies involved in reusing context, and a single netty context can usually support many thousands of overlapping requests without any issues.

**Comment by millems** [comment]
Are you still encountering this issue?

**Comment by debora-ito** [comment]
Closing this due to no response. Check the latest release and if you are still seeing this please open a new issue.
