### ISSUE TITLE
Initial build fails

### ISSUE THREAD

**Issue by trawicjc** [aws/aws-sdk-java-v2#925]
Attempting to propose a fix for issue #917.  Cloned the repo, ran mvn, and tests fail with no changes:

[ERROR] Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.223 s <<< FAILURE! - in software.amazon.awssdk.core.auth.policy.PolicyReaderTest
[ERROR] testPrincipals(software.amazon.awssdk.core.auth.policy.PolicyReaderTest)  Time elapsed: 0.213 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonView
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testPrincipals(PolicyReaderTest.java:48)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonView
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testPrincipals(PolicyReaderTest.java:48)

[ERROR] testMultipleConditionKeysForConditionType(software.amazon.awssdk.core.auth.policy.PolicyReaderTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testMultipleConditionKeysForConditionType(PolicyReaderTest.java:118)

[ERROR] testNoJsonArray(software.amazon.awssdk.core.auth.policy.PolicyReaderTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testNoJsonArray(PolicyReaderTest.java:240)

[ERROR] testPrincipalWithServiceNotInServicesEnum(software.amazon.awssdk.core.auth.policy.PolicyReaderTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testPrincipalWithServiceNotInServicesEnum(PolicyReaderTest.java:344)

[ERROR] testPolicyParsingWithNoEffect(software.amazon.awssdk.core.auth.policy.PolicyReaderTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testPolicyParsingWithNoEffect(PolicyReaderTest.java:151)

[ERROR] testFederatedUserBySAMLProvider(software.amazon.awssdk.core.auth.policy.PolicyReaderTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testFederatedUserBySAMLProvider(PolicyReaderTest.java:283)

[ERROR] testCloudHSMServicePrincipal(software.amazon.awssdk.core.auth.policy.PolicyReaderTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testCloudHSMServicePrincipal(PolicyReaderTest.java:312)

[ERROR] testMultipleStatements(software.amazon.awssdk.core.auth.policy.PolicyReaderTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyReaderTest.testMultipleStatements(PolicyReaderTest.java:178)

[INFO] Running software.amazon.awssdk.core.auth.policy.PolicyTest
[ERROR] Tests run: 5, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in software.amazon.awssdk.core.auth.policy.PolicyTest
[ERROR] testPrincipals(software.amazon.awssdk.core.auth.policy.PolicyTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyTest.testPrincipals(PolicyTest.java:51)

[ERROR] testMultipleConditionKeysForConditionType(software.amazon.awssdk.core.auth.policy.PolicyTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyTest.testMultipleConditionKeysForConditionType(PolicyTest.java:283)

[ERROR] testMultipleStatements(software.amazon.awssdk.core.auth.policy.PolicyTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.core.auth.policy.internal.JacksonUtils
	at software.amazon.awssdk.core.auth.policy.PolicyTest.testMultipleStatements(PolicyTest.java:315)

## Expected Behavior
Build succeeds.

## Current Behavior
Build fails.

## Possible Solution
Fix the build.

## Steps to Reproduce (for bugs)
mvn clean install -Dgpg.skip=true

## Context
Attempting to produce a pull request to fix issue #917 

## Your Environment
* AWS Java SDK version used: 2.1.4-SNAPSHOT
* JDK version used: Java(TM) SE Runtime Environment 18.3 (build 10+46)
* Operating System and version: macOS Mojave 10.14.1

**Comment by trawicjc** [comment]
Maven repository was corrupt.  Deleting it fixed the build.
