### ISSUE TITLE
NumberFormatException when parsing "Content-Length" -- should be long instead of int

### ISSUE THREAD

**Issue by azmras** [aws/aws-sdk-java-v2#963]
java.lang.NumberFormatException: For input string: "51747932945"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.valueOf(Integer.java:766)
        at software.amazon.awssdk.services.s3.internal.handlers.SyncChecksumValidationInterceptor.modifyHttpResponseContent(SyncChecksumValidationInterceptor.java:84)

## Possible Solution
**in SyncChecksumValidationInterceptor.modifyHttpResponseContent**
replace int with long

```
long contentLength = Long.valueOf(context.httpResponse().firstMatchingHeader(CONTENT_LENGTH_HEADER).orElse("0"));
```

**in AsyncChecksumValidationInterceptor.modifyAsyncHttpResponseContent**
replace int with long

```
long contentLength = Long.parseLong(context.httpResponse().firstMatchingHeader("Content-Length").orElse("0"));
```

## Steps to Reproduce (for bugs)
use S3Client.getObject  for large files (more than 2GB)

## Context
Downloading a 50+ GB File

## Your Environment

* AWS Java SDK version used: 2.2.0 
* JDK version used: 1.8
* Operating System and version: Amazon Linux 1

**Comment by zoewangg** [comment]
Thank you for reporting! The fix has been merged and we will let you know after a release is out.

**Comment by azmras** [comment]
That was quick, waiting for release... 
Thanks alot ...

**Comment by zoewangg** [comment]
The temporary workaround is to disable S3 checksum validation via `S3Configuration.Builder#checksumValidationEnabled` https://github.com/aws/aws-sdk-java-v2/blob/6846e3dfbca6a85c37f5869d183748f6e3c28b05/services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Configuration.java#L218

**Comment by metadaddy** [comment]
Did this make it into a release of the SDK yet? Seems to have been waiting a while!

**Comment by debora-ito** [comment]
@metadaddy yes, it was released in version [`2.3.0`](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#230-2019-01-09).
