### ISSUE TITLE
S3: DateTimeParseException when unmarshall response

### ISSUE THREAD

**Issue by keilon** [aws/aws-sdk-java-v2#981]
I used this sdk with an s3 compatible storage server. When calling s3 getObject api, following exception occurs:

`software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Text 'Fri, 28 Dec 2018 10:11:26 CST' could not be parsed at index 26). Response Code: 200, Response Text: OK`

response is success but could not parse the date string with RFC_1123_DATE_TIME formatter , just like https://stackoverflow.com/questions/45829799/java-time-format-datetimeformatter-rfc-1123-date-time-fails-to-parse-time-zone-n said.

## Expected Behavior
Seems not a bug in sdk but `DateTimeFormatter.RFC_1123_DATE_TIME` which `software.amazon.awssdk.utils.DateUtils` used do not handle zoneId expect for 'GMT and offset amounts' as [java docs](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#RFC_1123_DATE_TIME) said.

however， i don't care about the date of object metadata in the response and this did not appear in sdk 1.11.x 
## Current Behavior
Full stack trace here:
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Text 'Fri, 28 Dec 2018 10:11:26 CST' could not be parsed at index 26). Response Code: 200, Response Text: OK

 at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleSuccessResponse(HandleResponseStage.java:100)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:70)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
 at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:63)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:115)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:88)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:44)
 at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
 at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:51)
 at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:33)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:79)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
 at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
 at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
 at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
 at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
 at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
 at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:61)
 at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:51)
 at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:62)
 at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:1597)
 ...
Caused by: java.time.format.DateTimeParseException: Text 'Fri, 28 Dec 2018 10:11:26 CST' could not be parsed at index 26
 at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
 at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
 at software.amazon.awssdk.utils.DateUtils.parseInstant(DateUtils.java:125)
 at software.amazon.awssdk.utils.DateUtils.parseRfc1123Date(DateUtils.java:101)
 at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:62)
 at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:31)
 at software.amazon.awssdk.protocols.xml.internal.unmarshall.HeaderUnmarshaller$SimpleHeaderUnmarshaller.lambda$unmarshall$0(HeaderUnmarshaller.java:62)
 at java.base/java.util.Optional.map(Optional.java:265)
 at software.amazon.awssdk.protocols.xml.internal.unmarshall.HeaderUnmarshaller$SimpleHeaderUnmarshaller.unmarshall(HeaderUnmarshaller.java:62)
 at software.amazon.awssdk.protocols.xml.internal.unmarshall.XmlProtocolUnmarshaller.unmarshall(XmlProtocolUnmarshaller.java:90)
 at software.amazon.awssdk.protocols.xml.internal.unmarshall.XmlProtocolUnmarshaller.unmarshall(XmlProtocolUnmarshaller.java:74)
 at software.amazon.awssdk.protocols.xml.internal.unmarshall.XmlProtocolUnmarshaller.unmarshall(XmlProtocolUnmarshaller.java:58)
 at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlResponseHandler.unmarshallResponse(AwsXmlResponseHandler.java:82)
 at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlResponseHandler.handle(AwsXmlResponseHandler.java:61)
 at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlResponseHandler.handle(AwsXmlResponseHandler.java:41)
 at software.amazon.awssdk.core.client.handler.BaseClientHandler.lambda$interceptorCalling$2(BaseClientHandler.java:133)
 at software.amazon.awssdk.core.client.handler.AttachHttpMetadataResponseHandler.handle(AttachHttpMetadataResponseHandler.java:40)
 at software.amazon.awssdk.core.client.handler.AttachHttpMetadataResponseHandler.handle(AttachHttpMetadataResponseHandler.java:28)
 at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler$HttpResponseHandlerAdapter.handle(BaseSyncClientHandler.java:141)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleSuccessResponse(HandleResponseStage.java:89)
 ... 60 more
```

## Possible Solution
Maybe a easy way is just catch `DateTimeParseException` and show some warnings, then return object without date info? 

## Context
Moreover，the s3 compatible server return a GMT date string could be more gracefully...

## Your Environment
* AWS Java SDK version used: 2.2.0
* JDK version used:11.0.1
* Operating System and version: mac os X 10.14.2

**Comment by zoewangg** [comment]
As SDK, we can't catch and swallow any customer impacting exceptions. Going to mark this as a feature request to make `DateUtils.formatRfc1123Date` to support other zones. PRs are welcome!

https://github.com/aws/aws-sdk-java-v2/blob/a250d9d6fa8f0fa875cdd25dfe6e21a574b7f6e9/utils/src/main/java/software/amazon/awssdk/utils/DateUtils.java#L112

**Comment by keilon** [comment]
The s3 compatible server has fixed it with a GMT date format return.
